### ISSUE TITLE
New-MgTeamChannelMessage is not working

### ISSUE THREAD

**Issue by JohanssonMarkus** [microsoftgraph/microsoft-graph-docs#10032]
Hey 
New-MgTeamChannelMessage -TeamId $team.Id -ChannelId $channel.Id -Body @{ Content="Hello World" }

Above command is not working 
![image](https://user-images.githubusercontent.com/32453241/94070748-09b5a180-fdf3-11ea-8019-413bd2685afb.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee6c82de-5bf9-4281-868c-f97cebd1004d
* Version Independent ID: beb824e6-19f0-0ba5-2b09-7135ffdb586e
* Content: [Get started with the Microsoft Graph PowerShell SDK - Microsoft Graph](https://docs.microsoft.com/en-us/graph/powershell/get-started)
* Content Source: [concepts/powershell/get-started.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/powershell/get-started.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @jasonjoh
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jasonjoh** [comment]
Thank you for bringing this to my attention @JohanssonMarkus. This is a bug with the preview version of the PowerShell module that impacts multiple commands that I was told would be fixed by now (see https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/370). The fix for `Object reference not set to an instance of an object` is to add `-AdditionalProperties @{}` to the command.

However, this will only get you to another problem:

`New-MgTeamChannelMessage_CreateExpanded1: An item with the same key has already been added. Key: content`

This is tracked in https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/339

**Comment by darrelmiller** [comment]
@JohanssonMarkus   Both of these issues are fixed in the 1.0 release.  We had a minor issue in the release process and it should be out later today.  Sorry for the inconvenience.
