### ISSUE TITLE
Finding alternativeSecurityId and deviceId

### ISSUE THREAD

**Issue by alex182** [microsoftgraph/microsoft-graph-docs#1030]
I am attempting to register a machine in Azure AD using Graph API.  I am hitting a roadblock when filling out a few of the required fields.  

How exactly is the alternativeSecurityId generated/found (along with its type) and where can the deviceId be found?

Thanks!

**Comment by dkershaw10** [comment]
Sorry for the late response here.  We will be making a number of fixes to the Devices documentation shortly.  I would like to understand under what scenarios you need to register a machine through the API (i.e. POST /devices) rather than come through the normal device registration mechanisms that are offered today?  We erroneously exposed device creation and some properties on the device object that serve no purpose or know end-2-end scenarios that we are aware of.
