### ISSUE TITLE
Support for $filter "contains" keyword

### ISSUE THREAD

**Issue by swettstein** [microsoftgraph/microsoft-graph-docs#10338]
Is there any planned support for the "contains" keyword for $filter on groups/users/directory objects?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fefc984-0dac-5531-6620-13f577ebee5f
* Version Independent ID: 92438f30-1bb9-9b45-57dc-094fdcdeecc1
* Content: [Use query parameters to customize responses - Microsoft Graph](https://docs.microsoft.com/en-us/graph/query-parameters)
* Content Source: [concepts/query-parameters.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/query-parameters.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @mumbi-o
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by swettstein** [comment]
or maybe support the $search keyword? it appears to work in the portal when searching groups but not in graph explorer

**Comment by rdweaver** [comment]
I would like to see support for "contains" as well!
For example, the scenario with a user display name of 'Ryan Weaver', I would like to be able to search for _'yan'_ and have it return that user.
There is no way to do this with either  $filter or $search. The $search parameter does tokenization, so that is better but it is still doing "startsWith" and not "contains".
For example, If I do `$search="displayName:rya" ` it will return the user, but if I do `$search="displayName:yan"` it will not return

**Comment by FaithOmbongi** [comment]
Apologies for the delayed response. The `contains` operator is supported in Microsoft Graph, though currently on a very limited number of resources like [accessReviews](https://docs.microsoft.com/en-us/graph/api/resources/accessreviewsv2-root?view=graph-rest-1.0).

I've shared this request with the product team. I would also recommend you post this request at the [Microsoft 365 Developer Platform ideas](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform/label-name/Microsoft%20Graph) forum so it can be looked into by the relevant team and others can amplify your voice. Closing this issue for now.
