### ISSUE TITLE
Missing permission for updating an application in beta graph API

### ISSUE THREAD

**Issue by srjturner** [microsoftgraph/microsoft-graph-docs#1040]
Issue: The beta graph API introduces some operations on applications including the ability to update them. There is a section on the document for this operation that reads "The following scopes are required to execute this API:" but there is no value given. On the equivalent page for creating an application ([https://developer.microsoft.com/en-us/graph/docs/api-reference/beta/api/application_post_applications](https://developer.microsoft.com/en-us/graph/docs/api-reference/beta/api/application_post_applications)) the value is _Directory.AccessAsUser.All_ but experimentation suggests this does not work for updates on existing applications. I have also tried scoeps with _.default_, _Directory.AccessAsUser.All_ and _Application.ReadWrite.All_ but none of these work. My application has all possible permissions on the Graph API set and granted in the Azure portal. Please clarify what permission is needed.

Article: https://developer.microsoft.com/en-us/graph/docs/api-reference/beta/api/application_update

**Comment by dkershaw10** [comment]
Hi.  Thanks for pointing out this issue.  We're planning to make some major breaking changes to the Application APIs in /beta for Microsoft Graph.  We alluded to this [here](https://dev.office.com/blogs/microsoft-graph-or-azure-ad-graph) in the final section.  If you are planning to take a production dependency on the application APIs, you should not use /beta, and you should, for now, use AAD Graph API.

To answer your question on the permission.  There are 3 possible answers as to why this is not working:

1. You've granted all possible **delegated** permissions, but your app is using the client_credential application-only flow.
2. You've granted the Directory.AccessAsUser.All permission, but the user using the application **still** needs to be an administrator for this call to work.
3. In the Azure Portal you've selected all the **required** permissions, but not actually granted your app those permissions - either for you own tenant by clicking on the Grant Permissions button in the App Registration experience, OR because you have not consented to the app in the target tenant.

Hope this helps,
