### ISSUE TITLE
GET /groups/{id}/notes/sections/{id}/pages is giving wrong content URL for pages. The get on that request will is giving 400.

### ISSUE THREAD

**Issue by Prakashverma042** [microsoftgraph/microsoft-graph-docs#1074]
We are using onenote graph api extensively in our application. We do get section pages by calling this endpoint to get the list of pages.

GET /groups/{id}/notes/sections/{id}/pages

And then for every page we do a query on the contentUrl returned from the above request. This was working till last Friday fine. It does not work any longer and the reason is following.

The contentUrl returned from the above request for every pages is this.

https://graph.microsoft.com/beta/users/1666aff3-d025-479d-9792-3e645d3a9f20/onenote/pages/1-c7a8693bdd8a4e3ca9c784f159ac84e9!213-715180a6-df2a-49c8-ad43-83454d16b59d/content

If I replace the **onenote** from the url to **notes**, which is as per the documentation the call to this endpoint works fine(following url works)

https://graph.microsoft.com/beta/users/1666aff3-d025-479d-9792-3e645d3a9f20/notes/pages/1-c7a8693bdd8a4e3ca9c784f159ac84e9!213-715180a6-df2a-49c8-ad43-83454d16b59d/content

Please fix this ASAP, as this is failing a main important flow for our application.

**Comment by sharmajnu** [comment]
Please fix this ASAP, this has made our application non functional and we are forced to do a hotfix for this.

**Comment by natuamol** [comment]
Thanks for reporting the issue. The issue was fixed on 13th April.
One of our team member responded to your SO query here - http://stackoverflow.com/questions/43316725/get-groups-id-notes-sections-id-pages-is-giving-wrong-content-url-for-pages.
As communicated to your team in SO, we have now rolled out the updated Beta endpoint today. The documentation for the new endpoint and the changes can be found here - 
https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/onenote.md

**Thanks for being a OneNote Partner**
