### ISSUE TITLE
Does this endpoint work any more?

### ISSUE THREAD

**Issue by joshtransient** [microsoftgraph/microsoft-graph-docs#10762]
`https://graph.microsoft.com/v1.0/auditLogs/signIns/<guid>` always throws a 404 for me.
`https://graph.microsoft.com/v1.0/auditLogs/signIns?$filter=userId eq '<guid>'` works.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70120f36-0724-d3dc-aa32-58aa511cc750
* Version Independent ID: 5a88621e-13c3-d504-8b3b-36d27030b589
* Content: [Get signIn - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/signin-get?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/signin-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/signin-get.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @khotz
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
@joshtransient In the example in the docs, `https://graph.microsoft.com/v1.0/auditLogs/signIns/{id}` , `{id}` here refers to the unique id representing the sign-in activity, _not_ the `userId` (GUID). Also refer to the resource's [properties](https://docs.microsoft.com/en-us/graph/api/resources/signin?view=graph-rest-1.0#properties) table on this.

Please note that:

- Using the `id` of the sign-in activity will always return one record since every sign-in activity is unique. 

- You can also choose to filter by the `userId` (GUID) like in your second query, `https://graph.microsoft.com/v1.0/auditLogs/signIns?$filter=userId eq '<guid>'`. This will return all sign-in activities of the specified user.

I hope this clarifies the usage?

**Comment by joshtransient** [comment]
/sigh, shoulda read more carefully. Thx, closing.
