### ISSUE TITLE
Creating a team using SDK doesn't give the response.

### ISSUE THREAD

**Issue by vskvarma** [microsoftgraph/microsoft-graph-docs#10840]
Trying to create a Team using the below code.

```
var newTeam = new Team()
            {
                DisplayName = "TeamURL",
                Description = "TeamURL",
                AdditionalData = new Dictionary<string, object>()
                {
                    {"template@odata.bind", "https://graph.microsoft.com/v1.0/teamsTemplates('standard')"}
                },
                Members = new TeamMembersCollectionPage()
                {
                    new AadUserConversationMember
                    {
                        Roles = new List<String>()
                        {
                            "owner"
                        },
                        AdditionalData = new Dictionary<string, object>()
                        {
                            {"user@odata.bind", $"https://graph.microsoft.com/v1.0/users/1ab4e76f-5f52-44b8-8a72-7d03c05e6ff4"}
                        }
                    }
                }
            };

            Team team = await graphClient.Teams
                .Request()
                .AddAsync(newTeam);

            Console.WriteLine(team);

```
But it always gives null value in team variable.

![image](https://user-images.githubusercontent.com/65310468/100346086-4c6d4300-3009-11eb-9a4a-583e66bd4dff.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14650eac-eef3-e892-50ee-85e4692d21e9
* Version Independent ID: c7aeea07-12b6-45c9-8fb9-f942974811fa
* Content: [Create team - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/team-post?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/team-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/team-post.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Nikitha-MSFT** [comment]
When you create a team it will return only 200 okay response, You won't receive any details about the team, This is by design.

**Comment by vskvarma** [comment]
Looks like the document is not appropriate and I can't even catch the Status Code and the Location header using the above code, is there any solution for that?

**Comment by Nikitha-MSFT** [comment]
The status code will be shown in the graph explorer. Currently this is by design.

**Comment by thomasrothgrabx** [comment]
How can I find out when the team finished creating? and how can I get the teamsId?

**Comment by Nikitha-MSFT** [comment]
You can use get list joined teams API, Where you will all the teams list where you are member of the team. Please Check [List Joined Teams](https://docs.microsoft.com/en-us/graph/api/user-list-joinedteams?view=graph-rest-1.0&tabs=http)?

**Comment by thomasrothgrabx** [comment]
but how do I know the correct team? 
lets say I created a team with the displayName "Test"
but there is already a team with displayName "Test". 
When I fetch now all teams (or joined teams), I get two with the name "Test". So I have to guess which is the correct one.


In the docs it says it should have:
```
Location: /teams/{teamId}/operations/{operationId}
Content-Location: /teams/{teamId}
```
in the response. Do you know how I can access this information?
https://docs.microsoft.com/en-us/graph/api/team-post?view=graph-rest-1.0&tabs=http#response-1

**Comment by lrtoenjes** [comment]
I too, am wondering how to get the response when creating a Team through the .NET Graph SDK. It seems to me like it should be warranted that a developer would want to know the response of a call such as this. Otherwise, how am I to know the ID of the Team I just created, without using some sort of workaround?

For the time being, I am using  the `UnifiedGroupsUtility.GetUnifiedGroups()` method in the [PnP Framework](https://github.com/pnp/pnpframework) to get the group by `DisplayName`. Then I'm using the `GroupId` to get the Team that I just created.

In my use case I expect the `DisplayName` for each Team I create, to be unique, so I'm not running into the theoretical problem that @thomasrothgrabx has proposed. However, it still feels unnecessary to have to make two separate calls to get the object for the Team that I just created.

Another workaround that I can see, is to have some service account that you add as an initial owner for the Team you're creating and then [List Joined Teams](https://docs.microsoft.com/en-us/graph/api/user-list-joinedteams?view=graph-rest-1.0&tabs=csharp#http-request) for that user. Finally, filter that List by the `DisplayName` you're looking for.

If someone has a better way, I'm all ears.

**Comment by Nikitha-MSFT** [comment]
@thomasrothgrabx You need to give the unique name for each Team. And when you get the list of teams you will receive the created time in the response. You can differentiate using the create time.

**Comment by thomasrothgrabx** [comment]
@Nikitha-MSFT As @lrtoenjes said, there should be at least the ID in the response by design. 
The workaround you mentioned is error prone. As the displayName is not unique by design and creating a team is asynchronous. So it could happen that two teams are created at the same time with the same displayName. 

I found another workaround that works for me:

1. [Create a group](https://docs.microsoft.com/en-us/graph/api/group-post-groups?view=graph-rest-1.0&tabs=http) (here you get the groupId back)
2. Add groupId with teamProperties to a [storage queue](https://azure.microsoft.com/en-us/services/storage/queues/)
3. Function that listens on this storage queue: tries to [create a team from group](https://docs.microsoft.com/en-us/graph/api/team-post?view=graph-rest-1.0&tabs=http#example-4-create-a-team-from-group) (with a 10 sec delay between retries)
```
{
  "template@odata.bind": "https://graph.microsoft.com/v1.0/teamsTemplates('standard')",
  "group@odata.bind": "https://graph.microsoft.com/v1.0/groups('groupId')",
  ...teamProperties
}
```

Drawback: I have to validate the teamProperties myself.

All this just to create a team because:
POST /teams: 
- doesn't allow to add members (only 1 owner)
- doesn't return the teamId

**Comment by Nikitha-MSFT** [comment]
Currently when you create team it will not return the team id. This is by design.

**Comment by topa3b** [comment]
Agree, this is pretty much annoying. However you may retrieve underlaying GroupID right from [request responce](https://docs.microsoft.com/en-us/graph/api/team-post?view=graph-rest-1.0&tabs=http#example-4-create-a-team-from-group). 
Responce has headers:
```
HTTP/1.1 202 Accepted
Content-Type: application/json
Location: /teams/**{teamId}**/operations/{operationId}
Content-Location: /teams/**{teamId}**
Content-Length: 0
```

**Comment by lrtoenjes** [comment]
@topa3b You're correct in stating that the HTTP request response has the headers. HOWEVER, we're referring to the _.NET SDK_ here. The C# GraphClient method to create the team, does not have a return value. The header data we're looking for, is obfuscated behind that call.
