### ISSUE TITLE
Unclear how to get a reference to AuthorizationCodeProvider

### ISSUE THREAD

**Issue by Cisien** [microsoftgraph/microsoft-graph-docs#11067]
After following the steps in this document to create an IAuthenticationProvider instance for the Authorization Code flow of a confidential application, I am left with code that is unable to locate the AuthorizationCodeProvider class. 

Please update this documentation to document which nuget packages and namespaces I need to include in order to complete this exercise.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4537f77e-a8e8-e3f1-9cc4-2fd930db7ada
* Version Independent ID: 46396fa2-f7e2-322e-5e76-f9e2d17d1b48
* Content: [Choose a Microsoft Graph authentication provider - Microsoft Graph](https://docs.microsoft.com/en-us/graph/sdks/choose-authentication-providers?tabs=CS)
* Content Source: [concepts/sdks/choose-authentication-providers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/sdks/choose-authentication-providers.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @MIchaelMainer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by patanric** [comment]
I have the same problem for ClientCredentialProvider. It looks like these classes are available in `Microsoft.Graph.Auth` whitch is in preview since December 2020.

I think currently we have 2 options:

1. use MSAL es explained in [this Stackoverflow post](https://stackoverflow.com/a/56154921/4151472).
2. use the [preview assembly](https://www.nuget.org/packages/Microsoft.Graph.Auth) (1.5 milion downloads)

**Comment by jasonjoh** [comment]
The `Microsoft.Graph.Auth` package will never be release officially. With v4 of the Graph SDK, we've added support for the various credential classes from the `Azure.Identity` package. The recommendation here is to use the `AuthorizationCodeCredential`.
