### ISSUE TITLE
"Application.ReadWrite.OwnedBy" permission for Application permission doesn't allow ServicePrincipal update. 

### ISSUE THREAD

**Issue by frankchen76** [microsoftgraph/microsoft-graph-docs#11114]
Had a quick test on Application permission to update servicePrincipal. We need "Application.ReadWrite.All" permission. "Application.ReadWrite.OwnedBy" gave me permission error. Please remove "Application.ReadWrite.OwnedBy" for application permission. 

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c964cc2-808d-9cbf-0a1f-778b1017531d
* Version Independent ID: a7dc4262-533e-b866-e2c1-0663e7090dcb
* Content: [Update serviceprincipal - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/serviceprincipal-update?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/serviceprincipal-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/serviceprincipal-update.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @sureshja
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @frankchen76 for your feedback. `Application.ReadWrite.OwnedBy` permission will allow your application to update only apps and service principals for which it's an owner; Otherwise, please use use `Application.ReadWrite.All`. You can see more here 👉🏾 https://docs.microsoft.com/en-us/graph/permissions-reference#remarks-3.

No updates identified for the page for now. Closing the issue.
