### ISSUE TITLE
List of unallowed characters for the mailNickName is not complete

### ISSUE THREAD

**Issue by plamber** [microsoftgraph/microsoft-graph-docs#11129]
Hi,
The current description for the mailNickName states:
The mail alias for the group. Max. length: 64 characters. These characters cannot be used in the mailNickName: @()\[]";:.<>,SPACE. Required.

I accidentally failed to create a Group by using the characters §^°, which are not listed in the description above.

Are you going to update the documentation?

Cheers,
Patrick

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e7c37f6-ee5d-52a5-4db5-eee157bd3935
* Version Independent ID: 25cddb92-e198-16e9-635e-bc4dbd5587ac
* Content: [Create group - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/group-post-groups?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/group-post-groups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/group-post-groups.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @yyuank
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
@plamber 

Could you verify your query? I've tested this are I'm able to create a group with all three special characters in the **mailNickname** value. Please see below sample screenshots.

![mailNickname](https://user-images.githubusercontent.com/14026935/107749986-6b3bc580-6d2c-11eb-80a5-0717677e43b2.jpg)

No updates identified for the page. Closing the issue.

**Comment by plamber** [comment]
Hi, 
the issue still persists.

I am creating a Microsoft 365 Group with following name "test§^°group". I am receiving this error message:
![image](https://user-images.githubusercontent.com/18241305/107775409-86b0cb80-6d40-11eb-8d83-7986957ed0f3.png)

I am using the Graph .NET SDK for the tests.

br,
Patrick

**Comment by FaithOmbongi** [comment]
@plamber 
Noted. Seems this issue affects creation of M365 groups with the **mailNickname** having those special characters—because it also fails in Graph Explorer. Could be a bug that might need additional investigating.

Unfortunately, this channel is only for documentation issues and isn't monitored for functionality issues, but questions like this are monitored at [Microsoft Support](https://docs.microsoft.com/en-us/answers/search.html?type=question&q=microsoft-graph-*). Please ask your question there. There's a skilled team of Engineers ready to look further into this. Thank you for highlighting this issue.

**Comment by plamber** [comment]
@FaithOmbongi: thank you very much. Will ask the question there.

**Comment by plamber** [comment]
@FaithOmbongi: not sure if this is a bug. A Microsoft 365 Group provisions a SharePoint site with the URL which equals the mailnickname. The characters listed above are most likely not allowed in an URL for a shite. Therefore, this might fail.

I open a issue under Microsoft Support, but I believe this is by design
