### ISSUE TITLE
Improvement to resetpassword documentation

### ISSUE THREAD

**Issue by worksofliam** [microsoftgraph/microsoft-graph-docs#11284]
https://docs.microsoft.com/en-us/graph/api/passwordauthenticationmethod-resetpassword?view=graph-rest-beta&tabs=http

This page needs to document where the two IDs come from.

From some searching, I found [this page](https://docs.microsoft.com/en-us/graph/authenticationmethods-get-started), where on Step 4 has a get request where I can get those two IDs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe81600e-7193-3178-0e9c-44055f5138e4
* Version Independent ID: 19ba9c42-1b6d-5193-3d9e-64bcf668004f
* Content: [passwordAuthenticationMethod: resetPassword - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/passwordauthenticationmethod-resetpassword?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/passwordauthenticationmethod-resetpassword.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/passwordauthenticationmethod-resetpassword.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @mmcla
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by BakkerJan** [comment]
@worksofliam the password ID can be found with this API : https://docs.microsoft.com/en-us/graph/api/passwordauthenticationmethod-get?view=graph-rest-beta&tabs=http
The other ID is the the userID, but UserPrincipal Name works as well.

**Comment by FaithOmbongi** [comment]
Thank you @worksofliam for raising your issue. And thank you @BakkerJan for your response.

The design of the Microsoft Graph docs Table of Contents is such that all related Microsoft Graph APIs & their resources are grouped together in a node/sub-node. In addition, in queries where multiple `id`s are listed, the `id` is likely linked to the immediate preceding resource, unless stated otherwise. In this example, to [reset the user's password](https://docs.microsoft.com/en-us/graph/api/passwordauthenticationmethod-resetpassword?view=graph-rest-beta&tabs=http): 

         POST /users/{id | userPrincipalName}/authentication/passwordMethods/{id}/resetPassword

- The first `id` is the user's `id`. You can alternatively use their `userPrincipalName`.
- The second `id` is the **passwordMethod**'s id. You get it from the response you receive from running [List passwordMethods](https://docs.microsoft.com/en-us/graph/api/authentication-list-passwordmethods?view=graph-rest-beta&tabs=http) 👉🏾 `GET https://graph.microsoft.com/beta/{userPrincipalName}/authentication/passwordMethods`.

I hope this provides some clarity.

No updates identified for the page for now. Closing the issue.
