### ISSUE TITLE
Unable to call createToken from PowerShell to create/renew token.

### ISSUE THREAD

**Issue by timni-odk** [microsoftgraph/microsoft-graph-docs#11293]
I am attempting to call the /createToken endpoint, in order to create/renew the token for an AndroidEnterprise profile.
I am getting an HTTP 401 / Forbidden error.

Troubleshooting through Premier Support case yielded no solution, however I was informed that it worked when using GraphExplorer.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b2434d2-c334-026a-b5bf-7bf892705d9e
* Version Independent ID: f8b6a2ee-eca6-29ea-b9fa-79f2bc4c7523
* Content: [createToken action - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/intune-androidforwork-androidforworkenrollmentprofile-createtoken?view=graph-rest-beta)
* Content Source: [api-reference/beta/api/intune-androidforwork-androidforworkenrollmentprofile-createtoken.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/intune-androidforwork-androidforworkenrollmentprofile-createtoken.md)
* Product: **intune**
* Technology: **microsoft-graph**
* GitHub Login: @dougeby
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by pieewiee** [comment]
I get also get forbidden when trying to create a corporateOwnedFullyManaged device token.

**Comment by xmihux** [comment]
Same issue here with androidDeviceOwnerEnrollmentProfiles token.

**Comment by triplanedave** [comment]
Forbidden is typically a permissions issue.  What account role were you using?

**Comment by timni-odk** [comment]
> Forbidden is typically a permissions issue. What account role were you using?

The application permission specified in the MS documentation: DeviceManagementConfiguration.ReadWrite.All

https://docs.microsoft.com/en-us/graph/api/intune-androidforwork-androiddeviceownerenrollmentprofile-createtoken?view=graph-rest-beta

**Comment by timni-odk** [comment]
I have an ongoing premier support case going on this issue - however no satisfactory solution has been found yet.

**Comment by triplanedave** [comment]
Was that the only permission your app has?  I would also expect DeviceManagementManagedDevices.Read.All to be required. If you have a new repro with an ActivityID or RequestID reported in the error, I can take a look and see whether I can help with more info.

**Comment by anasimao** [comment]
hey @triplanedave , I'm currently working with @timni-odk  on the support case mentioned.
I did some tests around this endpoint and I was able to reproduce the issue even with an user and using the Graph Explorer.

The docs for the endpoint only mention teh DeviceManagementConfiguration.ReadWrite.All permission, but even including additional permissions like: DeviceManagementConfiguration.Read.All, Device.Read.All DeviceManagementApps.Read.All DeviceManagementApps.ReadWrite.All   DeviceManagementManagedDevices.PrivilegedOperations.All DeviceManagementManagedDevices.Read.All DeviceManagementManagedDevices.ReadWrite.All DeviceManagementRBAC.Read.All DeviceManagementRBAC.ReadWrite.All DeviceManagementServiceConfig.Read.All DeviceManagementServiceConfig.ReadWrite.All DeviceManagementServiceConfiguration.ReadWrite.All 

I was only able to make a successful request when using an user with Global Administrator role assigned. 
This shows that the operation might require some additional role on top of the  DeviceManagementConfiguration.ReadWrite.All, DeviceManagementManagedDevices.Read.All permissions.

Could you confirm if that's the case?

**Comment by triplanedave** [comment]
Two things to verify: 
1) can you POST to ~/deviceManagement/androidDeviceOwnerEnrollmentProfiles - that should require the same permissions as the createToken.
2) can you try this endpoint instead: https://docs.microsoft.com/en-us/graph/api/intune-androidforwork-androiddeviceownerenrollmentprofile-createtoken?view=graph-rest-beta

**Comment by anasimao** [comment]
I did some further tests as requested:

All the tests had the same results for the endpoints: 
POST https://graph.microsoft.com/beta/deviceManagement/androidForWorkEnrollmentProfiles/{id}/createToken
POST https://graph.microsoft.com/beta/deviceManagement/androidDeviceOwnerEnrollmentProfiles/{id}/createToken
POST https://graph.microsoft.com/beta/deviceManagement/androidDeviceOwnerEnrollmentProfiles

I tested with both a user and an application token.

**Application Scenario:**
Using just the permissions: DeviceManagementConfiguration.ReadWrite.All, DeviceManagementManagedDevices.Read.All
Resulted in the same forbidden error

**Granting Intune Administrator role to the service principal does not help, and still resulted in the same forbidden error.**

Since the roles are applied to the SP object and not the Application object, those roles are probably not taken into account when using client credentials to authenticate

I've also tried to grant every Application permission related to Devices, and still got the same Forbidden error

**User Scenario:**

Using just the permissions: DeviceManagementConfiguration.ReadWrite.All, DeviceManagementManagedDevices.Read.All
Resulted in the same forbidden error

**In order to do the referred operations the user had to be assigned with the Intune Administrator role (or a more privileged one like Global Admin)**

Note:  Cloud Device Admin role is not enough

**Comment by timni-odk** [comment]
> 2\. https://docs.microsoft.com/en-us/graph/api/intune-androidforwork-androiddeviceownerenrollmentprofile-createtoken?view=graph-rest-beta

Hi Dave..
Sorry for not noticing your message  before now :)
I was not able to post to the endpoint - received a 400 BadRequest, but I expected that.
It is the endpoint mentioned in the documentation you link to in bullet 2, that I have been using.

/Tim
