### ISSUE TITLE
Person Card not positioned correctly with Person component inside parent element with CSS transform()

### ISSUE THREAD

**Issue by MarkyDeParky** [microsoftgraph/microsoft-graph-docs#11562]
I was trying out the Person and Person Card components of the Graph Toolkit inside an SPFx web part. 
In this web part I use a grid component (react-grid-layout) to drag and drop elements around a grid. This grid component handles positioning of these grid elements using a combination of CSS attributes `position:absolute` and `transform: translate([x]px, [y]px)` to position them in the grid.

Now the problem is that if I use the mgt-person component (in my case from the MGT React library), the positioning of the flyout Person Card is not correct. It's way too far to the right and to the bottom and not nicely rendered below the person's avatar as supposed to.

I found out that the issue is caused by the CSS `transform` property used in a (or any) parent element. Apparently, using `transform` creates a new 'context' for child nodes to position themselves using `position:fixed` instead of the default 'viewport' (being the browser window/document) ([more on this here](https://stackoverflow.com/questions/36855473/position-fixed-not-working-is-working-like-absolute/36857029)). Because using `position:fixed` is how the Person component positions its child PersonCard component, positioning is not as expected in my scenario. 

I was wondering why I wasn't facing these positioning issues with other flyout components, like the Fluent UI components Tooltip or [Callout](https://developer.microsoft.com/en-us/fluentui#/controls/web/callout). I appears that these components put their flyout elements in the root of the DOM instead of as a child element somewhere deep in the DOM.

My question is:
- Could this be considered a bug or maybe a case for improvement? Can I help in any way?
- Given the current scenario, what would be a good approach to get around this?

Thanks!

Mark.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3b7efaf-8cb2-c191-8ec4-7ae9f375878d
* Version Independent ID: 90601657-f79a-1d58-4f4e-69187c3dd018
* Content: [Person component in the Microsoft Graph Toolkit - Microsoft Graph](https://docs.microsoft.com/en-us/graph/toolkit/components/person)
* Content Source: [concepts/toolkit/components/person.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/toolkit/components/person.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @nmetulev
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by nmetulev** [comment]
Hi @MarkyDeParky, you've perfectly summarized the issue with fixed positioning we are running into with our flyout (apparently it's a css feature :( ). This is definitely a bug we need to fix, currently [tracking here](https://github.com/microsoftgraph/microsoft-graph-toolkit/issues/877)

In terms of approach, since we are working with web components, ideally the flyout content will remain part of the component tree and not in the root of the body. I'm also not sure how our templating support will break by moving the flyout to the root. The solution I've been considering but haven't investigated yet was to add validation of the positioning of the flyout after layout and readjust the position if the flyout renders outside of where it is supposed to be. Any thoughts whether something like this could work?

**Comment by MarkyDeParky** [comment]
Hi @nmetulev, thanks for the prompt reply.

> The solution I've been considering but haven't investigated yet was to add validation of the positioning of the flyout after layout and readjust the position if the flyout renders outside of where it is supposed to be.

That could work, although I wonder how you'd prevent flickering while repositioning (rendering in the wrong position for a ms and then re-render in the right position)... 

Could it be an idea to traverse up the DOM to find the first parent that uses a `transform` style other than '' or 'none' and use that element's position (from `getBoundingClientRect()`) and deduct its `x` (or `left`) and `y` (or `left`) in your calculations beforehand and immediately use the corrected `left` and `top` values?

Something (rudimentary) like this:
```
const findFixedPositionContainer = (el) => {
    if (!el.parentElement) {
        return document.body;
    }
    if (el.parentElement.style?.transform && el.parentElement.style?.transform !== 'none') {
        return el.parentElement;
    }
    return recurseParentNodes(el.parentElement);
}
```

However, I do wonder if you'd be done if you solve this positioning issue, as I suspect you might have similar issues with the `z-index` style attribute. This index relies on the so called [stacking context](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context) to determine its rendering order. In other words, just giving the flyout a very high `z-index` won't automatically put the item always on top, which you do probably want for the fly-out. This might also be a reason to put the flyout in the root, as the Fluent UI team did with all of their 'floating' surfaces... I'm not familiar with your templating support yet so I'm not sure what the consequences would be on that end...

**Comment by nmetulev** [comment]
I agree the ideal solution is to move the flyout to the root, but this will be a bigger undertaking we will have to do when we go to our next major update.

In the meantime, I created a PR to add a workaround similar to what we are discussing here. Instead of traveling up the tree, I created two zero sized divs in the flyout (I call them scouts) and I position them at two opposing corners. This allows me to validate their positions ahead of time and detect when the stacking context has been changed and account for it. The PR is [here](https://github.com/microsoftgraph/microsoft-graph-toolkit/pull/921/files), let me know what you think.

I'll go ahead and close this issue however since we have the other issue on the main repo and the PR open, feel free to comment and review in the open PR.
