### ISSUE TITLE
"full_access_as_app" is missing from the enumeration of supported permissions

### ISSUE THREAD

**Issue by glennvanrymenant** [microsoftgraph/microsoft-graph-docs#12020]
The application permission "full_access_as_app" for EWS is not listed but can also be scoped using application access policies as per this communication from the EXO PG: https://techcommunity.microsoft.com/t5/exchange-team-blog/application-access-policy-support-in-ews/ba-p/2110361

Tested.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ca1eed2-d0ca-11de-4f25-f09865605a0f
* Version Independent ID: 9fd423e0-86e4-b7e4-9249-1bacb51e81ad
* Content: [Scoping application permissions to specific Exchange Online mailboxes - Microsoft Graph](https://docs.microsoft.com/en-us/graph/auth-limit-mailbox-access)
* Content Source: [concepts/auth-limit-mailbox-access.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/auth-limit-mailbox-access.md)
* Product: **applications**
* Technology: **microsoft-graph**
* GitHub Login: @abheek-das
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jasonjoh** [comment]
Thanks for opening an issue @glennvanrymenant. As you noted, that's an EWS permission, not a Graph permission. I think it would be confusing to list that permission in this topic since it has no bearing on Graph.

There is an open issue on the EWS documentation to add access policy information to [this page](https://docs.microsoft.com/exchange/client-developer/exchange-web-services/how-to-authenticate-an-ews-application-by-using-oauth). See https://github.com/MicrosoftDocs/office-developer-exchange-docs/issues/125
