### ISSUE TITLE
Missing nextlink and unsupported query parameters

### ISSUE THREAD

**Issue by ahbuddha** [microsoftgraph/microsoft-graph-docs#12043]
I work at a large company that can have applications with roles exceeding a thousand.
The claims token response only returns 999 roles so I was going to use MS graph when a user exceeds that limit.

When using the 'List appRoleAssignments granted to a user' and setting the '$top' to its maximum - the request does not include a nextLink in the response and the documentation says that it supports 'OData query parameters' but when I try to use skip, it comes back with an error.

Because of this limitation with MS graph, claims tokens and AAD - I am looking for an alternative outside of the MS ecosystem.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9258fed6-3de6-6c70-babe-b9595b205c85
* Version Independent ID: dbc979c2-dfdb-a252-f57e-9790375f6f9e
* Content: [List appRoleAssignments granted to a user - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-list-approleassignments?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/user-list-approleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-list-approleassignments.md)
* Product: **users**
* Technology: **microsoft-graph**
* GitHub Login: @psignoret
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by psignoret** [comment]
@ahbuddha Thanks for you feedback. 

We're adding support for paging to the queries to list a user, group or service principal's app role assignments in the coming months. However, it is very rare for this to be necessary for the scenario you describe. A token will only ever contain `roles` claim values for app roles that were defined on the service for which the token was issued—the audience of the token. Are you saying you have a single service which has more than 999 app roles defined, and all/most of them are assigned to a single user?

**Comment by ahbuddha** [comment]
@psignoret thanks for responding.

I am part of a team that is remediating a large number of applications. Some of these applications will have over a thousand roles; at this moment in time though, I haven't seen an application with a single user exceeding the 999 limit. I am trying to test the edges and get a better understanding of claims token size constraints and MS graph functionality so I can better educate the application teams.

**Comment by psignoret** [comment]
While theoretically possible, it is highly unlikely in a real-life scenario for a single user to be assigned more than 999 app roles for a single app. (In fact, it is highly unlikely for a single app to have that many different app roles in the first place, as doing so will put you close to the total number of values (across all properties) on a single app registration.)

If you need to query for a user's app role assignments to a single app, be sure to filter by the resource app's service principal:

```http
GET /v1.0/users/{id}/appRoleAssignments?$filter=resourceId eq {sp-id}&$top=999
```

In all but the most extreme cases, this will return all assignments to the user with **id** `{id}` for the app with service principal **id** `{sp-id}`.

Support for paging for this request will be added in the coming months.

**Comment by ahbuddha** [comment]
As stated above, many of the applications we are remediating exceed a thousand roles (these are large enterprise facing applications); for instance, one application has hundreds of different regions with many dimensions tied to each region and when flattened out, is well beyond a thousand. Some of our team members are in direct communication with MS FTEs and they too have apps that exceed a thousand roles, so not to "unlikely" at all.

I am using the above query already and as you point out - it will have paging soon

**Comment by psignoret** [comment]
Azure AD today does not support more than ~1000 app roles. So even if an application or service _internally_ has the concept of several thousand roles, those roles cannot currently be represented as app roles on one app registration in Azure AD. 

With that constraints in mind, it is highly unlikely that _a single user_ would be assigned more than the 999 app roles for a single service, making the fact that we do not currently support paging past the first 999 app role assignment irrelevant in the scenario you described in the original post. (It's irrelevant because you can't even define more than ~1000 roles, and the likelihood of a single user being assigned all of the roles is low.)

To address the remaining scenarios (e.g. listing all app role assignments (not only the ones for one app)), we will be adding support for paging beyond the first 999 in the coming months.

**Comment by ahbuddha** [comment]
I was able to create 1,200 app roles and assign them to 1,200 different groups respectively. Below is a call to the service principal demonstrating just that
![image](https://user-images.githubusercontent.com/5024922/112031918-16dcf000-8af9-11eb-9465-0bb087e888a4.png)

**Comment by psignoret** [comment]
Yes, that's the "~" in in "~1000". The actual limit will be affected by the number of other properties with values on them (e.g. redirect URLs, pre-authorized applications, identifier URIs, required permissions, delegated permission definitions, etc.).

Again, it is highly unlikely any single user would have all ~1000 (1200, in your example) app roles assigned. (I'm saying "highly unlikely" because it's theoretically possible, I've just never come across a real-life scenario where anyone has actually done this).

Closing this issue, as the original issue has been answered.

**Comment by ahbuddha** [comment]
Can you point me to the documentation that supports the claim "Azure AD today does not support more than ~1000 app roles" for I am dealing with many applications that will exceed that limit

Thanks

**Comment by psignoret** [comment]
This documents most limits at a high level: https://docs.microsoft.com/azure/active-directory/enterprise-users/directory-service-limits-restrictions. The limit we're discussing here is included in the "Application Manifest" limit which states:

> A maximum of 1200 entries can be added in the Application Manifest.
