### ISSUE TITLE
Object Hierarchy in v1.0 reference is inconsistent.

### ISSUE THREAD

**Issue by WieserSoftware** [microsoftgraph/microsoft-graph-docs#12114]
The events object is not visible when starting from here:
https://docs.microsoft.com/en-us/graph/api/resources/calendar?view=graph-rest-1.0

Yet the calendar object appears on this page.  Is there a way to explore the whole hierarchy that I'm missing?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b41a9857-98a9-e400-d7ce-bd7c0f37cd46
* Version Independent ID: b8b43aa7-df77-3203-7191-43a86297e835
* Content: [event resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/event.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/event.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @Harini84
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by WieserSoftware** [comment]
To be clear, it's the navigation on the left side where this page is rendered that is incorrect, not the page itself.

**Comment by Harini84** [comment]
@angelgolfer-ms 
Kindly check and help with this navigation issue in documentation.

**Comment by angelgolfer-ms** [comment]
Hi @WieserSoftware , thanks for your input.
FYI I added a link to "event" in the first sentence of the [calendar](https://docs.microsoft.com/en-us/graph/api/resources/calendar) resource topic, which appears as the first topic under "Users" >> "Calendar".
Hope that would make it more convenient to navigate from the calendar resource topic to the event resource topic.

By design, we don't repeat the entire set of resource and API topics under "Users" >> "Calendar", as compared with under "Calendar", otherwise the "Users" node would be extremely large, considering the many relationships of the user resource. We're afraid a huge table of contents would make navigating unwieldy. We try to provide a subset that makes it apparent that one can navigate from the user resource to each of these relationships, including the calendar API; customers can then further link from one topic to another.

Thank you again for your input.  My update is in PR #12189 . The fixes will be published within the next day.
