### ISSUE TITLE
[Doc-Bug] Example 2: Create an online meeting in a Microsoft Teams channel with a user token

### ISSUE THREAD

**Issue by SubbaReddi** [microsoftgraph/microsoft-graph-docs#12179]
Creating online meeting in MS Teams channel is working fine. But the meeting link which is posted in channel is not clickable. It seems it is expected behavior and known issue. If note can be added to documentation, it helps.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb82ac27-1e14-06dd-21b2-7238162fe68c
* Version Independent ID: 6cc4993f-2ae8-9b39-0bee-01dfb44d125b
* Content: [Create onlineMeeting - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/application-post-onlinemeetings.md)
* Product: **cloud-communications**
* Technology: **microsoft-graph**
* GitHub Login: @jsandoval-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by frankpeng7** [comment]
Hi @SubbaReddi If you were referring to the issue that channel meeting created via Graph API is not clickable (the meeting details page won't open), please rest assured that we are actively working on it. This should not be the expected behavior so we try not to declare that in the documentation and set the wrong expectation. (Please also note that /beta APIs are potentially unstable and subject to change). We'll consider updating the documentation if the issue cannot be fixed in the near future. Thank you for the suggestion! :)

**Comment by frankpeng7** [comment]
Closing as the item is being tracked in our backlog.
