### ISSUE TITLE
MS Graph Report doesn't return any result

### ISSUE THREAD

**Issue by devagnanam** [microsoftgraph/microsoft-graph-docs#12232]
[I tried using the API using v1.0 and beta in Graph Explorer, but it doesn't return any result/output. Adding snapshot for reference]
![image](https://user-images.githubusercontent.com/18620816/113955271-06d34900-9839-11eb-975b-138b8769b392.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3f31aac-34f8-0207-68fb-ab49772d51f6
* Version Independent ID: 995b9526-52d2-c2ee-e0a3-1d8506925f11
* Content: [reportRoot: getOneDriveUsageFileCounts - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/reportroot-getonedriveusagefilecounts?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/reportroot-getonedriveusagefilecounts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/reportroot-getonedriveusagefilecounts.md)
* Product: **reports**
* Technology: **microsoft-graph**
* GitHub Login: @sarahwxy
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by isvargasmsft** [comment]
Hello, 

My apologies for the delay in my response and thank you very much for your question.

The CSV format response cannot be successfully called from Graph Explorer due to CORS (Cross-Origin Resource Sharing). 

JSON format in beta API can support query from Graph Explorer. It's still okay to query API with CSV format in programming way.

Closing this issue as answer was provided. Please ask any future questions about Microsoft Graph at [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/questions/ask.html).

**Comment by devagnanam** [comment]
Thank you @isvargasmsft !!
