### ISSUE TITLE
Example Request URL does not work

### ISSUE THREAD

**Issue by quickwick** [microsoftgraph/microsoft-graph-docs#12254]
The example Request URL ( https://graph.microsoft.com/v1.0/reports/getSharePointSiteUsageDetail(period='D7') ) does not work. It provides no response. The working URL is https://graph.microsoft.com/beta/reports/getSharePointSiteUsageDetail(period='D7')?$format=application/json

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59129223-e77a-6b04-7a7c-0e81aac80f32
* Version Independent ID: 9d5b533b-08fc-f043-333d-8d0f02c8d485
* Content: [reportRoot: getSharePointSiteUsageDetail - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/reportroot-getsharepointsiteusagedetail?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/reportroot-getsharepointsiteusagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/reportroot-getsharepointsiteusagedetail.md)
* Product: **reports**
* Technology: **microsoft-graph**
* GitHub Login: @sarahwxy
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by isvargasmsft** [comment]
Hello, 

My apologies for the delays in my response. 

The CSV format response cannot be successfully called from Graph Explorer due to CORS issue. JSON format in beta API can support query from Graph Explorer. It's still okay to query API with CSV format in programming way.

Closing this issue as answer was provided. Please ask any future questions about Microsoft Graph at [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/questions/ask.html).
