### ISSUE TITLE
Filtering options not applicable to group listings

### ISSUE THREAD

**Issue by betuxy** [microsoftgraph/microsoft-graph-docs#12905]
I've seen the example to list all groups where the Type equals Microsoft365('Unified')
https://graph.microsoft.com/v1.0/groups?$filter=groupTypes/any(c:c+eq+'Unified')
Also another page states ne (not equal) is valid. However I didn't 
find a way to create a query which gets all Groups where the type is not
 Unified. I feel the documentation doesn't make quite clear how the 
/any(c:c [...]) works.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ce8c6d8-bc9a-1caa-37d8-0ebee8460236
* Version Independent ID: 1668bd18-63b3-6b21-d9c8-2706cb654e61
* Content: [List groups - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/group-list?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/group-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/group-list.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @Jordanndahl
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @betuxy for raising this issue. The `ne` operator is not supported on groupTypes, but `not` is. Use the following syntax and add the **ConsistencyLevel** header with the value `eventual`.

[https://graph.microsoft.com/v1.0/groups?$filter=not groupTypes/any(x:x eq 'Unified')&$count=true](https://developer.microsoft.com/en-us/graph/graph-explorer?request=groups%3F%24filter%3Dnot%20groupTypes%2Fany(x%3Ax%20eq%20'Unified')%26%24count%3Dtrue&method=GET&version=v1.0&GraphUrl=https://graph.microsoft.com&headers=W3sibmFtZSI6IkNvbnNpc3RlbmN5TGV2ZWwiLCJ2YWx1ZSI6ImV2ZW50dWFsIn1d)

We're working to provide additional guidance for `$filter` on collections. Hopefully, it'll be soon.

cc: @Licantrop0 for visibility

**Comment by Licantrop0** [comment]
@FaithOmbongi `ne` operator is supported on every directory object property using the advanced queries capabilities, but it doesn't make sense to be used inside an `any` operator.
The `any` operator means "go through the items in the list one by one and return true as soon as you find one matching the condition, otherwise return false"
If you use Not Equal for the contrition, it's like saying:
"Is ANY of the ITEMS in the list NOT equal to 'foo'?". That will *only* return false if the list is made by 1 item equal to 'foo' or all items are equal to 'foo'. In any other case it will return true.

The query using NOT like you suggested is the correct way to do this!
