### ISSUE TITLE
Example 3: 'GET https://graph.microsoft.com/v1.0/users/$count' should be 'GET https://graph.microsoft.com/v1.0/users?$count'

### ISSUE THREAD

**Issue by kamiyn** [microsoftgraph/microsoft-graph-docs#13630]
Example 3:

`GET https://graph.microsoft.com/v1.0/users/$count
`

should be

`GET https://graph.microsoft.com/v1.0/users?$count
`

That is '/' before '$' should be '?'.

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: fabdb652-eb03-bae6-fa99-66d71fbdd044
* Version Independent ID: 7f5744b6-6770-586e-217c-4b7ac7657051
* Content: [ユーザーを一覧表示する - Microsoft Graph v1.0](https://docs.microsoft.com/ja-jp/graph/api/user-list?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs.ja-JP/blob/main/api-reference/v1.0/api/user-list.md)
* Product: **users**
* Technology: **microsoft-graph**
* GitHub Login: @jpettere
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @kamiyn for raising this issue. `/count` is correctly applied in example 3 which seeks to return _only_ a raw count of users. Here, `$count` is used as a [URL path segment](https://docs.microsoft.com/en-us/graph/query-parameters#other-odata-url-capabilities).

Your suggestion to use `$count` after **?** is also correct, but for a different output. In this instance, `$count` would be used as a [query string](https://docs.microsoft.com/en-us/graph/query-parameters#count-parameter) and, 

+ Returns a list of users.
+ Because no value is assigned to it, it defaults to **false** (that is, `?$count=false`); therefore, no count of users is returned.  If you assign true (that is, ?$count=true), the count of users is returned together with the user objects. This count is shown by an **@odata.count** property in the response payload. [Try in Graph Explorer](https://developer.microsoft.com/en-us/graph/graph-explorer?request=users%3F%24count%3Dtrue&method=GET&version=v1.0&GraphUrl=https://graph.microsoft.com&headers=W3sibmFtZSI6IkNvbnNpc3RlbmN5TGV2ZWwiLCJ2YWx1ZSI6ImV2ZW50dWFsIn1d).

Hope that clarifies the example.
