### ISSUE TITLE
URL suffix required for the DriveItem PATCH to work

### ISSUE THREAD

**Issue by estrelow** [microsoftgraph/microsoft-graph-docs#13787]
[Enter feedback here]

Apparently the DriveItem PATCH method is merged with the ListItem PATCH. So, the URL that actually works as described is /drives/{drive-id}/items/{item-id}/ListItem/fields. The GET method also allows to read the item's metadata. The /ListItem after the DriveItem is likely the tweak to work with ListItem resource JSON applied to a DriveItem.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7283df5-a0b0-9bea-597c-83c043e7f08a
* Version Independent ID: 470d11d2-c91e-1970-5413-c1bf614b8ae6
* Content: [Update a file or folder - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/driveitem-update?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/driveitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/driveitem-update.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by JeremyKelley** [comment]
This kind of depends on which properties you want to PATCH.  The examples in the doc are correct for updating properties of the DriveItem object.  When you add the /ListItem/fields to the URL you're basically doing a cast from the DriveItem to its ListItem representation, since the underlying SharePoint fields are exposed through the ListItem model you would use that path to update them as a shortcut to going back up the object tree to access the List instead of the Drive.

This topic should likely be expanded on somewhere in the docs but I'm not sure if the Update docs are the right place.

Thank you for the feedback!
