### ISSUE TITLE
What happens to AzureAD PowerShell?

### ISSUE THREAD

**Issue by RobdeJong** [microsoftgraph/microsoft-graph-docs#13950]
AzureAD PowerShell depends on AAD Graph. Will my AzureAD PowerShell stop working after June 30th, 2022? If so, where can I find your migration guidelines for my PowerShell scripts to MSGraph PowerShell?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6d1b3bf-715e-a187-7086-b2ea3b3cd90b
* Version Independent ID: a1c1d3a4-bbaf-4503-3769-52103816679a
* Content: [Azure Active Directory (Azure AD) Graph to Microsoft Graph migration FAQ - Microsoft Graph](https://docs.microsoft.com/en-us/graph/migrate-azure-ad-graph-faq)
* Content Source: [concepts/migrate-azure-ad-graph-faq.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/migrate-azure-ad-graph-faq.md)
* Product: **applications**
* Technology: **microsoft-graph**
* GitHub Login: @FaithOmbongi
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by kimaniderrick** [comment]
@RobdeJong Due to the Graph deprecation, AAD PowerShell will be affected come June 2022. However, we are currently working on customer experience parity between the AAD and MS graph PowerShell to allow the customer to migrate their old scripts to the new module. We will also provide migration documentation with new cmdlets descriptions and examples to help with the migration. We will be communicating soon on where we are in regards to these efforts to prepare our customers for the next steps.

**Comment by FaithOmbongi** [comment]
Thank you @RobdeJong for raising this question & @kimaniderrick for the feedback. Rob, further communication as advised by Derrick will include via the [Microsoft Graph: Developer Blog](https://developer.microsoft.com/en-us/graph/blogs/).
