### ISSUE TITLE
Getting 500 error status code, when trying to remove certificate password via removeKey API

### ISSUE THREAD

**Issue by blackadi** [microsoftgraph/microsoft-graph-docs#13960]
When using this API to remove certificate password, a 500 status code was thrown.
![image](https://user-images.githubusercontent.com/16793335/130567974-fcff223e-b25b-4a48-bf88-32f41e9533c2.png)

![image](https://user-images.githubusercontent.com/16793335/130568084-be08ea33-fc3b-4910-85b3-76aab4e40536.png)

Then, I realized that I have to use [removeKey API ](https://docs.microsoft.com/en-us/graph/api/serviceprincipal-removekey?view=graph-rest-1.0&tabs=http) for this to work.

So getting 500 error code is expected here!?. 

It's somehow misleading, isn't 4xx - Client Error more informative since it's a bad request from my side (the requester) not MS back-end.

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4665a014-4bfe-afdb-c393-eec0d37bdf33
* Version Independent ID: bdac9c34-67f3-6c69-fe47-82a57eb643e2
* Content: [servicePrincipal: removePassword - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/serviceprincipal-removepassword?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/serviceprincipal-removepassword.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/serviceprincipal-removepassword.md)
* Product: **applications**
* Technology: **microsoft-graph**
* GitHub Login: @sureshja
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @blackadi for raising this issue. I believe I understand your point of view that the error message should be a bit more intuitive, in your case, correctly flagging client errors. Unfortunately, this forum is only for documentation bugs/gaps but, you may file this either as a product issue at [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/topics/microsoft-graph-applications.html) or as a feature request at [Microsoft 365 Developer Platform](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform/label-name/Microsoft%20Graph). 

Closing this issue here.
