### ISSUE TITLE
List notebooks doesn't return me the shared notebooks

### ISSUE THREAD

**Issue by vJianche** [microsoftgraph/microsoft-graph-docs#1402]
Thank you for helping us to improve the Microsoft Graph documentation.

So that we can better assist you, please note the following:
- If you have a question, need help, or are experiencing an issue with your code, we encourage you to post your question or issue on **Stack Overflow**. Tag your question with [microsoftgraph](http://stackoverflow.com/questions/tagged/microsoftgraph) or [Office 365](http://stackoverflow.com/questions/tagged/microsoftgraph).
- If you have a feature suggestion, please post your idea on our [**User Voice**](https://officespdev.uservoice.com/) page, and vote for your suggestions there.
- If you have an issue with the documentation, please provide the information here, or feel free to submit a pull request with your suggested changes. We will review your contributions and update our documentation accordingly.

------------
 
Issue: List notebooks doesn't return me the shared notebooks

Article:

**Comment by vJianche** [comment]
I have team onenote but I can't get the id from listing my onenotes..

**Comment by jstnbchnn** [comment]
@garethj-msft do you happen to have an update on this?

**Comment by mlafleur** [comment]
Currently the API doesn't return "shared" notebooks, at least not in the way one might expect. While it can access notebooks that are shared with the current user, there isn't a consolidated listing of them. 

Let's say JohnDoe@contoso.com has 3 Notebooks and has shared just one of them with me. If I were to request `/me/onenote/notebooks`, I wouldn't see the shared Notebook.  In order to see them, I need to reference the User or Group in my request. So calling `/users/JohnDoe@contoso.com/onenote/notebooks`  would return the single shared notebook. 

There is a less than exciting workaround to this issue using the OneDrive API. Shared Notebooks _will_ surface using the `/me/drive/sharedWithMe` endpoint. There is very limited support for query params with `sharedWithMe` so you should expect to pull the entire list for processing on your end. You can find OneNote by looking at the `remoteItem` resource, and inspecting the `package/type` property. If it is a OneNote Notebook, the type will be `onenote`:

``` 
{
   // ...
  "remoteItem": {
    // ...
    "package": {
      "type": "oneNote"
    }
  }
}

```

**Comment by jstnbchnn** [comment]
@mlafleur if I use the `sharedWithMe` endpoint, will it be paged? And if so, after how many items?

**Comment by garethj-msft** [comment]
Can you assign this to manjushm-microsoft  please as she owns the OneNote API.

**Comment by jthake-msft** [comment]
This is a feature request. As per the issue template creation process, feature requests should be added to UserVoice. https://developer.microsoft.com/en-us/graph/support

This issues lists is specifically for documentation issues, not the underlying service, sdks or samples. I will close this issue so our documentation team can focus on content issues.
The official channel for questions is StackOverflow with '[microsoft-graph](https://stackoverflow.com/questions/tagged/microsoft-graph
)' tag.
For issues, you can raise a support ticket on the Azure Portal where you registered your application. This [simple video](https://twitter.com/jthake/status/1030489336439959553) shows how to file it properly by visiting [here](https://portal.azure.com/#blade/Microsoft_Azure_Support/HelpAndSupportBlade/overview).
