### ISSUE TITLE
Query on meaning of ID

### ISSUE THREAD

**Issue by tkudya** [microsoftgraph/microsoft-graph-docs#14162]
[Enter feedback here]
 What does the ID mean? is it related to an update and how do i know what update it's actually related to? i.e the actually name instead of just the ID

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5f6807e-8775-64b4-d176-0ffafbdf79e2
* Version Independent ID: d208e5f1-9d7b-0059-a488-31915e8ab0be
* Content: [catalogEntry resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/windowsupdates-catalogentry?view=graph-rest-beta)
* Content Source: [api-reference/beta/resources/windowsupdates-catalogentry.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/windowsupdates-catalogentry.md)
* Product: **w10**
* Technology: **microsoft-graph**
* GitHub Login: @Alice-at-Microsoft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Alice-at-Microsoft** [comment]
Hi @tkudya --

The ID property on [catalogEntry](https://docs.microsoft.com/en-us/graph/api/resources/windowsupdates-catalogentry?view=graph-rest-beta) is an identifier for the catalogEntry resource. The ID itself is not related to the update itself.

In order to get information about the update itself, note that catalogEntry is the base type for [softwareUpdateEntry](https://docs.microsoft.com/en-us/graph/api/resources/windowsupdates-softwareupdatecatalogentry?view=graph-rest-beta), which is a base type for [featureUpdateCatalogEntry](https://docs.microsoft.com/en-us/graph/api/resources/windowsupdates-featureupdatecatalogentry?view=graph-rest-beta) and [qualityUpdateCatalogEntry](https://docs.microsoft.com/en-us/graph/api/resources/windowsupdates-qualityupdatecatalogentry?view=graph-rest-beta).

On featureUpdateCatalogEntry and qualityUpdateCatalogEntry, you'll see the displayName property, as well as some other properties that describe the update itself.

When you [list catalog entries](https://docs.microsoft.com/en-us/graph/api/windowsupdates-catalog-list-entries?view=graph-rest-beta&tabs=http), all entries that are returned have a displayName property (see [this example](https://docs.microsoft.com/en-us/graph/windowsupdates-deploy-update?view=graph-rest-beta#step-1-optional-get-a-list-of-deployable-updates)).
