### ISSUE TITLE
Clarification on Licenses included in list of subscribed Sku

### ISSUE THREAD

**Issue by dwanjuhi** [microsoftgraph/microsoft-graph-docs#14164]
A customer added an app license to their tenant and could see it on their admin portal under licenses and on their admin portal on power platform.

This license does not appear when they list all licenses using the graph API:  GET  https://graph.microsoft.com/v1.0/subscribedSkus

What licenses are included in acquired licenses ? 

Question originally asked on [QnA ](https://docs.microsoft.com/en-us/answers/questions/512719/index.html)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52263bf3-6bd2-2219-e2f0-dda921ea7e10
* Version Independent ID: b625c2db-d6a2-8a18-88dc-fad7e76f9251
* Content: [List subscribedSkus - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/subscribedsku-list?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/subscribedsku-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/subscribedsku-list.md)
* Product: **directory-management**
* Technology: **microsoft-graph**
* GitHub Login: @SumitParikh
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @dwanjuhi for raising this issue. All purchased licenses (including free trial plans) are returned by this API. If the license is listed in the Microsoft 365 admin center [Licenses](https://admin.microsoft.com/#/licenses) section, then it should also be returned by the GET /subscribedSkus method.

If the customer still can't see the license in the list of license objects returned by this API, kindly advise them to share their account details at [Microsoft Graph on Q&A](https://docs.microsoft.com/en-us/answers/questions/512719/index.html) for further investigation.

No updates identified for the page, closing the issue here.
