### ISSUE TITLE
List signIns - $filter not working properly

### ISSUE THREAD

**Issue by markholst** [microsoftgraph/microsoft-graph-docs#14173]
I'm unable to query the sign-in logs using a date based filter.

Trying any of these expressions:
https://graph.microsoft.com/v1.0/auditLogs/signIns?&$filter=createdDateTime ge '2021-09-07T00:00:00Z'
https://graph.microsoft.com/v1.0/auditLogs/signIns?$filter=createdDateTime ge '2021-09-07T00:00:00Z'
https://graph.microsoft.com/v1.0/auditLogs/signIns?$filter=createdDateTime ge '01-SEP-2021'
https://graph.microsoft.com/v1.0/auditLogs/signIns?$filter=createdDateTime ge '2021-09-01'
https://graph.microsoft.com/v1.0/auditLogs/signIns?$filter=createdDateTime gt '2021-09-01'

Returns a payload similar to:
{
    "error": {
        "code": "BadRequest",
        "message": "Invalid filter clause",
        "innerError": {
            "date": "2021-09-07T07:11:46",
            "request-id": "65525901-18fb-453f-b80a-beb8b2202811",
            "client-request-id": "65525901-18fb-453f-b80a-beb8b2202811"
        }
    }
}

Note the current UTC date/time is 7th September 2021 07:13:58

I have confirmed this call works:
https://graph.microsoft.com/v1.0/auditLogs/signIns

It seems like this issue was never confirmed as resolved:
https://github.com/microsoftgraph/microsoft-graph-docs/issues/5676

The only option is to filter client-side.

Unfortunately the article doesn't state what the default date range is, so I am guessing it is 7 days.

Note this is an Azure B2C Tenant!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06e7697f-b03a-3282-ebd8-748b65dde87d
* Version Independent ID: bfd3bfb8-4878-b0f7-48f8-ba08a7136108
* Content: [List signIns - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/signin-list?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/signin-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/signin-list.md)
* Product: **identity-and-access-reports**
* Technology: **microsoft-graph**
* GitHub Login: @besiler
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @markholst for raising this issue. You're getting the error because of the wrong syntax. createdDateTime is a DateTimeOffset type which shouldn't be in quotes in a $filter query. The correct syntaxes are:

https://graph.microsoft.com/v1.0/auditLogs/signIns?$filter=createdDateTime ge 2021-09-07T00:00:00Z
~https://graph.microsoft.com/v1.0/auditLogs/signIns?$filter=createdDateTime ge '01-SEP-2021'~
https://graph.microsoft.com/v1.0/auditLogs/signIns?$filter=createdDateTime ge 2021-09-01
https://graph.microsoft.com/v1.0/auditLogs/signIns?$filter=createdDateTime gt 2021-09-01

Regarding the following question
>Unfortunately the article doesn't state what the default date range is, so I am guessing it is 7 days.

Do you mean how far back you can retrieve logs? It's according to the [Azure AD data retention policy](https://docs.microsoft.com/en-us/azure/active-directory/reports-monitoring/reference-reports-data-retention#how-long-does-azure-ad-store-the-data).

Hope that helps.

**Comment by markholst** [comment]
Many thanks for this, that solved my problem.

Okay, it is this page that led me astray:
https://docs.microsoft.com/en-us/graph/query-parameters

![image](https://user-images.githubusercontent.com/56993727/132329747-6e84b7d5-a9f1-44fd-a522-13db257303a1.png)

**Comment by FaithOmbongi** [comment]
Ah, noted. The start/[dateTime ](https://docs.microsoft.com/en-us/graph/api/resources/datetimetimezone?view=graph-rest-beta) and end/dateTime properties of the [events ](https://docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-beta)API are actually **String** types, not **DateTimeOffset** types. Hence the quotes in that particular example.
