### ISSUE TITLE
Dynamic Distribution Lists using Graph API

### ISSUE THREAD

**Issue by rodrigoguariento** [microsoftgraph/microsoft-graph-docs#14294]
According to https://docs.microsoft.com/en-us/graph/api/resources/group?view=graph-rest-1.0 is possible to work with **Microsoft 365 Group** and **Security Group**.

Does it possible to list Dynamic Distribution Lists using Graph API? 

I'm a software developer, not a Microsoft specialist, then I'm confused about Distribution Groups, Dynamic Distribution Lists, and Security Groups. How far is the Graph API able to list this "groups" and its members (Active Directory & Exchange) in this context? The maximum that I got was this query: https://graph.microsoft.com/v1.0/groups?$filter=groupTypes/any(s:s eq 'DynamicMembership')&$select=displayName

Thank you.

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 0c5cd62a-5325-aeda-c1ae-33b6157eb04c
* Version Independent ID: c9b14f46-af37-3520-450c-3ed4d5f54f46
* Content: [Listar grupos - Microsoft Graph v1.0](https://docs.microsoft.com/pt-br/graph/api/group-list?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/group-list.md](https://github.com/microsoftgraph/microsoft-graph-docs.pt-BR/blob/main/api-reference/v1.0/api/group-list.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @Jordanndahl
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @rodrigoguariento for raising this issue. I believe the following query should work

[https://graph.microsoft.com/beta/groups?$filter=mailEnabled eq true and securityEnabled eq false and NOT(groupTypes/any(s:s eq 'Unified')) and groupTypes/any(s:s eq 'DynamicMembership')&$count=true](https://developer.microsoft.com/en-us/graph/graph-explorer?request=groups%3F%24filter%3DmailEnabled%20eq%20true%20and%20securityEnabled%20eq%20false%20and%20NOT(groupTypes%2Fany(s%3As%20eq%20'Unified'))%20and%20groupTypes%2Fany(s%3As%20eq%20'DynamicMembership')%26%24count%3Dtrue&method=GET&version=beta&GraphUrl=https://graph.microsoft.com&requestBody=eyJkZXNjcmlwdGlvbiI6IlRlc3QgY3JlYXRlIERMIiwiZGlzcGxheU5hbWUiOiJUZXN0IGNyZWF0ZSBETCIsImdyb3VwVHlwZXMiOltdLCJtYWlsRW5hYmxlZCI6dHJ1ZSwic2VjdXJpdHlFbmFibGVkIjpmYWxzZSwibWFpbE5pY2tuYW1lIjoidGVzdGRpc3RyaWJ1dGlvbmxpc3QiLCJvd25lcnNAb2RhdGEuYmluZCI6WyJodHRwczovL2dyYXBoLm1pY3Jvc29mdC5jb20vdjEuMC91c2Vycy80NTYyYmNjOC1jNDM2LTRmOTUtYjdjMC00ZjhjZTg5ZGNhNWUiXSwibWVtYmVyc0BvZGF0YS5iaW5kIjpbImh0dHBzOi8vZ3JhcGgubWljcm9zb2Z0LmNvbS92MS4wL3VzZXJzLzZlYTkxYThkLWUzMmUtNDFhMS1iN2JkLWQyZDE4NWVlZDBlMCIsImh0dHBzOi8vZ3JhcGgubWljcm9zb2Z0LmNvbS92MS4wL3VzZXJzLzk5ZTQ0YjA1LWMxMGItNGU5NS1hNTIzLWUyNzMyYmJhYmExZSIsImh0dHBzOi8vZ3JhcGgubWljcm9zb2Z0LmNvbS92MS4wL3VzZXJzLzQ1NjJiY2M4LWM0MzYtNGY5NS1iN2MwLTRmOGNlODlkY2E1ZSJdfQ==&headers=W3sibmFtZSI6IkNvbnNpc3RlbmN5TGV2ZWwiLCJ2YWx1ZSI6ImV2ZW50dWFsIn1d)
ConsistencyLevel: true

**Disclaimer:** I haven't been able to completely test it because we can't create DLs via Microsoft Graph, the Azure portal, or Microsoft 365 admin center. But I tested with `$filter=mailEnabled eq false and securityEnabled eq true and NOT(groupTypes/any(s:s eq 'Unified')) and groupTypes/any(s:s eq 'DynamicMembership')` (settings for security groups with dynamic membership) and the query worked.

**Note:** Don't forget the **ConsistencyLevel** header and **$count** query parameter are required in the query because you have used the `NOT` operator on the group resource. You can read more about why in [Advanced query capabilities on Azure AD directory objects](https://docs.microsoft.com/en-us/graph/aad-advanced-queries)
