### ISSUE TITLE
API /sites does not support filtering yet

### ISSUE THREAD

**Issue by aaronmi** [microsoftgraph/microsoft-graph-docs#14387]
[Enter feedback here]
1) The API does not support filtering yet. But the document says it supports one filter.
2) In the permissions section, it says the delegated permission works with work or school accounts. But with Graph explorer, the API does not return any sites but empty.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c69782e4-57f5-8739-1e03-12fcdf4853aa
* Version Independent ID: ae3692d0-2697-9713-46d9-628b29cf0e9c
* Content: [Enumerate sites - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/site-list?view=graph-rest-beta&tabs=http&source=docs)
* Content Source: [api-reference/beta/api/site-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/site-list.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by JeremyKelley** [comment]
This is confusingly written (and kind of a confusing feature) but technically correct.  Will update the docs to clarify what works.

Calling /sites with no parameters is supported with Application permissions only.  Not for delegated accounts.
/sites with the filter and select statement applied as stated in the article works for both App Only and App + User permissions.  Only the filter described in the article is supported for the specific case of retrieving the root site collections.

This is also why calling /sites with Delegated permissions returns an empty set rather than an error.  The filter version came before the Application permission version that returns all sites, to not break the original scenario Delegated must still be supported but returns no data.

**Comment by lramosvea** [comment]
@JeremyKelley doc seems to be updated, is the issue fixed already? If so can we close this issue? Thanks
