### ISSUE TITLE
Create user endpoint fail (internal server error)

### ISSUE THREAD

**Issue by nintexkj** [microsoftgraph/microsoft-graph-docs#1508]
Issue: When I call create user with a userPrincipalName which already exists, the endpoint return internal server error, with message "The given key was not present in the dictionary."

This is the endpoint document:

https://developer.microsoft.com/en-us/graph/docs/api-reference/beta/api/user_post_users

**Comment by AlexeyK83** [comment]
Hi! I have seen the same problem, but when using the same onPremisesImmutableId. 

More details here: https://social.msdn.microsoft.com/Forums/office/en-US/b59de469-9191-483a-9936-eb2d7f780653/internal-server-error-while-trying-to-add-an-user-with-the-same-onpremisesimmutableid?forum=Office365forDevelopers

**Comment by dkershaw10** [comment]
Sorry for the late response.  Interesting - I get a 400 error for this.
```json
{
    "error": {
        "code": "Request_BadRequest",
        "message": "Another object with the same value for property userPrincipalName already exists.",
        "innerError": {
            "request-id": "462649d3-a124-42bc-b046-815fb41aae76",
            "date": "2018-05-08T04:49:55"
        },
        "details": [
            {
                "target": "userPrincipalName",
                "code": "ObjectConflict"
            }
        ]
    }
}
```

If this still repros for you, can you add a full error response, including requestId and timestamp please?

**Comment by jthake-msft** [comment]
Closing due to no response.

This issues lists is specifically for documentation issues, not the underlying service, sdks or samples. I will close this issue so our documentation team can focus on content issues.
The official channel for questions is StackOverflow with '[microsoft-graph](https://stackoverflow.com/questions/tagged/microsoft-graph
)' tag.
For issues, you can raise a support ticket on the Azure Portal where you registered your application. This [simple video](https://twitter.com/jthake/status/1030489336439959553) shows how to file it properly by visiting [here](https://portal.azure.com/#blade/Microsoft_Azure_Support/HelpAndSupportBlade/overview).
