### ISSUE TITLE
employeeId accepting only Numbers

### ISSUE THREAD

**Issue by PawelKaczanowski7N** [microsoftgraph/microsoft-graph-docs#15675]
employeeId parameter accept only numbers

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bad15fb9-23aa-165f-2dbd-5838c951c5b5
* Version Independent ID: b99127ca-af8c-cfc8-074c-8699241984c5
* Content: [Update user - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/user-update?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/user-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/user-update.md)
* Product: **users**
* Technology: **microsoft-graph**
* GitHub Login: @jpettere
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Hi @PawelKaczanowski7N, could you clarify the issue?

**Comment by PawelKaczanowski7N** [comment]
![image](https://user-images.githubusercontent.com/98096619/152115757-213f1c9c-1e2d-4a59-a81d-90451efea55e.png)
EmployeeId attribute doesn't accept String. But AFAIK only Integer/Numbers.

**Comment by FaithOmbongi** [comment]
Hi @PawelKaczanowski7N, I've tested this and can confirm that **employeeId** does accept String data. This is important because each org may have a different format for the employee ID - others can be numbers only, others can have choose to have suffixes etc.

<img width="829" alt="image" src="https://user-images.githubusercontent.com/14026935/152117093-dc50819e-8981-4b04-b24c-832a04949dff.png">

<img width="820" alt="image" src="https://user-images.githubusercontent.com/14026935/152117463-62f446f0-7a9b-4bf2-a8bb-a13af6a80271.png">

**Comment by PawelKaczanowski7N** [comment]
You are absolutely right. Sorry for my mistake, it shows up that I was trying to push to long string to this attribute.
Limit for EmployeeId is 16 characters.

Thank you and once again sorry for false report.

**Comment by FaithOmbongi** [comment]
> You are absolutely right. Sorry for my mistake, it shows up that I was trying to push to long string to this attribute. Limit for EmployeeId is 16 characters.
> 
> Thank you and once again sorry for false report.

Not a problem, @PawelKaczanowski7N. Let me also indicate this character limit in the doc. Closing this issue.
