### ISSUE TITLE
MeetingRegistrant - BadRequest or NoJoinURl

### ISSUE THREAD

**Issue by Venkman42** [microsoftgraph/microsoft-graph-docs#15694]
Hi @frankpeng7 ,

I'm in need of your help once again.
The MeetingRegistration works fine, but now I want to add registrants to the Meeting.

I especially need the Custom JoinWebUrl for an organization User.

If I leave "AllowedRegistrants" in the MeetingRegistration on "everyone", I get a successcode, but no JoinWebUrl, when adding Meeting Registrants via /registration/registants.
When I set "Allowed Registrants" to "organization" I get a bad request when trying to add registrants, with no further information.

Thats the request of my MeetingRegistrant:
POST "https://graph.microsoft.com/beta/me/onlineMeetings/MeetingID(correct,tested with get)/registration/registrants"
Content-Type: application/json
{
    "@odata.type": "#microsoft.graph.meetingRegistrant",
    "firstName": "John",
    "lastName": "Smith",
    "email": "jsmith@myorganization.com"
}

I tested this via GraphExplorer and via Postman this time, both with the same result.
My client is really eager to implement this feature, but needs the Custom JoinWebUrl for assignement purposes in the background.

Thanks for your input in advance,
Cheers :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5083ae15-04f3-cb92-b429-90bfd62cffef
* Version Independent ID: feff4be2-4354-84a6-7275-da375269c3f5
* Content: [Create meetingRegistrant - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/meetingregistration-post-registrants?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/meetingregistration-post-registrants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/meetingregistration-post-registrants.md)
* Product: **cloud-communications**
* Technology: **microsoft-graph**
* GitHub Login: @mkhribech
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by frankpeng7** [comment]
Hi @Venkman42 
> If I leave "AllowedRegistrants" in the MeetingRegistration on "everyone", I get a successcode, but no JoinWebUrl, when adding Meeting Registrants via /registration/registants.

This is expected. The registrant you added will receive an email from Teams containing his/her personal JoinWebUrl - which is not manageable by the meeting organizer.

> When I set "Allowed Registrants" to "organization" I get a bad request when trying to add registrants, with no further information.

Can you share the `client-request-id` and timestamp in the response headers so that I can dig our logs?

Also, I'm not aware of your scenario but have you considered using external registration? The external registration API is built for customers who manage the registration part in an "external" system/platform and only use Teams as the meeting platform. In this API when you add a (external)registrant you will get a customized joinWebUrl in the response.

**Comment by Venkman42** [comment]
Hi @frankpeng7 ,

thanks for the quik reply. I already thought, that it was expected behavior with AllowedRegistrants set to everyone.

Heres the client-request-id and Timestmap for the failed create MeetingRegistrant with AllowedRegistrants set to organization:
4f6eb420-3497-4e55-98cd-57e3fc8a155e
Mon, 31 Jan 2022 10:48:15 GMT


Do you have any documentation link for the external registration API ? I would like to look into that, but I didnt find much with that name.

Thanks in advance,

Cheers

**Comment by frankpeng7** [comment]
Hi @Venkman42, looks like the registrant you were trying to add was not registered in AAD. When allowed registrant is set to "organization", there's backend validation that enforces all the attendees trying to register for the webinar must be under the same organization as the webinar organizer.

Here's the doc for external registration API: https://docs.microsoft.com/en-us/graph/api/resources/externalmeetingregistration?view=graph-rest-beta

**Comment by Venkman42** [comment]
Hi @frankpeng7 , the thing is, the registrant was definitively registered in AAD. The e-mail I specified in the request is also the main smtp-address the user has and identical to the samaccountname too. The user even has an exchange-online mailbox.
Thanks for the docs-link, I will look into it.

**Comment by frankpeng7** [comment]
@Venkman42 according to the investigation result, the request to add a registrant was not using that person's delegated token that's why it failed. It's a little bit unintuitive but if you think of Teams webinar experience, only the attendee can register himself/herself, not the organizer. (However, in external registration scenarios, organizer can add the registrants).

**Comment by Venkman42** [comment]
@frankpeng7 oh, alright, that would make sense. I was using another user. Thanks for looking into it :) external registration seems to do the job. 
Thanks again for your help :)
