### ISSUE TITLE
Information about advanced queries and the fact you need -ConsistencyLevel Eventual and -Countvariable <something> Should be added

### ISSUE THREAD

**Issue by JustinGrote** [microsoftgraph/microsoft-graph-docs#15711]
It should cover the obtuse error you get about the query and that you will need to do this. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc826d9c-c7e7-85de-7653-9249f7fade9f
* Version Independent ID: 11df7fb5-969b-98d4-0406-aa16f4cda0a4
* Content: [Navigating the Microsoft Graph PowerShell SDK - Microsoft Graph](https://docs.microsoft.com/en-us/graph/powershell/navigating)
* Content Source: [concepts/powershell/navigating.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/powershell/navigating.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @jasonjoh
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jasonjoh** [comment]
Hi @JustinGrote, thanks for opening this issue. I was looking for context here and saw this [issue](https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/513) you opened on the SDK repo. Just confirming that this is the related issue?

**Comment by JustinGrote** [comment]
Correct, this is a very obtuse condition and my other issue to have the cmdlet auto-figure this out was rejected, so the next area should be documentation to warn the user.

The user based on the obtuse error message is going spend all their time thinking their query is wrong when in fact it just needs additional parameters.

**Comment by maisarissi** [comment]
Hi @jasonjoh .
I just want to emphasize that this behavior is not just for PowerShell SDK cmdlets. Please, see more information [here](https://devblogs.microsoft.com/microsoft365dev/microsoft-graph-advanced-queries-for-directory-objects-are-now-generally-available/).

**Comment by JustinGrote** [comment]
And i want to emphasize **that doesn't mean that it shouldn't be documented here**. Your average Powershell User is going to expect Powershell-y things to work, they are not going to be a graph expert. You need to know your audience.

**Comment by jasonjoh** [comment]
@JustinGrote I hear you, and I agree with you.

@maisarissi Yep, understood. I'll play with this a bit and see what I can come up with to help the confusion. I know the invalid/unsupported query error can happen in cases other than the missing `ConsistencyLevel` for example, so it's not as simple as "if you get this error, use this".

Perhaps if we said something more like "if you get this error, check [here](https://docs.microsoft.com/graph/aad-advanced-queries) to see if your query requires a `ConsistencyLevel` header. If so, use these parameters..."

Thoughts?

**Comment by JustinGrote** [comment]
For the documentation perspective, I think that's at least reasonable. Users need to know it's likely not their ODATA query string but the fact they are missing these additional options and should try with them. This should be in the Cmdlet error directly, but here in the docs is a good 2nd place location.

Right now an easy way to detect is pretty much any query that's not `eq` requires an advanced query and the additional options :)

**Comment by jasonjoh** [comment]
Ah, nice, I hadn't made that connection. The challenge is that it's a relatively (compared to the whole of Graph) small number of entities this applies to. If someone gets an invalid filter on mail or file APIs for example, this wouldn't apply, and I certainly wouldn't want to add to the frustration :D

**Comment by JustinGrote** [comment]
Right but adding it costs you basically nothing, it always works on a query regardless of if it is specified or not, and at least then you can know that it probably *is* your query and not that stupid setting.

I literally have my PSDefaultParameter values set to always set consistencylevel to eventual and the countvariable to a long random variable. It's never hurt me and it's constantly helped me.

**Comment by jasonjoh** [comment]
Interesting. I'll definitely play with this some more and update the doc. It may be a day or two before I can set aside some time to do this.

**Comment by maisarissi** [comment]
Hi @JustinGrote . Yes, I know that doesn't mean it shouldn't be documented. I was just pointing out to @jasonjoh this is not PowerShell related, so that the documentation covers all SDKs and can be added in the place that makes the most sense, instead of [Navigating the SDK](https://docs.microsoft.com/en-us/graph/powershell/navigating), since you have opened this issue for this specific page.
![image](https://user-images.githubusercontent.com/22648831/152237979-7cbc07dd-9dbb-47c8-a0e0-3c734a093c8f.png)

Not arguing about if this should or shouldn't be documented :)

@jasonjoh I agree with you that adding these advanced queries information in a general way could bring more frustration for folks that are trying to use filter in APIs that doesn't support them.

Maybe we could add information about these advanced queries capabilities for Azure AD directory objects and their relationships in the known issues page? I saw that we already have [query parameters](https://docs.microsoft.com/en-us/graph/known-issues?view=graph-rest-1.0#query-parameters). We can say something around "If you are trying to query Azure AD directory objects and you are getting the "Unsupported or invalid query filter clause" error, you may want to check [advanced queries](https://docs.microsoft.com/en-us/graph/aad-advanced-queries)."
And than we can also add something in the Overview page telling people to check known issues on Graph and link to the Known Issues page.

What do you think?

**Comment by jasonjoh** [comment]
Let me give it some thought, but gut reaction is that we may want to surface this in multiple places, or at least put details in one single place and then add notes in other relevant places.

For example, we may add examples of adding the header in all SDKs to this page: https://docs.microsoft.com/en-us/graph/aad-advanced-queries

Then we could add a note to the Navigating topic with a link there.

**Comment by maisarissi** [comment]
I like the idea of having samples for each SDK and adding its reference to a few places. There is also the get started page, where we say to people [get an user](https://docs.microsoft.com/en-us/graph/powershell/get-started?view=graph-rest-1.0#get-the-signed-in-user). 
But I do believe we should add something under Known issues too.

Another possibility is to create a new page to show different types of OData queries and add examples of how to use them in each SDK. Then we can also cover these advanced queries scenarios.
