### ISSUE TITLE
Wrong example for C#

### ISSUE THREAD

**Issue by joergkrause** [microsoftgraph/microsoft-graph-docs#15802]
[Hier Feedback eingeben]
The example for C#, especially the part `Sites["{site-id}"].TermStore` refers to SharePoint, not to common groups.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 52e064c0-4789-0ec7-1e7c-c36519049ffd
* Version Independent ID: aa0adc0e-5c50-3a2f-ab01-152f8f3d92e3
* Content: [Gruppe abrufen - Microsoft Graph v1.0](https://docs.microsoft.com/de-de/graph/api/group-get?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/group-get.md](https://github.com/microsoftgraph/microsoft-graph-docs.de-DE/blob/main/api-reference/v1.0/api/group-get.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @Jordanndahl
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @joergkrause for catching this error. I've found that this was because of a code snippet naming conflict - example 1 on the Get group page had the same snippet name as another example on a termStore/sites page. Hence why the error wasn't in the beta code snippet.

I've deleted the wrong snippets, resolved the naming conflicts, and requested a fresh auto-generation of the snippets.
