### ISSUE TITLE
Delta reports invited guest user, but immediate operations on the user fail. Delays?

### ISSUE THREAD

**Issue by evilsufi** [microsoftgraph/microsoft-graph-docs#15839]
When we use invitations API to invite a guest user, the response includes id of the created user object. However, immediate Graph API operations on the created user object seem to fail with error
"code":"Directory_ObjectNotFound","message":"Unable to read the company information from the directory."
This seems to be the case even when we do delta polling, e.g. user delta returns the created (invited) user object information, but immediate patch operation still fails with the above error. Why does the delta API report the user object is created, if it cannot be modified right after? After an unspecified while, retried operation succeeds.

We have been unable to find any official documentation about the possible/expected delays in processing, or the needed retry procedures to follow. If the delays are expected "feature", this should be clearly documented and mitigating practices suggested. Or even better, the delta API shouldn't return "created" objects until after they can be further operated on.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ed6cea3-facc-cd9c-20f7-ff3660db6cdf
* Version Independent ID: 09c6da67-ca04-272c-6599-969b96ea5b81
* Content: [Get incremental changes for users - Microsoft Graph](https://docs.microsoft.com/en-us/graph/delta-query-users)
* Content Source: [concepts/delta-query-users.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/delta-query-users.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @FaithOmbongi
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @evilsufi for raising this issue.

These lags (and unexpected 404 Not found error code) are because of the replicated and distributed nature of the service and occur for write queries. The data would be first written to the primary and secondary storage replicas that are geographically nearer to you, then the change is propagated across all Azure AD data replicas. While Azure AD tries to use the same primary/secondary data replica throughout your authenticated session, sometimes there's re-routing or for some queries, only data that has been fully propagated across all primary and secondary replicas is returned.

Please note that most times, the lag may be less than a microsecond and unnoticeable. The recommendation is to retry the query after a little while. I'll raise a PR to add this note in the **List users** document.

**Note:** You may see a note about this lag in the [Processing delays section of the delta overview article](https://docs.microsoft.com/en-us/graph/delta-query-overview#processing-delays) and an almost similar note elsewhere across the API docs mentioning "_replication delays for [objects] that were recently created, updated, or deleted_."

**Comment by evilsufi** [comment]
Thank you for the quick reply and explanation. For Guest invitations, the delay seems to be few seconds at least. It would be great is the delta API would return the change only after the object would be fully available from the replicas as well. But in the meantime, some kind of retry mechanism needs to be implemented.

Referring to the documented Processing delays section of the delta overview article<https://docs.microsoft.com/en-us/graph/delta-query-overview#processing-delays>, I would like to add that the section only talks about delays from Graph API writes to the change being reported by the delta query. There are indeed delays in that, but that's quite ok. What's missing is a note that even after the delta query returns information about newly created object (e.g. user created based on invitation), the object may still not  be fully available for use (e.g. patch on returned user object fails) and operation should be retried after some time (any upper wait limit?).

-Ville
