### ISSUE TITLE
Insert Event with Online Meeting not returning conferenceId and tollNumber

### ISSUE THREAD

**Issue by lucasfcunha** [microsoftgraph/microsoft-graph-docs#15861]
Hi,

We are creating an event with the the `isOnlineMeeting` set as `true` and the `onlineMeetingProvider` as `teamsForBusiness`.
This used to return us an `onlineMeeting` object with the `conferenceId` and the `tollNumber`.

However, since the mid of the last week the API stopped returning the `conferenceId` and `tollNumber`. The request works correctly, the event is inserted and we get back the link for the meeting. The issue is just the missing `conferenceId` and `tollNumber`.

Here is a excerpt of the return of the insert event call:

```ruby
...
"onlineMeeting" =>  {
  "joinUrl" => {
    "https://teams.microsoft.com/l/meetup-join/19%3ameeting_redacted"
  }
}
```

Has something changed on the API that stopped returning the `conferenceId` and the `tollNumber`? How can we get those values, since they are important to our clients?

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ff7ff9f-c955-c32f-756c-59e9165f3fa3
* Version Independent ID: c181ecf0-6586-9b36-20a8-f2f1e1381397
* Content: [Create event - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/calendar-post-events?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/calendar-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/calendar-post-events.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @Harini84
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by lucasfcunha** [comment]
This looks similar to #10457 and #10215

**Comment by FaithOmbongi** [comment]
Thank you @lucasfcunha for raising this issue and my apologies for the delayed response. Because this isn't a docs issue but a functionality issue, such issues are investigated through Microsoft Graph Q&A. I see you've already reported it here: https://docs.microsoft.com/en-us/answers/questions/745958/insert-event-with-online-meeting-not-returning-con.html

Regardless, this is currently being investigated and you'll receive a response through Microsoft Graph Q&A. Closing this issue in the docs repo.
