### ISSUE TITLE
Creating or updating b2cUserFlow disables JavaScript support for page layouts

### ISSUE THREAD

**Issue by kleferbe** [microsoftgraph/microsoft-graph-docs#16075]
It seems to be no longer possible to create (POST) a userflow with JavaScript enabled via Graph API.
Also every update (PATCH) irrespective of the changed properties also disables JavaScript in the userflow and the `isJavaScriptEnabled` returns false.
A hint on how to create a JavaScript enabled userflow would be very appreciated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49f39b23-a0a8-bed9-fe32-49430517b3b7
* Version Independent ID: ff97e10f-a639-8344-9fc3-aa1b3f0a107c
* Content: [Create b2cIdentityUserFlow - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/identitycontainer-post-b2cuserflows?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/identitycontainer-post-b2cuserflows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/identitycontainer-post-b2cuserflows.md)
* Product: **identity-and-sign-in**
* Technology: **microsoft-graph**
* GitHub Login: @jkdouglas
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @kleferbe for raising this issue and my apologies for the delayed response. Unfortunately, this forum is only for documentation-related issues but functionality issues like this are investigated through [Microsoft Graph Q&A](https://docs.microsoft.com/en-us/answers/topics/microsoft-graph-identity.html). Kindly post your question there.

No updates identified for the doc for now but the docs will be updated when new information is available. Closing this issue here.
