### ISSUE TITLE
RoleEligibilitySchedule.ReadWrite.Directory permission not enforced

### ISSUE THREAD

**Issue by glennvanrymenant-tc** [microsoftgraph/microsoft-graph-docs#16399]
I was able to alter existing eligible assignments without the RoleEligibilitySchedule.ReadWrite.Directory permissions consented on the app (as a Privileged Role Administrator).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d7358a7-bef5-a501-26b5-89052e95cc37
* Version Independent ID: 4164c086-118e-c3c5-bfca-78a3ccfa5f46
* Content: [Create unifiedRoleEligibilityScheduleRequest - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/unifiedroleeligibilityschedulerequest-post-unifiedroleeligibilityschedulerequests?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/unifiedroleeligibilityschedulerequest-post-unifiedroleeligibilityschedulerequests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/unifiedroleeligibilityschedulerequest-post-unifiedroleeligibilityschedulerequests.md)
* Product: **governance**
* Technology: **microsoft-graph**
* GitHub Login: @japere
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by MonikaPradhan** [comment]
@glennvanrymenant-tc - Can you please check what other permissions were included in your token ? This API also supports RoleManagement.ReadWrite.Directory permission.

**Comment by mandardalvi** [comment]
@glennvanrymenant-tc - Can you please check what other permissions were included in your token ? This API also supports RoleManagement.ReadWrite.Directory permission.

**Comment by glennvanrymenant-tc** [comment]
@mandardalvi IIRC, I used the "https://graph.microsoft.com/.default" as scope and the app didn't have the RoleManagement.ReadWrite.Directory permission either.

**Comment by mandardalvi** [comment]
@glennvanrymenant-tc  can you please let me know what permissions your app has ? and which API you are calling ?

**Comment by FaithOmbongi** [comment]
Thank you @glennvanrymenant-tc for raising this issue. Unfortunately, I'm unable to replicate it having tested with `adminExtend `and `adminRemove` actions. Also for GET requests - Always geting a 403 Forbidden error.

Can you share a request ID so I can submit for investigation?

Unfortunately, this forum is only for documentation-related issues and functionality issues are investigated at [Microsoft Graph Q&A](https://docs.microsoft.com/en-us/answers/topics/microsoft-graph-governance.html). So I'll close this issue here. Regardless, if you share a request ID, I can forward for investigation.
