### ISSUE TITLE
List all service principals brings partial results

### ISSUE THREAD

**Issue by vicmar57** [microsoftgraph/microsoft-graph-docs#16548]
[Enter feedback here]
Hi. when issuing an API request to get all service principals, I get only a partial list of SPs.( there are more than 30 in the app registrations in the Azure Portal), but it bring only about 7-8 of these, and the microsoft SPs too.

on the other hand, when issuing a request to get a specific SP that was not present in the previous response, I've manage to successfully retrieve it. 
Why?
Thanks, 
Victor.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d9a1dcc-0e0d-e5ba-8fa3-ad0289803a52
* Version Independent ID: bccef64c-675b-364e-30f6-5c1310fef8bd
* Content: [List servicePrincipals - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/serviceprincipal-list?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/serviceprincipal-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/serviceprincipal-list.md)
* Product: **applications**
* Technology: **microsoft-graph**
* GitHub Login: @sureshja
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @vicmar57 for raising this issue. Please note that the Azure portal and the API map as follows:

| Azure portal page                                | Microsoft Graph API |
|--------------------------------------------------|---------------------|
| Azure Active Directory > App registrations       | [Applications](https://docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-1.0)        |
| Azure Active Directory > Enterprise applications | [Service principals](https://docs.microsoft.com/en-us/graph/api/resources/serviceprincipal?view=graph-rest-1.0)  |

So from this section of your issue 

> there are more than 30 in the app registrations in the Azure Portal

You should get all the app registrations when you call the **GET https://graph.microsoft.com/v1.0/applications** API.
And all enterprise applications (service principals) when you call the **GET https://graph.microsoft.com/v1.0/servicePrincipals** API.

On another note: If you call either API and the responses have fewer objects than you can see on the Azure portal, this will need to be investigated. Please post the question at [Microsoft Graph Q&A](https://docs.microsoft.com/en-us/answers/topics/microsoft-graph-applications.html) and provide your request ID so the issue can be investigated. This is because this forum is for documentation-related issues only, but functionality issues are investigated at [Microsoft Graph Q&A](https://docs.microsoft.com/en-us/answers/topics/microsoft-graph-applications.html).
