### ISSUE TITLE
Management Script always return 403

### ISSUE THREAD

**Issue by vgilbertsson** [microsoftgraph/microsoft-graph-docs#1657]
Issue: I have been trying to test out the new managementscript features of graph intune. But unfortunately it always return 403. I have ensured that I have enough permissions and other graph resources are working just fine. Currently I have only tested it in a single tenant.

Article: https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/intune_devicefe_devicemanagementscript.md

**Comment by vgilbertsson** [comment]
I have done a test with a different tenant and I get the same error.

The following endpoint require the same permissions and it works just fine.
https://developer.microsoft.com/en-us/graph/docs/api-reference/beta/api/intune_devicefe_remoteactionaudit_list

**Comment by billgatesfan** [comment]
I have noticed the same issue few weeks ago, and I directly opened a ticket at Intune support. 

The confirmed this issue with following statement "I’ve done some investigating on my end and have reached out to one of our Beta Engineers. It has been confirmed that the error message that we are encountering is expected for the time being because that specific query is not quite ready for the Beta release just yet.".  

My Ticket number was [REG:117072516091308] in case you want to use it as reference.

**Comment by vgilbertsson** [comment]
That is unfortunately. Would be really nice to tag a tenant as an "insider release" to make sure all the latest beta stuff is available.

**Comment by lleonard-msft** [comment]
@vgilbertsson - UserVoice is the best place to request [feature changes for Intune](https://microsoftintune.uservoice.com/forums/291681-ideas). 

For specific help with a specific implementation, post a question to StackOverflow with the tags "intune" and "microsoft-graph".
