### ISSUE TITLE
Would be nice to be able to pull when the user lastlogon info for the user.

### ISSUE THREAD

**Issue by Phenix51** [microsoftgraph/microsoft-graph-docs#17676]
Would be nice to be able to pull when the user lastlogon info for the user.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bae97ef5-d7e5-3934-6323-1bcff216f4fb
* Version Independent ID: 1ed620e1-cb79-dda3-2c18-30791ec9e15a
* Content: [Working with users in Microsoft Graph - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/users?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/users.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/users.md)
* Product: **users**
* Technology: **microsoft-graph**
* GitHub Login: @jpettere
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you, @Phenix51, for raising this issue. There are two ways to do so:

1) Directly from the user resource - you can; but only through the `beta` endpoint. Check the signInActivity of the user as indicated in [Example 3: Get users including their last sign-in time](https://docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-beta&tabs=http#example-3-get-users-including-their-last-sign-in-time)

2) Method 2: Read the **createdDateTime** property of the [signIn logs](https://docs.microsoft.com/en-us/graph/api/signin-list?view=graph-rest-1.0&tabs=http). Because the sign in logs are an audit trail, you may have to use the `$filter`, `$orderBy` and `$top` query parameters to scope the result to only the latest sign in record for a user. For example: `https://graph.microsoft.com/v1.0/auditLogs/signIns?$filter=userId eq '{userId}'&$orderBy=createdDateTime DESC&$top=1`. cc @besiler to provide any additional guidance.
