### ISSUE TITLE
Clarify permissions

### ISSUE THREAD

**Issue by michevnew** [microsoftgraph/microsoft-graph-docs#17905]
Can you please clarify the permissions required for these endpoints. I can certainly query the data via Graph explorer (delegate permissions) without consenting to CrossTenantInformation.ReadBasic.All. In fact, it seems to only require Directory.AccessAsUser.All, but that's of course dependent on the account I'm logged in with. In any case, CrossTenantInformation.ReadBasic.All does not seem to be a requirement, and there are additional permissions that can also work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29d8fbfc-bd64-1317-340d-f4c3e938af46
* Version Independent ID: 71be61e0-13f8-6521-62f9-853c3e4f251d
* Content: [tenantRelationship: findTenantInformationByDomainName - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/tenantrelationship-findtenantinformationbydomainname?view=graph-rest-beta)
* Content Source: [api-reference/beta/api/tenantrelationship-findtenantinformationbydomainname.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/tenantrelationship-findtenantinformationbydomainname.md)
* Product: **directory-management**
* Technology: **microsoft-graph**
* GitHub Login: @adimitui
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @michevnew for raising this issue. _Directory.AccessAsUser.All_ is one of the most privileged directory permissions and will allow you to perform CRUD operations for many Azure AD APIs. Because of its overprivileged nature, we recommend you grant it only when the API requires it. You'll see few API docs reference it even though many APIs might support it. Please use _CrossTenantInformation.ReadBasic.All_ which is the least privileged for this API.
