### ISSUE TITLE
UTC is missing in the doc for timeZone

### ISSUE THREAD

**Issue by Hongbo-Miao** [microsoftgraph/microsoft-graph-docs#1801]
Issue: 
For `event.start.timeZone` and `event.end.timeZone`, I cannot find the value `UTC` I got in the article.
![image](https://user-images.githubusercontent.com/3375461/31457540-ec6c15a6-ae71-11e7-811e-1378e59161c4.png)

Article:
https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/resources/datetimetimezone

**Comment by mlafleur** [comment]
I believe "UTC" is what is returned if either nothing is requested or the timezone requested wasn't known. 

Regardless, that page isn't clear at all:

* Rather than telling the reader they can use any timezone from Windows, it should really link back additional docs (possibly [Default Time Zones](http://massivescale.com/microsoft-v2-endpoint-primer/)?). 

* I couldn't sort out if I should use the `Country`, `Timezone` or specify `+/-UTC`. I also couldn't make _any_ options work with Graph Explorer (in fact it seemed to alternate between returning `UTC` and `Pacific Standard Time`).

**Comment by jasonjoh** [comment]
`UTC` would be covered as one of the "any timezones from Windows" I believe. :). However, the doc is a little odd here. The *correct* answer is that you can use any of the `alias` values returned from the user's [supported time zones](https://developer.microsoft.com/en-us/graph/docs/api-reference/beta/api/outlookuser_supportedtimezones), but that API is only in Beta for now.

```
{
  "alias": "UTC",
  "displayName": "(UTC) Coordinated Universal Time"
},
```
