### ISSUE TITLE
Unclear instructions on how to List/Get `AccessPackageAssignmentApproval` from `AccessPackageAssignmentRequest`

### ISSUE THREAD

**Issue by yourfrienddhruv** [microsoftgraph/microsoft-graph-docs#18170]
Unclear instructions on how to List/Get `AccessPackageAssignmentApproval` from `AccessPackageAssignmentRequest`

Logically was expecting to have a relationship `https://docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta#relationships` but it does not exists/supported to do `$expand=approvals` 

Wanted to get All/Pending Approvals  (Regardless of assignee/me ) of `AccessPackageAssignmentRequest`, Would like to know what is the correct way to do it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d64a79d0-31b1-e204-0609-570de6dcc83a
* Version Independent ID: bfa15bb9-fd35-fbc3-cfa2-0f5d8aae652a
* Content: [approval resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/approval?view=graph-rest-beta)
* Content Source: [api-reference/beta/resources/approval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/approval.md)
* Product: **governance**
* Technology: **microsoft-graph**
* GitHub Login: @markwahl-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by markwahl-msft** [comment]
The approval interfaces in Graph are provided for an application operating on behalf of a user who has been configured as an approver by policy.  Through the interfaces the application can query for one or more requests, to be able to update the request so that it can proceed to completion - delivered or denied.  This corresponds to the Approvals tab in the myaccess.microsoft.com UI.  There is no interface to query for approvals associated with requests where the calling user is not an approver.
