### ISSUE TITLE
securityEnabledOnly description doesn't quite match behavior

### ISSUE THREAD

**Issue by jamesdu-ms** [microsoftgraph/microsoft-graph-docs#18429]
The description for securityEnabledOnly seems a little incorrect. Or rather it doesn't quite capture the full behavior.

A user can be a member of a security group and not have it's ID returned even when securityEnabledOnly is true. We see this happen when the user is a member of a distribution group, and that distribution group is a member of the security group. 

It kind of makes sense - I guess all groups in the chain of membership must be security enabled for it to count as a member group for security purposes and this is expected behavior. But this documentation suggests otherwise, it implies the only thing that is checked is if the final group is a security group. This behavior caught us out.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a16de20-6176-fcb2-37f0-0b38f12431dc
* Version Independent ID: 54aacb41-fcef-1366-d91d-9dd32aa0812e
* Content: [directoryObject: getMemberGroups - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/directoryobject-getmembergroups?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/directoryobject-getmembergroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/directoryobject-getmembergroups.md)
* Product: **directory-management**
* Technology: **microsoft-graph**
* GitHub Login: @keylimesoda
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @jamesdu-ms for raising this issue.

About your comment

> A user can be a member of a security group and not have it's ID returned even when securityEnabledOnly is true. We see this happen when the user is a member of a distribution group, and that distribution group is a member of the security group.

Distribution groups have securityEnabled set to `false` so the behavior you encountered should be correct. 
Consider a scenario where USER1 is a member of both distribution group DL1 and mail-enabled security group MSG1, both of which are members of security group SG1. When you call /getMemberGroup API with `"securityEnabledOnly": false`

- The API doesn't return DL1 because DL1's securityEnabled is `false`. 
- The API will return MSG1 because MSG1's securityEnabled is `true`

I hope this clarifies the behavior as documented?

**Comment by FaithOmbongi** [comment]
> In your example, user is a member of DL1, and DL1 is a member of ~MSG1~ SG1.
> 
> Based on the wording in the documentation, I'd expect ~MSG1~ SG1 to be returned in the users member groups when securityEnabled=true, as ~MSG1~ SG1 is a security group.
> 
> However it does not show up unless securityEnabled=false.
> 
> I suspect this behavior is by design, to require all groups in the membership chain to be security groups when specifying securityEnabled=true, but it doesn't match the documentation.

First, corrections to the references. Otherwise, the behavior becomes different. Based on my initial response, I think you meant SG1 and not MSG1. I also corrected a reference in my response (I hope I didn't confuse you, LO!)

So back to the scenario in my initial response, USER1 isn't technically a member of SG1. USER1 is a member of DL1; and DL1 is a member of SG1. USER1 will only be a member of SG1 if you're looking at transitive membership, which is the purpose of the /getMemberGroups API. If you're looking at direct memberships of SG1, then USER1 should not show up.

HOWEVER: Think of "securityEnabled=true" as a filter condition that transforms the behavior of /getMemberGroups, "find me all groups that I'm a member of _and_ that have securityEnabled set to true", then when you run /getMemberGroups, DL1 won't match this "filter" condition. And by extension, therefore, USER1 doesn't match the filter condition.

> However it does not show up unless securityEnabled=false.

Correct. Because "securityEnabled=false" behaves as if the "filter" condition mentioned previously doesn't exist. "securityEnabled=false" excludes everything after the "and" condition above. 

>The issue comes up when the user is a transitive member of a security group indirectly through a membership in a distribution group.

This is the correct behavior because distribution groups are `securityEnabled=false`. So when you apply the `securityEnabled: true` condition, then the distribution group fails to match that condition.

Could you highlight the section of the documentation that looks off so I can look into it?
