### ISSUE TITLE
Can't update groups profile photo

### ISSUE THREAD

**Issue by ferronsw** [microsoftgraph/microsoft-graph-docs#18507]
I'm sending a patch request to:

`https://graph.microsoft.com/v1.0/groups/cac47c2c-7321-42f3-9101-cc28ff394388/photo/$value`

for a Office 365 group.

But I get this error:

```
{
    "error": {
        "code": "AppOnlyTokenNotSupportedForGroupUpdate",
        "message": "Exception of type 'Microsoft.Fast.Profile.Core.Exception.ProfileAccessDeniedException' was thrown.",
        "innerError": {
            "date": "2022-09-15T15:29:11",
            "request-id": "cf5fd96f-4f7f-476e-9399-1e29acce1ed1",
            "client-request-id": "cf5fd96f-4f7f-476e-9399-1e29acce1ed1"
        }
    }
}
```
According to de documentation the usage op an app registration with application permissions is supported.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d517bc8-e757-3822-848a-bf6b65d456b5
* Version Independent ID: ed8cafa6-65b9-fe58-57b3-3d57676fae46
* Content: [Update profilePhoto - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/profilephoto-update?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/profilephoto-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/profilephoto-update.md)
* Product: **people**
* Technology: **microsoft-graph**
* GitHub Login: @kevinbellinger
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by fzbm** [comment]
We are having the same issue, but there is an entry on the [known issues list](https://learn.microsoft.com/en-us/graph/known-issues#some-group-apis-dont-support-delegated-or-app-only-permissions) for exactly this problem. That said the line has been changed the last time about two years and was added at least three ago. It looks like nothing has changed since then.

It is really important that something like that works with app-only permissions. Using a technical account for updating a group image (and even for updating the one for teams which also **additionally requires a Teams license**) is not a valid scenario. There are applications out there which cannot use delegated permissions (for example provisioning processes which do their job without an user interaction).

**Comment by ferronsw** [comment]
Microsofts response:


> I would like to let you know that updating profile photo of a Group with application token is also not supported.
> It's mentioned in the known issue [article](https://learn.microsoft.com/en-us/graph/known-issues#some-group-apis-dont-support-delegated-or-app-only-permissions).
> 
> This has already been reported to the product group and the team will take measures on updating the [documentation](https://learn.microsoft.com/en-us/graph/api/profilephoto-update?view=graph-rest-1.0&tabs=http#to-update-the-profile-photo-of-a-contact).
> 
> About the functionality we cannot say whether it will be available in future or not.
