### ISSUE TITLE
Removed user is not in the response when running delta link

### ISSUE THREAD

**Issue by ilantom** [microsoftgraph/microsoft-graph-docs#18628]
Need some help understanding the following 2 scenarios:

1) When the user is deleted, the item contains an annotation: @removed with value of "reason": "changed".
2) When the user is permanently deleted, the item contains an annotation: @removed with value of "reason": "deleted".

What is the difference between these 2? My understanding is that 
1) indicates when a user is removed from the group, the response indicates  @removed with value of "reason": "changed".
2) indicates when a user is removed from AAD, the response indicates  @removed with value of "reason": "deleted".

I did the following testing:

1) Added a user to a **AAD group**
2) Deleted the user from AAD (and the user was automatically removed from the AAD group)

On running the delta link:

I see no response:

{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#groups",
    "@odata.deltaLink": "",
    "value": []
}

Is this a bug? Why is the response not showing the removed user?
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0ed6cea3-facc-cd9c-20f7-ff3660db6cdf
* Version Independent ID: 09c6da67-ca04-272c-6599-969b96ea5b81
* Content: [Get incremental changes for users - Microsoft Graph](https://learn.microsoft.com/en-us/graph/delta-query-users)
* Content Source: [concepts/delta-query-users.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/delta-query-users.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @jumasure
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jumasure** [comment]
Hi @ilantom ,

Kindly follow this link https://learn.microsoft.com/en-us/graph/delta-query-overview#:~:text=Removed%20instances%20are,in%20the%20responses. for information on the difference between "changed" and "deleted" changetypes in Delta Query

- `changed `:indicates the item was deleted and can be restored from [deletedItems](https://learn.microsoft.com/en-us/graph/api/resources/directory).
- `deleted `:indicates the item is deleted and cannot be restored.

For the second issue that when a user member is deleted, there is no delta returned for the group, that is by design. We only return delta if the group membership is added or removed explicitly, but not for the case if the member object itself is deleted (and thus the link is implicitly removed). The user deletion itself can still be tracked by query delta for users rather than groups.

**Comment by ilantom** [comment]
@jumasure Thank you! Is there an api to get users removed from an AAD group because they longer present in AAD?

**Comment by FaithOmbongi** [comment]
> @jumasure Thank you! Is there an api to get users removed from an AAD group because they longer present in AAD?

Hi @ilantom - I believe that you can only confirm within 30 days of their deletion using the [List deletedItems API](https://learn.microsoft.com/en-us/graph/api/directory-deleteditems-list?view=graph-rest-1.0&tabs=http) before they are permanently deleted. After that, check the [directory logs](https://learn.microsoft.com/en-us/graph/api/directoryaudit-list?view=graph-rest-1.0&tabs=http) which should have only the ID and UPN for that user.
