### ISSUE TITLE
'$filter=receivedDateTime+ge+{value}' stops working

### ISSUE THREAD

**Issue by cferrante** [microsoftgraph/microsoft-graph-docs#18636]
'The only supported $filter expressions are $filter=receivedDateTime+ge+{value} or $filter=receivedDateTime+gt+{value}'
is now **incorrect**.

Have been using the Graph API for years, and something changed over the weekend, so that above is now incorrect.

When performing a GET:
`https://graph.microsoft.com/v1.0/me/mailfolders/Inbox/messages/delta?filter=receivedDateTime+ge+2022-09-23`

Result: 
`400 Bad Request`

Response: 
`{"error":{"code":"ErrorInvalidUrlQuery","message":"The '$filter' parameter value is not supported for 'Messages' resource; only a value of 'receivedDateTime ge value' is supported."}}`

By trial and error, I finally removed **'filter='**, and now this GET:
`https://graph.microsoft.com/v1.0/me/mailfolders/Inbox/messages/delta?filter=receivedDateTime+ge+2022-09-23`
is successful.

I posted a solution here: [(https://stackoverflow.com/questions/73857091/solution-delta-filter-stops-working-for-microsoft-graph-email)]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c344f182-482b-e589-1014-cb387fd32c64
* Version Independent ID: aff8ed93-1239-b2cd-b1a0-b295ef375b8c
* Content: [Get incremental changes to messages in a folder - Microsoft Graph](https://learn.microsoft.com/en-us/graph/delta-query-messages)
* Content Source: [concepts/delta-query-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/delta-query-messages.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @jumasure
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Hi @abheek-das - Can you assist here? Thanks.

**Comment by fasterforward** [comment]
Since yesterday (26 September 2022, around 06:45 CET) we encounter the same problem as described above with _some_ of the emailboxes we connect to. 

However, the suggested solution does _not_ seem to work correctly. Omitting the "$filter"/"filter" in the messages delta url returns results, but the "receivedDateTime ge {value}" is ignored without the "$filter=" prefix. Results older than the receivedDateTime are still included.

* GET `https://graph.microsoft.com/v1.0/me/mailFolders/inbox/messages/delta?$orderby=receivedDateTime desc`
still works as intended, so the orderby parameter is still processed as intended

* GET `https://graph.microsoft.com/v1.0/me/mailFolders/inbox/messages/delta?$orderby=receivedDateTime desc&$filter=receivedDateTime ge 2022-09-27T06:15Z`  
returns:
```json
{
    "error": {
        "code": "ErrorInvalidUrlQuery",
        "message": "The '$filter' parameter value is not supported for 'Messages' resource; only a value of 'receivedDateTime ge value' is supported."
    }
}
```

Note that this is only the case with the `messages/delta` url, not the `messages` url:
* GET `https://graph.microsoft.com/v1.0/me/mailFolders/inbox/messages?$orderby=receivedDateTime desc&$filter=receivedDateTime ge 2022-09-27T06:15Z`
returns:  
```json
{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#users('USERID')/mailFolders('inbox')/messages",
    "value": [
        {
            "@odata.etag": "W/\"ETAG\"",
            "id": "AAMkAGUzZTg3Y2RiLWY1ZT...AAA=",
            "createdDateTime": "2022-09-27T07:13:47Z",
            "lastModifiedDateTime": "2022-09-27T07:19:05Z",
            ...
        }
    ]
}
```

Seems like the `$filter` handling got bugged since yesterday, because the example mentioned in the docs does not workf anymore:
* https://learn.microsoft.com/en-us/graph/api/message-delta?view=graph-rest-1.0&tabs=http#odata-query-parameters

Could you please look into this? It still seems to work properly with _some_ tenants / domains, but not for all.

**Comment by PaulDMendoza** [comment]
In my daily alert email I see I'm also getting these failures in the last 24 hours. 

I'm using the .NET Microsoft Graph Nuget package to build this request.  I've changed nothing with my deployment in the last 5 days and I haven't changed the package at all. Based on the number of failures I'd guess it isn't impacting all mailboxes.

```
Status Code: BadRequest
Microsoft.Graph.ServiceException: Code: ErrorInvalidUrlQuery
Message: The $filter parameter value is not supported for Messages resource only a value of receivedDateTime ge value is supported.
ClientRequestId: f8dff307-7cb3-4f98-ae19-9f8181995b33

   at Microsoft.Graph.HttpProvider.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at Microsoft.Graph.BaseRequest.SendRequestAsync(Object serializableObject, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Microsoft.Graph.BaseRequest.SendAsync[T](Object serializableObject, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Microsoft.Graph.MessageDeltaRequest.GetAsync(CancellationToken cancellationToken)
   at DragnetTech.EventProcessors.Office365.CheckOffice365Processor.MineEmailsAsync(IDbConnection center, IDbConnection team, source source, source mailboxsource, emailaccount emailaccount, Guid enterpriseID, Guid eventid, EventProcessorMailbox mailboxStatus, simplequeue simplequeue) in /codebuild/output/src291815337/src/Functions/DragnetTech.EventProcessors/Office365/CheckOffice365Processor.cs:line 1646
```

**Comment by cferrante** [comment]
Thanks @fasterforward! The messages url without delta [https://graph.microsoft.com/v1.0/me/mailFolders/inbox/messages?$orderby=receivedDateTime desc&$filter=receivedDateTime ge 2022-09-27T06:15Z](url) works for me. I wonder why we need the delta url? @PaulDMendoza please try the url recommended by @fasterforward.

**Comment by stevenou** [comment]
This issue appears to be resolved for me. We have automatic retries for these jobs and our retry queue size has been going down. I just manually retried the remaining and they all succeeded. 🤷‍♂️

**Comment by cferrante** [comment]
Thanks @stevenou! I had stopped watching the ticket. Our users would not wait, so I pushed code changes (taking into account tips mentioned by @fasterforward - Thanks!).

I just tested the previous code in an old test environment, and the delta appears to be working again for me as well.

@PaulDMendoza I hope you are back online as well.
