### ISSUE TITLE
Redirect URI update 

### ISSUE THREAD

**Issue by GhArchitecht** [microsoftgraph/microsoft-graph-docs#18643]
[Redirect URI has been updated on Postman Desktop and browser to  "https://oauth.pstmn.io/v1/callback". Get errors when using the following URI https://oauth.pstmn.io/v1/browser-callback]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 142c7d14-408c-e23d-a2b3-f08b815e09e5
* Version Independent ID: d13758c7-dd3c-1744-6163-b042c0e4afce
* Content: [Use Postman with the Microsoft Graph API - Microsoft Graph](https://learn.microsoft.com/en-us/graph/use-postman#step-5-get-a-delegated-access-token)
* Content Source: [concepts/use-postman.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/use-postman.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @jasonjoh
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jasonjoh** [comment]
@GhArchitecht I've update the collection so that we have the redirect explicitly set to `https://oauth.pstmn.io/v1/browser-callback`, which is what [Postman documentation](https://learning.postman.com/docs/sending-requests/authorization/#oauth-20) recommends:

> Callback URL - The client application callback URL to redirect to after auth. This must be registered with the API provider. If not provided, Postman will use a default empty URL and attempt to extract the code or access token from it. If this doesn't work for your API, you can use the following URL: https://oauth.pstmn.io/v1/browser-callback

I believe that by setting it explicitly, rather than relying on the app's default, it should work across all versions.
