### ISSUE TITLE
Cost  for graph.microsoft.com/v1.0/groups/delta?$filter=id eq 'id' 

### ISSUE THREAD

**Issue by ilantom** [microsoftgraph/microsoft-graph-docs#18776]
I see in the doc that **The following table lists base request costs. Any requests not listed have a base cost of 1**.

What about the cost for graph.microsoft.com/v1.0/groups/delta?$filter=id eq 'id' 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ce39639f-5e2c-06d6-5775-ac16a6a4828e
* Version Independent ID: ce39639f-5e2c-06d6-5775-ac16a6a4828e
* Content: [Microsoft Graph service-specific throttling limits - Microsoft Graph](https://learn.microsoft.com/en-us/graph/throttling-limits)
* Content Source: [concepts/throttling-limits.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/throttling-limits.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @FaithOmbongi
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @ilantom, for asking this question. The cost for `graph.microsoft.com/v1.0/groups/delta?$filter=id eq 'id'` is also 1.

**Comment by ilantom** [comment]
Thank you @FaithOmbongi! Is there any doc where it mentions that? I don't see x-ms-resource-unit header in the response on running graph.microsoft.com/v1.0/groups/delta?$filter=id eq 'id'. How do I check if 1 is the value?

**Comment by FaithOmbongi** [comment]
Hi @ilantom - Because we can't list all possible paths, we only list the exceptions in the table. And as per this note, all other identity and access resources nt in the "exception" table have a cost of 1.

<img width="509" alt="image" src="https://user-images.githubusercontent.com/14026935/195522308-2a10aea6-89c3-472e-a69f-8165cc880995.png">

Let me confirm about the x-ms-resource-unit header and when you should receive it.

**Comment by ilantom** [comment]
Any update?

> Let me confirm about the x-ms-resource-unit header and when you should receive it.
