### ISSUE TITLE
microsoft graph rest api returns 404

### ISSUE THREAD

**Issue by Venya331** [microsoftgraph/microsoft-graph-docs#1883]
Dear All,
when im trying to use graph rest api for tasks i have 404 answer. does it mean that this api is deprecated? or deleted?
![image](https://user-images.githubusercontent.com/33000995/31862067-a8ef62ba-b740-11e7-8856-96390652e89d.png)

**Comment by mlafleur** [comment]
Could you please post this question in [Stack Overflow](https://stackoverflow.com/questions/tagged/microsoft-graph) and tag your question with `microsoft-graph`? This repository a good forum for receiving technical support on the API itself. 

This forum is specifically for errors/issues with the Microsoft Graph Documentation set rather than the API itself. While there is certainly overlap, questions regarding the use of Microsoft should be posted on Stack Overflow where you'll likely get a quicker response and benefit other developers facing the same challenges.

**Comment by Hongbo-Miao** [comment]
@Venya331 did you add `Authorization: {token}` in your header?

Sign in with your account and try again in [Graph Explorer](https://developer.microsoft.com/en-us/graph/graph-explorer)
