### ISSUE TITLE
New User.employeeId ExtensionProperty not working

### ISSUE THREAD

**Issue by GregSpyra** [microsoftgraph/microsoft-graph-docs#1884]
Recently in our tenant appeared a new `employeeId` attribute to the `user` entity.

We have over 40k user accounts; some of them created as pure Azure AD Users and others as Mail Users (via Exchange Online).

For many accounts, attempting to `POST` to the `employeeId` fails with the following error:

> Unable to update the specified properties for objects that have originated within an external service.

We have tried with Microsoft Graph (`/Beta`), Azure Graph API (`v1.6`) and via the AAD v2 PowerShell module.

**Comment by mlafleur** [comment]
Could you please post this question in [Stack Overflow](https://stackoverflow.com/questions/tagged/microsoft-graph) and tag your question with `microsoft-graph`? This repository a good forum for receiving technical support on the API itself. 

This forum is specifically for errors/issues with the Microsoft Graph Documentation set rather than the API itself. While there is certainly overlap, questions regarding the use of Microsoft should be posted on Stack Overflow where you'll likely get a quicker response and benefit other developers facing the same challenges.

**Comment by GregSpyra** [comment]
Posted in [Stack Overflow - EmployeeId Not Working](https://stackoverflow.com/questions/46916470/new-user-employeeid-extensionproperty-not-working)

**Comment by PatAltimore** [comment]
Added missing employeeId property to beta documentation: https://github.com/microsoftgraph/microsoft-graph-docs/pull/1961

**Comment by PatAltimore** [comment]
#1961 Merged. Closing issue.
