### ISSUE TITLE
Instructions on claimsmappingpolicy assignment are incorrect

### ISSUE THREAD

**Issue by megakoresh** [microsoftgraph/microsoft-graph-docs#18898]
Cannot follow instructions on assignment of claims mapping policy when using tenant-specific urls, getting the following error:

```sh
curl https://graph.microsoft.com/v1.0/{tenantId}/servicePrincipals/{spId}/claimsMappingPolicies/$ref -H "Authorization: Bearer $t" -H "Content-Type: application/json" -X POST -d '{"@odata.id": "https://graph.microsoft.com/v1.0/policies/claimsMappingPolicies/{policyId}"}' | jq
```
Output:
```json
{
  "error": {
    "code": "BadRequest",
    "message": "Write requests are only supported on contained entities or navigation properties with bindings.",
    "innerError": {
      "date": "2022-10-17T15:13:17",
      "request-id": "62424292-3409-41ed-a0db-e1e7658b145d",
      "client-request-id": "62424292-3409-41ed-a0db-e1e7658b145d"
    }
  }
}
```

Cannot find any way to perform this operation. Trying the rest without tenant ID in url gives same error. Same if trying to add the tenant ID to `@odata.id` url.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 412d516c-ca9f-c3ab-29b9-f856e260ccd4
* Version Independent ID: de36d578-1a56-eb3f-a417-4c71ce17c31d
* Content: [Assign claimsMappingPolicy - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/serviceprincipal-post-claimsmappingpolicies?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/serviceprincipal-post-claimsmappingpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/serviceprincipal-post-claimsmappingpolicies.md)
* Product: **applications**
* Technology: **microsoft-graph**
* GitHub Login: @paulgarn
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by megakoresh** [comment]
> Hi @megakoresh - Microsoft Graph URLs don't require the tenant ID.
> 
> Can you remove the tenant ID and retry your query?

Like I said in the OP - the same error is given if no tenant ID is present.

```sh
(default) [sddev@sd-dev-vm ~/at-auth-api]$ curl https://graph.microsoft.com/v1.0/servicePrincipals/{spId}/claimsMappingPolicies/$ref -H "Authorization: Bearer $t" -H "Content-Type: application/json" -X POST -d '{"@odata.id": "https://graph.microsoft.com/v1.0/policies/claimsMappingPolicies/{policyId}"}' | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   421    0   294  100   127   1615    697 --:--:-- --:--:-- --:--:--  2313
{
  "error": {
    "code": "BadRequest",
    "message": "Write requests are only supported on contained entities or navigation properties with bindings.",
    "innerError": {
      "date": "2022-10-18T09:33:31",
      "request-id": "<redacted>",
      "client-request-id": "<redacted>"
    }
  }
}
```

**Comment by FaithOmbongi** [comment]
Hi @megakoresh -

I've tried to reproduce the issue but haven't been able to. Using Graph Explorer, I've created a similar policy and successfully assigned it to a service principal.

<img width="811" alt="image" src="https://user-images.githubusercontent.com/14026935/196402501-4106d519-b3c8-44c6-a932-77db2abf54aa.png">

<img width="815" alt="image" src="https://user-images.githubusercontent.com/14026935/196402555-d45abfdf-eee5-49eb-9f3f-729ae3287f08.png">


Unfortunately, this forum is only for documentation-related issues but functionality issues like this are investigated through [Microsoft Graph Q&A](https://docs.microsoft.com/en-us/answers/topics/microsoft-graph-identity.html). Please file this issue there and provide a request ID so it can be investigated. 

No doc updates identified for the related documentation for now, but the doc will be updated when required. Closing this issue here.
