### ISSUE TITLE
subscription/webhook for groups changes is not sending notifications

### ISSUE THREAD

**Issue by sharonAC** [microsoftgraph/microsoft-graph-docs#19138]
hello,
i am creating a subscription by:
POST https://graph.microsoft.com/v1.0/subscriptions
{
    "changeType": "created,updated",
    "notificationUrl": "https://devsrnst.ai-logix.net/api/AAD/",
    "resource": "groups",
    "expirationDateTime": "2022-11-07T14:00:00.0000000Z",
    "clientState": "SecretClientState"
}

and i am getting a successful response:
{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#subscriptions/$entity",
    "id": "e8f4aecd-a86d-4744-bdd5-1c9bf8bfb98e",
    "resource": "groups",
    "applicationId": "de8bc8b5-d9f9-48b1-a8ad-b748da725064",
    "changeType": "created,updated",
    "clientState": "SecretClientState",
    "notificationUrl": "https://devsrnst.ai-logix.net/api/AAD/",
    "notificationQueryOptions": null,
    "lifecycleNotificationUrl": null,
    "expirationDateTime": "2022-11-07T14:00:00Z",
    "creatorId": "9605bc51-2bfd-41f4-9223-4a7fc1bd4692",
    "includeResourceData": null,
    "latestSupportedTlsVersion": "v1_2",
    "encryptionCertificate": null,
    "encryptionCertificateId": null,
    "notificationUrlAppId": null
}

but when i try to change a group name for example, i am not getting any notification.
what am i missing?

thanks

**Comment by HACKED-need-HELP** [comment]
Jennifer has sent you an email via Gmail confidential mode:

[image: Gmail logo]Re: [microsoftgraph/microsoft-graph-docs] subscription/webhook for groups changes is not sending notifications (Issue #19138) <https://confidential-mail.google.com/msg/AGMme3Nh6dWACHF6fIvaB4i8H_dmVBPZpe4sGFHb73pJDekWX3ZTtWuPdairSC18NEXqDnJD3mj7X_D_cd4YiW2ZUNtONAreDKRfowz3r8AR0YS1ZaFemUIenjSH034V8GCxSm48tZwyOU0gQJomAFA5JC5mO8LLZAtJH9nAhVZp32NOq6SkaYV2AFJJo5feDJHme93Mxr-LKl-bT7lNK5y_AOg0whEPwvlzRPI=>

This message was sent on Nov 6, 2022 at 12:35:36 PM PST
You can open it by clicking the link below. This link will only work for ***@***.***

View the email <https://confidential-mail.google.com/msg/AGMme3Nh6dWACHF6fIvaB4i8H_dmVBPZpe4sGFHb73pJDekWX3ZTtWuPdairSC18NEXqDnJD3mj7X_D_cd4YiW2ZUNtONAreDKRfowz3r8AR0YS1ZaFemUIenjSH034V8GCxSm48tZwyOU0gQJomAFA5JC5mO8LLZAtJH9nAhVZp32NOq6SkaYV2AFJJo5feDJHme93Mxr-LKl-bT7lNK5y_AOg0whEPwvlzRPI=>

Gmail confidential mode gives you more control over the messages you send. The sender may have chosen to set an expiration time, disable printing or forwarding, or track access to this message. Learn more <https://support.google.com/mail/answer/7674059>
Gmail: Email by Google
Use is subject to the Google Privacy Policy <https://myaccount.google.com/privacypolicy?hl=en>
Google LLC, 1600 Amphitheatre Parkway, Mountain View, CA 94043, USA
You have received this message because someone sent you an email via Gmail confidential mode.
[image: Google logo]
