### ISSUE TITLE
"Grant an appRoleAssignment " API can be called with only "Application.ReadWrite.All" permission

### ISSUE THREAD

**Issue by mr-oliva** [microsoftgraph/microsoft-graph-docs#19193]
Does this API require "AppRoleAssignment.ReadWrite.All and Application.Read"?

I can call this API with only "Application.ReadWrite.All" permisson.
![image](https://user-images.githubusercontent.com/10346162/201023408-08c017d1-53a4-4c30-8067-c72f242e1045.png)

then, I click "{}" button in above picture to check access token at jwt.ms.

![image](https://user-images.githubusercontent.com/10346162/201024057-5eb42e52-cd47-4316-a88e-c17c24a6f174.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 47f3b787-b279-695c-8681-7832b203d5b8
* Version Independent ID: 794ffd87-99dd-0521-cd5d-8a340d5babad
* Content: [Grant an appRoleAssignment to a service principal - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/serviceprincipal-post-approleassignments?view=graph-rest-1.0&tabs=http#permissions)
* Content Source: [api-reference/v1.0/api/serviceprincipal-post-approleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/serviceprincipal-post-approleassignments.md)
* Product: **applications**
* Technology: **microsoft-graph**
* GitHub Login: @psignoret
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by DMoenks** [comment]
From my understanding, the list of permissions primarily contains least-privilege options and _Application.ReadWrite.All_ would be far more privileged than the combination of _AppRoleAssignment.ReadWrite.All_ and _Application.Read_, as far as I know 🤔

**Comment by FaithOmbongi** [comment]
Thank you @mr-oliva for reporting this issue. Unfortunately, I've been unable to replicate it. On my end, the API fails with a `403 Forbidden` error code when my calling app isn't granted the _AppRoleAssignment.ReadWrite.All_ permission. Please see my receipts below.

<img width="805" alt="image" src="https://user-images.githubusercontent.com/14026935/201394780-3d9c461d-1d77-4ca2-88ce-d61c9cfb5b20.png">

Unfortunately, this forum is only for documentation-related issues but I would recommend that this behavior be investigated further. Kindly file this functionality discrepancy at [Microsoft Graph Q&A](https://docs.microsoft.com/en-us/answers/topics/microsoft-graph-applications.html) and provide a request ID so it can be investigated.

No doc updates identified for now. But the doc will be updated when more information becomes available. Closing this issue here for now.

**Comment by mr-oliva** [comment]
@FaithOmbongi @DMoenks Thank you for your answer.

I acknowledge closing this ticket.
I'll investigate this behavior further.

@FaithOmbongi Did you try it with an admin account?
I think default user cannot call this API.

**Comment by FaithOmbongi** [comment]
> @FaithOmbongi @DMoenks Thank you for your answer.
> 
> I acknowledge closing this ticket. I'll investigate this behavior further using Microsoft Graph Q&A and so on.
> 
> @FaithOmbongi Did you try it with an admin account? I think default user cannot call this API.

@mr-oliva - I used a Global Admin account to test.
