### ISSUE TITLE
No values returned on servicePrincipals getMemberObjects

### ISSUE THREAD

**Issue by skalmark** [microsoftgraph/microsoft-graph-docs#19290]
When im making a https://graph.microsoft.com/beta/me/getMemberObjects I get some values returned, when Im calling this endpoint /servicePrincipals/{id}/getMemberObjects with an Application Object ID that should return at least three GUIDs this is the response 

`{
    "@odata.context": "https://graph.microsoft.com/beta/$metadata#Collection(Edm.String)",
    "value": []
}`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a0de6d0f-6ab2-68ca-674c-053176cff60a
* Version Independent ID: 1f308e98-494e-9ded-e6a1-c96795326485
* Content: [directoryObject: getMemberObjects - Microsoft Graph beta](https://learn.microsoft.com/en-us/graph/api/directoryobject-getmemberobjects?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/directoryobject-getmemberobjects.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/directoryobject-getmemberobjects.md)
* Product: **directory-management**
* Technology: **microsoft-graph**
* GitHub Login: @keylimesoda
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @skalmark for raising this issue.

> When im making a https://graph.microsoft.com/beta/me/getMemberObjects I get some values returned, when Im calling this endpoint **/servicePrincipals/{id}/getMemberObjects**

The endpoint that you shared points to the service principal, not the app object. Please use the service principal object ID.

**Comment by skalmark** [comment]
@FaithOmbongi Im using the object ID. 
I have called  /servicePrincipals/{id} with success but not when adding /getMemberObjects and the post BODY

**Comment by FaithOmbongi** [comment]
Hi @skalmark - I've been unable to repro this behavior. I've tested with both **securityEnabled** = `true` and `false`, and using both the object ID and the appId and my requests are working as per the screenshots I've shared below.

<img width="602" alt="image" src="https://user-images.githubusercontent.com/14026935/202657161-38b4b047-2105-4022-af81-cf282c8f22dc.png">

<img width="626" alt="image" src="https://user-images.githubusercontent.com/14026935/202657770-5db7f2fa-a752-4d1d-9d20-3be3735a0e20.png">

If you're still facing this issue, please file this issue at [Microsoft Graph Q&A](https://docs.microsoft.com/en-us/answers/topics/microsoft-graph-applications.html) and provide a request ID so that it can be investigated. Unfortunately, this forum is only for documentation-related issues but functionality issues like this are investigated through [Microsoft Graph Q&A](https://docs.microsoft.com/en-us/answers/topics/microsoft-graph-applications.html). 

Closing this issue here.
