### ISSUE TITLE
Update logo

### ISSUE THREAD

**Issue by alexdrenea** [microsoftgraph/microsoft-graph-docs#19305]
Can you show an example how to make an update request for the logo? 

The only indication on the page is that it requires a "stream" but how do you pass in a stream if the content type is Application/json?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8c6afab3-9682-0f8e-0441-2adfde3f84ef
* Version Independent ID: 6eee450a-b6d0-0908-0392-00e01d412185
* Content: [Update application - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/application-update?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/application-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/application-update.md)
* Product: **applications**
* Technology: **microsoft-graph**
* GitHub Login: @sureshja
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by alexdrenea** [comment]
Though more experimentation, I found that the docs are misleading in this case: 
You cannot (as far as I can tell) update the logo with a PATCH on the `/applications/{id}` endpoint, but rather a PUT on the `/applications/{id}/logo` endpoint

**Comment by FaithOmbongi** [comment]
Thank you @alexdrenea for asking this question.

Unfortunately, Graph Explorer doesn't support uploading an image. To update an image, you use the PUT method as you've rightly pointed out - Please see my screenshot below (I'll update the documentation). Please use Postman to test updating images. You can also file [a feature request](https://github.com/microsoftgraph/microsoft-graph-explorer-v4/issues) on the Graph Explorer repo so that support for uploading an image can be considered.

<img width="869" alt="image" src="https://user-images.githubusercontent.com/14026935/203099383-570c9411-5ac7-4517-a3b0-29c91c4e8fbe.png">

**Comment by alexdrenea** [comment]
Thank you @FaithOmbongi 
I think updating the docs to show the PUT /logo method, as well as an example on how to use it in powershell / bash that would be awesome. 
Thank you for the Postman example, however as you mentioned, that is good for testing. It would be useful to see this in action using scripts that can be included in automation.
Thanks again.
