### ISSUE TITLE
$expand is not working in transitiveMemberOf 

### ISSUE THREAD

**Issue by shayan-brcm** [microsoftgraph/microsoft-graph-docs#19424]
We are calling Microsoft's Graph API to retrieve user data via the /me endpoint, using $expand=transitiveMemberOf to get the user's groups both direct and indirect.
`https://graph.microsoft.com/v1.0/me?$expand=transitiveMemberOf`

The problem we are facing is that $expand=transitiveMemberOf seems to just be returning the same groups as $expand=memberOf.

Due to the implementation, we are restricted to a single API call therefore we cant make separate API
`https://graph.microsoft.com/v1.0/me/transitiveMemberOf`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: efff8389-bccd-8e3b-ceb1-cd176819b92c
* Version Independent ID: 38d4e860-024e-72de-2546-60d236667129
* Content: [List group transitive memberOf - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/group-list-transitivememberof?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/group-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/group-list-transitivememberof.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @psaffaie
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @shayan-brcm for raising this issue. The two APIs return "the same" set of results, but because of `?$expand=transitiveMemberOf`'s [limitation of 20 objects](https://learn.microsoft.com/en-us/graph/query-parameters#expand-parameter:~:text=With%20Azure%20AD%20resources%20that%20derive%20from%20directoryObject%2C%20like%20user%20and%20group%2C%20%24expand%20typically%20returns%20a%20maximum%20of%2020%20items%20for%20the%20expanded%20relationship%20and%20has%20no%20%40odata.nextLink.%20See%20more%20known%20issues.), and because the two APIs seem to use a different ordering scheme for results, the results seem different. But they are the same results.

> Due to the implementation, we are restricted to a single API call therefore we cant make separate API
> https://graph.microsoft.com/v1.0/me/transitiveMemberOf

Unfortunately, this forum is only for documentation-related issues but implementation and functionality issues like this are investigated through [Microsoft Graph Q&A](https://docs.microsoft.com/en-us/answers/topics/microsoft-graph-groups.html). Please file this issue there and fellow engineers can provide you with suggestions for implementation.
