### ISSUE TITLE
Unable to Update User.refreshTokensValidFromDateTime attribute

### ISSUE THREAD

**Issue by GregSpyra** [microsoftgraph/microsoft-graph-docs#1945]
User entity specification allows PATCH instruction for refreshTokensValidFromDateTime attribute, however when try setting it with Azure Graph API 1.6 for both federated and non-federated users receive the following HTTP error message:
"Bad_Request: Property 'refreshTokensValidFromDateTime' is read-only and cannot be set."

Are there any conditions that have to be met before the attribute could be set?
Should I submit documentation update request?

Thanks

**Comment by mlafleur** [comment]
Please note that the Azure Graph API and Microsoft Graph API (for which this repo holds the docs) are two different APIs. While some functionality overlaps, the endpoints and patterns are not interchangeable. 

Currently the documentation for the [User](https://github.com/microsoftgraph/microsoft-graph-docs/blob/64bb9e996748645168d23976ec195fd296172828/api-reference/beta/resources/user.md) resources states the following for the refreshTokensValidFromDateTime property:

> Any refresh tokens or sessions tokens (session cookies) issued before this time are invalid, and applications will get an error when using an invalid refresh or sessions token to acquire a delegated access token (to access APIs such as Microsoft Graph). If this happens, the application will need to acquire a new refresh token by making a request to the authorize endpoint. Read-only. **Use [invalidateAllRefreshTokens](https://github.com/microsoftgraph/microsoft-graph-docs/blob/64bb9e996748645168d23976ec195fd296172828/api-reference/beta/api/user_invalidateallrefreshtokens.md) to reset.**

The documentation for `invalidateAllRefreshTokens` shows that this method is called via a `POST` rather than a `PATCH`.

**Comment by GregSpyra** [comment]
Agree, only the [Azure Graph API Reference](https://msdn.microsoft.com/en-us/library/azure/ad/graph/api/entity-and-complex-type-reference#user-entity) actually specifies the possibility to set this attribute - what's incorrect.
However, if you look at the [Json Representation](https://developer.microsoft.com/en-us/graph/docs/api-reference/beta/resources/user#json-representation) of the User Entity for Microsoft Graph API (Beta) reference the `refreshTokensValidFromDateTime` property is missing. ;)

**Comment by dkershaw10** [comment]
We should fix the AAD Graph docs.  For Microsoft Graph beta User doc, this property is described, but is missing from the example JSON (which we need fix). However I would encourage you to use Graph Explorer as the source of truth - eventually we hope to evolve our docs to have "inline Graph Explorer" to try right from the docs.

Hope this helps,
