### ISSUE TITLE
Users - Error when selecting "birthday"

### ISSUE THREAD

**Issue by jimmywim** [microsoftgraph/microsoft-graph-docs#19565]
When adding `birthday` to the `select` of the `/users` endpoint, the following error is returned:

`GET https://graph.microsoft.com/v1.0/users?$select=displayName,employeeHireDate,birthday`

```
{
    "error": {
        "code": "-1, Microsoft.SharePoint.Client.InvalidClientQueryException",
        "message": "The expression \"id in ('8172ade2-0b74-41dd-9533-c5c223ae6ff8','7ab8f001-f15c-4fa2-87e6-847ffb7cd58e','63856979-7e23-4a8f-86c8-7c92b944c0f4','28a19981-2b96-417b-9d7c-034cd2e00927','a762f29d-4d7e-4f47-8be8-190f8a057b42','b4f305e5-e6fd-434f-9aee-c2b1bd80655e','3df66f71-b6f8-45c8-9a3c-c656749f74ce','355d424b-03e4-4a84-99dd-5558234eddb1','a1ba1c93-8e40-49b8-bc10-0dc9ca2cd30d','5f8d3632-336c-45ed-99ca-15a35d62a0fa','4f6b2881-caec-42b6-99d2-69c8ec16939c','dc5c2c47-72b0-461e-9415-ffbf6e215750','025d7a50-5925-4f09-9e2c-abf5f3dc1cd1','f4ccd09a-828d-4841-a274-e8a15125fd50','d7c6d258-a5a5-4c23-b03d-de4521cebf2c','544ac2b1-af11-4493-acef-980723d7235f','7883c6ef-9cbe-47d7-987b-ed720e6d8f7f','ce3883cb-8380-4ed2-896a-2ccd6e2fa1cf','8a8495d6-c2f0-4762-8ccc-6206b12c6a06','64659491-816c-4e64-9249-939dfa8e8a02','5c47e0c9-44d4-4588-8cca-b110d9e7ad9a','40f9ca7d-d80a-4dd8-b3cc-4cdd0d6b700e','e6bcfc9e-2925-4bfc-9906-976e7a091ef6','46c0726c-9602-4270-bb3b-54ef8abc34cc')\" is not valid.",
        "innerError": {
            "date": "2022-12-09T14:09:25",
            "request-id": "492cc883-cc3a-4b98-a74f-16b166569040",
            "client-request-id": "5b8e617c-da64-18c8-8b5e-37d8ea0b5fe2"
        }
    }
}
```

Ideally, we would like to be able to $select and $filter on users birthday and employee Hire Date - so we can e.g. return users whose birthday is in the 7 days, or are celebrating a work anniversary in the next 7 days, etc.

Additionally, when attempting to filter on `employeeHireDate` it returns `Invalid filter clause`, despite this doc stating it supports `$filter`.

---
#### Document details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 71215894-d1c8-8d36-9dbb-adb35cfbc5f9
* Version Independent ID: 34e2e6e4-578a-9309-ebcf-94b640dc4e4c
* Content: [user resource type - Microsoft Graph v1.0](https://learn.microsoft.com/en-gb/graph/api/resources/user?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/user.md)
* Product: **users**
* Technology: **microsoft-graph**
* GitHub Login: @yyuank
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jimmywim** [comment]
Apologies, I've just clocked the text near the top of the article that some properties are only returned when retrieving a single user:

```
Certain properties cannot be returned within a user collection. The following properties are only supported when [retrieving a single user](https://learn.microsoft.com/en-gb/graph/api/user-get?view=graph-rest-beta): aboutMe, birthday, hireDate, interests, mySite, pastProjects, preferredName, responsibilities, schools, skills, mailboxSettings.
```

Is there any possibility these SharePoint-based properties will be returned in a collection of users, is this something that will ever be implemented? Or are we still having to use the SharePoint User Profile Service coupled with SharePoint Search APIs to return these?

**Comment by yyuank** [comment]
@FaithOmbongi  could you please assign this issue to someone from SharePoint? We don't own the SharePoint properties and thus can't answer this question.

**Comment by FaithOmbongi** [comment]
Thank you @jimmywim for raising the issue and resolving it.

> Ideally, we would like to be able to $select and $filter on users birthday and employee Hire Date - so we can e.g. return users whose birthday is in the 7 days, or are celebrating a work anniversary in the next 7 days, etc.

Just as you've concluded from the doc, this query wouldn't work because $select of birthday in a collection isn't supported

> Additionally, when attempting to filter on employeeHireDate it returns Invalid filter clause, despite this doc stating it supports $filter.

**employeeHireDate** supports $filter only with [advanced query parameters](https://learn.microsoft.com/en-us/graph/aad-advanced-queries?tabs=http); otherwise, you get the invalid filter error message.

With these answers, and if you need help with implementation, you can file a question at [Microsoft Graph Q&A](https://docs.microsoft.com/en-us/answers/topics/microsoft-graph-users.html) so other devs can share tips on how to achieve what you want to implement. Unfortunately, this forum is only for documentation-related issues but functionality issues are discussed at [Microsoft Graph Q&A](https://docs.microsoft.com/en-us/answers/topics/microsoft-graph-users.html).

------------------------------------------------------

> Is there any possibility these SharePoint-based properties will be returned in a collection of users, is this something that will ever be implemented? Or are we still having to use the SharePoint User Profile Service coupled with SharePoint Search APIs to return these?

Unfortunately, I'm unable to answer this question. However, you can [submit a feature request](https://feedbackportal.microsoft.com/feedback/forum/ebe2edae-97d1-ec11-a7b5-0022481f3c80) so the engineering team can consider this functionality request; also so other devs can amplify your voice by upvoting your request.


Because no updates are required for the docs, I'll close this issue here.
