### ISSUE TITLE
Insufficient privileges to complete the operation

### ISSUE THREAD

**Issue by kenlthai** [microsoftgraph/microsoft-graph-docs#19702]
Follow the permission setting in the documentation result in error:

`statusCode: 403,
  code: 'Authorization_RequestDenied',`

The same permission setting work for GET and UPDATE command, but not for CREATE or DELETE

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cc45e9cc-5d66-5d5e-13d7-f9629b478bd8
* Version Independent ID: 1cdec7f7-c9ae-9afb-e857-51a335067471
* Content: [Create federationConfiguration - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/domain-post-federationconfiguration?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/domain-post-federationconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/domain-post-federationconfiguration.md)
* Product: **identity-and-sign-in**
* Technology: **microsoft-graph**
* GitHub Login: @akgoel23
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by lramosvea** [comment]
@FaithOmbongi to add the right labels

**Comment by FaithOmbongi** [comment]
Thank you @kenlthai for raising this issue. A few questions for you to help us troubleshoot:
+ Are you using a delegated scenario (calling the API with a signed-in user) or an app-only scenario (without a signed-in user)?
+ If delegated scenario, can you confirm that your app has both _Domain.ReadWrite.All_ permission and _Global Admin_ privileges?
+ Can you share a request ID?

**Comment by kenlthai** [comment]
Hi Faith,

Please refer below for the answer to your questions:

   - I'm using an App-only scenario.
   - I have Domain.ReadWrite.All permission set for my application.
   - Request ID is
      - code: 'Authorization_RequestDenied',
      requestId: '55fa02c5-6dac-4810-a6e9-ee21fcf5fb90',
      date: 2022-12-22T14:29:08.000Z,

If there is any other information needed, please let me know.

Kind regards,
Ken

**Comment by FaithOmbongi** [comment]
Thank you @kenlthai for this info. I'll forward this internally for investigation. Kindly bear with us.

**Comment by FaithOmbongi** [comment]
Thank you @kenlthai for your patience.
I've checked in with the team and unfortunately, Domain.ReadWrite.All doesn't work currently. We are working to resolve this issue.

In the mean time, instead of using Microsoft Graph application permissions, you can use Azure AD roles as an alternative. [Security Admin](https://learn.microsoft.com/en-us/azure/active-directory/roles/permissions-reference#security-administrator), [External Identity provider admin](https://learn.microsoft.com/en-us/azure/active-directory/roles/permissions-reference#external-identity-provider-administrator), and [Global admin](https://learn.microsoft.com/en-us/azure/active-directory/roles/permissions-reference#global-administrator) are all supported by this API in app-only context.
