### ISSUE TITLE
Example 2 for PowerShell is failing

### ISSUE THREAD

**Issue by alexandair** [microsoftgraph/microsoft-graph-docs#19758]
```powershell
Import-Module Microsoft.Graph.Users

# A UPN can also be used as -UserId.
Get-MgUser -UserId $userId -ExpandProperty "manager(`$levels=max;`$select=id,displayName)" -Property "id,displayName" -CountVariable CountVar -ConsistencyLevel eventual
```

Parameters `-UserId`, `-CountVariable`, and `-ConsistencyLevel` cannot be used at the same time.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0106f6fc-0b6d-deae-ef40-37f29a94abbd
* Version Independent ID: 8614876d-6a23-3c10-c2f6-97a059f5c73b
* Content: [List manager - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/user-list-manager?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/user-list-manager.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/user-list-manager.md)
* Product: **users**
* Technology: **microsoft-graph**
* GitHub Login: @yyuank
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Hi @msewaweru - Kindly assist here. Thanks.

**Comment by msewaweru** [comment]
This example does not work because the `Count` and `ConsistencyLevel` query parameters are applicable when [fetching a collection of resource type](https://learn.microsoft.com/en-us/graph/query-parameters?tabs=http#count-parameter). In this case, they are being used to fetch a single item, which is currently not supported. 
I've opened [an issue](https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/1749) in the SDK repo for investigation.

Proceeding to close this issue.
