### ISSUE TITLE
What is the updateCategory "unknownFutureValue" referes to?

### ISSUE THREAD

**Issue by Sudheerkumar** [microsoftgraph/microsoft-graph-docs#19859]
Hi,

Under the updateCategory - there are only two possible values mentioned
1. Feature
2. unknownFutureValue

So in case if I have an azure device and I enroll it has updateCategory = "feature" and enroll it into updateManagement - Does the devices which are enrolled with this property will only receive " feature " updates from **/catalog** api? `https://graph.microsoft.com/beta/admin/windows/updates/catalog/entries`

what is the device that is enrolled needs a quality/expedited update?

I really want to understand what that term updateCategory in /enrollassets mean

Thank you

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 59b7c47e-af3a-0a51-a260-8bf7ed56cebc
* Version Independent ID: 6521a8be-eec4-38d2-e953-1227e4ea399e
* Content: [updatableAsset: enrollAssets - Microsoft Graph beta](https://learn.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-enrollassets?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/windowsupdates-updatableasset-enrollassets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/windowsupdates-updatableasset-enrollassets.md)
* Product: **w10**
* Technology: **microsoft-graph**
* GitHub Login: @aarononeal
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by aarononeal** [comment]
> What is the updateCategory "unknownFutureValue"

Please see [evolvable enums](https://learn.microsoft.com/en-us/graph/best-practices-concept?context=graph%2Fapi%2F1.0&view=graph-rest-1.0#handling-future-members-in-evolvable-enumerations).

> I really want to understand what that term updateCategory in /enrollassets mean

By default Microsoft manages the updates a given device receives in various categories such as feature, quality, and driver. If you as the administrator want to manually approve or schedule updates using the WUfB deployment service, then you must enroll your devices (assets) into the service and specify the categories that you're taking control over.

If you enroll a device in feature update management, then your device will stop receiving feature updates unless you add the device to a feature update deployment. It will continue to receive quality updates per Microsoft defaults or per other IT managed configuration, such as through group policy settings.

The service doesn't currently provide general quality update controls, and that's why the enum doesn't have a value for quality updates yet. However, you can still deploy [expedited quality updates](https://learn.microsoft.com/en-us/graph/windowsupdates-deploy-expedited-update) even without enrolling.

**Comment by aarononeal** [comment]
Answered in #19861
