### ISSUE TITLE
$ sign for query parameters is confusing

### ISSUE THREAD

**Issue by BloodyRain2k** [microsoftgraph/microsoft-graph-docs#19879]
I still don't really understand what the difference is for running a query parameter with or without a $, like expand.
Is the $ sign the beta version that's not yet finalized? And if so, why is the page suggesting that the $ variant should be used by default?

Because I did find a query that works without the $, but fails with it (tested in the Graph Explorer):
`https://graph.microsoft.com/v1.0/me/drive/root?expand=children(select=name,id,folder,size)&$select=id,name,children,size`
This query works fine and returns all root items of the drive including the children for the folders.
But if `$expand` is used instead it fails and complains that it doesn't understand `(select=name,id,folder,size)`.

Not sure if this is just me not fully understanding the docs or if there's something going different from how it should, but I wanted to point it out at least.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 44f6304a-ab90-8543-39c7-2afd61197ffb
* Version Independent ID: 9ca019b5-063f-33a2-3cb9-3ab6baafe9d4
* Content: [Use query parameters to customize responses - Microsoft Graph](https://learn.microsoft.com/en-us/graph/query-parameters?context=graph%2Fapi%2F1.0&view=graph-rest-1.0&tabs=http)
* Content Source: [concepts/query-parameters.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/query-parameters.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @mumbi-o
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @BloodyRain2k for asking this question.

To add the `$` prefix or not is defined in the [OData protocol](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part2-url-conventions.html#sec_SystemQueryOptions) (see screenshot below). Microsoft Graph query options are compatible with OData v4.01.

   <img width="1059" alt="image" src="https://user-images.githubusercontent.com/14026935/212353668-9d88399b-1fc3-45ec-bd14-c9c0fe333019.png">

Following this, as a best practice and to help developers not forget to append `$` in their code, you'll find all the usages of these options in the Microsoft Graph documentation are appended with `$` prefix (if there are any without, may be an oversight).

About your comment

> But if $expand is used instead it fails and complains that it doesn't understand (select=name,id,folder,size).

If prefixing with `$`, prefix for all usage. If not (which I wouldn't recommend because `$` is optional only for a subset of APIs) then be consistent across the URL. **BUT, as a best practice, always prefix with `$`.** Therefore:

```
https://graph.microsoft.com/v1.0/me/drive/root?$expand=children($select=name,id,folder,size)&$select=id,name,children,size
```

Hope this helps.

**Comment by BloodyRain2k** [comment]
> ```
> https://graph.microsoft.com/v1.0/me/drive/root?$expand=children($select=name,id,folder,size)&$select=id,name,children,size
> ```
> 
> Hope this helps.

This actually did the trick. I guess the actual complaint was that not all parameters were prefixed, but the error message instead wasn't very clear.

```
{
    "error": {
        "code": "BadRequest",
        "message": "Parsing OData Select and Expand failed: Term '(select=name,id,folder,size)' is not valid in a $select or $expand expression.",
        "innerError": {
            "date": "2023-01-14T00:00:32",
            "request-id": "44dae486-4d29-490a-bf03-9865d3d269e6",
            "client-request-id": "99b6f2bb-7571-d245-7c3e-e299ae69fceb"
        }
    }
}
```

This doesn't really tell me that I should prefix the `(select=`, it sounds more like I'm trying to do something that isn't supported in this query at all. Maybe the error message could be a bit cleared up.

Either way, thanks for clearing this up.
