### ISSUE TITLE
permission issue on user_getmembergroups

### ISSUE THREAD

**Issue by lizzyinGit** [microsoftgraph/microsoft-graph-docs#1994]
Issue: 
delegation permisssion: it says least permission requested is : User.Read and Group.Read.All, 
but per testing, it is not enough. unless Directory.AccessAsUser.All is assigned, we are not able to get groups the user belongs to.

Article:
https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/api/user_getmembergroups

**Comment by CameronDwyer** [comment]
Groups is such a fundamental concept in the services unified through the Graph and the future of Office 365 that getting access to Groups a user is a member of needs to be as friction free as possible.

Groups has been pitched primarily as a self-service concept to allow self-organising groups or teams to be efficient without involving IT:
- Groups (and now Teams) allow for self service creation
- End users can acquire apps from the app store

For any of those apps the user acquires to know anything about the groups the user is a member of requires Admin Consent. This seems to be a step in the wrong direction. As an app developer, if I need to get Admin Consent for such a basic permission I may as well ask for everything I need (possibly more than is required) while I’ve got the Administrator looking at a consent form and then not have to bother the end users with user delegated permissions – kind of defeats the point of user delegated permissions.

Can we please get these permissions changed so that as user can see groups they are a member of with requiring Admin Consent? Thanks.

**Comment by krbain** [comment]
We've updated the permissions to add more granular permissions to get group membership without needing more privileges.
