### ISSUE TITLE
One App per Schema Extensions or more

### ISSUE THREAD

**Issue by goldfinger3** [microsoftgraph/microsoft-graph-docs#20216]
There is one open question:  
We can create multiple schema extension with on app.  
But Get-MsgSchemaExtension is showing only one extension. 
Get-MgSchemaExtension -Filter "owner eq '<appid>'"
Is this a bug or a non-supported configuration?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 27b7b26c-499c-6b30-96cd-04b6ac80fbc0
* Version Independent ID: 2e8b2a6a-961b-40d6-acf0-a096a3aec9a1
* Content: [Create schemaExtension - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/schemaextension-post-schemaextensions?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/schemaextension-post-schemaextensions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/schemaextension-post-schemaextensions.md)
* Product: **extensions**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @goldfinger3 for asking this question.

The maximum limit of schema extensions per owner app is five. Please see the comment in the table here:
[Choose an extension type for your application](https://learn.microsoft.com/en-us/graph/extensibility-overview?tabs=http#choose-an-extension-type-for-your-application).

> But Get-M~s~gSchemaExtension is showing only one extension.
> Get-MgSchemaExtension -Filter "owner eq ''"

Is it possible that the app owns only one schema extension? As you can see from the screenshot of my repro, the same command you ran matches correctly.

<img width="887" alt="image" src="https://user-images.githubusercontent.com/14026935/218491141-e613cc15-913c-41c8-a532-e5180c30d50c.png">

**Comment by goldfinger3** [comment]
No the owner app has 3 extensions. But I created only the first one  (extl6guiplz_LinuxAddOn) 
We are still developing, so they are in state of InDevelopment.
![schema](https://user-images.githubusercontent.com/62419481/218525063-132929bc-356c-4cf7-a52f-bc1e385ba974.PNG)

**Comment by FaithOmbongi** [comment]
> No the owner app has 3 extensions. But I created only the first one (extl6guiplz_LinuxAddOn) We are still developing, so they are in state of InDevelopment. ![schema](https://user-images.githubusercontent.com/62419481/218525063-132929bc-356c-4cf7-a52f-bc1e385ba974.PNG)


This response shows the owner app has only one extension.

> We are still developing, so they are in state of InDevelopment.

It shouldn't matter in this case because your request doesn't scope the filter to the **status** property.

Run the same request in [Graph Explorer](https://aka.ms/ge) and if it returns 1 extension, then I think the owner app has created only 1 extension. You can also run [GET https://graph.microsoft.com/v1.0/schemaExtensions](https://developer.microsoft.com/en-us/graph/graph-explorer?request=schemaExtensions&method=GET&version=v1.0&GraphUrl=https://graph.microsoft.com) and do a manual search of the response payload to verify the instances where the owner ID appears.

If you still find the response isn't accurate and there should be three extensions, kindly file an issue at [Microsoft Graph Q&A](https://learn.microsoft.com/en-us/answers/tags/306/microsoft-graph-extensions-api) and provide a request ID for investigation. This forum is only for documentation-related issues but functionality issues like this are investigated through [Microsoft Graph Q&A](https://learn.microsoft.com/en-us/answers/tags/306/microsoft-graph-extensions-api).

Closing this issue here.
