### ISSUE TITLE
Calling API triggers onMembersAdded function in Teams Bot

### ISSUE THREAD

**Issue by PerryRose** [microsoftgraph/microsoft-graph-docs#20348]
This page does not explain why calling this API to obtain the conversation between a user and a Teams bot has recently began triggering the onMembersAdded function inside the Bot - causing the Welcome card to be sent on every single call to that user (regardless of whether the API call was made inside the bot, or outside using Postman)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8e1a9606-814b-0523-9115-94c5dfe2449f
* Version Independent ID: c654b788-9879-f970-b629-2019b02db81d
* Content: [Get chat between user and teamsApp - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @AkJo
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Prasad-MSFT** [comment]
Thanks for reporting this. We are checking the issue and will get back to you shortly.

**Comment by Prasad-MSFT** [comment]
Yes @PerryRose - We are also able to repro this. When we are calling below API
`GET /users/{user-id | user-principal-name}/teamwork/installedApps/{app-installation-id}/chat`
to obtain the conversation between a user and a Teams bot. Its triggering the onMembersAdded function inside the Bot - causing the Welcome card to be sent on every single call to that user.

We will check this with engineering team and will update the doc accordingly if required.

Thanks again.

**Comment by Prasad-MSFT** [comment]
@PerryRose - We have raised an ICM for this issue and engineering team is looking into it. We will inform you once we get any update from them.

Thanks!

**Comment by PerryRose** [comment]
@Prasad-MSFT Thanks very much!

**Comment by Prasad-MSFT** [comment]
@PerryRose - We got update from engineering team saying "Generally we should use the `installationUpdates` to track the personal install events: https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/subscribe-to-conversation-events?tabs=dotnet#installation-update-event

The `memberAdded` event should be used only in group/channel scope to track when other users are added to the roster. This is by design.

**Comment by PerryRose** [comment]
> @PerryRose - We got update from engineering team saying "Generally we should use the `installationUpdates` to track the personal install events: https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/subscribe-to-conversation-events?tabs=dotnet#installation-update-event
> 
> The `memberAdded` event should be used only in group/channel scope to track when other users are added to the roster. This is by design.

Hi @Prasad-MSFT, I don't understand. I'm performing this API call to obtain the conversation id between a Teams user and the Teams bot. This is required for proactive messaging. When I perform this call, I can obtain the conversation id, however, as a result, that user will receive a welcome card from the bot as OnMembersAdded is triggered. I don't understand how this is by design, when this unexpected behavior has only began very recently. Why would getting the chat between a user and a Teams app trigger OnMembersAdded when these two things seem unrelated.? The documentation also doesn't reflect this. Thanks

**Comment by Prasad-MSFT** [comment]
@PerryRose - We discussed the same thing with engineering team as well and according to them "The root cause was that the get API call is actually making a create thread call. There are no other options, and this has been a behavior for a long time." Engineering team is checking it internally if they can get a proper get call.

In the meantime, please track the installations through the installation events and for new membersAdded events to save which members the welcome message is being sent to.
