### ISSUE TITLE
Incomplete list in the left menu

### ISSUE THREAD

**Issue by saraamini8** [microsoftgraph/microsoft-graph-docs#20430]
Hi Team,

In the left blade, we cannot see the list of supported methods for "oAuth2PermissionGrant resource type"
![image](https://user-images.githubusercontent.com/101718968/222399040-e81501af-c48c-4c3e-9978-4daa6a40be57.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a18a0f00-7443-3689-c20e-34c4d73a1082
* Version Independent ID: 63980aa5-c250-8b77-ba44-cc08fe7c6c2d
* Content: [oAuth2PermissionGrant resource type - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/resources/oauth2permissiongrant?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/oauth2permissiongrant.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/oauth2permissiongrant.md)
* Product: **identity-and-sign-in**
* Technology: **microsoft-graph**
* GitHub Login: @psignoret
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @saraamini8 for raising this issue.

The TOC view that you're looking for is under the User node. In this case, only the List operation relates to the user entity. I believe this becomes the default landing when you were viewing related docs because of the browser cache.

<img width="167" alt="image" src="https://user-images.githubusercontent.com/14026935/222704031-617d8c3d-3192-4f87-9eed-84a49c02fdfa.png">

To view all operations, you can select one of the other methods links and it takes you to this TOC view that lists all the files.

<img width="236" alt="image" src="https://user-images.githubusercontent.com/14026935/222703812-f30e4c29-45b7-40a9-970b-0c60b129eae9.png">

Hope this answers why the TOC view you shared doesn't list all API files.

**Comment by saraamini8** [comment]
Thank you @FaithOmbongi for helping me to understand it.
