### ISSUE TITLE
Can we increase teams webhook subscription maximum expiration time?

### ISSUE THREAD

**Issue by nikhil452** [microsoftgraph/microsoft-graph-docs#21159]
Teams webhook subscription maximum expiration time is very less. Is there any way I can subscribe webhook with expiration time more than 60 minutes. Refer to [this](https://learn.microsoft.com/en-us/graph/webhooks#subscription-lifetime) article for more details.

**Comment by FaithOmbongi** [comment]
Thank you @ for this suggestion Unfortunately, this forum is only for documentation issues but feature suggestions like this are submitted through the [Microsoft Graph feedback forum](https://feedbackportal.microsoft.com/feedback/forum/ebe2edae-97d1-ec11-a7b5-0022481f3c80). Please submit this feature suggestion through the appropriate forum and other developers can amplify your voice so that the suggestion can be considered for feature development.
