### ISSUE TITLE
List signIns api location data is wrong

### ISSUE THREAD

**Issue by cagrimunyas** [microsoftgraph/microsoft-graph-docs#21425]
Geolocation data on Sign-in logs are incorrect on a city level. 100s of kms of difference on some cases. Checking on few users none of them were correct. Which endpoint is this data generated from? 

For instance : 
- A user who works in Istanbul, TR , data shows that sign-in location is Bursa, TR
- Another user who works in Ankara, TR, data shows that sign-in location is Gebze , TR

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 06e7697f-b03a-3282-ebd8-748b65dde87d
* Version Independent ID: bfd3bfb8-4878-b0f7-48f8-ba08a7136108
* Content: [List signIns - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/signin-list?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/signin-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/signin-list.md)
* Product: **identity-and-access-reports**
* Technology: **microsoft-graph**
* GitHub Login: @besiler
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @cagrimunyas for raising this issue.

This documentation [Sign-in logs in Azure Active Directory](https://learn.microsoft.com/en-us/azure/active-directory/reports-monitoring/howto-access-activity-logs) has some information regarding IP Addresses and Location information. Please check if it helps to answer your question.

<img width="500" alt="image" src="https://github.com/microsoftgraph/microsoft-graph-docs/assets/14026935/3a46cced-78d4-4265-a69f-968f4faf9890">

However, if you still need more precise information, please file this issue at [Microsoft Graph Q&A](https://learn.microsoft.com/en-us/answers/tags/248/microsoft-graph-reports-api). This forum is only for documentation issues but functionality issues like this are investigated through [Microsoft Graph Q&A](https://docs.microsoft.com/en-us/answers/topics/microsoft-graph-governance.html).

Closing this issue here.

**Comment by cagrimunyas** [comment]
Thank you @FaithOmbongi . I believe This information is not just a functionality issue but also connected to the documentation on the API page as how the location property was generated. Because at the moment, Lat. and Long. properties of a Location, creates an illusion that it was extracted via device GPS coordinates rather than reverse lookup on the IP address. I believe the documentation should make it clear how it was generated so that the developers can make informed decision based on the precision of that property. I can't be the only one to think if there is a coordinate data, one would assume that it was a product of a gps device location, not reverse lookup on IP.
