### ISSUE TITLE
Is it possible to receive lifecycle notifications through Azure Event Hubs?

### ISSUE THREAD

**Issue by PeterUherek** [microsoftgraph/microsoft-graph-docs#21545]
I created subscription with LifecycleNotificationUrl pointed to eventhub. The validation of subscription passed but no lifecycle events were received in eventhub. I want to ask if is possible to receive lifecycle notifications through Azure Event Hubs? If not is there plan to implement this feature?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d65dc5fb-3034-3cb9-70b2-7988ce5f43dc
* Version Independent ID: d65dc5fb-3034-3cb9-70b2-7988ce5f43dc
* Content: [Receive change notifications through Azure Event Hubs - Microsoft Graph](https://learn.microsoft.com/en-us/graph/change-notifications-delivery-event-hubs?tabs=change-notifications-eventhubs-azure-cli%2Chttp)
* Content Source: [concepts/change-notifications-delivery-event-hubs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/change-notifications-delivery-event-hubs.md)
* Product: **change-notifications**
* Technology: **microsoft-graph**
* GitHub Login: @jumasure
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @PeterUherek for asking this question.

Please first confirm that the resource you want to receive lifecycle notifications for supports the lifecycle notification type as defined in [Resources that support lifecycle notifications](https://learn.microsoft.com/en-us/graph/webhooks-lifecycle?tabs=http#resources-that-support-lifecycle-notifications).

**Comment by PeterUherek** [comment]
Hi, 

It is User resource. I expect reauthorizationRequired notifications. It is defined for all resources by documentation.

**Comment by FaithOmbongi** [comment]
Hi @PeterUherek - I'm tagging this as a functionality issue so that this issue be investigated further. Unfortunately, this forum is only for documentation-related issues but functionality issues like this are investigated through [Microsoft Graph Q&A](https://learn.microsoft.com/en-us/answers/tags/304/microsoft-graph-change-notifications-api). Please file this issue there and provide the **subscriptionId** and the request ID (if you have it) so it can be investigated. Closing this issue here.
