### ISSUE TITLE
department in GET profile 

### ISSUE THREAD

**Issue by Hongbo-Miao** [microsoftgraph/microsoft-graph-docs#2155]
https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/api/user_get

In v1.0,
```
https://graph.microsoft.com/v1.0/users/someone@microsoft.com
```
The result does not include department info.

However,
```
https://graph.microsoft.com/v1.0/users/someone@microsoft.com?$select=department
```
returns department info.

So one of these should be "fixed".

**Comment by Hongbo-Miao** [comment]
Also if the v1.0 does not have `postalCode`, the article should not use it as example.
https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/api/user_get

But actually when I use
```
https://graph.microsoft.com/v1.0/users/someone@microsoft.com?$select=postalCode
```,
it does return `null` instead of nothing. So it is similar to `department`.

**Comment by dpim** [comment]
Your initial post describes expected behavior as not all properties of an entity are necessarily returned by default. For instance, `aboutme` is also only returned when explicitly specified via $select. The second issue you describe in which you're seeing `postalCode` come back as `null` is likely because your app does not have the [`User.Read.All` permission](https://msdn.microsoft.com/en-us/library/azure/ad/graph/howto/azure-ad-graph-api-permission-scopes). For privileged permissions such as `User.Read.All`, you will need tenant admin consent to get back the desired value. For instance, the sample query you described returns non-null values in  the [sample tenant for Graph Explorer](https://developer.microsoft.com/en-us/graph/graph-explorer).

**Comment by Hongbo-Miao** [comment]
Make sense, just saw [Optional query parameters](https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/api/user_get#optional-query-parameters) section.
