### ISSUE TITLE
Sending via /me/sendmail and sendas does not work

### ISSUE THREAD

**Issue by joergrenn** [microsoftgraph/microsoft-graph-docs#21572]
Hello,

according to the documentation it is possible to use the /me/sendmail endpoint to send email as another user with sendas permissions.
In the JSON I have set the "from" property to the mailbox that is supposed to appear as the sender.
I am logged in as the user that has the sendas permissions on the senders mailbox.
however when sending the mail, the from address is always the logged in user and not the address in the "from" property.

When I use the `/users/<from>/sendmail` endpoint , i need to have also full access permissions which I don't want to grant.
How can I sent a mail via graph with sendas permissions without having to grant also fullaccess permissions?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d61ed298-c1b2-31d1-472c-3e7b912459e9
* Version Independent ID: 1cd6a8dd-f3a9-bae9-462b-bede56d15c6c
* Content: [Send Outlook messages from another user using the Outlook mail API - Microsoft Graph](https://learn.microsoft.com/en-us/graph/outlook-send-mail-from-other-user)
* Content Source: [concepts/outlook-send-mail-from-other-user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/outlook-send-mail-from-other-user.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @jasonjoh
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jasonjoh** [comment]
@abheek-das did something change in Exchange with regards to permissions? I'll attempt to reproduce this once I get some time to investigate.

**Comment by jasonjoh** [comment]
@joergrenn how did you assign the permissions? Was it in the Microsoft admin portal, through Outlook, or some other way?

**Comment by jasonjoh** [comment]
@joergrenn also can you please try to "send as" using Outlook on the web to see if you see the same behavior? If you enable the **Show From** option on a new email, you can change the from there.

![image](https://github.com/microsoftgraph/microsoft-graph-docs/assets/8966342/53968798-cdc3-423d-a940-00ec599c09b7)

**Comment by jasonjoh** [comment]
Ah, I think I see the problem @joergrenn. You should NOT use the `/users/<from>/sendmail` endpoint *unless* you want the message to land in the "from" users's sent items folder. It should be the `/me/sendmail` endpoint. The message needs to go out through the *sender's* mailbox in order for the "send as" functionality to work with only "Send as" permissions. This is described in the [Sent Items behavior](https://learn.microsoft.com/en-us/graph/outlook-send-mail-from-other-user#sent-items-behavior) section of the doc. Specifically, it documents that **Full Access** is required if you want to send via the `/users/<from>/sendmail` endpoint.

This is because having the permission to "send as" does not include the ability to create an item in the user's mailbox.

Hope that clarifies!

**Comment by joergrenn** [comment]
tahnks @jasonjoh,

after your comment I gave this another try and got it to work:
Apparently my json body was valid, but the "from" property was outside the "message" node and thus ignored. the mail was thus always send as "me" and not the sendas mailbox.
Earlier already had it working using the /users/<from>/sendmail endpoint, but as you mentioned this only works with "full access" also due to send items behaviour.
thanks again.
