### ISSUE TITLE
Update api for Get servicePrincipals member in group

### ISSUE THREAD

**Issue by ruchija1n** [microsoftgraph/microsoft-graph-docs#21620]
Public doc link: https://learn.microsoft.com/en-us/graph/api/group-list-members?view=graph-rest-1.0&tabs=http

The public doc says that 'Currently service principals are not listed as group members due to staged roll-out of service principals on Graph V1.0 endpoint. This operation is not transitive.' Please add more context on what this actually means.

Also, add details about if user wants to get results of servicePrincipals in group then what api do they need to call and which permission they need.
As per my understanding, GET groups/id?$expand=members returns the results. Please include this in the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 51a32b12-951e-ff94-a7b8-c014968ce6cf
* Version Independent ID: fea401c3-ce70-d7ce-4bae-c112308a711a
* Content: [List group members - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/group-list-members?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/group-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/group-list-members.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @psaffaie
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @ruchija1n for raising this issue.

> 'Currently service principals are not listed as group members due to staged roll-out of service principals on Graph V1.0 endpoint. This operation is not transitive.'

These are unrelated sentences. 

- "This operation is not transitive." Yes, the /groups/{id}/members API is not transitive meaning it returns only direct members but not nested members. Consider security group B.2 that's a member of security group B.1, that's a member of security group B. `GET /groups/{id of group B}/members` will only return security group B.1 but not B.2. To get both direct and nested members, use the [List transitiveMembers API](https://learn.microsoft.com/en-us/graph/api/group-list-transitivemembers?view=graph-rest-1.0&tabs=http) or [Get group operation and expand the members relationship](https://learn.microsoft.com/en-us/graph/api/group-get?view=graph-rest-1.0&tabs=http) instead.

- "Currently service principals are not listed as group members due to staged roll-out of service principals on Graph V1.0 endpoint." Consider a service principals that's a member of group B. The `https://graph.microsoft.com/v1.0/groups/{id}/members` endpoint in v1.0 won't return service principal members. But [in beta, it will](https://learn.microsoft.com/en-us/graph/api/group-list-members?view=graph-rest-beta&tabs=http). This is a known issue.


> Also, add details about if user wants to get results of servicePrincipals in group then what api do they need to call and which permission they need.

Good call out. I've raised a PR to add this information.
 
> As per my understanding, GET groups/id?$expand=members returns the results. Please include this in the documentation.

Correct. I've raised a PR to document this.
