### ISSUE TITLE
Add Angular 2+ tutorial under Build your first app

### ISSUE THREAD

**Issue by Hongbo-Miao** [microsoftgraph/microsoft-graph-docs#2294]
Current Angular tutorial
https://developer.microsoft.com/en-us/graph/docs/concepts/angular
is for old version Angular 1.

I suggest adding new Angular 2+ tutorial.

**Comment by Hongbo-Miao** [comment]
Also, right now we are using name Angular in the table of content.
We might need change to AngularJS.

Because we use AngularJS referring old Angular 1.
We use Angular referring new Angular 2+ versions.

![image](https://user-images.githubusercontent.com/3375461/37081172-7a8bfbaa-219d-11e8-9827-ab0b56dd0ac2.png)

**Comment by Jackson-Woods** [comment]
This is a good point - we should definitely rename "Angular" in our docs to "AngularJS" where it refers to the Angular 1.x framework. They are not the same thing and are not interchangeable. The TOC you point out is one candidate. Our [Quick Start](https://developer.microsoft.com/en-us/graph/quick-start) page is another.

I think that's a separate issue from building an Angular 2+ tutorial or Quick Start. We do already have Angular 2 and 4 samples available, e.g. [https://github.com/microsoftgraph/angular4-connect-sample](https://github.com/microsoftgraph/angular4-connect-sample). The [Samples and SDKs page](https://developer.microsoft.com/en-us/graph/code-samples-and-sdks) should probably say something like "AngularJS/Angular" since it links to resources for both.

**Comment by jthake-msft** [comment]
This has been done.
