### ISSUE TITLE
Params to get excel pagesize 

### ISSUE THREAD

**Issue by agallart** [microsoftgraph/microsoft-graph-docs#2490]
Issue: 
When I try get file with :

`GET /drive/items/{item-id}/content?format={format}`
`GET /drive/root:/{path and filename}:/content?format={format}`

the file gets another page size.
Can I put another param to change page size?

Article:
[Link](https://stackoverflow.com/questions/49880196/how-to-define-export-size-of-excel-file-to-pdf-in-microsoft-graph)

**Comment by jthake** [comment]
Apologies for delay in responding here. Are you trying to download the file in chunks and want to define the size of the chunk? Your stack overflow question seems to be different in terms of downloading a excel file and a pdf file...

**Comment by jthake** [comment]
@daspek is there a way to do this? 
The documentation doesn't state anything but a format https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/api/driveitem_get_content_format

**Comment by daspek** [comment]
Unfortunately, the `format` API doesn't accept size for PDFs right now. @agallart, it would be great if you could add this feature request to our [user voice](https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback/category/101632-microsoft-graph-o365-rest-apis) so that others can vote on it and help us prioritize it.
