### ISSUE TITLE
OneDrive SharedWithMe endpoint only returns files shared within an organization

### ISSUE THREAD

**Issue by ElisaKazan** [microsoftgraph/microsoft-graph-docs#2581]
Issue: 
OneDrive SharedWithMe endpoint returns null in the [graph explorer](https://developer.microsoft.com/en-us/graph/graph-explorer) when there are files and folders that should appear.

Article:
Specifically "files shared with me" from the sample queries.
`https://graph.microsoft.com/v1.0/me/drive/sharedWithMe`
returns
`{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#Collection(driveItem)",
    "value": []
}`

**Comment by ElisaKazan** [comment]
After more investigating, it seems that Shared with me  only works for files shared within an organization. Is this intentional or not?

See more details in [Microsoft Graph Explorer Issue](https://github.com/microsoftgraph/microsoft-graph-explorer/issues/143#issuecomment-393642799)

**Comment by jthake** [comment]
Apologies for delay here. 

The documentation highlights the permissions required at the top of the page
https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/api/drive_sharedwithme

What permissions were you requesting?

**Comment by ElisaKazan** [comment]
I'm not quite sure. I'm just trying to see which files were shared and then download those files. I think this would be Files.Read.All but how would I check?

For testing, when I shared the files between users they have edit access if that's important.

Could you explain how I can get you this information? Thanks! :)

**Comment by jthake** [comment]
Have you confirmed you can see this in Delve from the app launcher? This is essentially the UI view of what this API does.

For permisssions scopes, in the Graph Explorer https://developer.microsoft.com/en-us/graph/graph-explorer when you sign in with your Microsoft account ( I would recommend an inprivate browser for this). 
Once you've signed in, there is a modify permissions hyperlink where you can ensure you have added the appropriate permissions. I get results returning with the default permission set the Graph Explorer gives me.

Do you see any results at all return for GET https://graph.microsoft.com/v1.0/me/drive/sharedWithMe ?

**Comment by denis1stomin** [comment]
If I'm correct the issue is about lacking of some files which are shared with you (means that you have access to those files). For example we have a simple app which shares OneDrive files with all organization (using "Everyone except external users")
Here you can find the code which does sharing
https://github.com/denis1stomin/okeears/blob/a1c1c708474e2e88d11a18577f9a6c1c17585659/webui/src/services/okrservice.js#L256-L270
So after that operation a file is shared and it is available for another users, the can find and open it using Delve, BUT.. when I GET https://graph.microsoft.com/v1.0/me/drive/sharedWithMe I only see a single file which I shared with all organization but using OneDrive Web UI.
So I expect that I can see all files shared with me but do not see it.
May this is not correct expectation.
Could you please explain?
Thanks

**Comment by samrajcse** [comment]
Hi Team,

I am also waiting for the solution. Say, I have a folder shared by my vendor who is using O365 and I can able to access the folder via public link. But I don't see that folder in my sharedwithme section. Also I am not getting the folder via sharedWithMe graph api endpoint as well. Is there any specific graph api endpoint to get this information.

**Comment by abraunegg** [comment]
This issue is also causing problems for the Linux OneDrive Client. See:
* https://github.com/abraunegg/onedrive/issues/966
* https://github.com/OneDrive/onedrive-api-docs/issues/1301

**Comment by joeflack4** [comment]
Having same/similar problem. I'm automating something for work. They have shared some folders with my personal OneDrive account. I have a valid token and am able to do things to non-shared folders/files using either my script or the graph api explorer. However when it comes to trying to access the children of a shared folder, I get:

```json
{'error': {'code': 'invalidRequest', 'message': 'Bad Argument', 'innerError': {'date': '2021-01-04T04:31:52', 'request-id': '2cbbbc2a-10c3-4f54-841a-feb301594e91', 'client-request-id': '2cbbbc2a-10c3-4f54-841a-feb301594e91'}}}
```

Here's the code:
https://github.com/TB-Modeling/snap-onedrive-report-aggregator/blob/master/src/aggregate.py

**Comment by karenirenecano** [comment]
Confirming this as well. I have a use case where a company domain owns the file and it has to be shared to an external domain or a personal email. Through the web ui it can be found but counter checking it on the graph explorer of the `sharedWithMe` endpoint, it does not include the company shared file on the personal email account signed in. Do you have an updated docs on this if this is indeed intentional? Thanks
