### ISSUE TITLE
Can an F1 user do a Graph call to Teams

### ISSUE THREAD

**Issue by MRuimerman** [microsoftgraph/microsoft-graph-docs#2701]
We are using a Graph call to list the teams the current user is a member of. The Graph call is part of a SPFX web part.
According to the [Microsoft documentation](https://products.office.com/en-us/business/office-365-f1) Teams is supported for F1 licenses but when using the Graph call to get the Teams for the logged in F1 user there is a message displayed: Something went wrong. Teams is disabled for your tenant.
This is also happens when using the Graph Explorer so it is not in our code.
An F1 user can be added as a member of a Teams site.

Steps to Reproduce:
Login as F1 user and use the following graph call: https://graph.microsoft.com/beta/me/joinedTeams

Issue: 
Is Teams not supported for F1 users or is this a bug?

Article:
#

**Comment by mlafleur** [comment]
Just to clarify, are you able to access Teams via the app?

**Comment by MRuimerman** [comment]
Good question. No, the user can't login to the Teams app.. So I suppose the is not really a graph issue but more a Teams issue.

**Comment by mlafleur** [comment]
Since the user cannot access Teams itself, it sounds like the API is behaving properly here. You may want to open a [support case with Teams ](https://support.office.com/en-us/home/chat?ContactUsExperienceEntryPointAssetId=S.HP.teams )to address the user's lack of access. 

As this isn't a Graph issue, I'm going to close this issue. If after resolving their Teams access you are still seeing this behavior we can always reopen it.
