### ISSUE TITLE
Microsoft Graph App Role permissions assigned to Security Group -- Members not inheriting permissions

### ISSUE THREAD

**Issue by cbrianball** [microsoftgraph/microsoft-graph-docs#2797]
I apologize ahead of time as I don't believe this is the correct place for this question, but I honestly can't find where I should post this question. Please point me in the right direction if I need to post this somewhere else.

I have several Managed Service Identity (MSI) accounts. I want to give them all the same set of Microsoft Graph permissions (Directory.Read.All and User.Read.All). I did this on one of the MSI and I am able to query the information I need from Microsoft Graph without any issues.

To simplify the permissions. I created a security group in Azure AD and assigned the aforementioned approles to the security group. I then added all the MSIs that need those permissions to that security group as members.

I've waited a day (because I've noticed sometimes it takes time for permissions to propagate), and I get an error whenever the MSIs try to access a user's photo. It looks like the MSIs are not inheriting the access from the security group they are assigned to.

1. Is this scenario supported?
2. If so, what might I be doing wrong?

**Comment by jthake** [comment]
@dkershaw10 could you help here? I couldn't find any documentation that covers this scenario...

**Comment by cbrianball** [comment]
Is there any update on this? @jthake @dkershaw10

**Comment by dkershaw10** [comment]
@cbrianball Sorry for the delayed response.  In future please file these kinds of questions on StackOverflow and tag with [microsoftgraph].  Issues for this repo are more targeted to doc bugs, in general.
However, since you and Jeremy have me here...
The system doesn't really work that way - or the way you are expecting it to.  

App roles can be assigned in one of 2 ways:

1. Assign an app role to a user or group.  When you do this this enables the user or members of the group to sign in to the app (that defines the app role), and then the app role is presented as a claim in the user token, and the app can authorize the user's access based on that app role.

2. Assign/Grant an app role (permission) to an app (servicePrincipal/MSI).  When you do this, the access token that the app (servicePrincipal/MSI) acquires to call an API (that defines those permissions that were granted) will have a claim that contains the permission/app role.  The API then authorizes based on the app roles claim.

So when you did your first step (granting your MSI some perms), you were going through flow #2. When you tried your step with #1, that doesn't work because that's geared towards user sign in (and using groups as a container for users).  In theory assigning those app role permissions to a group should have failed, because those app roles should have been configured as ONLY applicable to applications (i.e. #2 above) and not applicable to users and groups (i.e. #1).

OK - that's how it works. 
I think what you are suggesting, based on your expectation, is that you should also be able to assign app roles to a set of MSIs/servicePrincipals, and now those servicePrincipals/MSIs should all have the assigned level of access to the targeted API (in this case Microsoft Graph, based on the app roles assigned).   Do I have this correct?

**Comment by dkershaw10** [comment]
OK great on the SO question!
Yes I would have expected the assignment of the app role to the security group to have failed. If it didn't fail, then it's either a bug or the app role definitions are incorrectly defined (will need to check).

I'd also like to evaluate how common a scenario it is in devops to create multiple MSIs and assign them the same access levels to Microsoft Graph (or other APIs).  If so, enabling through group membership might seem a reasonable approach.

**Comment by cbrianball** [comment]
Mine isn't a DevOps scenario. I have an application that needs to query our Azure AD. I don't want to use delegated permissions (though it was a valid option), and my IT team didn't want to assign the permissions to the app since it has a non-expiring password (i.e. client secret).

I learned about MSIs and how they have a rolling password; this satisfied the IT teams requirements, so we moved forward with that. My app is hosted in Azure as an App Service, and App Services do not currently support user managed service principals, so I had to use an MSI, so each of my environments has its own MSI, but they all need the same permissions to the Microsoft Graph API.

**Comment by rohank-proarch** [comment]
Any update on this?

**Comment by FaithOmbongi** [comment]
I recommend posting this question at [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/products/m365#microsoft-graph) where you can receive help in managing this permission assignment. For the feature request, kindly post it at the [Microsoft 365 Developer platform ideas forum](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform/label-name/Microsoft%20Graph).

Unfortunately this forum isn't monitored for functionality issues, but questions like this are monitored at these channels.
