### ISSUE TITLE
Outlook Calendar: timezone issue for repeating all-day events

### ISSUE THREAD

**Issue by gabrielittner** [microsoftgraph/microsoft-graph-docs#2804]
All-day events are always in UTC. The `originalStart` property is according to the documentation also always returned in UTC.

However when using the `calendarView` method I'm receiving this:

```      
{
    "@odata.etag": "W/\"vdOlTJBut0KwhJp9zcb0dAABG3gJSQ==\"",
    "id": "AQMkADAwATM3ZmYAZS0wOGJlLTQxODktMDACLTAwCgFRAAgIANXKd0f1wABGAAACgipk6dGnnEWbtAgkOkWUiwcAvdOlTJBut0KwhJp9zcb0dAAAAgENAAAAvdOlTJBut0KwhJp9zcb0dAABG2JmPQAAABA=",
    "originalStartTimeZone": "UTC",
    "subject": "Test",
    "originalStart": "2018-06-05T07:00:00Z",
    "isAllDay": true,
    "type": "occurrence",
    "start": {
        "dateTime": "2018-06-05T00:00:00.0000000",
        "timeZone": "UTC"
    },
    "end": {
        "dateTime": "2018-06-06T00:00:00.0000000",
        "timeZone": "UTC"
    }
},
{
    "@odata.etag": "W/\"vdOlTJBut0KwhJp9zcb0dAABG3gJSQ==\"",
    "id": "AQMkADAwATM3ZmYAZS0wOGJlLTQxODktMDACLTAwCgFRAAgIANXLQHJfgABGAAACgipk6dGnnEWbtAgkOkWUiwcAvdOlTJBut0KwhJp9zcb0dAAAAgENAAAAvdOlTJBut0KwhJp9zcb0dAABG2JmPQAAABA=",
    "originalStartTimeZone": "UTC",
    "subject": "Test changed",
    "originalStart": "2018-06-06T07:00:00Z",
    "isAllDay": true,
    "type": "exception",
    "start": {
        "dateTime": "2018-06-06T00:00:00.0000000",
        "timeZone": "UTC"
    },
    "end": {
        "dateTime": "2018-06-07T00:00:00.0000000",
        "timeZone": "UTC"
	}
}
```

As you can see `originalStart` is returned in UTC as documented, but the value is wrong. It looks like you're taking the UTC start value, treating it as UTC-7 and convert it to UTC which results in a wrong result. (the UTC-7 is coincidentally the accounts default timezone).

**Comment by jasonjoh** [comment]
All-day events are weird, so they're handled a bit differently. Essentially the "time" portion of the start and end is meaningless, but the server (just to keep things consistent) always shifts the time portion to midnight on the relevant day.

You're seeing it return in UTC because that's the default way the API returns date/time. You can change it to another time zone using the following header:

```
Prefer: outlook.timezone="Pacific Standard Time"
```

But the times will still come back as midnight.

**Comment by gabrielittner** [comment]
Thanks for the reply Jason.

That it's always returned it UTC isn't the issue. If you take a non all-day event you get this (same occurrence requested in 3 different timezones):

```
"originalStart": "2018-06-05T15:00:00Z",
"originalStartTimeZone": "Pacific Standard Time",
"start": {
    "dateTime": "2018-06-05T15:00:00.0000000",
    "timeZone": "UTC"
}

"originalStart": "2018-06-05T15:00:00Z"
"originalStartTimeZone": "Pacific Standard Time"
"start": {
    "dateTime": "2018-06-05T08:00:00.0000000"
    "timeZone": "Pacific Standard Time"
}

"originalStart": "2018-06-05T15:00:00Z",
"originalStartTimeZone": "Pacific Standard Time",
"start": {
    "dateTime": "2018-06-05T17:00:00.0000000",
    "timeZone": "W. Europe Standard Time"
}
``` 

`originalStart` is always in UTC, `originalStartTimeZone` is always set to `Pacific Standard Time` which is the time zone the event was created in. 

This is what it looks like for an all-day event.
```
"originalStart": "2018-06-05T07:00:00Z",
"originalStartTimeZone": "UTC",
"start": {
    "dateTime": "2018-06-05T00:00:00.0000000",
    "timeZone": "UTC"
}

"originalStart": "2018-06-05T07:00:00Z",
"originalStartTimeZone": "Pacific Standard Time",
"start": {
    "dateTime": "2018-06-05T00:00:00.0000000",
    "timeZone": "Pacific Standard Time"
}            

"originalStart": "2018-06-05T07:00:00Z",
"originalStartTimeZone": "W. Europe Standard Time",
"start": {
    "dateTime": "2018-06-05T00:00:00.0000000",
    "timeZone": "W. Europe Standard Time"
}
```

`originalStart` is always in UTC (converted from PST) but `originalStartTimeZone` is always the requested one.

If I generate event occurrences myself based on the seriesMaster and want to match them to the occurrences and exceptions returned by the API I've got an issue. For the regular event I can just convert `originalStart` from UTC to whatever timezone I'm generating the occurrences in and they match.

When I generate occurrences for the all-day event I'd get this:
- generated in UTC: `2018-06-05T00:00:00`; `originalStart` in UTC `2018-06-05T07:00:00`
- generated in PST: `2018-06-05T00:00:00`; `originalStart` converted to PST `2018-06-05T00:00:00`
- generated in CET: `2018-06-05T00:00:00`; `originalStart` converted to CET `2018-06-05T09:00:00`

So for all-day events I can only get matches when I convert originalStart to PST. But because `originalStartTimeZone` isn't always set to PST like it is for regular events I don't know that I have to convert it to PST. For another user I'd might have to convert it to CET.

There are two ways to solve this:
1. as requested in my original post, don't convert originalStart to UTC for all-day events, just treat as if it were already UTC (which would result in the same as the `start.dateTime` field, a date with always 00:00:00 as time)
2. set `originalStartTimeZone` to the time zone you use when converting the event to UTC, this would also make it consistent with regular events

I hope this is understandable, happy to answer questions if there are any.

**Comment by jasonjoh** [comment]
Ah ok. So to succinctly boil down the issue, it's that for all-day events, the `originalStartTimeZone` is always returned as the requested time zone, not the actual time zone that the user created the appointment with, and `originalStart` is actually converted to UTC (from the user's original time zone), resulting in a non-midnight time there (unless you happen to create in UTC).

The idea with all-day is that time zone is irrelevant. It's midnight to midnight in all time zones, essentially. This is because all-day events aren't really an event that lasts 24 hours (like say, a meeting that runs from midnight to midnight), but are really more of a way to mark a day as being something special (like a birthday or holiday).

So if you are expanding these yourself to generate event occurrences, if you see the `isAllDay` flag set to true, then you should just ignore time zone and base your start end dates off of the `dateTime` values of `start` and `end`. You can just ignore `originalStartTimeZone` completely here.

Does that work?

**Comment by gabrielittner** [comment]
For example let's say we've got a weekly repeating all-day event. If the third occurrences is moved by one day, I'd get this from the API

```
start 2018-06-05T00:00:00Z; originalStart 2018-06-05T07:00:00Z; type = occurrence
start 2018-06-12T00:00:00Z; originalStart 2018-06-12T07:00:00Z; type = occurrence
start 2018-06-20T00:00:00Z; originalStart 2018-06-19T07:00:00Z; type = exception
start 2018-06-26T00:00:00Z; originalStart 2018-06-26T07:00:00Z; type = occurrence
```

In the case of the occurrences I can do what you suggested, just use `start` and ignore the original fields. For the exception that doesn't work because `start` is not equivalent to `originalStart`. 

I've got a workaround for that edge case that's based on how our recurrence expansion works internally. So while it would be nice to have a proper solution for this it's not that critical.

**Comment by jasonjoh** [comment]
Can you help me understand why the exception doesn't work for you? It sounds like you have a reliance on originalStart which I'm not groking :).

Here's why I'm asking: I can report this as a bug, but I'm not confident it would get fixed due to the design that all-day events are time-zone-agnostic. If I had a better understanding of how you're using the values, I can make a better case.

**Comment by gabrielittner** [comment]
I'm synchronizing Outlook calendar with Android's calendar database. Outlook events have these types: `singleInstance`, `seriesMaster`, `occurrence` and `exception`. The database wants `singleInstance`, `seriesMaster`, `exception` and deleted occurrences (they are inserted like an exception but with a cancelled flag). Occurrences are generated by the database itself. For the generation to work correctly with exceptions and deleted occurrences you have to set a column that's called `ORIGINAL_INSTANCE_TIME` which for deleted occurrences is just `start` and for exceptions it is the time when the occurrence would have started if it hadn't been moved.

If we go back to the example from my last comment and delete the 2018-06-26 occurrence everything would look like this:

Graph API delta gives me: 
```
start 2018-06-05T00:00:00Z; type = seriesMaster
start 2018-06-05T00:00:00Z; type = occurrence
start 2018-06-12T00:00:00Z; type = occurrence
start 2018-06-20T00:00:00Z; originalStart 2018-06-19T07:00:00Z; type = exception
```

What I want to insert in the database is:
```
start 2018-06-05T00:00:00Z (the series master)
start 2018-06-20T00:00:00Z; ORIGINAL_INSTANCE_TIME 2018-06-19T00:00:00Z (the exception)
start 2018-06-26T00:00:00Z; ORIGINAL_INSTANCE_TIME 2018-06-26T00:00:00Z; status = cancelled (the deleted occurrence)
```

For non all-day events the `originalStart` is equivalent to the `ORIGINAL_INSTANCE_TIME` I need and for all-day events that didn't change `start` I can use that. When `ORIGINAL_INSTANCE_TIME` is wrong you'll get duplicate occurrences in the database. In the example the database would generate an occurrence for 2018-06-19.

The mentioned workaround is a side-effect of how I handle the deleted occurrences, which aren't returned by the API. I expand the seriesMaster myself and compare it to the returned occurrences and exceptions. In that comparison I'm using `start` of occurrences, `originalStart` for non all-day exceptions and `start` for all-day exceptions (`start` is at least right for all-day event exceptions that didn't change `start`). My comparison doesn't find a matching returned occurrence/exception for 2018-06-19 so it assumes that it is a deleted occurrence. This is what I actually insert in the database:

```
start 2018-06-05T00:00:00Z (the series master)
start 2018-06-20T00:00:00Z; ORIGINAL_INSTANCE_TIME 2018-06-19T00:00:00Z (the exception)
start 2018-06-19T00:00:00Z; ORIGINAL_INSTANCE_TIME 2018-06-19T00:00:00Z; status = cancelled (this would have been the occurrence of the exception)
start 2018-06-26T00:00:00Z; ORIGINAL_INSTANCE_TIME 2018-06-26T00:00:00Z; status = cancelled (the deleted occurrence)
```

**Comment by jasonjoh** [comment]
Sorry for the huge delay here! I did want to check in with you and see if we can't get this sorted out.

So if I understand this correctly, you are already offsetting the `originalStart` for all-day events to midnight regardless of timezone (in otherwords, you're taking the value with the `T07:00:00` and changing to `T00:00:00`. The problem comes in when you are doing the deleted occurrence detection. You said for all-day exceptions you use `start`, but what are you comparing it to?

**Comment by jasonjoh** [comment]
Here's more information on this from our calendaring team:

The reported behavior is by design. The `originalStartTime` reported on occurrences and exceptions gets treated internally as an ID, and as such really shouldn't be getting shifted to midnight based on time zones, etc. 

We have a couple of suggestions/clarifications that may help: 

1. The `id` of an instance does not change when it is made into an exception, so if you have the ability to keep track of the `id`, that should be a more consistent and effective way of correlating instances than the current tactic (using `start`).

1. If for some reason keying off the `id` is not possible, normal occurrences also return the `originalStart` field, so you ought to be able to use that to correlate occurrences. Since you would be comparing `originalStart` to `originalStart`, instead of `originalStart` to `start`, that should allow you to avoid time zone / all-day issues. 

1. We'd also like to note that the `originalStartTimeZone` field, despite the somewhat misleading name, is not the time zone of `originalStart`, but of `start`. Similarly, the `originalEndTimeZone` field refers to the time zone of `end`.

The time zone associated with `originalStart` is generally the recurring time zone, which at least in the Graph can be found on the recurring master (`recurrence.range.recurringTimeZone`).
