### ISSUE TITLE
JSON batch limit of "20" is not correct

### ISSUE THREAD

**Issue by chilipepper987** [microsoftgraph/microsoft-graph-docs#2886]
Issue: 
For json-batching, it says a known issue 

> ### Limit on batch size
> JSON batch requests are currently limited to 20 individual requests.

However, in practice it isn't that high. When I send 20 requests, 4-6 of them (in no particular order) always fail with a 429 errror Could Not Connect To Mailbox Too Many Requests. For example, send _10_ batch requests in a row of _20_ requests each, _all 10_ will only have **16** succeed and **4** fail. Try it again in an hour, _all 10_ will each only have **14** succeed, **6** fail. 

If I ease it back to say, **9** requests per batch at a time, I don't get any errors, even with sequential batch requests.

I think the documentation should reflect whatever the actual limit is, if its a range or threshold than maybe give some parameters

Article:
https://developer.microsoft.com/en-us/graph/docs/concepts/known_issues#json-batching

**Comment by jthake-msft** [comment]
This issues lists is specifically for documentation issues, not the underlying service, sdks or samples. I will close this issue so our documentation team can focus on content issues.
The official channel for questions is StackOverflow with '[microsoft-graph](https://stackoverflow.com/questions/tagged/microsoft-graph
)' tag.
For issues, you can raise a support ticket on the Azure Portal where you registered your application. This [simple video](https://twitter.com/jthake/status/1030489336439959553) shows how to file it properly by visiting [here](https://portal.azure.com/#blade/Microsoft_Azure_Support/HelpAndSupportBlade/overview).

**Comment by chilipepper987** [comment]
Sorry, I'm a bit confused here. How is this not a documentation issue? I am not having a technical issue; the documentation correctly asserts that the JSON batch size is limited to a certain number, but the number is incorrect. The documentation says 20 and in practice it seems to be 14.

**Comment by cardoso-sansan** [comment]
Old thread but wanted to reply since I had similar problem and figured out something reading other parts of the documentation.

The limitation @chilipepper987 mentioned about `429 errror Could Not Connect To Mailbox Too Many Requests.` comes from a limitation on Outlook services, and it is described here:

https://docs.microsoft.com/en-us/graph/throttling
```
Outlook services limits
Limit | Applies to
10,000 API requests in a 10 minute period | v1.0 and beta endpoints
4 concurrent requests | v1.0 and beta endpoints
15 megabit upload (PATCH, POST, PUT) in a 30 second period | v1.0 and beta endpoints
```

You can probably send 20 requests just fine and run them in parallel if you are accessing other APIs in different services.

But if you are only dealing with same user mailbox everytime you do this json batch request, then you should maybe use sequentially, or reduce the batch to only 4 requests.

One thing I wanted to do was combine sequential with parallel requests using dependsOn, but unfortunately right now this is not supported by the Batch API. You either do all sequentially, or all parallel.

If that limitation from batch API would be removed, then this would be possile, have always 4 concurrent requests running to same mail box, but still use the 20 requests limit from batch endpoint.

```
1 -> 5 -> 9 -> 13 -> 17
2 -> 6 -> 10 -> 14 -> 18
3 -> 7 -> 11 -> 15 -> 19
4 -> 8 -> 12 -> 16 -> 20
```

**Comment by abheek-das** [comment]
As per Graph's [Throttling and batching guidance](https://docs.microsoft.com/en-us/graph/throttling#throttling-and-batching) - While 20 is the max number of requests that can be batched simultaneously by Graph, however:
- Depending on the APIs part of the batch request, the underlying services impose their own throttling limits that affect applications that use Microsoft Graph to access them
- Requests in a batch are evaluated individually against throttling limits and if any request exceeds the limits, it fails with a status of 429

Looking at the error signature - In the above scenario, most likely the requests part of the batch are towards the same mailbox, which triggers the [Outlook Service throttling limits](https://docs.microsoft.com/en-us/graph/throttling#outlook-service-limits) of max 4 concurrent requests pending at any time towards a given mailbox.

@angelgolfer-ms , please let me know if we should add a pointer to Graph's Throttling & batching guidance to this [Graph known issues article](https://developer.microsoft.com/en-us/graph/docs/concepts/known_issues#json-batching). Otherwise I believe, this issue can be closed.

**Comment by chilipepper987** [comment]
I think adding a comment (and potentially a link) to the "limit on batch size" section that different underlying services have their own restrictions would be very helpful

**Comment by isvargasmsft** [comment]
Adding clarification and link to the known issues article.
