### ISSUE TITLE
FindMeetingTimes only works with cloud provisioned Accounts. 

### ISSUE THREAD

**Issue by frankhu1234** [microsoftgraph/microsoft-graph-docs#2907]
Issue:  This graph call will only work with cloud provisioned accounts, please update the document to reflect this.  In addition if you can mark all the methods that only work with cloud provisioned accounts that would be beneficial. 

Article :https://developer.microsoft.com/en-us/graph/docs/api-reference/beta/api/user_findmeetingtimes

**Comment by jthake-msft** [comment]
Can you explain what you mean by "Cloud provisioned accounts"? Do you mean that the users mailbox needs to be in Exchange Online?

**Comment by frankhu1234** [comment]
Yes, from my understanding there is some sort of issue where componentshard mailboxes won't work properly with these calls. (This call in specific doesn't work properly)

**Comment by jthake-msft** [comment]
@ArunMSFT  can you confirm this? because we should definitely update the docs to state this.

**Comment by angelgolfer-ms** [comment]
Hi @frankhu1234 , generally production apps that use Outlook REST API should assume user mailboxes are on Exchange Online. 
Note that Outlook mail, calendar, and contacts REST API also work for user mailboxes in a hybrid deployment that meets specific [requirements](https://developer.microsoft.com/en-us/graph/docs/concepts/hybrid_rest_support#requirements-for-the-rest-api-to-work-in-hybrid-deployments). Because hybrid support is still in preview only, production apps should not take a dependency on hybrid support.

**Comment by frankhu1234** [comment]
Okay, that looks beneficial. Thank you for that info. Perhaps each of these outlook methods should have this link included? As a lot of people find the Graph API call through a search engine and never looks through all the side panel information.

**Comment by jthake-msft** [comment]
@frankhu1234 I have created a new GitHub issue to track this #2968
