### ISSUE TITLE
Group endpoint "all groups I belong to" doesn't return the groups in which user is only Owner.

### ISSUE THREAD

**Issue by JayakumarB** [microsoftgraph/microsoft-graph-docs#3049]
Issue: 
Group endpoint "all groups I belong to" doesn't return the groups in which user is only Owner.

Article:

Group endpoint "all groups I belong to" is "https://graph.microsoft.com/v1.0/me/memberOf" and so it is returning only the groups in which user is member. It's not returning the groups in which user is only Owner.

Thanks,
Jayakumar B

**Comment by mikemcleanlive** [comment]
Hi JayakumarB, technically we support an owner not being a member. This workflow is available when creating/managing groups in AAD. From an API perspective, there are actually 2 separate APIs: one to add members and another to add owners. However, when creating groups from Outlook, we made a conscious decision to always add the owner as a member automatically since this was the most frequent use case. This is why the /memberOf query only returns strictly the members of a group.

**Comment by JayakumarB** [comment]
Hi @mikemcleanlive ,

Thanks for the clarification. The endpoint "all groups I belong to" (/memberOf) works well for the groups created from Outlook/Teams as you said. But if we create group directly from [portal.office.com](https://portal.office.com), endpoint fails if we didn't add the owner as member. So from Graph API perspective I see two things,

1.  The endpoint "all groups I belong to" (/memberOf) should return all the groups I belong irrespective of either user is a owner or member. 

2.  Else, we may need another endpoint something like "all groups I owns"  (/ownerOf) which will return the groups in which i'm a owner. or do we have any other Graph endpoint which returns groups of user in which he is either member/owner?

So we don't miss the groups of the user at any cost.

Please suggest solution this problem.

Thanks,
Jayakumar B

**Comment by mikemcleanlive** [comment]
Since all Groups are Directory Objects, try the /ownedObjects API. You can call this API for a specific user and it will retrieve all the objects they own, which is essentially their owned groups. There is more documentation here: https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/api/user_list_ownedobjects

**Comment by JayakumarB** [comment]
Thanks a lot for the solution @mikemcleanlive , Its working.

**Comment by mikemcleanlive** [comment]
Awesome @JayakumarB ! Glad it helped!
