### ISSUE TITLE
Clarify when and what headers are returned

### ISSUE THREAD

**Issue by sk-** [microsoftgraph/microsoft-graph-docs#3066]
For all sent emails, the `internetMessageHeaders` are not returned (the field is not even set). And  for received messages we are missing at least the headers `From`, `To`, `Cc`, `Bcc` and `Sender`.

Is that working as expected? Or is there some special permission that I should request?

I tried it both with the `v1.0` and `beta` versions and the behavior is the same.

We have requested the following scopes:
```python
['email',
  'openid',
  'profile',
  'https://graph.microsoft.com/Calendars.Read',
  'https://graph.microsoft.com/Contacts.Read',
  'https://graph.microsoft.com/Mail.ReadWrite',
  'https://graph.microsoft.com/Mail.Send',
  'https://graph.microsoft.com/People.Read',
  'https://graph.microsoft.com/User.Read',
  'https://graph.microsoft.com/User.ReadBasic.All'],
```

Note that there is a [similar question](https://stackoverflow.com/questions/50734330/getting-blank-rfc-2822-headersreturn-path-in-reply-to-and-references-message) on Stack Overflow.

**Comment by CraigUpic** [comment]
I have a similar question/issue. When trying to perform a create message using https://graph.microsoft.com/v1.0/users/<userPrincipalName>/messages I am trying to set the internetMessageHeaders using my own custom header called x-custom-encrypt-message set to true. The message gets created and I'm able to send it out (internally and externally) and I never see the header in either message. I am trying to use the "Encrypt-Only" function through Azure RMS / OME and thought I could maybe trigger that through an Exchange Transport rule. It would be nice to just have the option built into the create message function so that nothing else special is needed but I can work with what is available provided it works and it doesn't seem like it is.

https://docs.microsoft.com/en-us/graph/api/user-post-messages?view=graph-rest-1.0&tabs=http (Look at Request 2)

**Comment by mstojanovv** [comment]
Same thing here, any solution for this?

**Comment by jasonjoh** [comment]
@sk this is expected. There are no internet message headers on the copies placed in Sent Items because those aren't the messages that actually went through transport, they're just a copy. You can check this yourself in Outlook by opening a message, going to **File**->**Properties**, and checking the **Internet headers** text box.

![image](https://user-images.githubusercontent.com/8966342/73453380-e60c8b00-4339-11ea-9936-dea09bd203b4.png)

**Comment by jasonjoh** [comment]
@CraigUpic I used the sample request from https://docs.microsoft.com/graph/api/user-post-messages?view=graph-rest-1.0&tabs=http#request-2 to create a draft message, then checked that the draft had the headers set. **Note:** You must explicitly request `internetMessageHeaders` via `$select`:

```
GET /me/messages/{message-id}?$select=subject,internetMessageHeaders

{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#users('deeb074f-40b0-4a1f-a471-7baab44c0026')/messages(subject,internetMessageHeaders)/$entity",
    "@odata.etag": "W/\"CQAAABYAAACuPIFjbMEkToHcVnQirM5qAAAfC3kF\"",
    "id": "AAMkAGUyN2I4N2RlLTEzMTAtNDBmYy1hODdlLTY2NTQwODE2MGEwZgBGAAAAAAA2J9QH-DvMRK3pBt_8rA6nBwCuPIFjbMEkToHcVnQirM5qAAAAAAEPAACuPIFjbMEkToHcVnQirM5qAAAfERIeAAA=",
    "subject": "9/8/2018: concert",
    "internetMessageHeaders": [
        {
            "name": "x-custom-header-group-name",
            "value": "Washington"
        },
        {
            "name": "x-custom-header-group-id",
            "value": "WA001"
        }
    ]
}
```

On the receiving side, I was able to do a similar GET and see the custom headers included in `internetMessageHeaders`.

That test was done sending from one user to another user in the same M365 tenant. I repeated the test sending to a user outside of the tenant, and I also tested sending using the /me/sendmail API (rather than creating a draft, then sending it). In all cases the custom header was received by the recipient.

**Comment by jasonjoh** [comment]
Closing this issue as I've answered the question and the docs seem to be correct here. If you're still having problems with custom headers, please post on Stack Overflow with the microsoft-graph tag.
