### ISSUE TITLE
Beta Azure AD /applications/{id}

### ISSUE THREAD

**Issue by moojjoo** [microsoftgraph/microsoft-graph-docs#3240]
{id} does not refer to either the ApplicationID or ObjectID in Azure, so why are you using the {ID} how does a developer get this ID, do we have to query via a filter first?  Example ?$filter=startswith(displayName,'My App')

Just trying to understand where the {id} comes from.  This is not exposed in Azure AD properties.

Issue: {id} where do you find this ID inside of Azure AD Resource?

Article: https://developer.microsoft.com/en-us/graph/docs/api-reference/beta/api/application_get

**Comment by moojjoo** [comment]
Unfortunatly I am not getting the same result --- In Azure Portal I have objectID = **eb82b636-2f5a-441c-9ed8-ac88e6921d95**

When I run in BETA Microsoft Graph
I am see something different when I run the following query:
     https://graph.microsoft.com/beta/applications?filter=startswith(displayName,'My Profi')

I get:

`
{
    "@odata.context": "https://graph.microsoft.com/beta/$metadata#applications",
    "value": [
        {
            **"id": "e8814097-4179-4a89-9051-29d166a834a7",**  _<-- Does not match the objectID._
            "deletedDateTime": null,
            "isFallbackPublicClient": false,
            "appId": "34b9f444-b266-484a-aea8-5c796aeb66f9",
            "identifierUris": [
                "https://dukeenergymyprofile-dukeenergytestb2b.msappproxy.net/",
                "http://customappsso0A08C969934E49578BFD627B8EC72DC7",
                "http://instanceid_8adf8e6e-67b2-4cf2-a259-e3dc5476c621_267BFA737CDE4A7C9AEA29EA5C7E2CCF",
                "http://customappsso/a3fcac64-7342-481f-b87d-dceabbb72e02"
            ],
            "createdDateTime": "2018-09-18T19:29:11Z",
            "displayName": "My Profile",
            "isDeviceOnlyAuthSupported": null,
            "groupMembershipClaims": null,
            "optionalClaims": null,
            "orgRestrictions": [],
            "publisherDomain": null,
            "signInAudience": "AzureADMyOrg",
            "tags": [],
            "tokenEncryptionKeyId": null,
            "api": {
                "requestedAccessTokenVersion": null,
                "oauth2PermissionScopes": [
                    {
                        "adminConsentDescription": "Allow the application to access Duke Energy My Profile on behalf of the signed-in user.",
                        "adminConsentDisplayName": "Access Duke Energy My Profile",
                        "id": "29b2c963-d6f1-426a-bd70-090a8e1af32f",
                        "isEnabled": true,
                        "type": "User",
                        "userConsentDescription": "Allow the application to access Duke Energy My Profile on your behalf.",
                        "userConsentDisplayName": "Access Duke Energy My Profile",
                        "value": "user_impersonation"
                    }
                ]
            },
            "appRoles": [
                {
                    "allowedMemberTypes": [
                        "User"
                    ],
                    "description": "User",
                    "displayName": "User",
                    "id": "18d14569-c3bd-439b-9a66-3a2aee01d14f",
                    "isEnabled": true,
                    "origin": "Application",
                    "value": null
                },
                {
                    "allowedMemberTypes": [
                        "User"
                    ],
                    "description": "msiam_access",
                    "displayName": "msiam_access",
                    "id": "b9632174-c057-4f7e-951b-be3adc52bfe6",
                    "isEnabled": true,
                    "origin": "Application",
                    "value": null
                }
            ],
            "publicClient": {
                "redirectUris": []
            },
            "info": {
                "termsOfServiceUrl": null,
                "supportUrl": null,
                "privacyStatementUrl": null,
                "marketingUrl": null,
                "logoUrl": "https://secure.aadcdn.microsoftonline-p.com/dbd5a2dd-sgyqf47kw-pdt4vbymkcbkucxde73ujmhj3mod9abec/appbranding/h72amofo3jobvaczo-gtt34bjn6tlsu3ayxwjtdubrc/1033/bannerlogo?ts=636729002649978453"
            },
            "keyCredentials": [],
            "parentalControlSettings": {
                "countriesBlockedForMinors": [],
                "legalAgeGroupRule": "Allow"
            },
            "passwordCredentials": [
                {
                    "customKeyIdentifier": "Q1dBUF9BdXRoU2VjcmV0",
                    "endDateTime": "2019-09-18T19:29:33.875306Z",
                    "keyId": "5e6ba67b-62d3-4bcc-9995-92990d6a251f",
                    "startDateTime": "2018-09-17T19:29:33.875306Z",
                    "secretText": null,
                    "hint": null
                }
            ],
            "requiredResourceAccess": [
                {
                    "resourceAppId": "00000002-0000-0000-c000-000000000000",
                    "resourceAccess": [
                        {
                            "id": "311a71cc-e848-46a1-bdf8-97ff7156d8e6",
                            "type": "Scope"
                        }
                    ]
                }
            ],
            "web": {
                "redirectUris": [
                    "https://dukeenergymyprofile-dukeenergytestb2b.msappproxy.net/"
                ],
                "logoutUrl": "https://dukeenergymyprofile-dukeenergytestb2b.msappproxy.net/?appproxy=logout",
                "implicitGrantSettings": {
                    "enableIdTokenIssuance": true,
                    "enableAccessTokenIssuance": false
                }
            }
        }
    ]
}
`

Any thoughts?

**Comment by psignoret** [comment]
Think of the `Application` object as the _definition_ of the app. This is what the app developer would typically define and control: reply URLs, app branding elements like the name and logo, the API permissions requested and exposed, etc. This corresponds to what's under _App registrations_ in the Azure portal.

Think of the `ServicePrincipal` object as the _instance_ of the app in a tenant. (Remember, apps can be multi-tenant apps, so there could be multiple `ServicePrincipal` objects in different tenants, all referring back to the same "backing" `Application` object in the app publisher's tenant.) The `ServicePrincipal` object is the security principal representing the app in the tenant. It's what an IT admin might typically control/view: which apps have been consented which permissions, which users are assigned to which applications (and whether or not assignment is required to access the app), what conditional access policies apply to the app, etc. This all corresponds to what's under _Enterprise apps_ in the Azure portal.

You can read some more about this here: https://docs.microsoft.com/en-us/azure/active-directory/develop/app-objects-and-service-principals

You may also want to get into the habit of querying for `Application` objects and `ServicePrincipal` objects by unique identifiers, instead of `displayName` (which is not unique, so you may get multiple results). There are several you can choose from:
 *  By **`id`** - All objects have a unique object ID, as a Guid. This will be different for the `Application` and `ServicePrincipal` objects of the same app (because they're different objects).

        GET .../applications/e8814097-4179-4a89-9051-29d166a834a7
        GET .../servicePrincipals/eb82b636-2f5a-441c-9ed8-ac88e6921d95

 * By **`appId`** - An app is uniquely identified by the AppId, also a Guid. This will be the _same_ for the both the `Application` object, and the `ServicePrincipal` object of the same app.

       GET .../applications?$filter=appId eq '34b9f444-b266-484a-aea8-5c796aeb66f9'
       GET .../servicePrincipals?$filter=appId eq '34b9f444-b266-484a-aea8-5c796aeb66f9'

 * By **`identifierUris`** (for `Application`) - Each app can have one or several values in `identifierUris` which are alternative, usually more friendly, ways to identify apps, as URIs. These values will be unique to the `Application` object in the tenant, and for multi-tenant apps, unique across _all_ `Application` objects in all tenants.

       GET .../servicePrincipals?$filter=identifierUris/any(uri: uri eq 'https://dukeenergymyprofile-dukeenergytestb2b.msappproxy.net/')

 * By **`servicePrincipalNames`** (for `ServicePrincipal`) - When a `ServicePrincipal` object is created, the backing `Application` object's `appId` and all `identifierUris` values are copied into the `ServicePrincipal` object's `servicePrincipalNames` collection. Each of these is a unique identifier for the `ServicePrincipal` object in that tenant.

       GET .../applications?$filter=servicePrincipalNames/any(spn: spn eq 'https://dukeenergymyprofile-dukeenergytestb2b.msappproxy.net/')

**Comment by moojjoo** [comment]
Thank you so much for taking the time to write this explanation out.  I am just on a holding pattern for the Beta Version of the Microsoft Graph because we will be building a UI to allow the business to add applications based on Azure AD security.

**Comment by dkershaw10** [comment]
@moojjoo Assuming it's OK to close this issue now.
