### ISSUE TITLE
permissions_reference - how to find apps permissions

### ISSUE THREAD

**Issue by 217Wilder-User1** [microsoftgraph/microsoft-graph-docs#3329]
I'd like to understand how to find the granted delegated permission on an existing app.  The documentation doesn't explain how to find the permissions.

**Comment by mitchellw3** [comment]
Thanks microsoft

**Comment by dkershaw10** [comment]
@217Wilder-User1 While this question is probably best posted on stackoverflow (tag [microsoft-graph] to actually find this information (I suspect it's already been answered there), I'll give a brief answer here. Our docs are definitely due an over-arching set of topics about applications, service principals and permissions, and using these APIs. However, this info is available, albeit somewhat buried.

For an instance of an application - i.e. [servicePrincipal](https://graph.microsoft.com/beta/servicePrincipals/002192f9-e0dd-42a2-bbf1-3b82ca3baf23/oauth2PermissionGrants) you can get the `oauth2PermissionGrants` (see [info](https://developer.microsoft.com/en-us/graph/docs/api-reference/beta/resources/oauth2permissiongrant)) which will list the delegated permissions granted to the app.  So for example:

`GET https://graph.microsoft.com/beta/servicePrincipals/{id}/oauth2PermissionGrants` 
where {id} is the identifier for the service principal (different from the appId, which is another property on the service principal. 

Recommend you try this out in [Graph Explorer](https://aka.ms/ge).

Hope this helps.

**Comment by 217Wilder-User1** [comment]
@dkershaw10 Thanks for the information. 

From the documentation, it would be nice to know general strategies to locate application permissions.  Azure portal?  Microsoft graph Beta? Microsoft graph v1? 

My user story:

As a front-end developer who does not have access to the Azure Active Directory Portal, I need a list of permissions assigned to my app (tenant), so that I can set the consentScopes for my MsalModule.

As a front-end developer who does not have access to the Azure Active Directory portal and the people managing it have little experience with Azure applications, I need talking points when asking for the application permissions, so that it doesn't take days or weeks to get basic permission information about my application.

Note: We're still in the process of implementing graph.microsoft.com.  Working in environment with 50K+ users can be tricky.

**Comment by FaithOmbongi** [comment]
A while since this issue was first posted. To add onto Dan's response, the APIs to programmatically retrieve the application permissions is different from the API to retrieve delegated permissions granted:

- [`GET /servicePrincipals/{id}/appRoleAssignments`](https://docs.microsoft.com/graph/api/serviceprincipal-list-approleassignments?view=graph-rest-1.0&tabs=http) to list application permissions (app roles) granted to your app.
- [`GET /oauth2PermissionGrants?$filter=clientId eq {id} and consentType eq 'AllPrincipals'`](https://docs.microsoft.com/graph/api/oauth2permissiongrant-list?view=graph-rest-1.0&tabs=http) to list delegated permissions granted on behalf of all users (e.g. via tenant-wide admin consent) to the app
