### ISSUE TITLE
When will this beta version be generally available?

### ISSUE THREAD

**Issue by ashoks104** [microsoftgraph/microsoft-graph-docs#3423]
When will the beta version be generally available? I am trying out the beta api for getting the details of Applications in AD.

**Comment by jthake-msft** [comment]
What particular applications capabilities are you looking for to GA out of interest? Can you provide a sample HTTP request?

**Comment by ashoks104** [comment]
I am basically checking the date of expiry of secret for an AD app. The API call used is:
https://graph.microsoft.com/beta/applications/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
If we can get the expiry date of a AD app's secret, we can track it and take necessary action before it expires.

**Comment by jthake-msft** [comment]
At this stage we don't have a clear date on when this will move from beta to v1.0. We are still receiving feedback on the APIs since moving it to Microsoft Graph. Please keep an eye on the [change log](https://docs.microsoft.com/en-us/graph/changelog) and [blog](https://developer.microsoft.com/en-us/graph/blogs/) for updates on this.
