### ISSUE TITLE
purpose of microsoftStoreForBusinessApp through Microsoft Graph?

### ISSUE THREAD

**Issue by ioanmoraru** [microsoftgraph/microsoft-graph-docs#3607]
Hello. 

What is the purpose of creating microsoftStoreForBusinessApp through Microsoft Graph? Aren't these apps supposed to be got only through MS Store for Business and then syncronized to Intune? 
When I try to create as specified in the documentation: (https://docs.microsoft.com/en-us/graph/api/intune-apps-microsoftstoreforbusinessapp-create?view=graph-rest-beta) I always get bad request. I think I missed or did not understand something. 
Could you please give me a little help into this direction?

Thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a28f113d-3406-ee2b-fd76-5bff856ca87b
* Version Independent ID: bf58b483-0afc-4015-7f29-c72eb5f5a836
* Content: [Create microsoftStoreForBusinessApp - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/intune-apps-microsoftstoreforbusinessapp-create?view=graph-rest-beta)
* Content Source: [api-reference/beta/api/intune-apps-microsoftstoreforbusinessapp-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/intune-apps-microsoftstoreforbusinessapp-create.md)
* GitHub Login: @jthake-msft
* Microsoft Alias: **jthake-msft**

**Comment by jthake-msft** [comment]
@lleonard-msft could you help here?

**Comment by ioanmoraru** [comment]
@lleonard-msft @jthake-msft Could you please give me some info? It's about the MS documenation, not about a bug! :-((((

**Comment by lleonard-msft** [comment]
@triplanedave - Do you have any insight here?

**Comment by triplanedave** [comment]
The process of creating a store for business app is different than regular client apps.  

1. You're right - these apps are sync'd in the background programmatically.  The Graph API's documentation is generated through automated tools.  My guess is that the Graph API call is made in the backend as part of the sync process, but it got picked up by the automation tools, and added to docs.  

2. As to the bad request, typically that happens because there is some of the JSON request body text that's incorrect.  We've found some examples where the programmatically generated JSON sample text is not correct for the API.  My apologies for that.  Typically the JSON text can be verified by doing F12 in the browser to watch the network trace made by the UI calling Graph, but that's not possible in this case.

So, I'd ask two things - are you trying to replicate the back end process to generate a Store for Business app without using the sync?  And, if so, more for curiosity, what's the use case for doing so?  
Secondly, if you get an activityID from the bad request (ideally you'd do another one so we have a more recent ActivityID), that would help us determine what's actually triggering the return code.

Dave
