### ISSUE TITLE
Missing documentation for query parameters support

### ISSUE THREAD

**Issue by sumeet-automate** [microsoftgraph/microsoft-graph-docs#3620]
#### Issue

There are instances where query parameters work, and where they do not work.

For instance:
I tried using using the filter parameter over the site/lists endpoint but it didn't work, and there's no documentation for such.

`https://graph.microsoft.com/v1.0/sites/{siteId}/lists/{listId}/items?$filter=createdDateTime gt '2018-12-12T09:32:18Z'`

There are other instances where these don't work. Some give the direct errors - rejecting the use of quey parameters, while others silently ignore it. Kindly update the documentation providing proper info about the query parameters for all end points with a few more examples.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fefc984-0dac-5531-6620-13f577ebee5f
* Version Independent ID: 92438f30-1bb9-9b45-57dc-094fdcdeecc1
* Content: [Use query parameters to customize responses - Microsoft Graph](https://docs.microsoft.com/en-us/graph/query-parameters?toc=./ref/toc.json&view=graph-rest-1.0)
* Content Source: [concepts/query-parameters.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/query-parameters.md)
* GitHub Login: @jthake-msft
* Microsoft Alias: **jthake-msft**

**Comment by jthake-msft** [comment]
We are aware of this. We are actively working on better documentation to make it clearer on which APIS support which OData Queries.

**Comment by jthake-msft** [comment]
@madansr7 as you've been tracking this work, I'm assigning this one to you.

**Comment by Joombalaya** [comment]
I would also like to add. That a contains filter on Users may be critical so that we can easily pull account information using the onPremisesSamAccountName.

**Comment by zaphod4254** [comment]
Agreed with Joombalaya about "contains".  Seems MOST string related filter operators are not implemented.  I have a need to return all users who have an email address that uses a certain domain (my company manages many domains).  I.e., equivalent to the get-msoluser -domainname whatever.com PowerShell command.  I can't find any way to do this using the $filter.  "contains" doesn't work, nor do an of the other string operators that I could otherwise use to try to combine and construct an alternative (length, indexof, substring).  This is a must-have function.

**Comment by Mhbuur** [comment]
A start would be to document which query types are supported in the different end points. 

While it would be great with global full OData Query support, the real frustrating part is that you have to do trial and error.

Fingers crossed :-)

**Comment by sumit-kakadiya** [comment]
Is there any plan to have "contains", "startwith", or "has" type of support in filter?

**Comment by FaithOmbongi** [comment]
A while since this issue was raised, but in case anyone else is facing this same issue:

- The `contains  `and `startsWith` operators are now supported across Microsoft Graph. Kindly review the [Query parameters](https://review.docs.microsoft.com/en-us/graph/query-parameters?branch=pr-en-us-13212#filter-parameter) article.
- `contains` is supported in a small subset of APIs, though not on Users, Groups, and Applications objects. The team is actively working to include its support by these resources.
- `endsWith` works but requires the use of advanced query parameters. That is, the **ConsistencyLevel** header set to `eventual` and `$count`. More guidance is in the [Advanced query capabilities](https://docs.microsoft.com/en-us/graph/aad-advanced-queries) article. An example:

**Click to try in Graph Explorer:** [../users?$count=true&$filter=endsWith(mail,'@domainxyz.com')](https://developer.microsoft.com/en-us/graph/graph-explorer?request=users%3F%24count%3Dtrue%26%24filter%3DendsWith(mail%2C'%40domainxyz.com')&method=GET&version=v1.0&GraphUrl=https://graph.microsoft.com&headers=W3sibmFtZSI6IkNvbnNpc3RlbmN5TGV2ZWwiLCJ2YWx1ZSI6ImV2ZW50dWFsIn1d)

- While `contains` might not be supported on Users yet, **onPremisesSamAccountName** supports various `$filter` operators. You can check the [Advanced query capabilities](https://docs.microsoft.com/en-us/graph/aad-advanced-queries#support-for-filter-on-properties-of-azure-ad-directory-objects) article to see which operators would work for your case in the meantime.

More guidance will be available on the the articles shared and the main resource pages. Closing this issue for now.
