### ISSUE TITLE
Response payload returns an array of organizations.

### ISSUE THREAD

**Issue by freerangeeggs** [microsoftgraph/microsoft-graph-docs#3654]
As shown below, the response is slightly different to what is documented, in that a "value" is returned which is an array of organizations rather than a single org.
I haven't seen a situation where multiple organizations are returned, I have only seen one, but is there a situation where multiple could be returned?

```
{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#organization",
    "value": [
        {
            "id": "...",
            <other fields here>
        }
    ]
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e1a63d98-d88c-01fe-afca-31d1920ba76c
* Version Independent ID: 7c2deaf1-192f-e3a6-57dd-6b9caa7c2e4c
* Content: [Get organization - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/organization-get?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/organization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/organization-get.md)
* GitHub Login: @jthake-msft
* Microsoft Alias: **jthake-msft**

**Comment by jthake-msft** [comment]
@lleonard-msft I believe this would be in your ownership right? It didn't actually pick up in my author update, so worth adding author yaml manually as part of this...

**Comment by dkershaw10** [comment]
Thank you for pointing this out. The documentation needs to be fixed. `GET /organization` does indeed return a collection (of one).  This actually mirrors the behavior of AAD Graph (for tenantDetails). Currently there are no situations where more than one record it returned - as it represents the organization (or tenant) that the user or app is signed in to.  All calls to Microsoft Graph (for enterprise scenarios) are **always** in the context of an organization (or tenant).
Really `organization` should be modeled as a singleton, rather than a collection.  We have this queued up for future versions, but making this change in v1.0 would represent a breaking change.

Hope this helps.

**Comment by freerangeeggs** [comment]
I does help; thanks very much.

**Comment by rocketraman** [comment]
The beta API still returns an array...

**Comment by dkershaw10** [comment]
@rocketraman Yes it does - all versions return a collection.  Please see my earlier comment.

**Comment by rocketraman** [comment]
@dkershaw10 Yup, I've read through the issue. My comment was in response to this statement:

> We have this queued up for future versions, but making this change in v1.0 would represent a breaking change.

Presumably the beta can contain breaking changes?

**Comment by dkershaw10** [comment]
Yes it can, but at this stage (at least for the Directory APIs), we're more likely to keep these API versions in sync.  We also need to figure out our versioning strategy for our next major version, and what beta means there.

**Comment by landall** [comment]
I think the api should names /organizations because of the update url is /organization/{id}.
Maybe you should add a new api /tenant to return only one organization.
