### ISSUE TITLE
do i need a bot

### ISSUE THREAD

**Issue by paulobriennz** [microsoftgraph/microsoft-graph-docs#3717]
Is this the API to use to just get general Teams Client calling events? For example if someone calls in to Teams (via 1:1 or Direct Routing), can you use this API to hook and get those details?  Confused as to whether need to configure BOT to just get overall Teams Client events like Incoming Call or can just connect to Teams tenant via an App Registration and then get calling events.. (in Lync SDK could register for incoming calls, presence changes etc) ...  any point in the right direction would be appreciated.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab778516-a025-958b-5b15-bb4df6cf490b
* Version Independent ID: a859b2fa-a1cc-d834-a65d-3a088bfe5ffb
* Content: [Get call - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/call-get?view=graph-rest-beta)
* Content Source: [api-reference/beta/api/call-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/call-get.md)
* GitHub Login: @VinodRavichandran
* Microsoft Alias: **jthake-msft**

**Comment by stefan2410** [comment]
@VinodRavichandran  How can  I get a call information (CDR) in my tenant scope?  using another application, preferably during the call and   right after hangup?

**Comment by VinodRavichandran** [comment]
Are you looking to receive some sort of notification after the call has ended to receive CDR of that call into your application?

**Comment by stefan2410** [comment]
Yes,  in 2 different scenarios . 
1. when the user answers the call. 
2. after the call 
I need the participants (Peer to Peer, incoming calls, never mind if other participants would added later)
I need the call info in JSON  or  the callId to get the info with an API call ( the later should be in tenant scope for any user)

**Comment by VinodRavichandran** [comment]
Ok, thanks for sharing the scenarios. We do plan to expose calling events at some point but don't have a public timeline to share at this point. You can retrieve CDRs from dashboard (should check with tenant admins) or have an application/bot join the call and get a list of participants/roster from the meeting/call until the feature is available. 

FYI - @zhengni-msft

**Comment by stefan2410** [comment]
@VinodRavichandran  Is there a way  an application/bot  to join the call automatically ?
Maybe I don't know the way. What I've understood is that the user should directly ask the bot to join.
This can't work.

**Comment by VinodRavichandran** [comment]
No, we are starting to plan for such a functionality based on asks, but don't have anything at this point.

**Comment by stefan2410** [comment]
Think of a bot  like the IncidentBot  to get incoming calls in a group as Auto Attendant.

**Comment by rugt0r** [comment]
@VinodRavichandran 
"have an application/bot join the call and get a list of participants/roster from the meeting/call until the feature is available"

We don't appear to be able to get a list of participants from a call which started out p2p but was escalated to a group call. We can only get participants from a scheduled meeting that the bot has called into. See my posts here:
https://github.com/microsoftgraph/microsoft-graph-comms-samples/issues/102

We need realtime information- list of ongoing calls in a tenant, participants for each call, the ability to track calls through transfers, etc. This is really important for contact centre functionality.

**Comment by Fensterbank** [comment]
> We need realtime information- list of ongoing calls in a tenant, participants for each call, the ability to track calls through transfers, etc. This is really important for contact centre functionality.

That's our need too, all other ideas (e.g. let a bot join a call automatically) are workarounds to get exactly this feature.
In fact this is a core feature for every centralized phone system, but at the moment it seems there is no way to achieve this.
The calling methods from Graph API are always intended to be used by a bot, which was called directly.

In our use case, we want to support employees when they get called by customers, so when an incoming call by a known number was made, our backend service will fetch some details and uses the bot to send an adaptive card with customer details to the user.

My app can programmatically get every event, every contact and every mail of any user, it makes no sense, that there is no way to retrieve any little information about calls for or from users.

Since the idea of @stefan2410 is not possible either, the only way to achieve this feature is to **train the employees to always add the bot to the call** with the customer to get the information.... if this is possible, the comment from @rugt0r sounds bad at this point... 😕

I hope Microsoft implements these features ASAP, a lot of companies are migrating their phone system to O365 only to realize that all their calls are now in a black box which cannot be accessed programmatically. 🤦‍♂

**Comment by cKehres** [comment]
Same here, simple task: load all calls by employees and save in our crm, curently no chance?!
