### ISSUE TITLE
How do I get mail Id after sending mail with this api

### ISSUE THREAD

**Issue by bewithdhanu** [microsoftgraph/microsoft-graph-docs#3766]
How do I get mail Id after sending mail with this api
https://graph.microsoft.com/v1.0/me/sendMail
its not sending any response, How do I know its mail Id

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3b984b6-9100-69aa-f0f8-84bcdcea20dd
* Version Independent ID: 3f8b622d-becd-f287-98ac-18e408200523
* Content: [Send mail - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-sendmail.md)
* Product: **microsoft-identity-platform**
* GitHub Login: @dkershaw10
* Microsoft Alias: **jthake-msft**

**Comment by Misiu** [comment]
@bewithdhanu were You able to get mail id?

**Comment by jasonjoh** [comment]
This is by design. I'm assuming that you want to get the `id` of the message after it is saved in Sent Items?

If that's your need, the way to do it is to tag the message with a custom identifier, then find it in Sent Items after you've sent it.

## Send the message with custom identifier

Send the message as you are now, but include a [single-value extended property](https://docs.microsoft.com/graph/api/resources/singlevaluelegacyextendedproperty?view=graph-rest-1.0) in the message payload.

What you should do is define your own GUID and property name, which then remains constant. You would then generate a unique value every time you send a message. For example, if you look at  the sample payload below, I define the `id` of my `singleValueExtendedProperty` as `String {630b1eb6-293a-4c92-ba78-a40aadad5ae7} Name SendMailId`. The GUID is one I generated, and the name `SendMailId` is just something I defined. I would use this same `id` value every time I send mail, but I would change the `value` of the `singleValueExtendedProperty` to something unique.

**Request**

```
POST /me/sendmail
Content-type: application/json

{
  "message": {
    "subject": "Did you see last night's game?",
    "importance": "Low",
    "body": {
      "contentType": "HTML",
      "content": "They were <b>awesome</b>!"
    },
    "toRecipients": [
      {
        "emailAddress": {
          "address": "AdeleV@m365x930361.onmicrosoft.com"
        }
      }
    ],
    "singleValueExtendedProperties": [
      {
        "id": "String {630b1eb6-293a-4c92-ba78-a40aadad5ae7} Name SendMailId",
        "value": "1234"
      }
    ]
  }
}
```

## Find the message by the custom identifier

Now you can find the message by using a `$filter` clause. You can also optionally include an `$expand` clause if you want the custom identifier to be included in the response.

**Request**

```
GET /me/messages?
$filter=singleValueExtendedProperties/Any(ep:ep/id eq 'String {630b1eb6-293a-4c92-ba78-a40aadad5ae7} Name SendMailId' and ep/value eq 'Food')&
$expand=singleValueExtendedProperties($filter=id eq 'String {630b1eb6-293a-4c92-ba78-a40aadad5ae7} Name SendMailId')
```

**Response (truncated)**

```
{
  "value": [
    {
      "id": "AAMkAGE1...",
      "subject": "Did you see last night's game?",
      "singleValueExtendedProperties": [
        {
          "id": "String {630b1eb6-293a-4c92-ba78-a40aadad5ae7} Name SendMailId",
          "value": "1234"
        }
      ]
    }
  ]
}
```

**Comment by bewithdhanu** [comment]
👍 
Thax @jasonjoh

**Comment by kehers** [comment]
You can actually generate your own message id and send the mail with it.

```
POST https://graph.microsoft.com/v1.0/me/sendMail
Content-type: application/json

{
  "message": {
    "internetMessageId": "[valid rfc2822 message id]",
    ...
  }
}
```

**Comment by sudostack** [comment]
@jasonjoh First of all, thanks for providing a useful example, but there's a point of confusion for me. Perhaps you can help clarify...

An extended property contains two fields, `id` and `value`

I have the same scenario as OP and I'm curious as to why a property's `id` field needs to include a GUID/UUID in the format of `<datatype> {<GUID>} Name <some name>`? 

My mental model of an extended property is more like:
```
{
  "id": "GUID", // or SendMessageId
  "value": <some GUID/UUID>
}
```

It appears that the GUID is unique to a resource action as indicated by the name that you've chosen, `SendMailId`. If I'm generating unique identifiers for each message, should I be generating another GUID/UUID for the `value` field?

**Comment by jasonjoh** [comment]
The GUID in this case is what ensures uniqueness. The GUID serves as a namespace identifier. The idea is that your application defines a namespace, and any custom properties your application uses are in that namespace. So you only need to define a GUID once here. This is an older MAPI concept, and predates open extensions. You also really would only need to define one name here.

For open extensions, there are few problems. First, you can't filter on them, so that makes it a bit more work to find it in the Sent Items folder. I'm also not sure if open extensions are preserved when you send.

**Comment by kshitijrana** [comment]
You can get the message ID from the Sent Items folder by this request https://graph.microsoft.com/v1.0/me/mailFolders/${sentMailboxId}/messages. It would be the first message in the array. However, make this request after a timeout function so that the mail is populated in Sent Items folder.

**Comment by sudostack** [comment]
@kshitijrana while that may work for a single message send. I’m not sure this idea works for multiple message sends. I hesitate to rely on this if there’s no documentation stating that order is guaranteed, and if messages are sent in behalf of the user from different services, this reconciliation becomes even more difficult. So this probably only works for a very simple and narrow use case. Am I right?

**Comment by Misiu** [comment]
We have webhooks and they should be used to get id and other properties after the message was sent.
Right now You must pull (query) graph after x seconds until You find that email in Sent Items folder.
I've created a [feature request](https://microsoftgraph.uservoice.com/forums/920506-microsoft-graph-feature-requests/suggestions/36957805-webhook-email-send-notification) that would allow us to get notifications when email was sent.
This would simplify everything so much.

1. You send email using graph
2. Email get send
3. You get a webhook notification and You can read all the properties (for example sentDateTime).

If others need such functionality please upvote my feature request.

**Comment by kshitijrana** [comment]
@sudostack You're right. If the account is being used from different services simultaneously, this will not guarantee the correct message ID.

**Comment by sudostack** [comment]
@Misiu I like that idea. Yeah, that's precisely what I do at the moment in my organization's application code. I wrote an SDK that my application consumes. Our response to the 4xx status code that they supply when the message isn't yet available is to retry with delay. It isn't ideal or elegant, but a webhook notification would provide what is needed although the use-case is pretty limited to a few consuming clients like us. The alternative that I think Microsoft could supply is allowing the option of making a send **synchronous** and having the consuming client (us) pass an option for it, but it may not be possible or reasonable for Microsoft to have when considering service availability

**Comment by kshitijrana** [comment]
@Misiu @sudostack Wouldn't it be better if send mail end point sends the relevant information with the response? Instead of the empty response that it sends right now. I think this might be better than having a web hook.

**Comment by Misiu** [comment]
@kshitijrana that would be awesome, but emails are queued on Exchange and having this functionality will extend the response time (because mail must get send before You will get a response).
Currently, You only get confirmation that Exchange has registered Your request for processing (please correct me if I'm wrong). This is the async (the default) behavior as @sudostack described.

But for simple use cases, this would be the preferred way to go. The only thing missing is a parameter in the request that would inform Exchange to perform an synchronous operation and return all the information we normally query for.

But for large systems that need to send a lot of emails, the preferred way would be to use webhooks because the You use all the goodness of async operations - You send and forget and Exchange informs You that the email was sent.

**Comment by kshitijrana** [comment]
@Misiu Thanks for explaining. I wasn't aware of the Exchange and how it works. What you say makes sense.

**Comment by Misiu** [comment]
@kshitijrana I'm glad I could help :)
I've created [this feature request](https://microsoftgraph.uservoice.com/forums/920506-microsoft-graph-feature-requests/suggestions/36957805-webhook-email-send-notification) for this type of notifications (webhooks). Please upvote it and spread the word. Maybe someday this will get implemented

**Comment by sudostack** [comment]
@kshitijrana what @Misiu stated is what I meant, but to add, it isn't unique to Exchange. 

In large scale distributed systems, "service availability" (the A in the CAP theorem) is what's typically deployed at scale (choosing P [partition tolerance] and A [availability]) over consistency. 

They send you an ACK with a 202 (accepted status code) to let you know that they've received the request, but it isn't necessarily processed yet, so their systems can keep humming along (they likely process them in serial in some queue), but if they had to ACK (acknowledge) and process an then let you know that the work has been done, that's going to be a waiting game for us (the consuming client) and their resources could be locked up trying to do a synchronous operation (which blocks). An email system at scale needs to be highly concurrent -- therefore webhooks satisfies this need, as they can just dispatch a notification when the work is actually done (processed) instead of (acknowledgement and processing)

**Comment by Misiu** [comment]
@sudostack @kshitijrana I'm currently building solution based on webhooks. I'm subscribing to `sentitems` folder.
I have a problem when trying to access `SingleValueExtendedProperties` but the basic concept works.
I'll share more info when everything will be working as expected 🙂

**Comment by kshitijrana** [comment]
@sudostack Thanks for the information. I understand that the response for the API is just for the developer to know that the request has been registered and the system does the processing later. Doing it as a synchronous operation would involve more waiting time for the client's code (us) and makes their system less concurrent.
 If you allow me to go a little off topic here, Gmail API gives the message ID as well as the thread ID (conversation ID in case of this API) in the response for the send mail API. So, would it be fair assume that they are performing a synchronous operation? I can only guess, but I think the request body of Gmail API's send mail endpoint which requires the entire email message to be RFC 2822 formatted and base 64 encoded requires less processing on their part. Do you think that's the reason why sending mail is faster for them? Or there are some other reasons involved as well?

**Comment by sudostack** [comment]
@kshitijrana I’ve not worked with the Gmail API. The implementation details are opaque to the consuming client. I was only making an assumption. 

What you’ve described seems to me like a synchronous operation, particularly if the HTTP status code that is returned is a 200 as opposed to a 202.

The architectures are likely wildly different, because Gmail is historically newer than Exchange. However, it could simply be that Microsoft didn’t anticipate our use case and saw no need to do any additional compute. It’d be interesting to see what the response times are between the two APIs, though

**Comment by Misiu** [comment]
@sudostack @kshitijrana I've managed to build POC application using the subscription on `sentitems` folder - `$Resource = "users/{user.Id}/mailFolders('sentitems')/messages"`.
Hoverwer there is one side effect - I get at least 3 notifications for each email sent. Ideally, I'd like to have only a single request, so there should be a new notification type or I must add a filter.

I've tried adding a filter to get notifications only for emails that have my singleValueExtendedProperty. My filter looks like this:

```
var newSubscription = await graphClient.Subscriptions.Request().WithImmutableId().AddAsync(new Subscription
{
    Resource = $"users/{user.Id}/mailFolders('sentitems')/messages?$filter=singleValueExtendedProperties/Any(ep: ep/id eq 'String {{1f5657a1-f16a-493e-9baf-461f9e2218b7}} Name MyId' and ep/value ne null)",//?$filter=subject eq 'Test'",
    ChangeType = "updated",
    NotificationUrl = "https://6025c15b.ngrok.io/api/values",,
    ClientState = Guid.NewGuid().ToString(),
    ExpirationDateTime = DateTimeOffset.UtcNow + new TimeSpan(0, 0, 5, 0)
});

```
This filer works:
`$"users/{user.Id}/mailFolders('sentitems')/messages?$filter=subject eq 'Test'"`
but this don't:
`$"users/{user.Id}/mailFolders('sentitems')/messages?$filter=singleValueExtendedProperties/Any(ep: ep/id eq 'String {{1f5657a1-f16a-493e-9baf-461f9e2218b7}} Name MyId' and ep/value ne null)"`

I'm adding singleValueExtendedProperty using below code:
```
var guid = "62a8d197-c880-4ca6-a361-dcad8a24e095";
var email = new Message
{
    Body = new ItemBody
    {
        Content = "Works fine! " + DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss"),
        ContentType = BodyType.Html,
    },
    Subject = "Test",
    ToRecipients = recipientList,
    Attachments = att
};

var p = new SingleValueLegacyExtendedProperty
{
    Id = $"String {{{guid}}} Name MyId",
    Value = "Test"
};
email.SingleValueExtendedProperties = new MessageSingleValueExtendedPropertiesCollectionPage
{
    p
};
```

Can I filter subscription using `singleValueExtendedProperties`?

**Comment by minaairsupport** [comment]
I dont know why you closing this issue 
I think we should get the id after the email sent without making any extra thing
currently we didnt get anything in Rest response

**Comment by sudostack** [comment]
Probably should've linked back to https://github.com/microsoftgraph/microsoft-graph-docs/issues/6256
