### ISSUE TITLE
User.ReadWrite.All used in the permissions example. is that correct?

### ISSUE THREAD

**Issue by piotrci** [microsoftgraph/microsoft-graph-docs#3810]
Perhaps a nitpick: the doc explains that the caller needs to have the permission to read/write a resource to access the extension data. As an example we sue the User.ReadWrite.All permission - is that correct? in this scenario, couldn't a lower permission be used?  Would User.ReadWrite be OK for the signed-in user only?

"For example, for an app to be able to update the signed-in user's profile with custom app data, the app must have been granted the User.ReadWrite.All permission."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1fbbb2e0-38fb-fb9a-da33-138c09262fbd
* Version Independent ID: 583af78a-8160-e4d3-9710-998b6e6f13f1
* Content: [Add custom data to resources using extensions - Microsoft Graph](https://docs.microsoft.com/en-us/graph/extensibility-overview#feedback)
* Content Source: [concepts/extensibility-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/extensibility-overview.md)
* GitHub Login: @dkershaw10
* Microsoft Alias: **jthake-msft**

**Comment by wpbrown** [comment]
@piotrci I was curious about this as well. I did some testing with Azure AD Directory Schema Extensions (that appear in the form of extension_APPID_NAME properties on the resource in the Microsoft Graph). I created an extension on the user object.

User.ReadWrite.All (application role) works and makes sense for applications. As for delegation scopes, I tried User.ReadWrite and I could not update the property, even on the signed-in user. Actually even User.ReadWrite.All was not enough to update signed in user or any user. The user also needed to be 'User Administrator' or 'Global Administrator'. User.ReadWrite + 'User Administrator' did not work. Only when User.ReadWrite.All was combined with 'User Administrator' could I update the property.

There is a lot of detail that could be added to this section to make it more useful. I only tested the Azure AD Directory Schema Extension (because these are usable as Optional Claims). What is the behavior for Microsoft Graph Open Extensions or Schema Extensions? Do they also have this interaction with directory roles? And I was augmenting the 'User' resource which has a special role 'User Administrator' associated. What is the minimum directory role that other resource types would need to be modified?
