### ISSUE TITLE
Acquiring access token to already signed in Dynamics 365 CE users 

### ISSUE THREAD

**Issue by AhmedAnwarHafez** [microsoftgraph/microsoft-graph-docs#3828]
I am working on a single-page application (SPA) that should connect to SharePoint via Graph API.
The SPA will be hosted in Dynamics 365 CE as a web resource. Users who use the SPA (web resource) are already authorized and authenticated in Dynamics 365 CE.

I checked the React sample in the Tutorials section and I couldn't find any SPA or JS samples that connect to Graph for already signed in users.

Should apps hosted in CE be treated as external SPAs like in code samples in the documentation here?
https://docs.microsoft.com/en-nz/graph/tutorials/react

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28ef7a19-9ce7-7b73-8fa5-b071efacf6ba
* Version Independent ID: 03006629-3161-c4f7-355e-f94a462626e0
* Content: [Get access on behalf of a user - Microsoft Graph](https://docs.microsoft.com/en-nz/graph/auth-v2-user)
* Content Source: [concepts/auth-v2-user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/auth-v2-user.md)
* Product: **microsoft-identity-platform**
* GitHub Login: @Jackson-Woods
* Microsoft Alias: **jthake-msft**

**Comment by markjsc** [comment]
Hi Ahmed,
I was able to get an Access Token inside a Dynamics 365 CE (CRM) Web Resources SPA using the MSAL library. I had to do a couple of things that would not usually apply to standalone, custom SPAs:
- I could only get the Login Token and Access Token using the respective Popup methods. The Acquire Token Silent method did not work from my main SPA, likely due to the fact that it is already hosted inside an iFrame (and the silent method uses yet another iFrame for part of the process). This is not the preferred user experience, but because the popup windows close quickly and without user intervention (after the initial scope acceptance), it is OK for my purposes.
- I had to create a separate Web Resource for the purpose of receiving the post-auth Redirect. I configured the Redirect URI to be the URL of this Web Resource. Using the componentDidMount() method of React, I called GetAccessTokenSilent, although I didn't do anything with the resulting token in this page. This seems to store the accessToken in storage (either session or local, depending on how you configure it), making it available to the original Web Resource. This will be displayed as a popup window and will close immediately.

The popup window will actually be displayed twice - once for login and a second time for the Access Token. You can cache the Access Token (you'll need to catch the exception it throws after expiring and renew it).

Hope this helps!

**Comment by AhmedAnwarHafez** [comment]
@markjsc I found outdated articles that use your a similar but with adal.js.
May I ask you to share a code snippet? I have been trying to get this working for literally a week and got to nowhere.

You'll be my hero.

**Comment by markjsc** [comment]
@AhmedAnwarHafez - I just posted the details on my blog: [Deep Dive: Authenticating for using Microsoft Graph API inside Microsoft Dynamics 365 Customer Experience (i.e. Micorosoft Dynamics CRM)](https://johnstonsoftwaresolutions.com/2019/02/24/deep-dive-authenticating-for-using-microsoft-graph-api-inside-microsoft-dynamics-365-customer-experience-i-e-micorosoft-dynamics-crm/)
I can't guarantee that it's 100% complete or error-free since I had to simplify it from my working solution. But at least you should be able to get the idea.
Hope this helps!

**Comment by AhmedAnwarHafez** [comment]
@markjsc 
Man, thank you so much for your fast reply and for writing a complete detailed blog. You ARE a legend.
The code works like a charm and now I'm able to get access tokens (sigh) after spending so many days on this frustrating access tokens. 
Wish I could buy you a pizza or a drink
Thank you 🥇

**Comment by drod910** [comment]
With this post is now a being year old does it still work? Has anyone found a more cleaner approach to do this through a supported API Call? I'm guessing not, but fingers crossed. I might do this via an embedded power app vs a web-resource otherwise.

**Comment by FaithOmbongi** [comment]
Hello @drod910 , apologies for the delayed response.

Unfortunately this forum isn't monitored for functionality issues, but questions like this are monitored at [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/index.html). Please ask your question there to get expert help in working with your code. Closing this issue for now.
