### ISSUE TITLE
The following fields are available properties for Group but not listed in the docs

### ISSUE THREAD

**Issue by gmicek** [microsoftgraph/microsoft-graph-docs#3880]
These fields come back without $select parameter set, but they are not shown in the docs here. The first 2 I tried did also work with $select parameter

I personally don't mind, just an FYI for docs team.

creationOptions
deletedDateTime
resourceBehaviorOptions
resourceProvisioningOptions

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae6b4ebd-685c-0854-6793-2f900cadc554
* Version Independent ID: 953200ad-c9af-a80d-7bc2-836a25ddc273
* Content: [group resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/group?view=graph-rest-1.0#properties)
* Content Source: [api-reference/v1.0/resources/group.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/group.md)
* Product: **groups**
* GitHub Login: @dkershaw10
* Microsoft Alias: **jthake-msft**

**Comment by Lauragra** [comment]
@angelgolfer-ms , you might want to look into this since you recently updated the group resource topic. Thanks.

**Comment by angelgolfer-ms** [comment]
@gmicek , thanks for your comment. Cc @lleonard-msft who is tracking documenting these properties.

**Comment by lleonard-msft** [comment]
Hi @gmicek - This is going to need a little research.  I'm adding this to my backlog and will tackle it in a future sprint.  Thanks for letting us know.

**Comment by tfrancois** [comment]
I'd also like to add a few new attributes that have shown up in the group object returned (without $select) that appears absolutely nowhere in any documentation here or otherwise:
externalGroupIds
externalGroupProviderId
externalGroupState

Can the documentation please be updated accordingly.

**Comment by dkershaw10** [comment]
deletedDateTime should be documented.  The rest no - unless we doc as do not use (I'll take this up with our writers).
They were released in the service (but not in the CSDL schema) - and were prematurely added in some cases (before the feature is ready). Because the group type is an open type, and in beta we return all properties, these do show up in the response, even if they are not described in the schema. In the case of the 3 you mention, @tfrancois - these should be deprecated.  Again - released too soon, and now we have different ideas about how the feature will be delivered, and these properties are no longer relevant.

**Comment by davidmu1** [comment]
deletedDateTime has now been documented.
