### ISSUE TITLE
Include the "block scheduled action" in an HTTP GET request

### ISSUE THREAD

**Issue by jseerden** [microsoftgraph/microsoft-graph-docs#4103]
When retrieving a Compliance Policy, the scheduledActionsForRule property is missing in the response, which is required for creating a new Compliance Policy.

GET + POST results in "Compliance policy must have one and only one block scheduled action". If it must have one and only one when creating, why not include it within the request itself?

If it can't be included a suggestion would be allowing us to create a Compliance Policy using Microsoft Graph, without the mandatory block scheduled action, using a default value if not specified.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb528776-0afb-da64-29f8-ad79dce07960
* Version Independent ID: f3e772cb-7136-0d95-5249-07c53ca07ef6
* Content: [Get windows10CompliancePolicy - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/intune-deviceconfig-windows10compliancepolicy-get?view=graph-rest-1.0#feedback)
* Content Source: [api-reference/v1.0/api/intune-deviceconfig-windows10compliancepolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/intune-deviceconfig-windows10compliancepolicy-get.md)
* Product: **intune**
* GitHub Login: @tfitzmac
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by phuong-vo** [comment]
Wow, this question is here for almost a year, but ms graph sdk/api developers did not have any single comment! I have same issue and tried to post question but looks like useless.

**Comment by DecimalZero** [comment]
Having the same issue.  Has anyone figured this out?

**Comment by habit81** [comment]
I found a workaround for creating compliance policy using REST API. I analyzed http traffic when creating compliance policy via Azure portal and found those additional details that are missing. All you need to do is add below lines to your existing compliance policy json body:

"scheduledActionsForRule":  [
                                    {
                                        "scheduledActionConfigurations":  [
                                                                              {
                                                                                  "actionType":  "block"
                                                                              }
                                                                          ],
                                        "ruleName":  null
                                    }
                                ]
I think the actionType is the most important here. Anyway give it a try and let me know if it helped.

**Comment by DecimalZero** [comment]
@habit81 Thank you!! Going to try that today. If this works, I am going to buy you a cup of coffee!! 😃

**Comment by habit81** [comment]
Upon further troubleshooting it turned out that the correct REST API url to get minimum mandatory information for creating new compliance policy is
https://graph.microsoft.com/beta/deviceManagement/deviceCompliancePolicies/25a52c3c-aa97-450f-81de-babd6c3b69e1?$expand=scheduledActionsForRule($expand=scheduledActionConfigurations)
where above ID is of course the ID of a source compliance policy. 
Once the result is returned you have to remove two properties:
scheduledActionsForRule@odata.context and scheduledActionConfigurations@odata.context
in order to properly create new compliance policy via REST API.
I did some tests and found one problem so far. If your policy has an action "Send email to end user" and you're exporting policy from tenant A to tenant B, you will most likely end up with all notification templates assigned to that new policy unless you replace notificationTemplateId with all zeros. If you also configured "Additional recipients" the new policy will show selected count but no O365 groups will in fact be selected.

**Comment by triplanedave** [comment]
Closing as it looks like this was resolved with community help.
