### ISSUE TITLE
Issue with subfolder image search

### ISSUE THREAD

**Issue by htryggva** [microsoftgraph/microsoft-graph-docs#4209]
I have an issue when searching for images scoped on a subfolder and it's children. The same issue does not seem to occur when searching for text files. I've noticed this issue both on OneDrive and Teams drives.

Example: My OneDrive looks like this:
```
Root/
    subdirectory/
        image.png
        textfile.txt
```
If I query:

`/me/drive/items/{id-of-subdirectory}/search(q='textfile')`

my result will contain the file that I'm searching for (with the addition of the subdirectory itself):

```
"value": [
    {
        "id": "id-of-subdirectory",
        "name": "subdirectory"
    },
    {
        "id": "id-of-textfile.txt",
        "name": "textfile.txt"
    }
]
```

But if I query for the image:

`/me/drive/items/{id-of-subdirectory}/search(q='image')`

my result doesn't contain the image (only the subdirectory)

```
"value": [
    {
        "id": "id-of-subdirectory",
        "name": "subdirectory"
    }
]
```

What is the reason for why the image isn't showing up in the search result?
Is there another way to perform searching scoped to a particular subfolder and it's children?

Note: I posted this question some time ago on StackOverflow without any response:
https://stackoverflow.com/questions/49534903/microsoft-graph-issue-with-onedrive-subfolder-image-search

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de33ed18-c074-a734-0b01-648888cb94aa
* Version Independent ID: 9fa15051-394e-d4ce-4687-c93be0ca8b80
* Content: [Search for files - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/driveitem-search?view=graph-rest-1.0#feedback)
* Content Source: [api-reference/v1.0/api/driveitem-search.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/driveitem-search.md)
* Product: **sharepoint**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKelley**

**Comment by Rismal** [comment]
same issue here.

i have an account just to serve images from a shared folder of another account, so my app can get them through API.
it seemed to be working, until my client decided to move all images directly in the service account, and now search doesn't work properly any longer.

after several sample checks i noticed that a few images in some folders are returned, while the vast majority doesn't; i haven't been able to pin down what's so special about these lucky ones.
obviously i double checked app permissions ( though i'm troubleshooting directly with the graph explorer ) and item sharing.
i waited hours and days hoping that maybe they needed to be indexed, but nothing; also i can't find a pattern in created/lastModified DateTime, because no image after December 2019 is returned, but just a few of last year images are.

i discovered it searching just "jpg", instead than by name, and i suddenly get some result for the first time; right now while i'm writing i searched again, and no result!
it's driving me mad!

in addition, unless i missed something, querying a specific drive and/or folder is pointless, because i've always got results from the whole account.

so i wonder: did search ever work?

**Comment by nike171196** [comment]
same issue here...

When listing all files via '/children" in a folder the images are present. Only when i am using the "/search" on the same folder i am not getting any results.
