### ISSUE TITLE
Missing docs on how to Create an orgContact

### ISSUE THREAD

**Issue by ericleigh007** [microsoftgraph/microsoft-graph-docs#4222]
I'm looking to have a list on SharePoint that authorized users may add to in order to get a contact setup in the Global Address List (which I've previously verified is accessible from /contacts).  
Unfortunately, this documentation lacks information on how to Create a contact, even though we have docs on updating one and deleting one.

I'm assuming POST /contacts with a JSON payload should do it.

Can we add the docs for this please?
-thanks
-e

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8eb66a5c-0028-3a06-964f-c7a82055365b
* Version Independent ID: 6d5e2f12-0ff8-977b-2765-f6bebbf73eff
* Content: [orgContact resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/orgcontact?view=graph-rest-beta)
* Content Source: [api-reference/beta/resources/orgcontact.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/orgcontact.md)
* Product: **microsoft-identity-platform**
* GitHub Login: @lleonard-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by bevand10** [comment]
:+1: Can't understand why this critical and super-useful feature has not been implemented yet?

**Comment by kevinblumenfeld** [comment]
@ericleigh007 @bevand10  I presume you guys have not been able to create new Org Contacts as of yet with Graph, correct? Regardless of documentation :-) 
Microsoft is there any sort of ETA.  Even the legacy Azure AD Graph lacks this important feature.

**Comment by Jackson-Woods** [comment]
Org Contacts will be coming to GA this quarter. It will not feature creation of organizational contacts. If you need this capability, please file a suggestion on UserVoice (microsoftgraph.uservoice.com).

**Comment by ericleigh007** [comment]
Suggestion: Mcirosoft has heard from at least two customers here that this is an important feature.  What might be nice is to have that be enough.  Why should we have to spend additional time creating a UserVoice topic when our voices should have already been heard?  Thx.

**Comment by Jackson-Woods** [comment]
@ericleigh007 Thanks for your reply. We ask you to use UserVoice because that's our forum for understanding customer requests and where it will get attention from the appropriate feature team at Microsoft. Posting feature requests as docs issues is not the best way to make your request known to the right people. 

In this case, there's already an item on UserVoice that has been declined by the development team with a suggested workaround. Please provide your feedback on that specific item: https://microsoftgraph.uservoice.com/forums/920506-microsoft-graph-feature-requests/suggestions/17617309-make-it-possible-to-create-organizational-contacts

**Comment by kevinblumenfeld** [comment]
@Jackson-Woods that issue was declined and closed in Nov 2018.
@ericleigh007 and @bevand10 would you please up-vote these two uservoice:
https://microsoftgraph.uservoice.com/forums/920506-microsoft-graph-feature-requests/suggestions/38083912-make-it-possible-to-create-organizational-contacts
and
https://microsoftgraph.uservoice.com/forums/920506-microsoft-graph-feature-requests/suggestions/38085454-make-it-possible-to-manipulate-customattributes-fo
