### ISSUE TITLE
Tenant does not have a SPO license error while making graph api call using postman

### ISSUE THREAD

**Issue by dhheeraj** [microsoftgraph/microsoft-graph-docs#4233]
Issue: 

Article:

**Comment by jthake-msft** [comment]
Can you provide more information here in the descriptoin of the issue? For instance, what Microsoft Graph request call are you making in postman? and what is the response you get. And why do you expect a SPO licensing error...

**Comment by agaonkar-cleo** [comment]
I am also facing same issue. I have an user and I am trying to update the following details.
"aboutMe":"BEST DEVELOPER TEST",
   "birthday":"1995-01-01T00:00:00Z",
   "hireDate":"2019-01-01T00:00:00Z",
   "interests":["dancing","singing"],
   "mySite":"https://www.mysite.com",
   "pastProjects":["API", "Greenhouse"],
   "responsibilities":["research", "development"],
   "schools":["KV", "MountCarmel"],
   "skills":["Quick Learning", "Dedicated"]


If I use any of the above fields is PATCH user by its ID, I get the below error:
{
  "error": {
    "code": "BadRequest",
    "message": "Tenant does not have a SPO license.",
    "innerError": {
      "request-id": "5e168552-7757-4843-b5db-fc8e10cfb458",
      "date": "2019-10-03T10:30:03"
    }
  }
}

Not sure what is causing this. Can anyone please help. I am also trying from postman.

**Comment by OlliV** [comment]
Which auth flow do you use and what's the exact API path?

**Comment by spacem** [comment]
I am getting this same issue..

The senario is that I have an active directory application and I invite a user in using thier gmail address as a guest to use that application. They create a microsoft account, login (via adal), and accept that the application can have basic access to their acccount.

Our application then tries to access graph api to create a folder for storing files in their drive account by posting to `https://graph.microsoft.com/v1.0/me/drive/root/children`

I am expecting since it is a first time user they will get a 403 error after which I will ask them to consent to reading and writing files.
(ie. `window.location.href = https://login.microsoftonline.com/common/oauth2/v2.0/authorize/${clientId}&response_type=code&redirect_uri=${redirectUri}&scope=https%3A%2F%2Fgraph.microsoft.com%2Ffiles.readwrite`)

This works fine for users coming in from a 'work' account but with a personal account I get this body returned:

```
{
 "headers": {
  "normalizedNames": {},
  "lazyUpdate": null
 },
 "status": 400,
 "statusText": "Bad Request",
 "url": "https://graph.microsoft.com/v1.0/me/drive/root/children",
 "ok": false,
 "name": "HttpErrorResponse",
 "message": "Http failure response for https://graph.microsoft.com/v1.0/me/drive/root/children: 400 Bad Request",
 "error": {
  "error": {
   "code": "BadRequest",
   "message": "Tenant does not have a SPO license.",
   "innerError": {
    "request-id": "xxxxxxxxxxxxxxxxxxxxxxxxx",
    "date": "2020-02-10T23:25:18"
   }
  }
 }
}
```

The user doesnt have a sharepoint license but I thought this api would store their files in their personal one drive account?

**Comment by OlliV** [comment]
So first of all, what I have noticed is that some auth flows require SPO (SharePoint Online) license and some don't. `/me/drive` always requires that the user has an O365 license or SPO license. Based on my empirical experience with the API the error messages don't seem distinguish between the license types and you just have to know which one is needed. Note that `/me` always points to the accounts own resources. If you wish to access something that's shared then you'll need something else in place of `/me`.

Secondly, if possible you should probably migrate from ADAL to MSAL.

Disclaimer: I don't work for Microsoft. I'm just playing around with Graph API for fun.

**Comment by deeDude** [comment]
It's sad and inexplicable how Microsoft Azure documentation is so terrible...

**Comment by frumbert** [comment]
Some user properties listed https://docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0 require sharepoint / 365; others do not. It's unclear which ones trigger this message. If you call `https://graph.microsoft.com/v1.0/users/?$select=country,displayName,givenName,surname,jobTitle,department,userPrincipalName,id,state,userType` you'll get a response, but throw in another property - `school` and it triggers the SPO licence message. Just a column describing which properties are included by what would be nice.

**Comment by schalkvanwyk** [comment]
I'm getting this error using the b2c-ms-graph sample console app after including the Birthday attribute.

**Comment by guillermodimas** [comment]
> I'm getting this error using the b2c-ms-graph sample console app after including the Birthday attribute.

Same error for the exact scenario. Anyone have a workaround?
