### ISSUE TITLE
Microsoft Graph API Groups Delta Query Never Returns @odata.DeltaLink (Infinite recursion with nextLink)

### ISSUE THREAD

**Issue by foxniver** [microsoftgraph/microsoft-graph-docs#4263]
Issue: 
While working with Microsoft Graph Explorer, I noticed that when you submit a groups delta request like https://graph.microsoft.com/beta/groups/delta, you will get a response with the @odata.nextLink available. However, when I follow the provided link, I start getting exactly the same set of groups as in the previous response with another @odata.nextLink leading to the endless recursion if I keep following the links. The expected behavior is to get @odata.deltaLink at some point but it never arrives in the responses received. I have 63 groups in my Azure environment.
Noticed that it tends to happen only when group members are included.
Tried excluding members from the query by sending https://graph.microsoft.com/v1.0/groups/delta?$select=displayName. In this case, I get @odata.deltaLink on the second page after following @odada.nextLink once.

**Comment by darrelmiller** [comment]
Hey @foxniver I just tried to repro this on my own tenant with Graph Explorer and I was not able to repro it.   
 I got a page with a skiptoken in the nextlink, I followed that and go no groups in the next response but I did get a deltalink. Do you have access to a different tenant that you try it on?

**Comment by foxniver** [comment]
Hi @darrelmiller. I have only one tenant. Is there anything I can provide you with to help troubleshoot the issue?

**Comment by foxniver** [comment]
@darrelmiller. I found the problem. One of the groups has 1000 members and it extended the responses over more pages than I anticipated. However, my anticipation was based on the results of non-delta query like https://graph.microsoft.com/v1.0/groups?$expand=members which returned only 20 out 1000 members for the same group. Is it common to see more members returned from the delta query? Thank you.

**Comment by Rtoribiog** [comment]
Any update on this ?  i have the same issue in my production tenant,  but not in test tenant.

**Comment by darrelmiller** [comment]
@Rtoribiog Could you open this as an issue on Stack Overflow?  This issue on the docs repo will not get the correct people viewing it to get an answer.  Thanks.

**Comment by Rtoribiog** [comment]
the issue is already posted in github and nobody answered  @darrelmiller .

https://stackoverflow.com/questions/55379873/microsoft-graph-api-groups-delta-query-never-returns-delta-query-infiinite-loop

Microsoft does not state to post issues with their code here, but issues with your own code. The format on StackOverflow is to ask a specific question, with details about what you've tried so far. – Webber Mar 27 at 14:52

 @jthake-msft  where i can address this issue ?

**Comment by nheimann1** [comment]
I have also encountered this issue.
I'm using the Delta API for groups. I create one delta request per group (I'm not tracking all groups, only specific ones).

I'm working against the same tenant while developing for few weeks with the delta response. Besides once, it always worked almost as expected. When I made a delta request I got the nextLink, I followed it until I got the deltaLink.
I'm saying it almost work as expected, because a lot of times, after the first/two responses with data, I got most of the time another 1-3 next links with no additional data.

The last time I have tried, I got around 50 responses with nextLinks until the function timeout, all of those response besides the first few, had no data in it.

This is a testing environment with around 30 users on the group.  

I have used 
 `https://graph.microsoft.com/v1.0/groups/delta?$select=id,displayName,members&$filter=id eq 'groupId'`

In the infinite loop those are the kind of responses I get


`{'id': '402-xxx-ee0', 'status': 200, 'headers': {'Preference-Applied': 'odata.track-changes', 'Cache-Control': 'no-cache', 'OData-Version': '4.0', 'Content-Type': 'application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false;charset=utf-8'}, 'body': {'@odata.context': 'https://graph.microsoft.com/v1.0/$metadata#groups', '@odata.nextLink': 'https://graph.microsoft.com/v1.0/groups/delta?$skiptoken=5ZZ_<long_token>_OXWrtiE', 'value': []}}`

As you can see their is no data in the value, but still I get nextLink
When I'm following this next link I'm getting

`{'id': '402-xxx-ee0', 'status': 200, 'headers': {'Preference-Applied': 'odata.track-changes', 'Cache-Control': 'no-cache', 'OData-Version': '4.0', 'Content-Type': 'application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false;charset=utf-8'}, 'body': {'@odata.context': 'https://graph.microsoft.com/v1.0/$metadata#groups', '@odata.nextLink': 'https://graph.microsoft.com/v1.0/groups/delta?$skiptoken=5ZZ_<long_token>_DNF5rRE0', 'value': []}}]}`

As you can see, another response, with another next link (a different one) which again return empty value. 

This happens again an again until my function timed out.

I'm expecting to get the deltaLink before at the first response with no more data, or at the maximum at the first empty response.
