### ISSUE TITLE
Graph Call

### ISSUE THREAD

**Issue by EthanCo81** [microsoftgraph/microsoft-graph-docs#4338]
On step 5, Are Authorization and Host both required headers? If so, Is Bearer a required part of the header value? If that could be clarified on this page, I would greatly appreciate it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38b3d5e6-46bc-11d2-214f-b9c4fa29c326
* Version Independent ID: ad6dd1cd-c08f-f447-ffd3-7a3473f169fb
* Content: [Get access without a user - Microsoft Graph](https://docs.microsoft.com/en-us/graph/auth-v2-service)
* Content Source: [concepts/auth-v2-service.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/auth-v2-service.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @Jackson-Woods
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Jackson-Woods** [comment]
Thanks, we'll clarify the doc. Authorization header is definitely required.

**Comment by c-mmachado** [comment]
When I call https://graph.microsoft.com/v1.0/users/b02cf73b-849e-4b54-9dfa-b36e5f12e08b/drive/list using a token returned by the app authentication (using app deamon with client_id and secret) I always receive this anwser:
{
"error": {
"code": "serviceNotAvailable",
"message": "Service unavailable",
"innerError": {
"request-id": "bb3aab7a-83d4-43c2-b4a7-a8b3141d7bd4",
"date": "2020-01-10T12:21:16"
}
}
}

but for Graph Explorer I have on Ok response.

Can you explain to me the reason, Please

**Comment by Farishta** [comment]
I am having exactly the same issue when I try to access any of my SharePoint site using the app permissions. However, I can retrieve the users using the app permission without any issue.

I have all the required permissions and I verified the access token content that shows 
"roles": [
    "Sites.Read.All",
    "Sites.ReadWrite.All",
    "Sites.Manage.All",
    "Files.ReadWrite.All",
    "Directory.Read.All",
    "User.Read.All",
    "Files.Read.All",
    "Group.Selected"
  ],

On Graph Explorer, it is working fine since it uses Delegated permissions.

Any ideas? any one?

**Comment by FaithOmbongi** [comment]
Thank you @EthanCo81 for raising your issue. I see from the docs that this has since been resolved.

Hello @c-mmachado , @Farishta: Unfortunately this forum isn't monitored for functionality issues, but questions like this are monitored at [Microsoft Support](https://docs.microsoft.com/en-us/answers/products/m365#microsoft-graph). Please ask your question there. 

No immediate changes identified for the page. Closing this issue.
