### ISSUE TITLE
Incorrect POST size limits

### ISSUE THREAD

**Issue by mlafleur** [microsoftgraph/microsoft-graph-docs#4345]
Currently the [Size limitations for POST pages request](https://docs.microsoft.com/en-us/graph/onenote-images-files#size-limitations-for-post-pages-requests) states:

> -  The total POST size limit is ~70 MB, including images, files, and other data. The actual limit is affected by downstream encoding, so there's no fixed byte-count limit. Requests that exceed the limit may produce unreliable results.
>
> - The limit for each data part is 25 MB, including the part headers. Data parts that exceed the limit are rejected by Microsoft Graph.

This may be the limits set by the backend API for this workload, but in practice, Graph's 4 MB request limit overrides the underlying API's limits. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e71dd9c-098b-e832-46f6-2724124302e0
* Version Independent ID: 59ed1107-9cf6-69d4-711d-aa6d5b27c527
* Content: [Add images, videos, and files to OneNote pages - Microsoft Graph](https://docs.microsoft.com/en-us/graph/onenote-images-files#size-limitations-for-post-pages-requests)
* Content Source: [concepts/onenote-images-files.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/onenote-images-files.md)
* Product: **onenote**
* Technology: **microsoft-graph**
* GitHub Login: @jewan-microsoft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by hugcar** [comment]
I'm having the exact same problem...

**Comment by bvirlet** [comment]
I have a follow-up question regarding this issue: we are using the OneNote API in our application and were planning to transition to MSGraph. This upload limit is a showstopper for us because our users upload fairly large PDFs (often larger than 4 MB) to their OneNote account.

Part of the reason we were transitioning to MSGraph was to use the more modern https://github.com/AzureAD/microsoft-authentication-library-for-objc instead of the old https://github.com/AzureAD/azure-activedirectory-library-for-objc.

I understand that we should stick to the underlying OneNote API. In that case, can we use it with the MSAL library, or do we need to revert to ADAL.

Last but not least, what is the recommended way to authenticate with the MS services. We see that ADAL is still maintained but it's not recommend in the MSGraph documentation.

Thanks!

**Comment by bvirlet** [comment]
Do you have an ETA for when this upload limit would be lifted or an endpoint provided (such as OneDrive's `createUploadSession`) to let us upload larger files to OneNote through the MSGraph API?

**Comment by bvirlet** [comment]
Hello, 
Does closing this issue means that the upload limit has been increased?
