### ISSUE TITLE
Handling S/MIME emails containing digital signature

### ISSUE THREAD

**Issue by SamShekhovtsov** [microsoftgraph/microsoft-graph-docs#4585]
Issue: 

When accessing Office 365 Outlook Email that contains digital signature (S/MIME) using Microsoft Graph API - the content of that email is re-formatted, cropped and there is always only 1 attachment: smime.p7m All actual email attachments are ignored and are impossible to retrieve.

Article:

**Comment by Laykou** [comment]
I encounter the same issue. I went through documentation and Google but I was unable to find a way how to read such S/MIME e-mail from Office 365 via Graph API and decrypt the attachments.

Could anyone please help?

**Comment by egyangel** [comment]
same here

**Comment by jasonjoh** [comment]
Microsoft Graph has no ability to decrypt encrypted email (smime.p7m indicates encryption). In order to decrypt the file, you'd need access to the recipient's SMIME certificate private key.

Assuming you have that, Graph will give you the smime.p7m file. Using an appropriate crypto library (like System.Security.Cryptography for .NET), you would decrypt that file to get the MIME content of the email.
