### ISSUE TITLE
Update plannertaskdetails - If-Match header contains an invalid value

### ISSUE THREAD

**Issue by joostvdlinden** [microsoftgraph/microsoft-graph-docs#4617]
Issue: 
I am trying to update (PATCH) an existing Microsoft Planner task, to add one (1) checklist item to it. I am using Microsoft doc https://docs.microsoft.com/en-us/graph/api/plannertaskdetails-update?view=graph-rest-1.0&tabs=javascript as a reference, and I am using Postman to send the request.

This is my PATCH: https://graph.microsoft.com/v1.0/planner/tasks/n...................pYAM-DX/details

These are my headers:
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJub..........
If-Match: W/"JzEtVGFzayAgQEBAQEBAQEBAQEBAQEBARCc="

This is my body:
```
{
	"previewType": "checklist",
	"checklist": {
	"{{$guid}}":{
      "@odata.type": "microsoft.graph.plannerChecklistItem",
      "title": "Update task details",
      "isChecked": false
    	}	
	}
}
```

I am receiving this response:
```
{
    "error": {
        "code": "",
        "message": "The If-Match header contains an invalid value.",
        "innerError": {
            "request-id": "7b50a25b-7c5a-443b-9a41-1b6314be4014",
            "date": "2019-05-16T23:59:03"
        }
    }
}
```

As far as I can see, the If-Match key is built up exactly the same as how Microsoft's article used it.
I have found a somewhat similar article (https://powerusers.microsoft.com/t5/Connecting-To-Data/Custom-Connector-Graph-The-If-Match-header-must-be-specified-for/td-p/144092), but this person is filling in the If-Match value differently, and it doesn't work for me at all...

I reused the eTAG value from the response received after creating the task in the first place:
`    "@odata.etag": "W/\"JzEtVGFzayAgQEBAQEBAQEBAQEBAQEBARCc=\"",`

Does anyone have a clue what I am doing wrong here? 

Thanks in advance for all help provided!
Joost

Article:

**Comment by cookiesoldier** [comment]
Hey, i had some issues with this issue aswell.

I stumbled accross a comment on: https://stackoverflow.com/questions/52706054/graph-api-change-plan-name-patch-syntax

He mentions that if you copy and paste the e_tag value it does not work, but it is copied programatically then it works.

I tried this in postman by retrieving the task details and extracting the value to a variable in my enviroment.
Then i reference the variable in the following patch call.
Then it worked in postman

**Comment by flowt-au** [comment]
The reason is that the double quotes that are part of the etag are escaped in the JSON via `\"`
`"W/\"JzEtVGFzayAgQEBAQEBAQEBAQEBAQEBARCc=\""`
So, the string to use would then be:
`W/"JzEtVGFzayAgQEBAQEBAQEBAQEBAQEBARCc="`
When if use that "syntax" in the If-Match parameter value in MsGraph, all is well.
:-)

**Comment by ThiagoGrabe** [comment]
Even after fixing the **If-Match** as @flowt-au explained, I'm still getting a bad request just to update the task name.

> Bad Request - 400 - 415ms

> {
    "error": {
        "code": "",
        "message": "The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters. ",
        "innerError": {
            "request-id": "LONG ID",
            "date": "2019-11-29T13:32:20"
        }
    }
}

**Comment by murrah** [comment]
I have an open request here related to this: [custom connector topic](https://powerusers.microsoft.com/t5/Building-Power-Apps-Formerly/Custom-Planner-Connector-to-update-the-bucketId-on-a-task-how-to/m-p/413442/highlight/false)

I am still working on getting this fully working. One thing I did discover (from a comment somewhere else) is that you also need to specify the following in the request header in order to get any data back. This is not mentioned in the docs! Once I did that I stopped getting the error you mention above (although that might just have been a coincidence!)
`Prefer: return=representation`
So hard when there are no clear examples and the docs are wrong!
Murray
