### ISSUE TITLE
Admin Consent not reflected immediately

### ISSUE THREAD

**Issue by jayClaysys** [microsoftgraph/microsoft-graph-docs#4765]
I have created an Azure AD app and set reply url. As soon as Admin consented the app, it will take admin to the reply url (My dot net application). Where I'm using HttpClient to call Graph API. But I'm getting unauthorized, I decoded the access token and found that my permission scopes are not reflected. If i add retry logic and try 3 to 4 times it works.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38b3d5e6-46bc-11d2-214f-b9c4fa29c326
* Version Independent ID: ad6dd1cd-c08f-f447-ffd3-7a3473f169fb
* Content: [Get access without a user - Microsoft Graph](https://docs.microsoft.com/en-us/graph/auth-v2-service?view=graph-rest-1.0#feedback)
* Content Source: [concepts/auth-v2-service.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/auth-v2-service.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @Jackson-Woods
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jayClaysys** [comment]
Just to add some insights. My Azure AD application type is `Web app/API` and a Multi Tenant app.

**Comment by jayClaysys** [comment]
Any update on this issue please?

**Comment by FaithOmbongi** [comment]
Hello @jayClaysys . My apologies, this issue must have slipped through our tracking.

Are you still experiencing the challenge? I recommend you ask your question at [Microsoft Support](https://docs.microsoft.com/en-us/answers/products/m365#microsoft-graph). Unfortunately this forum is dedicated to doc issues and isn't monitored for functionality issues, but questions like this are monitored at Microsoft Support.

Closing this issue here.
