### ISSUE TITLE
The filter option is not fully supported

### ISSUE THREAD

**Issue by lypan** [microsoftgraph/microsoft-graph-docs#4781]
Issue: 
I saw in the document that 
```For more details about $filter syntax, see the OData protocol.```
But when I try the graph api based on the [OData protocol](https://docs.oasis-open.org/odata/odata/v4.0/errata03/os/complete/part2-url-conventions/odata-v4.0-errata03-os-part2-url-conventions-complete.html#_Toc453752358), only ```startswith``` work, other options such as ```endswith``` don't work.
Article:
https://docs.microsoft.com/en-us/graph/query-parameters#

**Comment by dkershaw10** [comment]
The limited support is (generally) documented in the topic that you reference.  Are there particular scenarios you have that require additional $filter options (like `endswith`)?

If you are looking for new feature support - please feel free to add suggestions in UserVoice (or vote up existing suggestions on query options) to further prioritize those items.

**Comment by lypan** [comment]
Got it. Since I try to filter the data that only belongs to the Microsoft domain.
Right now, I manually filter the data in client side, but I hope graph API can support the it since it is computed in the server side which can save resources on client.
Thanks

**Comment by FaithOmbongi** [comment]
A while since this issue was raised but to provide feedback for anyone who has the same issue:

The `endsWith` operator is supported only on **mail** and **userPrincipalName** properties and requires the advanced query parameters - the `ConsistencyLevel: eventual` header and `$count`. For example:

1. [https://graph.microsoft.com/v1.0/groups?$filter=groupTypes/any(c:c eq 'Unified') and endsWith(mail,'contoso.com')&$count=true](https://developer.microsoft.com/en-us/graph/graph-explorer?request=groups%3F%24filter%3DgroupTypes%2Fany(c%3Ac%20eq%20'Unified')%20and%20endsWith(mail%2C'contoso.com')%26%24count%3Dtrue&method=GET&version=v1.0&GraphUrl=https://graph.microsoft.com&headers=W3sibmFtZSI6IkNvbnNpc3RlbmN5TGV2ZWwiLCJ2YWx1ZSI6ImV2ZW50dWFsIn1d)
2. [https://graph.microsoft.com/v1.0/users?$filter=endsWith(userPrincipalName,'contoso.com')&$count=true](https://developer.microsoft.com/en-us/graph/graph-explorer?request=users%3F%24filter%3DendsWith(userPrincipalName%2C'contoso.com')%26%24count%3Dtrue&method=GET&version=v1.0&GraphUrl=https://graph.microsoft.com&headers=W3sibmFtZSI6IkNvbnNpc3RlbmN5TGV2ZWwiLCJ2YWx1ZSI6ImV2ZW50dWFsIn1d)
