### ISSUE TITLE
There is no C# code for this page

### ISSUE THREAD

**Issue by chanmmn** [microsoftgraph/microsoft-graph-docs#4878]
[Enter feedback here]

Is there C# code for this API?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0acbb629-4115-c63a-8c97-878f58ea612e
* Version Independent ID: fc917f4f-99bc-1ff2-a378-091dc1ea5977
* Content: [settings resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/user-settings?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/user-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/user-settings.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by dkershaw10** [comment]
@darrelmiller Is there a reason that GET user settings doesn't have a code sample?

**Comment by darrelmiller** [comment]
@dkershaw10 We only generate example code snippets if there is an example HTTP request.  This page has no example HTTP request.

**Comment by darrelmiller** [comment]
@dkershaw10  However there is on this page https://raw.githubusercontent.com/microsoftgraph/microsoft-graph-docs/master/api-reference/beta/api/user-get-settings.md and we haven't generated a snippet.  @andrueastman do you know why there is no snippet for the user-get-settings.md page?

**Comment by andrueastman** [comment]
@darrelmiller Unfortunately the example request is missing the block type annotations for apidoctor to pick up the request for snippet generation and validation. 
Ideally we would want a block type annotation that looks like this in the raw markdown before the request. 
```
<!-- {
  "blockType": "request",
  "name": "get_user_settings"
}-->```

There is currently ongoing work in Api doctor to enforce a validation rule so that all json/http code-blocks are preceded by metadata so that we don't miss such stuff elsewhere as well.

**Comment by lramosvea** [comment]
Closing as this page no longer exists.
