### ISSUE TITLE
Need SDK example in Example 1

### ISSUE THREAD

**Issue by AskYous** [microsoftgraph/microsoft-graph-docs#4905]
I see how to get `Me` from the SDK, but it doesn't show how to get a specific user by their email or id or userprinciplename. Is the only way just to `$filter` even though I know the exact id of the person? Can you please insert this into the docs?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3162dd2-cc3e-64f1-757b-ab752a6320ac
* Version Independent ID: d6551c10-ae06-eb82-c905-88ec2beb760a
* Content: [Get a user - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-get?view=graph-rest-1.0&tabs=cs)
* Content Source: [api-reference/v1.0/api/user-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-get.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by fairwater** [comment]
I was trying to figure this out - I found an example in the UserTests.cs for the library:
    var user = await client.Users[userId].Request().GetAsync();

"userId" can be either the id or the user principal name.

**Comment by darrelmiller** [comment]
@Jackson-Woods We don't insert an example because the example explicitly has this:

       

I'm not sure why that is there in the example.

**Comment by nadcraker** [comment]
I want to know how to do this too.

**Comment by FaithOmbongi** [comment]
A while since this issue was raised but to provide feedback:

I see the code snippet is already available in the source, expecting it to be surfaced soon. 

You can also use Graph Explorer to confirm your code syntax.

1. Run your HTTP query, replacing **/me** with the **/id** (For example, [/users/398164b1-5196-49dd-ada2-364b49f99b27](https://developer.microsoft.com/en-us/graph/graph-explorer?request=users%2F398164b1-5196-49dd-ada2-364b49f99b27&method=GET&version=beta&GraphUrl=https://graph.microsoft.com)) or **/userPrincipalName** (For example, [/users/testuser@contoso.com](https://developer.microsoft.com/en-us/graph/graph-explorer?request=users%2Fadmin%40contoso.com&method=GET&version=beta&GraphUrl=https://graph.microsoft.com)).
2. When you get a success response (200 code), click the **Code snippets** tab in the response area of Graph Explorer.
3. See how to configure the same request in 4 languages.
