### ISSUE TITLE
More precise examples

### ISSUE THREAD

**Issue by DaveBoehmPBSI** [microsoftgraph/microsoft-graph-docs#5015]
GET https://graph.microsoft.com/beta/financials/companies('{id}')/customers('{id}') is useful, but I get a syntax error with every attempt to adapt this to Cronus.  Could you PLEASE begin including a fully-qualified example???

Example: https://graph.microsoft.com/beta/financials/companies('CRONUS US')/customers('10000')

BTW, this doesn't work.  Why does it not work?  Who knows?  So, I start adding back curly braces, subtracting parenthesis, etc.

Why can't you just include a working example of Cronus.  I know this probably seems too simple, but I don't like having to guess at what this should look like.  In this case, I don't know whether my syntax is truly incorrect, or if your example simply doesn't work as designed.

I'm sorry if this post seems a bit terse, but I'm been trying to get your "example" to work for about 10 minutes, now.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b252bb3-498a-55be-12ca-1f2fd7abf56f
* Version Independent ID: 52d7e0a4-c94c-2875-007d-2593eab3b51a
* Content: [Get customers - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/dynamics-customer-get?view=graph-rest-beta#feedback)
* Content Source: [api-reference/beta/api/dynamics-customer-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/dynamics-customer-get.md)
* Product: **dynamics-365-business-central**
* Technology: **microsoft-graph**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jaredha** [comment]
Hi Dave, 

Great question. We can work on getting more detail into the documentation.

For this issue, the APIs in Microsoft Graph for Business Central have a little bit different syntax than the OData v4 endpoints you would set up through the Web Service page in the application. In Graph, each instance of an entity is identified by the id property (the GUID) rather than the name. So in your example, it would look something like this:

https://graph.microsoft.com/beta/financials/companies('20a3c075-49d8-466f-a0f8-8af611ee505d')/customers('653053b1-d580-4102-845f-00df29a77e1e')

Jared
