### ISSUE TITLE
How does the "skip" get its value for pagination?

### ISSUE THREAD

**Issue by AlphaTangoFoxtrot** [microsoftgraph/microsoft-graph-docs#5029]
Issue: How does the "skip" get its value for pagination?

Article: When reading through the documentation for [Paging Microsoft Graph data in your app](https://docs.microsoft.com/en-us/graph/paging) and watching the video, I learned you can paginate to the next page for emails by grabbing the link provided by the `@odata:nextLink` property. The thing is, when I GET the https://graph.microsoft.com/v1.0/me/messages endpoint, I always get 10 emails back in the JSON response but the `@odata:nextLink` property I get is https://graph.microsoft.com/v1.0/me/messages?$skip=12. Why does skip=12? Why is it not always in increments of 10?

**Comment by saeed-vayghan** [comment]
Same issue:

Initial link: https://graph.microsoft.com/v1.0/me/messages?$top=5
Next link: https://graph.microsoft.com/v1.0/me/messages?$top=5&$skip=5
Nezt link: https://graph.microsoft.com/v1.0/me/messages?$top=5&$skip=1486

What is wrong with skip?

**Comment by jthake-msft** [comment]
There is actually nothing wrong with the skip. The odata:nextLink is meant to be opaque to developers and the reason in this case it is returning 7 rather than what you may expect as 5 is because of the underlying message store. There are objects in our back end that are not message objects we return such as the folder object etc.
