### ISSUE TITLE
Upload bytes to the upload session fails IE with error XMLHttpRequest: Network Error 0x80070005, Access is denied.

### ISSUE THREAD

**Issue by sharmajnu** [microsoftgraph/microsoft-graph-docs#515]
We are trying to upload file to Office 365 groups drive using upload session. The session is created fine and while uploading to the endpoint received we get 
SCRIPT7002: XMLHttpRequest: Network Error 0x80070005, Access is denied.

The same code works fine in chrome, we are using XmlHttpRequest to send the PUT request, we also tried Jquery and angular 2 http service to send the request all results in the same error.

I can see in fiddler that the CORS preflight request to the PUT endpoint is send and returned with 200 status but IE is aborting the request and stopping the processing.

**Comment by figgsoftware** [comment]
Any update on this one? This bug is really hurting our application at our customers now.

**Comment by jthake-msft** [comment]
Due to inactivity and the fact this is an issue.


This issues lists is specifically for documentation issues, not the underlying service, sdks or samples. I will close this issue so our documentation team can focus on content issues.
The official channel for questions is StackOverflow with '[microsoft-graph](https://stackoverflow.com/questions/tagged/microsoft-graph
)' tag.
For issues, you can raise a support ticket on the Azure Portal where you registered your application. This [simple video](https://twitter.com/jthake/status/1030489336439959553) shows how to file it properly by visiting [here](https://portal.azure.com/#blade/Microsoft_Azure_Support/HelpAndSupportBlade/overview).
