### ISSUE TITLE
I just want the list of time zones supported by Microsoft API.

### ISSUE THREAD

**Issue by Ezhilarasu1330** [microsoftgraph/microsoft-graph-docs#5158]
I am trying to create an outlook calendar event from my webapp using Graph REST API. When i pass some timezones i am getting error in my response. 

If there is any list of supported list of timezones supported by Graph API which will much be better to list out those time zones in my user interface.

**Comment by jthake-msft** [comment]
@angelgolfer-ms I've seen this concern come up a few times. do we have a doc that explains this?

**Comment by angelgolfer-ms** [comment]
Hi @Ezhilarasu1330 , great question! 
In general, the _possible_ time zone string values is the ones that Windows currently supports plus an additional list that the calendar API supports. This info is currently in the [dateTimeTimeZone](https://docs.microsoft.com/en-us/graph/api/resources/datetimetimezone?view=graph-rest-1.0) topic. 

However, when setting or updating the time zone of an event start or end time, you also should take into account which time zones the user's mailbox server supports, by calling [supportedTimeZones](https://docs.microsoft.com/en-us/graph/api/outlookuser-supportedtimezones?view=graph-rest-1.0&tabs=http). This is basically because the list of possible time zones is not static and changes because governments around the world can change time zones for their countries and regions over time.

I made some doc clarifications in PR #5171  about calling the supportedTimeZones function, and including a link to the corresponding Windows topic for the time zones Windows supports. The doc updates should be live in about a day.
