### ISSUE TITLE
`ms.prod` vs `ms.service`

### ISSUE THREAD

**Issue by ificator** [microsoftgraph/microsoft-graph-docs#5164]
Issue:
According to [this docs validation reference](https://docs.microsoft.com/en-us/contribute/validation-reference/ms-prod-or-service-missing) `ms.prod` is used for on-premise products while `ms.service` is used for cloud services. Given what Graph is, it seems like Graph should therefore be using `ms.service` but instead all the docs seem to have `ms.prod`. Should they all be updated to use `ms.service`?

Article:
Pretty much all of them.

**Comment by jthake-msft** [comment]
You are referring to our use of yaml headers in our docs @ificator ?

If so, this was a loong winding road. @Lauragra  can give a clear answer on why this went this way...

**Comment by Lauragra** [comment]
The best way to explain it is that we did this for reporting purposes since some content is shared across Office applications, and we want our metadata to align. This will also help us implement future site features, such as content suggestions, that require a consistent taxonomy. Unfortunately we are limited by the fact that we can't use both ms.prod and ms.service, which would better enable us to meet our reporting and taxonomy requirements.

**Comment by ificator** [comment]
Interesting, thanks!

It sounds like you have a good argument for having it what it is so I'm ok closing this out.
