### ISSUE TITLE
Microsoft Graph API Daily Limitation

### ISSUE THREAD

**Issue by TranBaVinhSon** [microsoftgraph/microsoft-graph-docs#5177]
I'm using Microsoft Graph API for my project and My service has a lot of traffic so I want to know about the daily limitation of Microsoft Graph API? How many requests I can send to Microsoft Graph per day?  I read about `Throttling`: `Throttling is done per user per app. The threshold is 10000 requests every 10 minutes.` , but I'm not really sure about Daily Limitation API?  
``` 
10 minutes - 10000 requests 
1 day (1440 minutes) - 1440000 requests 
``` 
Is that correct?
Any advice is welcome!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8df32e5f-8ccb-0c93-28d9-02392f9c7256
* Version Independent ID: 4aadd084-fb61-e89b-f63f-3b71622636b7
* Content: [Microsoft Graph throttling guidance - Microsoft Graph](https://docs.microsoft.com/en-us/graph/throttling)
* Content Source: [concepts/throttling.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/throttling.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @piotrci
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by andrewconnell** [comment]
You can't reliably calculate limits like that because it all depends on what you're doing. Reads vs. writes, which endpoint, how expensive the query is. There's no real magic number to measure against.

IMHO, like any service, you need to test things out, work to write efficient & optimized queries (not just to avoid throttling, but to have a well-performing app). Assume you will hit throttling responses, so ensure you build good mitigation strategies into your applications.
