### ISSUE TITLE
List of Permissions 

### ISSUE THREAD

**Issue by dgancho** [microsoftgraph/microsoft-graph-docs#5305]
Permissions in this page (all types) are listed as "Not Supported", while they are supported for both Delegated and Application (Directory.Read.All and above).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c10a6bf-b0f6-37ab-6986-96a88fa74618
* Version Independent ID: 2cc62631-7aeb-d8fd-d074-4b253df340f1
* Content: [List owners - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/group-list-owners?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/group-list-owners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/group-list-owners.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by dkershaw10** [comment]
@krbain @davidmu1 Looks like we fixed these only in v1.0 but not in beta.  We should do a sweep across all the groups topics to make sure that beta is updated in line with v1.0.

@dgancho Thanks for reporting. Is there any reason you are using the beta version of this API, rather than the GA version?

**Comment by davidmu1** [comment]
Added permissions.
