### ISSUE TITLE
There is no such method IGraphServiceClient.app() in msgraph-sdk-java

### ISSUE THREAD

**Issue by demonsked** [microsoftgraph/microsoft-graph-docs#5379]
Issue:
There is no such method IGraphServiceClient.app() in [msgraph-sdk-java](https://github.com/microsoftgraph/msgraph-sdk-java)

Article:
[Create online meeting](https://docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta&tabs=java)

**Comment by baywet** [comment]
Hi @demonsked 
Thanks for reaching out and thanks for the patience.
Since the creation of your issue we have released a beta SDK for java and we have re-enabled samples generation for java. https://github.com/microsoftgraph/microsoft-graph-explorer-api/pull/364 (samples will get generated soon)
The applications method also made it to v1. 
Closing
