### ISSUE TITLE
Filter + sort on email

### ISSUE THREAD

**Issue by SGSmyth** [microsoftgraph/microsoft-graph-docs#5518]
Would be good to mention the interaction between filtering and sorting for the messages endpoint, described in https://developer.microsoft.com/en-us/office/blogs/update-to-filtering-and-sorting-rest-api/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fefc984-0dac-5531-6620-13f577ebee5f
* Version Independent ID: 92438f30-1bb9-9b45-57dc-094fdcdeecc1
* Content: [Use query parameters to customize responses - Microsoft Graph](https://docs.microsoft.com/en-us/graph/query-parameters)
* Content Source: [concepts/query-parameters.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/query-parameters.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @piotrci
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by angelgolfer-ms** [comment]
@SGSmyth , thank you for your input.
There is a [section ](https://docs.microsoft.com/en-us/graph/query-parameters#orderby-parameter) about $orderby, in the [query parameters](https://docs.microsoft.com/en-us/graph/query-parameters) article, that refers to these restrictions:

>>
When you specify $filter the server will infer a sort order for the results. If you use both $orderby and $filter, because the server always infers a sort order for the results of a $filter, the properties in the $filter must be listed first in the $orderby before any other properties, and they must be listed in the order that they appear in the $filter parameter.

In PR #5769 , I made these restrictions clearer in the "list messages" topics (v1 and beta), and in sections for both $filter and $orderby in the query parameters article.

PR #5769 should be published on the first week day next week.

Thanks again for your suggestion.
