### ISSUE TITLE
Delta Queries only work for some tenants

### ISSUE THREAD

**Issue by michelejohlbs** [microsoftgraph/microsoft-graph-docs#5572]
I have wasted a month already being chased from pillar to post by MPN Support.
We are busy developing a service to sync user profile images from Microsoft Graph to our system for clients using our SaaS platform.
The list of clients includes 200 clients and 4’000’000 Microsoft users about are affected by this.
 
Doing full sync daily from Microsoft Graph is suicide on our end and it will be murder on the Microsoft Graph infrastructure as we run these syncs globally across the globe for all our clients.
To get around us having to hammer the Graph service, we opted to run full sync once per client, store the delta token and then from that point on wards we only sync updates from the delta every 30 minutes.
 
During development, we tested this against one of our test tenants and it all went well. The full sync completes and from that point on wards we would see delta results if a user updated their profile image.
We then started testing against our primary tenant and some client tenants and very quickly found that the delta query was not returning results on updates on some tenants. This brought the entire project plan to a halt and as a result, we cannot sync profile images, forcing to stay on the current plan of over querying Graph with live queries.

**Comment by michelejohlbs** [comment]
Some further testing now and the tenant it is working on, it only works via Delve. If you upload a image via portal.office.com that actually uses graph.microsoft.com for the PUT request to upload the image, the delta does not show either.

**Comment by michelejohlbs** [comment]
I have testing subscriptions as an alternative, and I am facing the same problem. Works on 1 tenant and does not work on another, the same as Delta.

The subscriptions also has a major flaw on deletion / get as well. 
I do a GET for the subscriptions and the one I created is listed. I then DELETE the subscription, receive a proper 204 response, but it still shows up when I do the GET again.
If I try to DELETE it again a get a 404 response.

The entire delta / subscription engine has wasted days of my life so far. 

**Why is this not working?**

I want to believe in this and I want to be a voice to our 200 Microsoft clients in how great this is, but right now I have to send an email to 200 Microsoft clients and say sorry, Microsoft Graph does not work!

**Comment by michelejohlbs** [comment]
@Lauragra @piotrci @clearab @JeremyKelley @VinodRavichandran @tlenig @MIchaelMainer @finsharp @angelgolfer-ms @dipakboyed @dkershaw10 @davidmu1 @CelesteDG 

I am on my knees here....

**Comment by jthake-msft** [comment]
@michelejohlbs  could you be more specific on exactly what requests you are making (removing ids with {id})?

**Comment by mjohl** [comment]
@jthake-msft After weeks of getting nowhere quickly I had a call with escalation yesterday it turns out that photo uploads are not supported to show in deltas for updates on the user object. And the fact that it is working in some cases is actually the problem. 
I was asked to create a user voice for the feature.

https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback/suggestions/38526250-delta-returned-for-users-on-photo-update

Hopefully one day it gets added. It will be a million times better if the user object indicated if the user actually had a photo and what the version or update date of the photo is. It should then work or be supported for delta queries and subscriptions as well.

So.......what is actually lacking in the documentation is which property changes on objects, like user, will cause it to show in delta's and subscriptions.

**Comment by piotrci** [comment]
Added clarification regarding properties that are not supported in delta query.
