### ISSUE TITLE
Workbook via Application (Not Delegated) Permissions

### ISSUE THREAD

**Issue by brcolow** [microsoftgraph/microsoft-graph-docs#5705]
It seems that, according to docs and after trying to access a workbook via application permissions that *only* delegated permissions are supported on Workbooks. If that's the case how can a daemon-type application (severless, headless) access a Workbook? Is there a reason for not supporting Application Permissions or is it just a TODO that hasn't been done yet?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12e3842a-93a5-b75c-f370-f95ce50c6194
* Version Independent ID: b5f3a3f3-f954-ced6-4c9e-2368c551c2dd
* Content: [Working with Excel in Microsoft Graph - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/excel?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/excel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/excel.md)
* Product: **excel**
* Technology: **microsoft-graph**
* GitHub Login: @grangery
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by brcolow** [comment]
It seems like all that is required is to prepend the URL with whatever user you wish to delegate as. For example instead of `drives/%s/items/%s/workbook` it would be `users/%s/drives/%s/items/%s/workbook`. This will work for my purpose (authenticating with application permissions in a headless environment and being able to make changes to an Excel workbook).

**Comment by jthake-msft** [comment]
Yes you are correct. Application permissions are not supported. There are currently no plans to support this.

COuld you please add this request on uservoice here please? This helps our PMs prioritize. https://microsoftgraph.uservoice.com/forums/920506-microsoft-graph-feature-requests?category_id=359629

**Comment by igorski89** [comment]
Dear @jthake-msft @microsoftgraph

Thank you very much for the clarification. 

I must say I was unpleasantly surprised to stumble upon this after investing almost 2 days of work.

I understand various reasons why application permissions are not supported, however my expectations as a user would be to:
1) clearly outline in the [Authorisation and scopes](https://docs.microsoft.com/en-gb/graph/api/resources/excel?view=graph-rest-1.0#authorization-and-scopes) section. It is completely not evident that `Files.Read.All` / `Files.ReadWrite` are not the superset of `Files.Read.All` / `Files.ReadWrite`
2) [API call to get a session](https://docs.microsoft.com/en-gb/graph/api/resources/excel?view=graph-rest-1.0#api-call-to-get-a-session) **must** return a clear error code/message about insufficient permissions, where currently it is `AccessDenied` / `Could not obtain a WAC access token.` – almost impossible to track down the root cause.

Thank you very much in advance, please let me know if any need any further details.

**Comment by bignorm64** [comment]
I too need to be able to update a Workbook from a server side service type application that has application permissions. The application can add/delete documents that are Excel workbooks so what is the logic in preventing them from manipulating their contents?

**Comment by igorski89** [comment]
@bignorm64 I would make an assumption it's due to internal editing / collaboration model for Word/Excel/PowerPoint specifically – requires some sort of a user for live editing, tracking changes, etc., likely simply due historical reasons of underlying file formats, etc.

OneDrive, through which files are being uploaded to a folder, on the other hand, does not share the same model hence permits these actions.

Ideally, the API would automatically create a "shadow user" to transparently bridge the calls, but unfortunately that's not the case currently.

I would imagine, if it fits in your use-case, creating a dummy user in AD, then headless authenticating it on the backend to obtain the token could effectively achieve the same. Haven't tried myself 'though.

**Comment by bignorm64** [comment]
> I would imagine, if it fits in your use-case, creating a dummy user in AD, then headless authenticating it on the backend to obtain the token could effectively achieve the same. Haven't tried myself 'though.

@igorski89 that's what I am now going to have to do which is a pain as I can do everything else I need to do without that. 

It will also help with more granular permissions as the app is all or nothing but if logged on as a user individual permissions can be applied. I see there is a user voice entry for defining permissions for an application but who knows when/if that will be done.

**Comment by igorski89** [comment]
@bignorm64 I am sorry to bother you, just wanted to ask if you have found a sucessful way to authenticate on the backend through email / pass and then obtain an OAuth token? If yes, maybe you can share a code snippet?
