### ISSUE TITLE
Unable to subscribe when user email contains apostrophe

### ISSUE THREAD

**Issue by AFrankowicz** [microsoftgraph/microsoft-graph-docs#5755]
When trying to subscribe using Microsoft Graph Java SDK (version 1.6.0) I get an error:

```
{
  "error": {
    "code": "ExtensionError",
    "message": "Operation: Create; Exception: [Status Code: ServiceUnavailable; Reason: Mailbox info is stale.]",
    "innerError": {
      "request-id": "2b5bda0c-5df6-4dfc-804e-6d59eb015cf5",
      "date": "2019-09-20T08:47:59"
    }
  }
}
```

This occurs when user email contains apostrophe.

**Comment by piotrci** [comment]
Pani Alicjo,

currently we have a bug affecting the Outlook resources; when a UPN is used in the resource path, and it contains an apostrophe, we do not correctly handle that case. we recommend developers use the guid user id instead of the UPN. when using the SDK, pass the guid id instead of UPN and everything should work. let us know if you run into more problems around this.

dziekujemy!

**Comment by vanta** [comment]
Panie Piotrze,

Can you reference this bug here? Any ETA when it's fixed?

**Comment by macmaxbh** [comment]
As a heads up--this workaround is no longer necessary; you should be able to subscribe to email resources by user email address even if the address contains apostrophes. I'm working to get the workaround information removed from the docs.
