### ISSUE TITLE
Attachments

### ISSUE THREAD

**Issue by nozhT** [microsoftgraph/microsoft-graph-docs#5770]
I think it should be mentioned here that events in group calendars do not support attachments (ref: https://docs.microsoft.com/en-us/graph/api/resources/attachment).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a073f203-e931-588c-7b15-227483fe01fb
* Version Independent ID: 59982274-4dae-4c9e-fd55-414ec30c0573
* Content: [calendar resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/calendar?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/calendar.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/calendar.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by angelgolfer-ms** [comment]
@nozhT , thanks for the feedback.
Yes, the info you mentioned - events in group calendars do not support attachments - is only in the attachment resource topic right now (v1 and beta).
I can see adding that info to the [event resource topic ](https://docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-1.0) as well, since attachment is applied to events, and there's an existing list in the [event resource topic ](https://docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-1.0) that describes the API behavior differences between calendars and events for groups, and calendars and events for users.

**Comment by angelgolfer-ms** [comment]
Hi @nozhT , PR #5775 added the note to the event topic, about support for attachments in events in only user calendars. The content update should be live in the next day.
Thanks again for your input.
