### ISSUE TITLE
Documented response (200 OK) does not match actual response (204 No Content)

### ISSUE THREAD

**Issue by djswilly** [microsoftgraph/microsoft-graph-docs#5794]
Successful PATCH request returns 204 No Content response code, and does not return anything in the response body.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 997a134d-c820-9ab8-b4e0-f9c94ebfb876
* Version Independent ID: fdb8371f-9c97-769f-3bf7-882ae5a16724
* Content: [Update plannertask - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/plannertask-update?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/plannertask-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/plannertask-update.md)
* Product: **planner**
* Technology: **microsoft-graph**
* GitHub Login: @TarkanSevilmis
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by thesofakillers** [comment]
I seem to have found a solution [here](https://stackoverflow.com/a/55560688/9889508) where @TarkanSevilmis himself says that you need to specify `Prefer: return=representation` in the request header to receive the expected response as described in the documentation. Adding this parameter in the request header does indeed reproduce the expected behaviour. Now all that's missing is adding this header requirement in the documentation page, given that it is not mentioned. I believe this addresses #4586 aswell.
