### ISSUE TITLE
User fax number

### ISSUE THREAD

**Issue by AveAdam** [microsoftgraph/microsoft-graph-docs#581]
the fax number is missing in User.

**Comment by robward-ms** [comment]
Correct, the user object only has mobile and phone number. This is by design.

The contact object contains many phone numbers including business, home, mobile. The documentation is here: https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/resources/contact

However, the v1.0 version of contact does not contain a faxNumber. It has been added in the beta version of contact: https://developer.microsoft.com/en-us/graph/docs/api-reference/beta/resources/contact

The documentation changes for the contact object which adds fax numbers can be found here: https://github.com/microsoftgraph/microsoft-graph-docs/commit/daec19c0043290094b24b709ee3f751c93451e25
