### ISSUE TITLE
Create eventMessage method dosen't exist.

### ISSUE THREAD

**Issue by subhanusharma** [microsoftgraph/microsoft-graph-docs#5835]
There is no way we can create eventMessage using graph API. If we try to create using create message of Mail then it gives error as Odata type not supported 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2369710c-4fd0-81a5-85cb-9a2df36b8826
* Version Independent ID: d27b4de4-8d69-e914-6ed1-2dea91b4edb2
* Content: [eventMessage resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/eventmessage?view=graph-rest-1.0#feedback)
* Content Source: [api-reference/v1.0/resources/eventmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/eventmessage.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by christianortega123** [comment]
Is there an update on this?

**Comment by jasonjoh** [comment]
This is by design. There is no way to create an `eventMessage` by itself without an associated calendar `event`. An `eventMessage` is the invitation that's sent out to attendees for a meeting. So basically, you create an `eventMessage` as a byproduct of creating an `event` with attendees. You don't explicitly create it, the server creates it and sends it on your behalf.
