### ISSUE TITLE
Adding Rows to Tables with Formulas

### ISSUE THREAD

**Issue by deyanimay** [microsoftgraph/microsoft-graph-docs#5860]
Is there a way to add a row of data but only partially fill in the row? For example, say I have a table with 6 columns, the first 3 are input data, and the last 3 have formulas defined in excel that process the data in the first 3 columns. If I send the create row request with nothing in the body then it creates a row with blank cells in the first 3 columns and properly fills in the formulas for the other 3 columns. Unfortunately if I try to input the data for the first 3 columns only I get an error saying the number of columns doesn't match the table, and inputting blanks for those columns just results in blank cells with no formulas.

```
{} - fills in blanks for first 3 cells and correct formulas for last 3
{"values": [["a", "b", "c"]]} - gives error
{"values": [["a", "b", "c", "", "", ""]]} - makes last 3 cells blank
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa8ea6cf-6f8f-c862-ae29-699c5e0ddc0e
* Version Independent ID: 5787d91b-2b8d-3a44-e2ec-475909e682ed
* Content: [Create TableRow - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/table-post-rows?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/table-post-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/table-post-rows.md)
* Product: **excel**
* Technology: **microsoft-graph**
* GitHub Login: @lumine2008
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by aianta** [comment]
I would also benefit from this feature. 

As a temporary work around I noticed that I can in fact enter the desired formulas as the values for the rows.  This is fairly sketchy however as I have to query the #of rows in the table first so I can properly compute the formulas. 

That said, this workaround really only works for very simple formulas.

Ex: `{"values":[["4","5","=A2+B2"]]}`

which can be computed through
`"=A" + (rowIndex + 2) + "+B" + (rowIndex+2) `

Each row index retrieved through the graph API should be incremented by 2 if the table has headers or 1 if it doesn't. 

Lastly, to save anyone else the time, I initially tried making my table contain only the values I want to insert through the Graph API and then just defining formulas in the columns adjacent to the table in excel in hopes that they would compute their values once I inserted some rows. This did **not** work, when the rows got added, the formulas in the adjacent columns broke, turning into things like `=#REF!+#REF!`

**Comment by DaveZG** [comment]
Is there any update on this feature request?  Is there an ETA on when it might be available?  I have some complex formula's that I cannot enter using the work around proposed here and thus I need to only partially fill some of the cells when I add the row.  Using the Graph API is the only option I have left as using the inbuilt MS Power Automate Excel Add row step seems to have an internal timeout when the add row takes longer than 30 seconds and then I keep getting duplicate rows added because both the original and retry are actually successful in adding a row.

**Comment by DaveZG** [comment]
So reading the docs a bit more (https://docs.microsoft.com/en-us/graph/api/resources/excel?view=graph-rest-1.0) it turns out what works for me is to simply add null to each cell if you want it to leave the contents alone (saving any formulas that exist there).  The only issue now is that you still need to have all columns represented in the body of the POST request but this is workable for me.

**Comment by grangeryy** [comment]
@DaveZG Thanks for the details you provided! The work around so far is just you mentioned above. We'll open a backlog item to track how to improve on this. Thx!
