### ISSUE TITLE
Attachment in the event

### ISSUE THREAD

**Issue by lcgosi** [microsoftgraph/microsoft-graph-docs#5981]
To use the attachment I need to use ('/me/events/'+event_id+'/attachments/') or can I just use ('/me/events')?
i am using the ('/me/events/'+event_id+'/attachments/') but i dont receive the attachment, but i can find it on my sent events.

because to send an email i can do as well: ('/me/sendMail')... i dont need to create as  +event_id+'/attachments/' can i do the same way to events? ( i tried, but no sucessed)
below is my json to send email with attachment:
data = {
  "message": {
    "subject": subject,
    "body": {
      "contentType": "text",
      "content": body
    },
    "toRecipients": [
      {
        "emailAddress": {
          "address": email
        }
      }
    ],
  "attachments": [
      {
        "@odata.type": "#microsoft.graph.fileAttachment",
        "name": name,
        "contentType": mime_type,
        "contentBytes": base64_string
      }
    ],
  },
  "saveToSentItems": "true"
}

here is from my ('/me/events/'+event_id+'/attachments/')
  data = {"@odata.type": "#microsoft.graph.fileAttachment",
          "name": name,
          "contentBytes": base64_string
        }

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4156ca1c-a519-c562-8d6e-383975ce918e
* Version Independent ID: 87fbaaf5-67fa-7eac-b765-f01d06114a4a
* Content: [Create Event - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-post-events?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/user-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-post-events.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by angelgolfer-ms** [comment]
@lcgosi , thank you for your question. If your app is adding an attachment on behalf of the event organizer, then after adding the attachment, the app can do an event [update](https://docs.microsoft.com/en-us/graph/api/event-update?view=graph-rest-1.0) to "send" and update the event with the attachment for each attendee as well.

FYI I got PR #6431 to clarify this process in the "add attachment" topic for both v1 and beta; you can take a look there meanwhile. Due to the upcoming US Thanksgiving holidays, the docs may not be updated on the live site until early next week. Thanks for your patience.

**Comment by lcgosi** [comment]
Nice!
Thanks a lot for your reply.
i will take a look!
