### ISSUE TITLE
Clarification on what's needed to send proactive message

### ISSUE THREAD

**Issue by rjgmail88** [microsoftgraph/microsoft-graph-docs#6024]
[Enter feedback here]

[This document](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/bots/bot-conversations/bots-conv-proactive#obtain-necessary-user-information) says we would only need user’s _unique ID_ and _tenant ID_ to send a notification. 

[This doc](https://docs.microsoft.com/en-us/graph/teams-proactive-messaging#get-the-chat-thread-id) says we would only need to use _chatThreadId_ to send a notification. 

Which method and document to follow ? I can also see for [nodejs](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/bots/bot-conversations/bots-conv-proactive#using-nodejs) example here code is only using userId, tenantId, appId,appName and serviceUrl to send a proactive message. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c4690677-2b12-0d63-06db-45172132f540
* Version Independent ID: 129f7f1f-78c4-4e80-2eac-f0ce7619f231
* Content: [Proactive messaging using a bot in Microsoft Teams - Microsoft Graph](https://docs.microsoft.com/en-us/graph/teams-proactive-messaging)
* Content Source: [concepts/teams-proactive-messaging.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/teams-proactive-messaging.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @clearab
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by billbliss** [comment]
They both work because they are different APIs. The one that uses the user's _unique ID_ and _tenant ID_ is the Bot Framework approach, and implicitly requires the app which contains the bot to be installed for every user the bot wants to send a message to.

The approach on this page uses Graph where the _tenant ID_ is already known and defines a way to install the app if it isn't already, and it uses Azure AD user IDs as opposed to the user IDs used for bots which are obfuscated for privacy reasons.

In part, the approach on this page was created to address the shortcomings of the Bot Framework approach: what if the app/bot isn't installed? What if you don't have the User ID of the user you want to send a message to? With Graph, those problems were solved already.
