### ISSUE TITLE
Suggestions for "Known issues with Microsoft Graph"

### ISSUE THREAD

**Issue by bpcastilho** [microsoftgraph/microsoft-graph-docs#6038]
Issue:
For this documentation we have some entries with dates information of beginning and resolution, but others are structured differently.
The entries with dates might cause mislead customers to believe that might be fixed, when they are actually by design as for the User part with the "No instant access after creation".
A note clarifying that it is a design decision for performance or security reasons for example instead of the tradicional "by design".

On a design note the issues titles are almost not distinguishable from their descriptions.

Article:
[https://developer.microsoft.com/en-us/graph/docs/overview/release_notes](https://developer.microsoft.com/en-us/graph/docs/overview/release_notes)

**Comment by jthake-msft** [comment]
Thanks for the feedback and apologies for the delay. Its something we've been discussing recently actually.  We'd like to also tie this to the change log and make this more dynamic so you could show previously know issues easier.
I'd also like to see these issues show up inline with the actual operation pages so people get more awareness of this page.
It is something we are trying to prioritize after we have released the new change log capability that will be dynamically generated rather than manually created like it is now.
