### ISSUE TITLE
planner permissions

### ISSUE THREAD

**Issue by Ofer-Gal** [microsoftgraph/microsoft-graph-docs#6142]
I keep getting "Looks like you may not have the permissions for this call." what permissions could I be missing?

It will be a good idea that the graph explorer will tell me, which permissions are missing instead of telling me I don't have them. 👎 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28e8ce4e-3f18-1f9f-7ec6-0414491eb541
* Version Independent ID: b661ff9f-2d57-021b-515b-e626ad59c4b9
* Content: [Create plannerPlan - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/planner-post-plans?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/planner-post-plans.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/planner-post-plans.md)
* Product: **planner**
* Technology: **microsoft-graph**
* GitHub Login: @TarkanSevilmis
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by luisms89** [comment]
Getting the same error. I got a token as and application that have Delegate Group.ReadWrite.All permissions. I am using the group id as the owner of the Planner. But i keep getting Unauthorized: Access is denied due to invalid credentials

**Comment by TarkanSevilmis** [comment]
Permissions do not only mean scopes, but it is also user's permissions. For example, a non-member won't be able to create a plan in a group (Note that at at the time of this writing group owners and members are separate collections, and owners are not necessarily members). The second issue is unrelated, as it is a problem with the authentication token or missing authentication token instead of a permission issue.
