### ISSUE TITLE
Finding a room with delegated permissions (places API)

### ISSUE THREAD

**Issue by tobiasviehweger** [microsoftgraph/microsoft-graph-docs#6227]
Hi,

we are trying to allow our users to select a room from their tenant to book a meeting. Unfortunately, this is really hard using the Graph API, and a bit badly documented as well. 

Using /findRooms, you can only get 100 rooms, without any possibility to search for a room (maybe we are using it wrong?)

Using the following call we can actually achieve what we want: https://graph.microsoft.com/beta/places/microsoft.graph.room?$filter=startswith(displayName,'Main2') or startswith(emailAddress,'buero')

Unfortunately, Azure Portal says that the delegated permission for "Places.Read.All" requires admin consent, whereas this page says it should not require admin permissions: https://docs.microsoft.com/en-us/graph/permissions-reference#places-permissions 

Could you clarify what is correct?

Thanks! :)
Tobias

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 227ceac7-ddb7-01ff-a42b-4d71394d3a74
* Version Independent ID: 44cfac3b-3d9f-0f26-5f50-e695da0fcea7
* Content: [place resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/place?view=graph-rest-beta#feedback)
* Content Source: [api-reference/beta/resources/place.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/place.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @vrod9429
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by vrod9429** [comment]
Hi Tobias, Thanks for pointing this out. For delegate users admin consent is needed. You can request this with the Microsoft auth page or azure powershell.

**Comment by tobiasviehweger** [comment]
@vrod9429 thanks.. Is there really no way then, to search for a meeting room/place without requiring admin consent? It's usually a lot harder to get customers (esp. large ones) to agree to that..

**Comment by vrod9429** [comment]
Hey @tobiasviehweger are you looking for delegate permission or app permission? If you want access to all meeting room/places for a given tenant then the admin for that tenant would need to provide you with admin consent for app permission.

**Comment by tobiasviehweger** [comment]
Hi @vrod9429,

I'm just looking for delegate permissions. We have a simple scenario, where we want to let the user search for meeting locations, but this is turning out to be quite difficult :( 

![image](https://user-images.githubusercontent.com/2111803/71251853-bf633980-2323-11ea-80d0-8412db93c79e.png)

- /me/findRooms does only return 100 results (non-filterable, non-searchable, non-pageable)
- /places/microsoft.graph.room requires admin consent (hard to get for bigger corps)

That's my dilemma..

Thanks
Tobias

**Comment by vrod9429** [comment]
Hey @tobiasviehweger do you still need help with this?

**Comment by tobiasviehweger** [comment]
@vrod9429 Yeah.. Is there any plan to have the Place.Read.All permission not require admin consent? It feels kinda overkill to justify this to customers, to need admin permissions to select a room on the UI.

**Comment by alexandersoto** [comment]
I'd also like to add a vote for this feature, and I imagine there are many others developers in this situation. Specifically, we need a way to access all the rooms a user has access to. With delegated permissions but not requiring admin consent.

Requiring admin consent is a big ask of customers, and to the best of my knowledge this additional security is not required since `findRooms` does this for companies with < 100 rooms and only requires `User.ReadBasic.All` scope without admin consent. Some companies also already expose rooms via https://docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&tabs=http, which also does not require admin consent.

Another way to support this would be to remove the 100 room limit from the `findRooms` endpoint.

**Comment by vrod9429** [comment]
Thank you for your feedback. The product team had taken the feedback and we will work on updating our permissions.

**Comment by egrabs** [comment]
Chiming in here to add my vote. Having to choose between the `findRooms` endpoint with its 100 rooms limit and asking for the `Place.Read.All` permission which requires an admin consent is putting us in a tough spot with some of our customers.

Because rooms are already exposed both via `findRooms` and via `list users`, neither of which require admin consent, I'm a bit confused as to why the `Place.Read.All` permission _does_ require admin consent.
