### ISSUE TITLE
POST /users/{id | userPrincipalName}/mailFolders/inbox/messageRules has incrrect required scopes

### ISSUE THREAD

**Issue by Nothing4You** [microsoftgraph/microsoft-graph-docs#6239]
The endpoint /users/{id | userPrincipalName}/mailFolders/inbox/messageRules does not work for an account other than the one logged in with the permission MailboxSettings.Read.
This is likely just a documentation issue, but I wasn't able to find a working permission set from performing some testing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8037fd99-6c46-2c2d-a1f1-a0338bef4b7e
* Version Independent ID: eb1b915b-f376-82d4-ecc6-c9da3b78af89
* Content: [List rules - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/mailfolder-list-messagerules?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/mailfolder-list-messagerules.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/mailfolder-list-messagerules.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by adhill254** [comment]
Is there an update on this issue?  This issue seems to apply to all `mail` endpoints (that I can only get information for the logged-in account, regardless of permissions)

**Comment by jasonjoh** [comment]
My guess is that is by design. There is no .Shared version of the MailboxSetting scopes. Compare that with Mail.Read, which allows the app to *only* access the logged-in user's mail, and Mail.Read.Shared, which allows the app to read mail in other mailboxes that the logged-in user has access to.

**Comment by adhill254** [comment]
True, but in that case why does the endpoint exist at all?  

There is already the `/me/mailFolders/inbox/messageRules` endpoint that gets the information for the logged-in user's mail.  Why make another one that requires specifying the user if the intention is to only accept `me`?

I'm also just hoping this is unfinished functionality, because it would make my use case much easier.

**Comment by jasonjoh** [comment]
Well because /me is an alias. It really translates to /users/{logged-in-users-id}. Both forms will work.

**Comment by jasonjoh** [comment]
I'd suggest opening a feature request on [UserVoice] (https://microsoftgraph.uservoice.com/forums/920506-microsoft-graph-feature-requests) for this, as I don't think we support editing other users' rules in delegate access scenarios.

**Comment by jasonjoh** [comment]
@svpsiva this is the issue I pinged you about.

**Comment by jnixea** [comment]
From what I can tell, the only alternative is to use the Application role MailboxSettings.ReadWrite.  This is problematic since it applies to ALL mailboxes.  I cannot use this as it is overly permissive.  I need to be able to access JUST the Delegated box and any shared boxes just like Mail.ReadWrite.Shared allows me to.
