### ISSUE TITLE
User not appearing

### ISSUE THREAD

**Issue by ufeg02** [microsoftgraph/microsoft-graph-docs#6249]
When I add a User to a School I get the following error:

``` JSON
{
  "error": {
    "code": "Request_BadRequest",
    "message": "A conflicting object with one or more of the specified property values is present in the directory.",
    "innerError": {
      "request-id": "d9878c9f-4788-4ef5-83d7-919297288acd",
      "date": "2019-11-07T18:26:42"
    }
  }
}
```

Appearently the user is already added but is not visible in sds.microsoft.com and in Azure. How can I check if all went right?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88809c4b-5d28-d725-b253-ab9a8e59826d
* Version Independent ID: 271cdb3a-7026-6e94-501e-580abd4eda8f
* Content: [Add educationUser to an educationSchool - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/educationschool-post-users?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/educationschool-post-users.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/educationschool-post-users.md)
* Product: **education**
* Technology: **microsoft-graph**
* GitHub Login: @mmast-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by mlafleur** [comment]
Thank you for reporting this. I have a couple of follow up questions:

1. Was the User you're attempting to add to this School imported using School Data Sync?
2. Is this only happening one User/School or are you seeing multiple examples of this issue?

One potential solution is to make sure you're requesting the `Member.Read.Hidden` scope. It is possible for Class (Group) or School (Administrative Unit) membership to be hidden. From the permissions [documentation](https://docs.microsoft.com/en-us/graph/permissions-reference#remarks-12):

>Membership in some Office 365 groups can be hidden. This means that only the members of the group can view its members. This feature can be used to help comply with regulations that require an organization to hide group membership from outsiders (for example, an Office 365 group that represents students enrolled in a class).

**Comment by ufeg02** [comment]
I added the user by using the Graph Api: 'Add education user'

` $graph->createRequest("POST", "/education/users")`

That's working well, in Azure I can see the user is created as a teacher. Is happens with all users.

 I check your suggestions first.

**Comment by ufeg02** [comment]
In sds.microsoft.com the user is still not appearing. Also not able to find it with 'Member.Read.Hidden'...

**Comment by ufeg02** [comment]
UPDATE: If using the https://graph.microsoft.com/beta/education/schools/{school-id}/users request the users are returned... Online on sds.microsoft.com the list of teachers/students is empty.

"primaryRole": "teacher" is set.

**Comment by mlafleur** [comment]
Thank you for the additional information. I suspect SDS is filtering out this user because on or more properties are either missing or have an invalid value assigned. I will take a look and see if I can find which property or properties might be causing this behavior.

**Comment by ufeg02** [comment]
Thanks, do you have an api-response of a 100% correct user so I can also compare?

**Comment by mlafleur** [comment]
The SDS UI assumes it is only responsible for the data SDS is importing and therefore actively ignores non-SDS entities.  

The reason SDS isn't showing your User is that SDS leverages additional schema extension (`extension_fe2174665583431c953114ff7268b7b3_Education_ObjectType`) to determine the the "Object Type". In most cases, the type gets set automatically based on the endpoint the object was created through (Schools = `school`, Classes = `section`).

The `/education/users` endpoint, however, behaves differently. The Education Graph APIs does not make any distinction between User subtypes, they are all treated equally. Within SDS, however, there are a number of subtypes that it expects to see:

- `Teacher`
- `Student`
- `Parent`
- `Contact`

In order to have Users show up correctly within the SDS UI, the `Education_ObjectType` needs to be set to one of those values

Teacher Example:
```
PATCH /users/{id}
{
  "extension_fe2174665583431c953114ff7268b7b3_Education_ObjectType": "Teacher"
}
```

Student Example:
```
PATCH /users/{id}
{
  "extension_fe2174665583431c953114ff7268b7b3_Education_ObjectType": "Student"
}
```

Note that since `extension_fe2174665583431c953114ff7268b7b3_Education_ObjectType` is not surfaced from the `/education/users` endpoint, you will need to set this via the `/users` endpoint. This is also distinct from the `primaryRole` property.
