### ISSUE TITLE
Request returns HTTP 400 if no Content-Type

### ISSUE THREAD

**Issue by MicBe** [microsoftgraph/microsoft-graph-docs#6259]
Hello,

Sending that request only works if "Content-Type: application/json" is present in the header.
Shouldn't the Content-Type be optional in this case?

Here is the error I get when not setting the Content-Type:
{
    "error": {
        "code": "BadRequest",
        "message": "Unable to read JSON request payload. Please ensure Content-Type header is set and payload is of valid JSON format.",
        "innerError": {
            "request-id": "ef82330f-c448-4e72-beb5-7442f1d593d4",
            "date": "2019-11-08T21:29:49"
        }
    }
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f031d83c-aa02-de48-82dc-d6980c1f4399
* Version Independent ID: c741c55b-f20b-9786-4f00-a73ddcf95611
* Content: [group: renew - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/group-renew?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/group-renew.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/group-renew.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by tfrancois** [comment]
Hi this is of help to you, but are you setting the `"json": true` property in the request.  When this property is set the need to add the Content-Type header for a JSON-formatted body payload is not required.  If it is omitted or not included, setting the Content-Type: 'application/json' needs to me manually set and is not otherwise assumed.

See the accepted answer in the following stackoverflow thread for more info:
https://stackoverflow.com/questions/16188137/how-should-i-pass-json-data-in-the-request-payload-of-http-post-request/16194906

**Comment by MicBe** [comment]
It seems like it's been fixed.
