### ISSUE TITLE
Cannot user OData query paramter ($orderby)

### ISSUE THREAD

**Issue by dipakboyed** [microsoftgraph/microsoft-graph-docs#6345]
Issue: The documentation on the page says:
`This method supports the OData query parameters to help customize the response. `
However, if I try to use $orderby on displayName, the API fails.
Is ordering by properties such as displayName supported?

Article:  https://docs.microsoft.com/en-us/graph/api/group-list-members?view=graph-rest-1.0

**Comment by yyuank** [comment]
We don't support $orderby for group members on displayName, because a group can contain devices, users, groups and service principals, etc. Not all directory objects have displayName as a property. This should work, because they are all users: GET https://graph.microsoft.com/v1.0/users?$orderby=displayName
