### ISSUE TITLE
Delta Query - Possible Delays

### ISSUE THREAD

**Issue by fowl2** [microsoftgraph/microsoft-graph-docs#6376]
There can be a delay between when a change is made and it is available in a delta query. I've seen it take ~15 minutes in a test tenant with only 15 or so users for delta to show a group membership change for example.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac7ca25a-037d-5202-debc-92c06a2c8480
* Version Independent ID: 8ebb4dbc-76a1-00fd-e740-87eda29a40f0
* Content: [Known issues with Microsoft Graph - Microsoft Graph](https://docs.microsoft.com/en-us/graph/known-issues#delta-query)
* Content Source: [concepts/known-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/known-issues.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @MSGraphDocsvTeam
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jthake-msft** [comment]
@davidmu1 for Groups and Users Delta, how do we communicate an SLA for these APIs? I think it might be worth setting expectation here.

**Comment by baywet** [comment]
Hi @fowl2 
Thanks for pointing this lack of information in the documentation.
Unfortunately we cannot provide specific numbers to developers because these delays can vary a lot depending on a multitude of conditions.
However I authored a PR #6962 that adds information to let developers know they should expect to experience delays.
Hopefully this addresses at least partially your concerns.
This issue will be closed when the PR gets merged
