### ISSUE TITLE
Issue with Attendee tag formation using Olingo/OData

### ISSUE THREAD

**Issue by soupayand** [microsoftgraph/microsoft-graph-docs#6428]
[Enter feedback here]

Hi

I have been trying to send a create event request by forming the payload using OData library i.e. Olingo for JAVA. But I keep getting an error message stating "The property 'name' does not exist on type 'Microsoft.OutlookServices.Attendee' " 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ff7ff9f-c955-c32f-756c-59e9165f3fa3
* Version Independent ID: c181ecf0-6586-9b36-20a8-f2f1e1381397
* Content: [Create event - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/calendar-post-events?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/calendar-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/calendar-post-events.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by angelgolfer-ms** [comment]
Hi @soupayand , if you haven't found an answer to your code question yet, may I suggest you post your question on stackoverflow and tag it with "microsoftgraph" please?
The GitHub issues site is for documentation issues. If it turns out there is something lacking in the docs, I'd appreciate the information and feel free to reopen this GitHub issue. Thank you for your support!
