### ISSUE TITLE
Better communication on time frame for move from beta to production

### ISSUE THREAD

**Issue by lafe** [microsoftgraph/microsoft-graph-docs#6434]
It is great, that there is a page that lists all changes to the Graph API, but there is a page missing that gives ETAs or at least a status for the arrival of beta features in the production endpoint. There are some endpoints and properties that are in the beta endpoint for more than a year without any guidance if and when they will be production ready. For a quick eye opener, see the difference in returned properties on the `user` object between `v1.0` and `beta`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a84942d-0326-24c3-d8fa-4fbd782132b3
* Version Independent ID: 08ab36ac-6f96-920a-b4dd-07c292fbacae
* Content: [Changelog for Microsoft Graph - Microsoft Graph](https://docs.microsoft.com/en-us/graph/changelog#november-2019)
* Content Source: [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/changelog.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @MSGraphDocsvTeam
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jthake-msft** [comment]
Sorry for the delay here. 

By design, we return all properties on beta, but require $select in v1.0 to get properties. This is because we want to optimize call payload for production applications. And allow you to experiment on beta.

With regards to finding out what is coming. You can go over to https://microsoftgraph.uservoice.com/ where customers have requested features. You can sign in and folllow features that interest you and be notified when things move from in backlog to in progress to in preview to in production. We are still improving this process as there are obviously features that were not requested from customers and not on this list. Also there are features that will arrive on Microsoft Graph that are under wraps for a big reveal based on product strategy. Search Connectors was a great example of this recently and there will always be these that we don't disclose.

We have a dedicated program manager working on improving our disclosure and are actively workin go a better more querable change log that you can subscribe to based on workloads you are interested in.
