### ISSUE TITLE
C# Example 1

### ISSUE THREAD

**Issue by InfoZone** [microsoftgraph/microsoft-graph-docs#6537]
Hi, when i call example 1 i get the following error:

Code: ErrorInvalidRequest
Message: The OData request is not supported.
Inner error:
	AdditionalData:
	request-id: 75562ab5-3199-48ea-a3cb-8ee9ca38b067
	date: 2019/12/10 8:23:18 AM
ClientRequestId: 75562ab5-3199-48ea-a3cb-8ee9ca38b067

The only difference is this is done via an apllication and not in a users context. So we update the OOF status of a user 

 var status = await graphServiceClient.Users["{Users' GUID goes here}"]
                .Request()              
                .UpdateAsync(me);

I can read the users details but i cannot update it but the application has got Read and write all user mailbox settings and consent given by IT

Please help

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 743129d7-ae63-b658-2690-8f9ee2c2743d
* Version Independent ID: 04d4f30e-15cc-e4bf-ec8e-2da840ce5d9f
* Content: [Update user mailbox settings - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-update-mailboxsettings?view=graph-rest-1.0&tabs=csharp#feedback)
* Content Source: [api-reference/v1.0/api/user-update-mailboxsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-update-mailboxsettings.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by angelgolfer-ms** [comment]
@InfoZone , if you haven't found an answer to your code question yet, may I suggest you post your question on stackoverflow and tag it with "microsoftgraph" please?
The GitHub issues site is for documentation issues and few product side folks monitor questions on this site. If it turns out there is something lacking in the docs, I'd appreciate the information and feel free to reopen this GitHub issue. Thank you for your support!
