### ISSUE TITLE
Which platform for C# for Windows Desktop applications

### ISSUE THREAD

**Issue by JeremyTBradshaw** [microsoftgraph/microsoft-graph-docs#6612]
Hello,

I'm wondering if any of the existing platforms that are listed are well-suited for C# intended for Windows desktop applications.  I see .NetCore and ASP.NET, but no .Net45 or other .Net##'s.  I'm looking to do these tutorials and take what I learn to C# (which I'm learning).  Eventually this knowledge would like to find its way into some PowerShell cmdlets that I will create with C#.

Thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0733b09-b4b0-a83f-d417-32ed26c33790
* Version Independent ID: 2bc7308f-0688-d7d6-d6e9-be06b3452cb8
* Content: [Microsoft Graph tutorials - Microsoft Graph](https://docs.microsoft.com/en-us/graph/tutorials)
* Content Source: [concepts/tutorials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/tutorials.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @jasonjoh
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jasonjoh** [comment]
@JeremyTBradshaw both the ASP.NET and the UWP tutorials use the full .NET Framework. The Graph SDK itself is the same between .NET Core and .NET Framework, so that bit of it should translate over :).

I'm not sure if you're aware, but we have a preview Powershell SDK for Graph (https://github.com/microsoftgraph/msgraph-sdk-powershell) that might save you having to write your own.

**Comment by JeremyTBradshaw** [comment]
@jasonjoh Thanks for the answer, but also for the SDK reference.  I had a look and that repository is going to be a perfect learn by example of C#-written cmdlets for me.  So double thanks!
