### ISSUE TITLE
We using the microsoft graph changed event but at the outlook client calendar not changed

### ISSUE THREAD

**Issue by wzyxdwll** [microsoftgraph/microsoft-graph-docs#6657]
Issue: We using the microsoft graph changed event but at the outlook client calendar not changed

Article: We create a meeting at 2019-12-19 6:00-7:00, then we use the microsoft graph v1.0 changed this event end-time at 2019-12-19 6:00-6:30, the result tell successful, but the outlook calendar not changed, then we use the outlook create a meeting at 2019-12-19 6:30-7:00, we found it accepted by meetingroom mail

**Comment by angelgolfer-ms** [comment]
Hi @wzyxdwll , it seems you have a question about using the Microsoft Graph API to change the event time returns success but your Outlook client doesn't reflect the changed event time? Perhaps you can verify if you're looking at the same user and same calendar in Outlook? And upon verifying that, you can isolate changing the event time by trying the REST operation in Graph Explorer (rather than in your app) and verify if your Outlook client reflects the time change?

In general, this site is for reporting documentation issues. For questions about using the Microsoft Graph API in an app, you may find more help posting on stackoverflow and tagging your post with microsoftgraph.

**Comment by wzyxdwll** [comment]
@angelgolfer-ms thanke you very much,i'll try it
