### ISSUE TITLE
GET https://graph.microsoft.com/v1.0/user/{id}/planner/tasks results in 404 Not Found errror

### ISSUE THREAD

**Issue by MaartenTell** [microsoftgraph/microsoft-graph-docs#6708]
Hi, 

The request GET https://graph.microsoft.com/v1.0/user/{id}/planner/tasks results in 404 Not Found errror. For the same user (id) a calendarView, mailFolders en messages does work. Any ideas why this is? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52f60667-9c25-f040-1bb0-b214ad2d55cb
* Version Independent ID: e00d1752-cfad-d7d5-93a1-d4de96e8aa09
* Content: [List tasks - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/planneruser-list-tasks?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/planneruser-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/planneruser-list-tasks.md)
* Product: **planner**
* Technology: **microsoft-graph**
* GitHub Login: @TarkanSevilmis
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by MaartenTell** [comment]
I mean the request  GET https://graph.microsoft.com/v1.0/users/{id}/planner/tasks.

**Comment by TarkanSevilmis** [comment]
The segments look correct. This error is either due to calling with a Microsoft Account (Planner is currently not available to use with Microsoft Accounts, you need a work or school (organizational) account), or it is due the the tenant not having a SKU that includes Planner. The latter case will have an informative error message, the former will only say segment not found.
