### ISSUE TITLE
Tokens from OAuth 2.0 authorization flow don't work for SMTP

### ISSUE THREAD

**Issue by campriceaustin** [microsoftgraph/microsoft-graph-docs#6739]
When trying to send an email via smtp.live.com using an OAuth token generated via https://login.microsoftonline.com/common/oauth2/v2.0/… I receive the following error:

```
535 5.7.3 Authentication unsuccessful 
```

It works if I use an auth token obtained via the legacy flow (https://login.live.com/oauth20_authorize.srf)

I've confirmed the access token is valid (it works for Graph API calls, including the send mail call).

I've requested the following scopes:

```
['offline_access', 'User.Read', 'MailboxSettings.ReadWrite',   'Mail.Send', 'Mail.ReadWrite', 'Mail.Read', 'Mail.ReadBasic', 'Contacts.ReadWrite',   'Mail.Read.Shared', 'Mail.ReadWrite.Shared', 'Mail.Send.Shared', 'MailboxSettings.Read',   'profile', 'openid', 'email', 'Calendars.ReadWrite',   'EAS.AccessAsUser.All', 'EWS.AccessAsUser.All'];
```
 
For the legacy token (the one which works), the scopes are different:

```
['wl.emails', 'wl.offline_access', 'wl.imap']; 
```

Other things I've tried:

* Using smtp.office365.com instead of smtp.live.com
* Obtaining fresh access tokens
* Ensuring app settings/permissions are configured correctly, as per [this article](https://www.emailarchitect.net/easendmail/sdk/?ct=object_oauth_live)
* [Enable Exchange SMTP Auth](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/enable-or-disable-modern-authentication-in-exchange-online)

Note, I've posted a [question](https://stackoverflow.com/questions/59639809/outlook-365-oauth-535-5-7-3-authentication-unsuccessful) on StackOverflow for this too.

**Comment by jasonjoh** [comment]
@campriceaustin Issues in this repo should be limited to issues with the Graph documentation itself. We're not set up to provide product support here :). However, what you're seeing is expected and by design. OAuth tokens are issued with a specific "audience" in mind, and the tokens you're describing are issued for use with the Graph REST API, not the SMTP services. So when the SMTP server validates the token, it finds it isn't a token issued for it, and rejects it.

That said, I'm not sure how you would go about requesting a token for the SMTP servers through the Microsoft Identity endpoint.

**Comment by campriceaustin** [comment]
Ah, I see @jasonjoh. My apologies, and thanks for the tip.
