### ISSUE TITLE
Broken format in Calendar(Teams + isOnlineMeeting: true). Create from API 

### ISSUE THREAD

**Issue by cln-m4rie** [microsoftgraph/microsoft-graph-docs#6743]
If `"isOnlineMeeting": true` and `Body` property not set or `Body.ContentType: TEXT`, then format is broken.

correct:
```
"Body": {
    "ContentType": "HTML"
}
```
<img width="578" alt="スクリーンショット 2020-01-08 15 20 46" src="https://user-images.githubusercontent.com/16286987/71955020-77e91280-322a-11ea-9c6b-86f0a017bfe1.png">

broken:
```
"Body": {
    "ContentType": "TEXT"
}
```
or Body property not set
<img width="590" alt="スクリーンショット 2020-01-08 15 38 37" src="https://user-images.githubusercontent.com/16286987/71956025-50e01000-322d-11ea-80a8-4e64c51a721c.png">

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47a07dc2-1600-00ed-275f-8415493df511
* Version Independent ID: 87fbaaf5-67fa-7eac-b765-f01d06114a4a
* Content: [Create Event - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/user-post-events?view=graph-rest-beta&tabs=http#feedback)
* Content Source: [api-reference/beta/api/user-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/user-post-events.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by angelgolfer-ms** [comment]
@cln-m4rie , I have carefully compared events created in HTML format vs in text format, in both English and in Japanese. I think what's perceived as a broken format is mainly two issues:
(a) In the HTML meeting request/event, links are embedded. For example, the first link (https://teams.microsoft.com/l/meetup-...) is embedded in the link text "Microsoft Teams 会議に参加".

In the meeting request/event that's formatted as text, because text format doesn't support embedding links, they are displayed inline with the rest of the content.

(b) Line breaks can certainly improve the formatting of the message, now having link text and the corresponding link just displayed one after the other.

I also noticed in Outlook on the web, even if I change the setting to compose emails in text (as opposed to the default setting HTML), events I create in the Outlook user interface are still in HTML, and so I wouldn't get an event with a section for Teams calling similar to the second screen shot you showed above.

So what I can help here is validate the behavior you observed (event in text format with Teams section poorly formatted), and the docs are by design. 

If there are specific reasons you'd like to format your events in text format, and therefore would like the Teams calling information to be better formatted, I have included @Harini84 for her info. I focus on the docs, @Harini84 works on calendar and API design.

BTW, I noticed that you had first opened this issue on the general MicrosoftDocs/feedback repo, and was asked to open the issue here in the microsoftgraph/microsoft-graph-docs repo instead. I apologize for the inconvenience and extra time incurred. 

Just in case you'd like to give feedback again for Microsoft Graph in the future:

- If there is an issue with the Microsoft Graph documentation, for example, incomplete or incorrect content, please go to a specific Microsoft Graph article that you found the problem (like you have opened this GitHub issue from the "create event" article) and open a GitHub issue. GitHub issues in the microsoftgraph/microsoft-graph-docs repo are for documentation problems.

- If you have suggestions for a new feature or change in feature behavior, which can be this case, please go to [User Voice](https://microsoftgraph.uservoice.com/forums/920506-microsoft-graph-feature-requests), and either vote for a similar existing request or enter a new request there. UserVoice is a central location to let product teams track and prioritize their efforts based on community need.

- If you have questions about the API behavior, and if you have an Azure subscription, please go to the [Azure Admin Center](https://ms.portal.azure.com/#blade/Microsoft_Azure_Support/HelpAndSupportBlade/newsupportreq). Or, as a tenant administrator, you can go to the [Microsoft 365 Admin Center](https://admin.microsoft.com/).

- And lastly, if you have questions on Microsoft Graph API behavior, please go to [Stack Overflow and tag it with [microsoft-graph]](https://stackoverflow.com/questions/tagged/microsoft-graph). 

I apologize again for the complexity of feedback/question reporting. We just recently incorporated this information as part of the Microsoft Graph GitHub issues workflow, to be displayed in a dialog for better discovery.

**Comment by angelgolfer-ms** [comment]
Closing this issue, since there's no more activity.
