### ISSUE TITLE
The Filter method does not work with Transitive Groups

### ISSUE THREAD

**Issue by michaelgalyon** [microsoftgraph/microsoft-graph-docs#6746]
Issue:  When making a transitiveMemberOf  call that tries to see if a user is a member of a group or subgroups, the filter by ID command does not work if the user is a member of a subgroup.

The filter will return correctly if the user is a direct member, but not if they are a transitive member.

Example:
User is a direct member of Group 1, which has been added to Group 2.
https://graph.microsoft.com/v1.0/me/TransitiveMemberOf?$select=displayName,id&$filter=id eq '<ID of Group 1>' returns the filtered group correctly.
https://graph.microsoft.com/v1.0/me/TransitiveMemberOf?$select=displayName,id&$filter=id eq '<ID of Group 2>' returns a Request_ResourceNotFound error despite returning the group if no filter is selected.

Article:  https://docs.microsoft.com/en-us/graph/api/user-list-transitivememberof

**Comment by jthake-msft** [comment]
This issue will be closed because we do not support feedback captured directly from github new issue page. Also, this issue list is not intended for service issues, questions or service feedback.

To provide feedback on content on Microsoft Graph documentation, please scroll to the bottom of the content page to the Feedback section on docs.microsoft.com. You can create new feedback there. This gives the team the complete context of what content feedback you have.

If you have service issues and want to raise a support request. Please either:
1.  visit the **[Azure Admin Center](https://ms.portal.azure.com/#blade/Microsoft_Azure_Support/HelpAndSupportBlade/newsupportreq)** and raise a new technical support ticket; or
2. visit the **[Microsoft 365 Admin Center](https://admin.microsoft.com)** and raise a new service request in the Support menu.

If you would like to ask a question about Microsoft Graph, please visit [Stack Overflow](https://stackoverflow.com/questions/tagged/microsoft-graph) and ask your questions there using `[microsoft-graph]` tag. 

If you have suggestions or feedback on Microsoft Graph, please submit this at [Microsoft Graph Uservoice](https://microsoftgraph.uservoice.com/).
