### ISSUE TITLE
Microsoft Graph always serviceNotAvailable

### ISSUE THREAD

**Issue by c-mmachado** [microsoftgraph/microsoft-graph-docs#6774]
When I call https://graph.microsoft.com/v1.0/users/b02cf73b-849e-4b54-9dfa-b36e5f12e08b/drive/list using a token returned by the app authentication (using app deamon with client_id and secret) I always receive this anwser:
{
"error": {
"code": "serviceNotAvailable",
"message": "Service unavailable",
"innerError": {
"request-id": "bb3aab7a-83d4-43c2-b4a7-a8b3141d7bd4",
"date": "2020-01-10T12:21:16"
}
}
}

but for Graph Explorer I have on Ok response.

Can you explain to me the reason, Please

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38b3d5e6-46bc-11d2-214f-b9c4fa29c326
* Version Independent ID: ad6dd1cd-c08f-f447-ffd3-7a3473f169fb
* Content: [Get access without a user - Microsoft Graph](https://docs.microsoft.com/en-us/graph/auth-v2-service#feedback)
* Content Source: [concepts/auth-v2-service.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/auth-v2-service.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @Jackson-Woods
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by DDAndyChen** [comment]
We have the same issue too, please help.

**Comment by c-mmachado** [comment]
See the follow code:
From portal.azure.com (register app)
folder id  es el tenantID
App Id. es el clientId

URL urlObj = new URL("https://login.microsoftonline.com/"+config.tenantID+"/oauth2/v2.0/token");
HttpURLConnection httpCon = (HttpURLConnection) urlObj.openConnection();
		
String urlParameters = "" + // para la v2.0
"grant_type"+"="+"password"+"&"+ /
"scope" + "=" + "https%3A%2F%2Fgraph.microsoft.com%2F.default" +"&" +
"client_id" + "=" + config.clientId +"&" +
"client_secret" + "=" + config.clientSecret +"&" +
"username" + "=" + config.username +"&" +
"password" + "=" + config.contrasena +"&";
		
byte[] postData = urlParameters.getBytes( StandardCharsets.UTF_8 );
int postDataLength = postData.length;
		
httpCon.setRequestProperty("Content-Type", "application/x-www-form-urlencoded");
httpCon.setRequestProperty("Content-Length",String.valueOf(postDataLength));
httpCon.setRequestMethod("POST");
				
httpCon.setDoOutput(true);	 
OutputStreamWriter writer = new OutputStreamWriter(httpCon.getOutputStream());
writer.write(urlParameters);
writer.flush();

int status = httpCon.getResponseCode();

BufferedReader in = new BufferedReader(new InputStreamReader(httpCon.getInputStream()));
String inputLine;
StringBuffer content = new StringBuffer();
while ((inputLine = in.readLine()) != null) {
    content.append(inputLine);
}
in.close();
String body = getBody(content.toString());

Strin token = null;
final ObjectNode node = new ObjectMapper().readValue(body, ObjectNode.class);
if (node.has("access_token")) {
     token = node.get("access_token").asText();
} 
httpCon.disconnect();

return token;

**Comment by ChaoGuo** [comment]
@Jackson-Woods We have the same issue too, please help.

**Comment by Jackson-Woods** [comment]
@c-mmachado Graph Explorer only calls in a delegated context, so it won't help with debugging or validating app permission scenarios.

Can you add the application permission User.Read.All to your app in the Azure portal, grant admin consent, and then acquire an app-only token using Postman? When I follow this flow, the call succeeds. See here if you need more info on Graph + Postman: https://docs.microsoft.com/en-us/graph/use-postman

@JeremyKelley Is this issue known to you, or can you help? I can't repro the error using Postman.

**Comment by Farishta** [comment]
I am having exactly the same issue when I try to access any of my SharePoint site using the app permissions (for instance, https://graph.microsoft.com/v1.0/sites/root). I always get the below error response.
``` yaml
{
  "error": {
    "code": "serviceNotAvailable",
    "message": "The service is not available. Try the request again after a delay. There may be a Retry-After header.",
    "innerError": {
      "request-id": "1f34f05e-c08d-4ac5-b8df-0e9e33e0cf11",
      "date": "2020-02-21T01:12:13"
    }
  }
}
```

However, I can retrieve the user information using the app permission without any issue.

I have all the required permissions and I verified the access token content (using jwt.io) that shows
``` yaml
"roles": [
"Sites.Read.All",
"Sites.ReadWrite.All",
"Sites.Manage.All",
"Files.ReadWrite.All",
"Directory.Read.All",
"User.Read.All"
],
```
On Graph Explorer, it is working fine since it uses Delegated Context.

Any ideas? anyone?

**Comment by bobbrady** [comment]
@Farishta : I have a similar problem and have  created a Stackoverflow ticket here:
https://stackoverflow.com/questions/60532096/microsoft-graph-api-servicenotavailable-error-when-getting-site-by-id

I get this only on my two free Developer O365 subscriptions.  I run the same code, with the same infrastructure on my company's licensed O365 and it works in test batch calls of 100 times each.

It seems the free  Developer O365 instances are having some issues and MSFT is throttling  people down to zero with no chance of a successful retry since it has been days since I've gotten a successful response.  I was throttled after about 50-100 requests in a 2 hour period.  The same code and app keys just suddenly started throwing 503 serviceNotAvailable errors.

**Comment by bobbrady** [comment]
Here is [another person reporting this issue on stack overflow](https://stackoverflow.com/questions/60559789/the-service-is-not-available-received-when-calling-ms-graph-api?noredirect=1&lq=1l).

**Comment by bobbrady** [comment]
My problem accessing any resource in the sites API was caused by having both the Groups.Create and Groups.ReadWrite.All permissions granted at the same time for application type access.

Removing Groups.Create allowed the all CRUD calls to be successful without serviceNotAvailable errors, even command line calls that just access sites.

Be sure to update admin grant and your token if you change the permissions for a test.

Stackoverflow User @user13034886 mentioned the permission clash in another post.

**Comment by FaithOmbongi** [comment]
Thank you everyone for raising this issue and providing feedback. Unfortunately this forum isn't monitored for functionality issues, but questions like this are monitored at [Microsoft Support](https://docs.microsoft.com/en-us/answers/products/m365#microsoft-graph). If you feel this functionality issue is still unresolved, please ask your question at [Microsoft Support](https://docs.microsoft.com/en-us/answers/products/m365#microsoft-graph). We have a team ready to help you with your code. 

No immediate change identified for the page, but the page will be updated when possible. Closing this issue for now.
