### ISSUE TITLE
"wellKnownName" not/no longer supported in the C#-API?

### ISSUE THREAD

**Issue by MVIF** [microsoftgraph/microsoft-graph-docs#6919]
Hello, I cannot see the "wellKnownName" property in the C# "MailFolder" class. Is this a bug or intended? If so: how can one identify system folders independently of localization?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ad44cdb-5d58-2689-6731-f9b1f791c33f
* Version Independent ID: 5f41b59d-994a-36d8-978f-db8a738fe10d
* Content: [List mailFolders - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-list-mailfolders?view=graph-rest-1.0&tabs=csharp#feedback)
* Content Source: [api-reference/v1.0/api/user-list-mailfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-list-mailfolders.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by MVIF** [comment]
I use:
MS.G  1.21.0
MS.G.Auth x1.0.0-preview.3
MS.G.Core x1.20.0-preview.2

Trying to downgrade to Core 1.19 and see if the effect persists.

**Comment by MVIF** [comment]
Missing in Core 1.19, too.

**Comment by jasonjoh** [comment]
@MVIF: The v1 API does not have a `wellKnownName` property on the `mailFolder` resource. This is a bug in the documentation's example response (see #4922). The doc for `mailFolder` doesn't list this in the properties table (see https://docs.microsoft.com/graph/api/resources/mailfolder?view=graph-rest-1.0#properties)

You can verify this by requesting the v1 metadata:

```
GET https://graph.microsoft.com/v1.0/$metadata
```

Here's the definition of `mailFolder`:

```xml
<EntityType Name="mailFolder" BaseType="microsoft.graph.entity">
  <Property Name="displayName" Type="Edm.String" />
  <Property Name="parentFolderId" Type="Edm.String" />
  <Property Name="childFolderCount" Type="Edm.Int32" />
  <Property Name="unreadItemCount" Type="Edm.Int32" />
  <Property Name="totalItemCount" Type="Edm.Int32" />
  <NavigationProperty Name="singleValueExtendedProperties" Type="Collection(microsoft.graph.singleValueLegacyExtendedProperty)" ContainsTarget="true" />
  <NavigationProperty Name="multiValueExtendedProperties" Type="Collection(microsoft.graph.multiValueLegacyExtendedProperty)" ContainsTarget="true" />
  <NavigationProperty Name="messages" Type="Collection(microsoft.graph.message)" ContainsTarget="true" />
  <NavigationProperty Name="messageRules" Type="Collection(microsoft.graph.messageRule)" ContainsTarget="true" />
  <NavigationProperty Name="childFolders" Type="Collection(microsoft.graph.mailFolder)" ContainsTarget="true" />
</EntityType>
```

The SDK doesn't have this property because it doesn't exist in the API :). The `wellKnownName` property does exist in the beta API, and the [beta SDK](https://www.nuget.org/packages/Microsoft.Graph.Beta/0.12.0-preview) does define this property.

**Comment by MVIF** [comment]
Thank you for this info.

Still, I would like to ask again: how can one identify system folders independently of localization variations in the "displayName" then; if at all?

**Comment by jasonjoh** [comment]
There isn't an easy way in v1. You can use the wellKnownName values in GET URLs like:

```
GET /me/mailfolders/inbox
```

Theoretically you could do that to build a list of folder IDs that correspond and manage it yourself. That's why they've added it to beta, to make it easier. I'm not sure if they will promote that to v1 (it would be nice!)

**Comment by MVIF** [comment]
OK, fingers crossed then   ;)  

Thank you very much.
