### ISSUE TITLE
Cloning a team results in two 'Wiki' tabs

### ISSUE THREAD

**Issue by alexc-MSFT** [microsoftgraph/microsoft-graph-docs#6922]
Cloning a team results in two 'Wiki' tabs in each cloned channel. 

One of the tabs is configured, the other one is not.

The source team has only one Wiki tab.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8770dbec-d5f8-6737-ddf6-da50a7892657
* Version Independent ID: 93752ea2-470d-0226-2928-439d71fe711b
* Content: [Clone a team - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/team-clone?view=graph-rest-beta#feedback)
* Content Source: [api-reference/beta/api/team-clone.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/team-clone.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by soidevinc** [comment]
I've also noticed this and because of the inconsistency in which it takes place had to write a flow that looks for duplicate wiki tabs then runs the delete tab. I've also noticed that tabs that were configured in the base team I am cloning from do not carry over in a "ready for setup" as documented, but i am forced to click the + button in order for them to appear then i cancel out of the add a tab and they are ready for setup.

**Comment by dbaldacchino** [comment]
I can confirm this is still happening.

**Comment by alexc-MSFT** [comment]
Has there been any updates on this one please? I have recently released along with the MS Teams product group, a solution to request/provision teams and this is causing our customers issues. Thanks

**Comment by spotnick** [comment]
I encounter the same error. Is there a solution already present?

**Comment by Prasad-MSFT** [comment]
The issue seems to be fixed now. After cloning a team using Graph API, now it doesn't create two 'Wiki' tabs.
