### ISSUE TITLE
Is this graph API fully supported?

### ISSUE THREAD

**Issue by chriszohno** [microsoftgraph/microsoft-graph-docs#7042]
This one works: POST /me/mailFolders/inbox/messageRules
This one does not work: POST /users/{id | userPrincipalName}/mailFolders/inbox/messageRules
When creating a rule for a different user, the api returned 403 : Forbidden

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ace596d-332b-508d-d862-b214c0a88c36
* Version Independent ID: 65ac6e68-21e4-4b4a-d357-85dada00cbb2
* Content: [Create rule - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/mailfolder-post-messagerules?view=graph-rest-1.0&tabs=java)
* Content Source: [api-reference/v1.0/api/mailfolder-post-messagerules.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/mailfolder-post-messagerules.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by dcegress** [comment]
I also am having this issue, is there a fix or workaround?

**Comment by Jimmy062006** [comment]
I'm not able to list rules from other users either even with the below.

![image](https://user-images.githubusercontent.com/4639349/84898487-40b34300-b09f-11ea-8135-76ce197a2ca3.png)

Just getting a list is Denied

**Comment by jasonjoh** [comment]
You cannot read other user's rules using Graph if you are using a user token. The scope `MailboxSettings.ReadWrite` only gives access to the logged on user's mailbox settings.

If you use app-only permissions, then the `MailboxSettings.Read` or `MailboxSettings.ReadWrite` permissions will allow you to access the settings for *all* mailboxes in the tenant.

@Jimmy062006 your issue is that you've assigned the permission in the "Exchange" API, not Graph.
