### ISSUE TITLE
Policies endpoint does not exist anymore

### ISSUE THREAD

**Issue by MrTantum** [microsoftgraph/microsoft-graph-docs#7261]
The endpoint `https://graph.microsoft.com/beta/policies` does not seem to exist anymore. It returns the following error in graph explorer:

```
{
    "error": {
        "code": "Request_InvalidRequestUrl",
        "message": "Request url was invalid. The request should be like /tenantdomainname/Entity or /$metadata. Tenant domain name can be any of the verified, unverified domain names or context id.",
        "innerError": {
            "request-id": "35daa30c-df92-49d2-b0be-277f8fa13471",
            "date": "2020-03-03T13:49:25"
        }
    }
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14d632e7-1811-aaaf-89ca-0184b334997b
* Version Independent ID: bd3f530e-5746-94c3-6a6f-ededd46b5773
* Content: [List Policies - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/policy-list?view=graph-rest-beta)
* Content Source: [api-reference/beta/api/policy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/policy-list.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @davidmu1
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by ZachEdwards7** [comment]
@MrTantum there was a breaking change to this policy in September 2019. This documentation needs to be updated -- but in the meantime please see this page: https://developer.microsoft.com/en-us/identity/blogs/breaking-changes-policy-api-microsoft-graph-beta/

**Comment by MrTantum** [comment]
Thank you for the info.

Unfortunately none of these policies seems to contain the setting we loaded from this endpoint in the past. We are looking for the policy **B2BManagementPolicy**.

See old examples (which now don't work anymore):

https://tantumpoint.wordpress.com/2019/02/11/ms-graph-get-external-collaboration-settings/
https://github.com/MicrosoftDocs/azure-docs.de-de/blob/master/articles/active-directory/b2b/one-time-passcode.md

The policy returned the settings from this page in the Azure AD:

![image](https://user-images.githubusercontent.com/31658807/75981258-6ba8cb00-5ee4-11ea-8a79-8a16dfd38971.png)

This was the only way to determine these settings in the graph.

I tried the list operations for 

- tokenLifetimePolicies
- featureRolloutPolicy
- groupLifecyclePolicy
- trustFrameworkPolicy

but the results where all empty.

**Comment by dkershaw10** [comment]
@MrTantum Sorry about this.  In this transition, this is a policy we missed (partly because these policies are not typed and are generic, so they are hard to discover).  While we work on fixing this by adding a new policy type for this, are you able to use AzureAD Preview PowerShell (you'll need the latest module)?  That should still be working.

**Comment by MrTantum** [comment]
Thanks for the feedback! Would be fantastic if you could update this thread again when the policy is available in the graph beta.

No we can't switch to PowerShell because the policy check is needed in multiple web applications. Therefore we need the graph endpoint. We currently have some workarounds but they aren't very nice (e.g. checking the exception text if the guest invite is disabled at all / if the domain is blocked).

I'm very happy with the fast feedback for this! Normally unlike SharePoint and MS Teams graph topics getting feedback for Azure AD graph topics is nearly impossible.

**Comment by dkershaw10** [comment]
@MrTantum Sorry about your experiences here.  We'll try and do better.  Yes - I'll update the thread when I get some more information, and when this policy is available (again) in beta.

**Comment by MrTantum** [comment]
Another point:

Can you already guess which permissions will be needed for the new endpoint?

The current range of application permissions used for the reading the different policies (tokenLifetimePolicies, featureRolloutPolicies, groupLifecyclePolicies, trustFrameworkPolicies) is quite messy:

```
Application | Not supported.
Application | Directory.Read.All or Directory.ReadWrite.All
Application | Policy.Read.All, Policy.ReadWrite.TrustFramework
Application | Policy.Read.All, Policy.ReadWrite.ApplicationConfiguration
```

Would be nice to have a hint if `Policy.Read.All` is the permission to go for the future  when reading policies or we should stay with `Directory.Read.All`. Updating permissions for our apps is always complex therefore we don't want to bother our customers with this too often.

**Comment by rajashekarusa** [comment]
@dkershaw10 Any update on Policy end point B2BManagementPolicy?

**Comment by dkershaw10** [comment]
@MrTantum (sorry for the delayed response).  Missed your post.
Yes - Policy.Read.All application permission **should** be able to read all policy types.  I say should, because in general this is fine.  However there could be some policies that we may decide contain extremely privileged information, such that they require their own specific/granular read permission.  We do this analysis on a case-by-case basis.  I'll look through the docs as there could be some errors.  For groupLifecyclePolicy - this is an older policy that we'll want to retrofit for more least privileged  permissions to ensure it supports  Policy.Read.All and Policy.ReadWrite.{policyType} for writes.  That's the pattern we want to adopt.  I hope this helps.

@rajashekarusa It's still PowerShell only I'm afraid.  The good news is that the team is working on releasing a new policy type.  We hope to get that released soon.  Please follow the [Microsoft Graph changelog](https://docs.microsoft.com/en-us/graph/changelog) (because I'll inevitably forget to post back to this thread :) )

**Comment by AlexCalu** [comment]
Hi, 
Another thing that seems impossible to setup now is this one:
https://docs.microsoft.com/en-us/azure/active-directory/manage-apps/configure-authentication-for-federated-users-portal#tutorial-for-setting-hrd-policy-on-an-application
Setting Home Realm Discovery options per registered application. How does one do that now? 
Thanks. 
Alex

**Comment by dkershaw10** [comment]
@AlexCalu Sorry for the delayed response.  You can set up HRD (in v1.0) for all applications (service principals) in the tenant.  Service Principals only recently got added to v1.0, which is why you cannot apply an HRD policy to a service principal yet.  This capability *should* be added next week.  There's a PR with the doc changes to support this.  Here's the doc for this operation: https://github.com/microsoftgraph/microsoft-graph-docs/pull/8617/files#diff-85b0bb473ef849832f77e3720661fa54

In the meantime you *could* use the same mechanism which is available and supported in /beta.

@MrTantum Sorry - but I don't have details on the B2B Management Policy API. cc: @elisolMS

**Comment by dkershaw10** [comment]
Folks - I'm closing this issue.  I think everything is addressed in existing docs and comments.  The only outstanding item is the B2B management policies.  Another team is working on that.  Please follow the Microsoft Graph changelog to see when this shows up in /beta.
