### ISSUE TITLE
Cannot Authorize when an organization in an unmanaged state

### ISSUE THREAD

**Issue by landall** [microsoftgraph/microsoft-graph-docs#7342]
I cannot authorize my app to access my onedrive and return the following error.
And I register this account by myself and cannot find anyone to claim this tenant.
What should I do to use Microsoft Graph API to handle this account?

error=invalid_client
error_description:
AADSTS650051: Using application 'OneDriveIndex(ODI)' is currently not supported for your organization ustc.edu because it is in an unmanaged state. An administrator needs to claim ownership of the company by DNS validation of ustc.edu before the application OneDriveIndex(ODI) can be provisioned.
Trace ID: eb67a2dd-0daf-4bb5-b42e-5f473e411300
Correlation ID: e292213a-167d-409c-a464-b87904bfc551
Timestamp: 2020-03-11 13:23:37Z

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28ef7a19-9ce7-7b73-8fa5-b071efacf6ba
* Version Independent ID: 03006629-3161-c4f7-355e-f94a462626e0
* Content: [Get access on behalf of a user - Microsoft Graph](https://docs.microsoft.com/en-us/graph/auth-v2-user?context=graph%2Fapi%2F1.0&view=graph-rest-1.0)
* Content Source: [concepts/auth-v2-user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/auth-v2-user.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @Jackson-Woods
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by psignoret** [comment]
Closing the loop on this old issue, in case someone comes across this in the future:

The short answer is: you can't. Some applications require permissions that only an administrator of the organization (work or school) can grant. Because there aren't any administrators in "unmanaged" tenants, these applications can't be used with these accounts until an administrator of the organization takes over the tenant and explicitly approves the app by granting admin consent.

**Comment by FaithOmbongi** [comment]
Thank you for the clear explanation @psignoret. 
@landall : For guidance for the administrator to take over the unmanaged tenant, kindly refer to this article 👉🏾  https://docs.microsoft.com/en-us/azure/active-directory/enterprise-users/domains-admin-takeover
