### ISSUE TITLE
onPremises field is not documented

### ISSUE THREAD

**Issue by williamlooney** [microsoftgraph/microsoft-graph-docs#7343]
I have received feed back from a partner who is receiving an IdentitySet as part of the CallRecord resource using the /beta endpoint and the IdentitySet includes a "onPremises" property that is not doucmented on this page 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3825d97e-dc1b-a6b7-e646-d69ba6a83578
* Version Independent ID: c4bfe768-94e2-b136-1380-6df5121d92e0
* Content: [IdentitySet - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/identityset?view=graph-rest-beta#feedback)
* Content Source: [api-reference/beta/resources/identityset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/identityset.md)
* Product: ****
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
A long time since this issue was asked but to answer it for anyone who might wish to ask the same: the identitySet property is an open type property. This allows it to have some extra properties, varying from resource to resource, beyond the three pre-defined properties (application, user, and device). This might have been the case in the API that returned the callRecords resource.
