### ISSUE TITLE
Severe delays when adding users to groups using Graph

### ISSUE THREAD

**Issue by jflieben** [microsoftgraph/microsoft-graph-docs#7374]
I'm seeing delays of up to 24 hours when using the Graph to add users to a Teams enabled O365 group. I think this should be clearly stated on this page

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30c10d6f-f836-ccc7-992d-36f1d904737e
* Version Independent ID: c2a9877d-ccf8-2829-bef0-4f813ee155ee
* Content: [Add member - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/group-post-members?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/group-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/group-post-members.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by JarbasHorst** [comment]
Hello @jflieben 

I am facing the same issue, but only when adding owners. Do you experience delay when adding owners and member?

Regards,
Jarbas

**Comment by jflieben** [comment]
@JarbasHorst both :)

**Comment by MohamedSattar** [comment]
We have the same issue, and even worse, few owners requests got dropped and never been added to the team, This lead to Teams with no owners (Orphaned Teams), Any idea or workaround?

**Comment by yyuank** [comment]
Group owners and members should be updated on Teams correctly through MS Graph. Teams gets notifications directly from MS Graph. This sounds like a service reliability issue. Please file a support case if issues like this continue.

**Comment by ashoksubedi1** [comment]
So I am creating a groups and added members to it and then add teams to it all using graph API. But not all members of the group are shown in the teams. I have to come back to teams and add members manually. That is weird. Is it because I adding about 18 users at the same time to a group using a batch call. Some teams all members load of correctly from groups and some none of them gets into the teams. i have to do manually. Help!!!!!!!!!!
