### ISSUE TITLE
Wrong permission?

### ISSUE THREAD

**Issue by guillaumemeyer** [microsoftgraph/microsoft-graph-docs#7454]
Looks like the required permission in delegated mode is "UserNotification.ReadWrite.CreatedByApp" not "Notifications.ReadWrite.CreatedByApp".
At least the "Notifications.ReadWrite.CreatedByApp" scope is not enough to execute the sample request in Graph Explorer

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c576541f-9ea9-880b-c2fb-bc96c427da51
* Version Independent ID: 568e0b9d-b625-09de-49cf-147bf6fa8b6d
* Content: [Create and send a notification - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/user-post-notifications?view=graph-rest-beta#permissions)
* Content Source: [api-reference/beta/api/user-post-notifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/user-post-notifications.md)
* Product: **notifications**
* Technology: **microsoft-graph**
* GitHub Login: @merzink
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by guillaumemeyer** [comment]
OK even with the right permissions, I still receive a 401 error in graph explorer:
``` json
{
    "error": {
        "code": "UnknownError",
        "message": "{\"Message\":\"AAD Authentication Failed\"}",
        "innerError": {
            "request-id": "ce54fd19-ff94-4ba2-91b2-db3bcc869fa1",
            "date": "2020-03-20T18:09:03"
        }
    }
}
```

**Comment by fmalothomas** [comment]
Any news ?
I get the same here using "UserNotification.ReadWrite.CreatedByApp" and "Notifications.ReadWrite.CreatedByApp".

```
{
    "error": {
        "code": "UnknownError",
        "message": "{\"Message\":\"AAD Authentication Failed\"}",
        "innerError": {
            "request-id": "210f3366-e1c5-4af9-903a-0b9465353213",
            "date": "2020-04-20T12:54:45"
        }
    }
}
```

**Comment by merzink** [comment]
Hello - To clarify, what app are you targeting with the notification through Graph Explorer? If you're using Graph Explorer and not your own app backend to send a notification, you'll be limited to sending notifications only to Microsoft published notification sample apps on Windows and Android. This is by design because the publisher of the notification has to be authorized to send a notification to the desired endpoint i.e. Graph Explorer is not authorized to send notifications to just any app, even if the signed-in user is the same. To send notifications via your own backend, the registration process outlined [here](https://docs.microsoft.com/en-us/graph/notifications-integration-e2e-overview) connects you as an application publisher with the actual target application on your chosen platform.

Let us know if my assumption above about the scenario you're trying is incorrect.

Cheers!

**Comment by fmalothomas** [comment]
Hello, I didn't change anything in the sample query body.
`https://graph.microsoft.com/beta/me/notifications`
with
```
{
  "targetHostName": "graphnotifications.sample.windows.com",
  "appNotificationId": "sampleRawNotification",
  "payload": {
    "rawContent": "Hello World!"
  },
  "targetPolicy": {
    "platformTypes": [
      "windows",
      "ios",
      "android"
    ]
  },
  "priority": "High",
  "displayTimeToLive": "60"
}
```
Thank you for your answer !

**Comment by merzink** [comment]
@fmalothomas : Thanks for the details and I've asked the team to investigate the issue. Have you also tried this sample in Graph Explorer with a MSA account or just your AAD account?
