### ISSUE TITLE
Discrepancy between Documentation and Actual JSON received

### ISSUE THREAD

**Issue by vsanganectar** [microsoftgraph/microsoft-graph-docs#7485]
The identitySet JSON representation of the resource lists applicationInstance field above but is not documented in the properties. 

Also the properties listed conversation, conversationIdentityType above are not actually received in the actual CDR JSON at all. Please clarify and correct the discrepancies

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3825d97e-dc1b-a6b7-e646-d69ba6a83578
* Version Independent ID: c4bfe768-94e2-b136-1380-6df5121d92e0
* Content: [IdentitySet - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/identityset?view=graph-rest-beta#feedback)
* Content Source: [api-reference/beta/resources/identityset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/identityset.md)
* Product: ****
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Flagging as similar to [#7373](https://github.com/microsoftgraph/microsoft-graph-docs/issues/7343).

A long time since this issue was asked but to answer it for anyone who might wish to ask the same: the identitySet property is an open type property. This allows it to have some extra properties, varying from resource to resource, beyond the three pre-defined properties (application, user, and device). This might have been the case in the API that returned the identitySet object.
