### ISSUE TITLE
SupportedTimeZones call fails

### ISSUE THREAD

**Issue by jbiversen** [microsoftgraph/microsoft-graph-docs#7594]
When I try to execute this C# code

```
var timeZones = await graphServiceClient
	.Me
	.Outlook
	.SupportedTimeZones(TimeZoneStandard.Iana)
	.Request()
	.Top(1000)
	.GetAsync();
```

I get this error:

ServiceException: Code: BadRequest
Message: The parameter 'TimeZoneStandard=Iana' is not in scope.
Inner error:
	AdditionalData:
	request-id: b122e2b4-1922-4d54-a477-5dfdf4a18870
	date: 2020-04-03T00:58:53
ClientRequestId: b122e2b4-1922-4d54-a477-5dfdf4a18870

Looking at the request sent to MS Graph in fiddler I see that this is the GET request

https://graph.microsoft.com/v1.0/me/outlook/microsoft.graph.supportedTimeZones(timeZoneStandard=Iana)?$top=1000 

but in the documentation it says that it should be 

GET https://graph.microsoft.com/v1.0/me/outlook/supportedTimeZones(TimeZoneStandard=microsoft.graph.timeZoneStandard'Iana')

so I think there might be a problem in the C# SDK for MS Graph.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 03a09144-1c0b-7e8e-cd0f-7b8a84489b5c
* Version Independent ID: f45d8ded-bdee-3ea1-e2e5-632488c8a996
* Content: [outlookUser: supportedTimeZones - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/outlookuser-supportedtimezones?view=graph-rest-1.0&tabs=csharp)
* Content Source: [api-reference/v1.0/api/outlookuser-supportedtimezones.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/outlookuser-supportedtimezones.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by contivero** [comment]
Since a couple of days ago, this stopped working too. I wrote a more detailed description [here](https://stackoverflow.com/questions/65955685/syntax-error-at-position-57-in-timezonestandard-microsoft-graph-timezonestanda/65992752#65992752), but in any case, the idea is exactly the same as the one described by @keesschollaart81, just changing the string from `"microsoft.graph.supportedTimeZones(TimeZoneStandard=microsoft.graph.timeZoneStandard'Iana')"` to `"supportedTimeZones(TimeZoneStandard='Iana')"`.
