### ISSUE TITLE
lastPasswordChangeDateTime?

### ISSUE THREAD

**Issue by chadcarlton** [microsoftgraph/microsoft-graph-docs#7612]
Is this attribute currently in either the release or beta endpoints? I am not seeing it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71215894-d1c8-8d36-9dbb-adb35cfbc5f9
* Version Independent ID: 34e2e6e4-578a-9309-ebcf-94b640dc4e4c
* Content: [user resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0#feedback)
* Content Source: [api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/user.md)
* Product: **users**
* Technology: **microsoft-graph**
* GitHub Login: @krbain
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by abhijaykh07** [comment]
Any update on this issue ? I am facing the same. LastPasswordChangeDateTime value not returning.
The only option I am seeing to fetch this value via running powershell scripts.
Please reply to the earliest @krbain

**Comment by rkaw92** [comment]
Hi, I'm having an issue where this property is not documented as read-only, but any write attempt via PATCH results in:
```
Error: Property 'lastPasswordChangeDateTime' is read-only and cannot be set.
```

**Comment by davidmu1** [comment]
This seems to have been documented since the issue was submitted. This is the definition currently on the resource page:


lastPasswordChangeDateTime | DateTimeOffset | The time when this Azure AD user last changed their password. The date and time information uses ISO 8601 format and is always in UTC time. For example, midnight UTC on Jan 1, 2014 would look like this: '2014-01-01T00:00:00Z'

Here is the result when I run this call: https://graph.microsoft.com/beta/me?$select=lastPasswordChangeDateTime

{
    "@odata.context": "https://graph.microsoft.com/beta/$metadata#users(lastPasswordChangeDateTime)/$entity",
    "lastPasswordChangeDateTime": "2020-09-01T16:52:06Z"
}

No change identified for this page. Closing the issue.
