### ISSUE TITLE
create an "invitedusermessageinfo" object with powershell?

### ISSUE THREAD

**Issue by phillkOCCM** [microsoftgraph/microsoft-graph-docs#7615]
I tried $object  = get-content message.json | convertfrom-json and its creating as a custom object? should I be looking at powershell? or anyone have any tips?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aba8d0d2-dce7-23a2-91a7-d8c6eac5627c
* Version Independent ID: 08119651-f376-243e-130c-ffc5a2fbd05d
* Content: [Configuring the invitation message - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/invitedusermessageinfo?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/invitedusermessageinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/invitedusermessageinfo.md)
* Product: ****
* Technology: **microsoft-graph**
* GitHub Login: @girish
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Hello @phillkOCCM 

Do you still need guidance on this topic? If so, I recommend posting it at the [Microsoft Support](https://docs.microsoft.com/en-us/answers/search.html?type=question&q=microsoft-graph-*) channel. I know it's been a while since you raised the issue and I apologize for directing you somewhere else at this time—but the [Microsoft Support](https://docs.microsoft.com/en-us/answers/search.html?type=question&q=microsoft-graph-*) channel is monitored for such issues and you'll get the help you need to run your code. This channel is only for documentation issues.

No immediate updates identified for the page. Closing the issue.
