### ISSUE TITLE
/groups?$filter=groupTypes/any(c:c+eq+'Unified') does not work as decribed

### ISSUE THREAD

**Issue by AspenForester** [microsoftgraph/microsoft-graph-docs#7779]
I've seen this query listed in multiple places in the Graph API documentation and reference as the way to return only unified groups, but in my experience, the filter is ignored and *all* groups are returned, regardless of whether the groupTypes collection contains "Unified" or not.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fefc984-0dac-5531-6620-13f577ebee5f
* Version Independent ID: 92438f30-1bb9-9b45-57dc-094fdcdeecc1
* Content: [Use query parameters to customize responses - Microsoft Graph](https://docs.microsoft.com/en-us/graph/query-parameters?context=graph%2Fapi%2F1.0&view=graph-rest-1.0#odata-system-query-options)
* Content Source: [concepts/query-parameters.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/query-parameters.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @baywet
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by JarbasHorst** [comment]
Hello @AspenForester 

I haven't been able to reproduce this issue using the API: https://graph.microsoft.com/v1.0/groups?$filter=groupTypes/any(c:c+eq+'Unified')&$top=999. In my case it returns only unified groups. If I remove the filter, then it returns also security groups.

Note that I have included the $top query parameter to the request in order to retrieve all groups from my dev tenant. It helped me to compare the results. Consider using https://developer.microsoft.com/en-us/graph/graph-explorer for tests.

I hope it helps!

Regards,
Jarbas

**Comment by AspenForester** [comment]
I found the problem, and it's a parsing issue.  It escaped me that: In PowerShell; when the URI string is wrapped double quotes (which is a natural thing to given that there are already single quotes in the URI);  That the dollar sign in `...?$filter...` needs to be escaped as `$filter otherwise PowerShell tries to evaluate the variable named "filter"

Testing with either PostMan or the Graph explorer will not uncover this problem.  I would suggest that a note be added to https://docs.microsoft.com/en-us/graph/query-parameters?context=graph%2Fapi%2F1.0&view=graph-rest-1.0 reminding people of the PowerShell variable evaluation behavior.  I'll be happy to open an issue on that page if that would be helpful.
