### ISSUE TITLE
Where can I get VideoTeleconferenceId from?

### ISSUE THREAD

**Issue by aldvintumbelaka** [microsoftgraph/microsoft-graph-docs#8003]
Hi, I try to create an online meetings, but the videoTeleconferenceId is always null. Therefore, I cannot do the get request because the filter can only support videoTeleconferenceId.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3dece941-e3be-086c-aa88-a0cdd44f28ec
* Version Independent ID: f6f92861-6d72-2260-2277-d963793fbce2
* Content: [Get onlineMeeting - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta&tabs=http#feedback)
* Content Source: [api-reference/beta/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/onlinemeeting-get.md)
* Product: **cloud-communications**
* Technology: **microsoft-graph**
* GitHub Login: @ananmishr
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by mRWSEI** [comment]
I have the same problems. I am unable to get meetings without videoTeleconferenceId and can't find where to find it out.

**Comment by ananmishr** [comment]
Hi @aldvintumbelaka and @mRWSEI the videoTeleconferenceId comes from the meeting room devices, which are generated for Cloud-Video-Interop licensed users.

Currently, we don't support the GET online meeting API to retrieve meeting details that weren't created with a VTC id.

If you have a need to embed an online meeting to a custom calendar, and if you specify an **external ID** to associate the online meeting with, I would recommend the [beta createOrGet online meeting](https://docs.microsoft.com/en-us/graph/api/onlinemeeting-createorget?view=graph-rest-beta&tabs=http) API. This API lets you both create and get online meetings. Since this is a beta API, I do not recommend it for production use.

**Comment by mRWSEI** [comment]
@ananmishr 
Any other method to get past meeting attendees (name,, join/left times).
Its essential for schools, universities online classess.
I have seen there's UserVoice topic with a lot of votes
https://microsoftteams.uservoice.com/forums/555103-public/suggestions/33989875-view-or-export-a-list-of-users-who-attended-a-meet

We need this feature inside API too

**Comment by Mists13** [comment]
Hi, the meetings i'm trying to retrieve have the videoTeleconferenceId ( well I know that by checking the details of the meeting on the app ). However I'm not managing to find that information through the OnlineMeeting nor the Calendar objects.
