### ISSUE TITLE
Subscribe to beta APIs?

### ISSUE THREAD

**Issue by js-securecom** [microsoftgraph/microsoft-graph-docs#8047]
is resource hard coded to https://graph.microsoft.com/v1.0/?

Can you subscribe to beta api's such as https://graph.microsoft.com/beta/me/presence? and if so how?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cbe0590e-070b-cf56-cbc7-1dcb8a266380
* Version Independent ID: 2d912536-afc5-60f1-e381-2eef892cbded
* Content: [subscription resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-1.0#feedback)
* Content Source: [api-reference/v1.0/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/subscription.md)
* Product: ****
* Technology: **microsoft-graph**
* GitHub Login: @baywet
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by baywet** [comment]
If you use the beta version to create the subscription (beta instead of v1.0 in the URL) the path will be relative to beta for the resource property. See the [beta documentation](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/subscription.md).
Subscribing to presence information is not yet supported, you can however upvote the [idea](https://microsoftgraph.uservoice.com/forums/920506-microsoft-graph-feature-requests/suggestions/39456202-teams-subscription-to-user-presence-updates) to get notified on any update.
