### ISSUE TITLE
Start Print With Universal Print From Web Application

### ISSUE THREAD

**Issue by nguyenquochungptit** [microsoftgraph/microsoft-graph-docs#8097]
Hello, I am currently developing web applications and Universal Print.
I have successfully performed 3 steps: **create print job**, **upload Data** and **start Job** on a printer that is registered Universal Print with PrinterConnector.
The printer has also met the conditions like Shared, ... but we do not see the job done on a physical printer.
Please ask what we need to do to print the document.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 314b19af-9c9e-4f82-83d1-eb2261d9c108
* Version Independent ID: 08f4d779-585c-45a7-339b-45e364ac0400
* Content: [Universal Print cloud printing API overview - Microsoft Graph](https://docs.microsoft.com/en-us/graph/universal-print-concept-overview#feedback)
* Content Source: [concepts/universal-print-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/universal-print-concept-overview.md)
* Product: **universal-print**
* Technology: **microsoft-graph**
* GitHub Login: @braedenp-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by braedenp-msft** [comment]
Hi, glad to hear you're making progress on your issue! We want to help get you up and running, but the right people to answer your question won't see it in the documentation.

If you have a support plan with Microsoft please create a support ticket with this question. Otherwise, post on the [Universal Print Community](https://aka.ms/upcommunity) where someone will help you quickly resolve your issue.
