### ISSUE TITLE
Getting error even when archive/unarchive is successful

### ISSUE THREAD

**Issue by michta42** [microsoftgraph/microsoft-graph-docs#8134]
The error I get is
404 -- Not Found: No team found with Group Id {GUID}.

The strange this is that with Fiddler I get an Unknown error after calling either endpoint, but in my app I get the 404 with reference to the Group Id. Both operations work, however, so I'll just ignore the error for now.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a20088f1-c784-991b-952d-238b1b74fba5
* Version Independent ID: 5b72dce5-7cea-d2fd-327e-dd1d8860ccd8
* Content: [Archive team - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/team-archive?view=graph-rest-1.0#feedback)
* Content Source: [api-reference/v1.0/api/team-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/team-archive.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by HunaidHanfee-MSFT** [comment]
Hey, We tried doing this and faced no issue. It worked properly and got 202 on successful archival of Team. Can you please share the response so that we can investigate what's going wrong in your case.

Please make sure that group Id is correct, you can get from 
![image](https://user-images.githubusercontent.com/64194049/130050770-9b16005c-0da5-4836-bbfa-83583f65e320.png)

Just copy the part after group-Id:
teams.microsoft.com/l/team/19%0000W5r9m9c4NI_N6q2TyuRSAFs-000SJmAF3pn9E0%40thread.tacv2/conversations?groupId=**c7000076-0ef8-4ca6-ace9-29a000092420**&tenantId=c0000afd-64ac-4008-8e05-12fe00ba000090

**Comment by Wajeed-msft** [comment]
Please re-open if you are still facing this issue.
