### ISSUE TITLE
appliesTo for servicePlans

### ISSUE THREAD

**Issue by GvYK** [microsoftgraph/microsoft-graph-docs#8138]
When retrieving "appliesTo" for servicePlans, the result seems to be different between "subscribedSkus" and "licenseDetails".

* subscribedSkus
  https://docs.microsoft.com/en-us/graph/api/subscribedsku-list?view=graph-rest-1.0&tabs=http

  * For example, "appliesTo" of "SWAY" returns "User".

* licenseDetails of a user
  https://docs.microsoft.com/en-us/graph/api/user-list-licensedetails?view=graph-rest-1.0&tabs=http

  * For example, "appliesTo" of "SWAY" returns "Company".
  * By the way,  user-based licensing is done.

Could you tell me the reason "appliesTo" is different between "subscribedSkus" and "licenseDetails"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: daea34fb-b26a-6e10-535c-0bc229d8be18
* Version Independent ID: 92ebd94c-a4f3-9657-95eb-d76fab8e3f56
* Content: [List licenseDetails - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-list-licensedetails?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/user-list-licensedetails.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-list-licensedetails.md)
* Product: **users**
* Technology: **microsoft-graph**
* GitHub Login: @krbain
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by krbain** [comment]
@SumitParikh can you please take a look at this for licensing?

**Comment by SumitParikh** [comment]
subscribedSkus - provides list of SKU's subscribed in an organization. Here appliesto in service plan indicates whether the services plan is a company level or user level.

licenseDetails - provides licenses assigned to a user. this will return a licenseDetails object which should provide same appliesto vlaues for service plans. Also instead of using licenseDetails, you should use licenseAssignmentStates property on user object as this is the latest API and licenseDetails will be deprecated.

**Comment by SumitParikh** [comment]
I answered.





Thanks and Regards,
Sumit Parikh, Senior Program Manager
Microsoft Corporation
M: +1 425.241.5440

**Comment by GvYK** [comment]
Thank you for the polite explanation.
I understood the specification of subscribedSkus and licenseDetails.
Please close this issue.
