### ISSUE TITLE
question regarding to this api

### ISSUE THREAD

**Issue by OsenseTechNeo** [microsoftgraph/microsoft-graph-docs#8263]
I'm facing trouble making a phone call between two users with Graph Explorer.
I tried "https://graph.microsoft.com/v1.0/communications/calls" with 'Example 3, Create a group call with service hosted media' and changed the targets' id to two team users. However, it returned an error message of "Unsupported AAD Identity", and I'm stuck.
Any suggestion?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 776d5045-0abc-cdf9-f6c0-a2242c63ad42
* Version Independent ID: 7aa5b80a-5565-b702-20ae-8d550357980a
* Content: [Create call - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/application-post-calls?view=graph-rest-1.0&tabs=http#example-3-create-a-group-call-with-service-hosted-media)
* Content Source: [api-reference/v1.0/api/application-post-calls.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/application-post-calls.md)
* Product: **cloud-communications**
* Technology: **microsoft-graph**
* GitHub Login: @ananmishr
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by ramgesg** [comment]
Cloud Communications APIs require Application permission, Graph Explorer uses Delegated permission. In order to register an application you can follow [Register an application with the Microsoft identity platform](https://docs.microsoft.com/en-us/graph/auth-register-app-v2#register-a-new-application-using-the-azure-portal)
