### ISSUE TITLE
https://graph.microsoft.com/v1.0/me/calendars can not list my delegated calendar

### ISSUE THREAD

**Issue by ling595659851** [microsoftgraph/microsoft-graph-docs#8286]
Hi, I treid the api in the developer tool(https://developer.microsoft.com/en-us/graph/graph-explorer), and given the Calendar.ReadWrite.Shared permission. But I still cannot get the delegated calendar resources listed by using api(https://graph.microsoft.com/v1.0/me/calendars) and I notify that there is no Calendar.ReadWrite.Shared permission listed in the 'Modify permissions' tab. Is there any suggestions?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5907baa8-7825-8b17-7bbb-7e0aca7aec6e
* Version Independent ID: 82b9604e-342e-e4fd-50fa-3b79ede1895e
* Content: [Get shared or delegated Outlook calendar and its events - Microsoft Graph](https://docs.microsoft.com/en-us/graph/outlook-get-shared-events-calendars#sharee-get-shared-custom-calendar-or-its-events-from-sharees-mailbox)
* Content Source: [concepts/outlook-get-shared-events-calendars.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/outlook-get-shared-events-calendars.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by ling595659851** [comment]
Is there anyone can help to answer me?

**Comment by jasonjoh** [comment]
@ling595659851 sorry for not responding sooner. This repository isn't a good place to get support on the API - it's intended for reporting errors with the documentation. We're just not set up to respond to these kind of questions.

That being said: calendar sharing is a tricky feature. Shared calendars will only show up under /me/calendars if they have been shared with the "modern" way of sharing calendars. What I mean by that is using Outlook on the web to share:

![image](https://user-images.githubusercontent.com/8966342/83792874-b237ce00-a669-11ea-95d1-78fbcb558ef0.png)

The person you share with receives a sharing invitation in their inbox. They must accept.

![image](https://user-images.githubusercontent.com/8966342/83793007-e7442080-a669-11ea-8fc7-263ed420d596.png)

Once that's done, you'll see the shared calendar in /me/calendars. That's because this way of sharing creates a copy of the calendar in your mailbox. You access the calendar just like any other non-shared calendar: GET /me/calendars/{id}

For calendars not shared this way (maybe shared years ago, or permissions set by an admin, etc.), you have to know the calendar ID ahead of time, and you access it like:

GET /users/{calendar-owner-id}/calendars/{calendar-id}

That's as described in https://docs.microsoft.com/graph/outlook-get-shared-events-calendars#sharee-get-a-shared-calendar-or-its-events-directly-from-calendar-owners-mailbox
