### ISSUE TITLE
List AppRoleId

### ISSUE THREAD

**Issue by Freakling** [microsoftgraph/microsoft-graph-docs#8342]
I need to correlate specific permissions with their appRoleIds in order to automate my delegations.

I've tried but I can't find any way except for building the list myself (adding one permission at a time in the portal and checking the appRoleId).

Is there a possibility to do this programatically or perhaps add this information to this site?

When getting the appRoleAssignments i get a list of objects like the one below.

GET /servicePrincipals/{id}/appRoleAssignments

id                   : OWuHaF24PUi0v-7QIVwQ_6BcrR503XpFvJ-SFN_z2_8
deletedDateTime      : 
appRoleId            : 01d4889c-1287-42c6-ac1f-5d1e02578ef6
createdDateTime      : 2020-05-20T14:34:33.8609533Z
principalDisplayName : REDACTED
principalId          : REDACTED
principalType        : ServicePrincipal
resourceDisplayName  : Microsoft Graph
resourceId           : REDACTED

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05d9333e-3b22-fd5a-2bc7-9aac994778a1
* Version Independent ID: 1d92b01c-f82d-7e62-8e7e-9b9ce1b37a92
* Content: [Microsoft Graph permissions reference  - Microsoft Graph](https://docs.microsoft.com/en-us/graph/permissions-reference#feedback)
* Content Source: [concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/permissions-reference.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @Jackson-Woods
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Freakling** [comment]
found it.

Get-AzureADServicePrincipal | Where-Object AppId -Match '\w{8}-\w{4}-\w{4}-c000' | Where-Object{$_.DisplayName -eq 'Microsoft Graph'} | 
    Select-Object -expand Oauth2Permissions | 
    Select-Object Id, Value | 
    Sort-Object Value

**Comment by psignoret** [comment]
You're definitely on the right track there: you can get the delegated permission ID and app role IDs (application permissions) from the API's service principal object.

A few comments about your proposal above:
1. Without the `-All $true` parameter, `Get-AzureADServicePrincipal` will only retrieve 100 service principals, which might not include the one you're looking for.
2. Use server-side filtering on the service side to avoid having to retrieve all service principals and then filtering them with PowerShell. (Many organizations have hundreds of thousands of service principals, so that could take hours!)
3. You should always be very careful when matching on display names, as they are not unique. Instead, you should prefer identifiers which are guaranteed to be unique (for example `appId`).

With those considerations in mind, you could do the following:

```powershell
Get-AzureADServicePrincipal -Filter "appId eq '00000003-0000-0000-c000-000000000000'" `
| select -expand OAuth2Permissions | select id, value | sort value
```

Alternatively, you could use `servicePrincipalNames` to find the API by the URI identifier:

```powershell
Get-AzureADServicePrincipal -Filter "servicePrincipalNames/any(n:n eq 'https://graph.microsoft.com')" `
| select -expand OAuth2Permissions | select id, value | sort value
```

And finally, you may want to consider switching to use the new [Microsoft Graph PowerShell](https://docs.microsoft.com/graph/powershell/get-started) module (though for this case, the usage is almost exactly the same):

```powershell
Get-MgServicePrincipal -Filter "servicePrincipalNames/any(n:n eq 'https://graph.microsoft.com')" `
| select -expand OAuth2PermissionScopes | select id, value | sort value
```
