### ISSUE TITLE
A subscription is returned for an unsupported resource?

### ISSUE THREAD

**Issue by ChrisDXC** [microsoftgraph/microsoft-graph-docs#8454]
I mistakenly assumed I could subscribe to **/users/**_{id}_**/memberOf** but did not realize this is not supported (or is it???) until I read again that page. However I was still getting a registration id and no error.
Some other inconsistent requests result in an exception like subscribing to any _created_ event for **/users/**_{id}_ - although this is not document that error makes sense to me.
So why not returning an exception as well for unsupported subscription resources?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33d14c58-7163-a7b7-6f84-c075d0f6870d
* Version Independent ID: 3710d019-8a67-59cc-75b6-bcecc106180d
* Content: [Use the Microsoft Graph API to get change notifications - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/webhooks.md)
* Product: ****
* Technology: **microsoft-graph**
* GitHub Login: @baywet
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by baywet** [comment]
Thank you for reporting this issue with the documentation!
I authored a pull request to document additional resources that were not documented previously (group members and owners).
#8487

Additionally I confirmed with the team that `/users/{id}/memberOf` is not supported and you should get an error instead of a subscription. I filled a bug for this to get fixed and I'll update this issue once it's done.
