### ISSUE TITLE
List of permissions missing

### ISSUE THREAD

**Issue by h-david-a** [microsoftgraph/microsoft-graph-docs#9407]
SPN has to have Agreement.Read.All permission.

In case of Delegated Permissions, account has to have one of the following:
        -Global Administrator
        -Security Administrator
        -Conditional Access Administrator

Which is a bit overkill. Shouldn't that be "Security Reader"? Or "Global Reader"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e44dd129-e33a-5faf-cc4a-3c3fcde5ec3e
* Version Independent ID: 8647fda8-9854-ef2b-c2eb-1afd0e6bb35a
* Content: [List agreements - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/agreement-list?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/agreement-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/agreement-list.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @raprakasMSFT
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Hello @h-david-a ,

**Global reader** role works - but only for the LIST/GET APIs. This is because Global reader is the read-only counterpart to Global Administrator.

**Security reader** on the other hand is only for read-only access to security features, sign-in reports, and audit logs.

No updates identified for the page for now. Closing the issue.

**Comment by h-david-a** [comment]
Thanks for the update. However, the issue is the you can't READ terms of
service with Global Reader.
