### ISSUE TITLE
Unexpected 404 response

### ISSUE THREAD

**Issue by jasonbianco** [microsoftgraph/microsoft-graph-docs#9581]
I am getting a 404 response in Python for seemingly no reason.

```
tenant = ********
client_id =************
client_secret = *************
scope = "https://graph.microsoft.com/.default"
URL = https://login.microsoftonline.com/" + tenant + "/oauth2/v2.0/token HTTP/1.1?client_id=" + client_id + "&client_secret=" + client_secret + "&scope=" +scope + "&grant_type=client_credentials"

r = requests.post(URL)
print(r.status_code)
```

Returns 404 every time. I also tried using my Application ID URI + .default as the scope and that also returned 404. Whats the issue?

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38b3d5e6-46bc-11d2-214f-b9c4fa29c326
* Version Independent ID: ad6dd1cd-c08f-f447-ffd3-7a3473f169fb
* Content: [Get access without a user - Microsoft Graph](https://docs.microsoft.com/en-us/graph/auth-v2-service)
* Content Source: [concepts/auth-v2-service.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/auth-v2-service.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @Jackson-Woods
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by psignoret** [comment]
(Answering now, in case someone comes across this in the future.)

There are a few issues with the code:

1. The parameters should be submitted as parameters in the body of the POST request, not as query parameters in the URL.
1. The parameter values need to be URL encoded, so that special characters (e.g. in `client_secret` and `scope`) aren't misinterpreted. The `requests` library for Python takes care of this for you if you use the `data` parameter.
1. The URL has some extra characters ` HTTP/1.1` which are probably the result of copy-paste.

The following example takes these considerations into account:

```python
import requests

tenant = 'contoso.onmicrosoft.com'
client_id = 'b792693d-1cd6-4afc-b526-66aba5d0f1fa'
client_secret = '**********'
scope = 'https://graph.microsoft.com/.default'
url = 'https://login.microsoftonline.com/' + tenant + '/oauth2/v2.0/token'
payload = {
    'grant_type': 'client_credentials',
    'client_id': client_id,
    'client_secret': client_secret,
    'scope' : scope
}

r = requests.post(url, data=payload)
print(r.status_code)
print(r.text)
```

The result is something similar to this (I've omitted the full access token for legibility):

```none
200
{"token_type":"Bearer","expires_in":3599,"ext_expires_in":3599,"access_token":"eyJ0eXAiOiJ..."}
```

Of course, in a real application, you really wouldn't construct the request manually like this. Instead, I recommend looking at the [Microsoft Authentication Library for Python](https://github.com/AzureAD/microsoft-authentication-library-for-python), which will take care of all of this (plus a lot more!) for you.
