### ISSUE TITLE
Pagination not working on chat messages

### ISSUE THREAD

**Issue by shivajivarma** [microsoftgraph/microsoft-graph-docs#9588]
hey guys,
Pagination is not working on `https://graph.microsoft.com/beta/me/chats/{chat.id}/messages`. I'm getting nextLink, put it on new request, but is not working, throwing 400 error.
first call: https://graph.microsoft.com/beta/me/chats/{chat.id}/messages?$top=10
nextLink: https://graph.microsoft.com/beta/me/chats/{chat.id}/messages?$top=10&$skiptoken={skiptoken}

please, could you help me?

Thanks in advance!

**Comment by mamilov** [comment]
Since no one is responding to the stack overflow question (https://stackoverflow.com/questions/63582014/pagination-problem-bad-request-when-trying-to-use-the-odata-nextlink?noredirect=1#comment112541302_63582014), I would like this ticket to be reopened, since we're currently not able to get chat messages.
