### ISSUE TITLE
Get user scope information incorrect

### ISSUE THREAD

**Issue by NBajanca** [microsoftgraph/microsoft-graph-docs#990]
Issue: The ``scope`` information is incorrect.

Article: [Get a user](https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/api/user_get)

With client credentials auth you need ``Directory.Read.All``, ``User.Read.All`` returns lack of permissions.

I don't now where to correct this because I don't understand how you've implemented the permissions, otherwise, I would do a PR.
If this is general, you should add in the scopes article information about how ``User.Read.All`` is not adequate for client credentials.

More info in this [Stack Overflow question](http://stackoverflow.com/q/42960959/4470542).

**Comment by dkershaw10** [comment]
Arguably for getting a user we should remove User.Read and User.ReadWrite, since those are only applicable for /me (signed in user).  User.Read.All **does** exist as a delegated permission, but that cannot be used with client credentials flow.  User.Read.All application permission does exist in MS Graph, but is not yet supported by the directory service.  We are currently fixing this.

**Comment by NBajanca** [comment]
@dkershaw10  thank you for the answer.
I would suggest that meanwhile, you add a note in the docs referring that. 

This way you have all the time in the world to fix it :)

**Comment by NBajanca** [comment]
#1017 Done!
