### ISSUE TITLE
OData cast transitive membership filter not supported as described

### ISSUE THREAD

**Issue by ryanspletzer** [microsoftgraph/microsoft-graph-docs#9948]
This query described on [this page](https://docs.microsoft.com/en-us/graph/query-parameters#filter-parameter) doesn't work (says `$filter` is not supported).

"Use OData cast to get transitive membership in groups with a display name that starts with 'a' including a count of returned objects."

```
https://graph.microsoft.com/beta/me/transitiveMemberOf/microsoft.graph.group?$count=true&$filter=startswith(displayName, 'a')
```

![image](https://user-images.githubusercontent.com/1481108/93383142-384edd80-f831-11ea-8f82-68cf699c2065.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fefc984-0dac-5531-6620-13f577ebee5f
* Version Independent ID: 92438f30-1bb9-9b45-57dc-094fdcdeecc1
* Content: [Use query parameters to customize responses - Microsoft Graph](https://docs.microsoft.com/en-us/graph/query-parameters#filter-parameter)
* Content Source: [concepts/query-parameters.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/query-parameters.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @mumbi-o
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by ryanspletzer** [comment]
I believe this can be fixed by adding the `consistencylevel: eventual` HTTP header and the `$count=true` query parameter and doing something like this:

`https://graph.microsoft.com/beta/me/memberOf/microsoft.graph.group?$orderby=displayName%20asc&$filter=startsWith(displayName, 'a')&$count=true`

**Comment by darrelmiller** [comment]
@angelgolfer-ms I confirmed that this example query we have doesn't work.  We should find a better one.

**Comment by FaithOmbongi** [comment]
A while since this issue was opened but to provide additional feedback for anyone who faces the same in the future:

@ryanspletzer : as you accurately pointed out, the `ConsistencyLevel: eventual` header was required in both queries because:
- you used an OData cast (microsoft.graph.group)
- `$count` was used in both
- `$orderby` and `$filter` were used in the same query for the 2nd

`$count` query parameter and the `ConsistencyLevel` header are a set of advanced query parameters that are required for some queries to work. Additional guidance for this will be available soon in/via the [Use query parameters](https://docs.microsoft.com/en-us/graph/query-parameters?context=graph%2Fapi%2F1.0) page.

cc @darrelmiller
